#!/usr/bin/env python3
"""IQ3_S vec-dot for the HIP MMVQ path.

Supersedes apply_iq3s_vecdot_hip.py, whose OLD_LOOP anchor occurs in neither upstream nor the
tree, so it could no longer reproduce what the tree contains.

Generated by tools/make_patch_script.py from the tree it must reproduce, so every anchor is
unique by construction. 4 hunks across 1 file(s).

Usage: python patches/apply_iq3s_vecdot.py [tree]
"""
import io
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
tree = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "src", "llama.cpp")
MARKER = 'strixllama_iq3s_sign_mask'

EDITS = {
    os.path.join(tree, "ggml", "src", "ggml-cuda", "vecdotq.cuh"): [
        ('''
#define VDR_IQ3_S_Q8_1_MMVQ 2
''',
         '''
#if defined(GGML_USE_HIP)
// strixllama: 0xFF in byte i when sign bit i is set, for the 4-weight halves of an IQ3_S sign byte
static __device__ const uint32_t strixllama_iq3s_sign_mask[16] = {
    0x00000000u, 0x000000FFu, 0x0000FF00u, 0x0000FFFFu, 0x00FF0000u, 0x00FF00FFu, 0x00FFFF00u, 0x00FFFFFFu,
    0xFF000000u, 0xFF0000FFu, 0xFF00FF00u, 0xFF00FFFFu, 0xFFFF0000u, 0xFFFF00FFu, 0xFFFFFF00u, 0xFFFFFFFFu,
};
#endif

#define VDR_IQ3_S_Q8_1_MMVQ 2
'''),
        ('''            iq3s_grid[qs[l0 + 1] | ((qh << (7 - l0)) & 0x100)]);

        const int signs0 = __vcmpne4(((signs_packed_8[l0/2] & 0x03) << 7) | ((signs_packed_8[l0/2] & 0x0C) << 21), 0x00000000);
        const int signs1 = __vcmpne4(((signs_packed_8[l0/2] & 0x30) << 3) | ((signs_packed_8[l0/2] & 0xC0) << 17), 0x00000000);
''',
         '''            iq3s_grid[qs[l0 + 1] | ((qh << (7 - l0)) & 0x100)]);

        const int u0 = get_int_b4(bq8_1[iqs/2].qs, l0 + 0);
        const int u1 = get_int_b4(bq8_1[iqs/2].qs, l0 + 1);
#if defined(GGML_USE_HIP)
        // strixllama: __vcmpne4 / __vsub4 are byte loops on HIP. The grid magnitudes are positive, so split
        // each word by the sign mask and take two native dp4a instead: identical integer result.
        const uint32_t m0 = strixllama_iq3s_sign_mask[signs_packed_8[l0/2] & 0x0F];
        const uint32_t m1 = strixllama_iq3s_sign_mask[signs_packed_8[l0/2] >> 4];
        sumi  = ggml_cuda_dp4a((int) ((uint32_t) grid_pos.x & ~m0), u0, sumi);
        sumi -= ggml_cuda_dp4a((int) ((uint32_t) grid_pos.x &  m0), u0, 0);
        sumi  = ggml_cuda_dp4a((int) ((uint32_t) grid_pos.y & ~m1), u1, sumi);
        sumi -= ggml_cuda_dp4a((int) ((uint32_t) grid_pos.y &  m1), u1, 0);
#else
        const int signs0 = __vcmpne4(((signs_packed_8[l0/2] & 0x03) << 7) | ((signs_packed_8[l0/2] & 0x0C) << 21), 0x00000000);
        const int signs1 = __vcmpne4(((signs_packed_8[l0/2] & 0x30) << 3) | ((signs_packed_8[l0/2] & 0xC0) << 17), 0x00000000);
'''),
        ('''
        const int u0 = get_int_b4(bq8_1[iqs/2].qs, l0 + 0);
        const int u1 = get_int_b4(bq8_1[iqs/2].qs, l0 + 1);

        sumi = ggml_cuda_dp4a(grid_l, u0, sumi);
''',
         '''
        sumi = ggml_cuda_dp4a(grid_l, u0, sumi);
'''),
        ('''
        sumi = ggml_cuda_dp4a(grid_l, u0, sumi);
        sumi = ggml_cuda_dp4a(grid_h, u1, sumi);
    }

    sumi *= 1 + 2*((bq3->scales[iqs/4] >> ((iqs << 1) & 0x04)) & 0x0F);
''',
         '''
        sumi = ggml_cuda_dp4a(grid_l, u0, sumi);
        sumi = ggml_cuda_dp4a(grid_h, u1, sumi);
#endif
    }

    sumi *= 1 + 2*((bq3->scales[iqs/4] >> ((iqs << 1) & 0x04)) & 0x0F);
'''),
    ],
}


def main():
    texts = {p: io.open(p, encoding="utf-8").read() for p in EDITS}
    if any(MARKER in t for t in texts.values()):
        print("already applied")
        return
    for p, pairs in EDITS.items():
        for old, new in pairs:
            if texts[p].count(old) != 1:
                sys.exit("anchor found %d times, expected once, in %s" % (texts[p].count(old), p))
            texts[p] = texts[p].replace(old, new, 1)
    for p, t in texts.items():
        io.open(p, "w", encoding="utf-8", newline="").write(t)
    print("patched", ", ".join(os.path.basename(p) for p in EDITS))


if __name__ == "__main__":
    main()
