#!/usr/bin/env python3
"""A failing operator new reports its size and call stack before "bad allocation" surfaces

The server turns std::bad_alloc into "decode() failed: bad allocation", which cannot tell an out-of-memory machine from a size computed out of garbage. A new handler prints the requested size and the call stack as module+offset; it found the commit limit above.

Generated by tools/make_patch_script.py from the tree it must reproduce, so every anchor is
unique by construction. 1 hunks across 1 file(s).

Usage: python D:/Work/strixllama/patches/apply_alloc_failure_report.py [tree]
"""
import io
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
tree = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "src", "llama.cpp")
MARKER = 'NEW_FAILED'

EDITS = {
    os.path.join(tree, "tools", "server", "server-context.cpp"): [
        ('''static strixllama_spec_timing g_spec_timing;

''',
         '''static strixllama_spec_timing g_spec_timing;

// strixllama: a failing operator new reports the size it asked for and its call stack as module+offset before the
// std::bad_alloc surfaces as "bad allocation". That message alone could not tell an out-of-memory machine from a
// size computed out of garbage; on this machine it was the first (the commit limit, see docs/measuring.md).
#if defined(_WIN32)
#include <new.h>
static int strixllama_new_handler(size_t size) {
    void * frames[48];
    const USHORT n = CaptureStackBackTrace(1, 48, frames, nullptr);
    fprintf(stderr, "NEW_FAILED size=%zu (0x%zx)\\n", size, size);
    for (USHORT i = 0; i < n; ++i) {
        HMODULE mod = nullptr;
        char name[MAX_PATH] = "?";
        if (GetModuleHandleExA(GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS | GET_MODULE_HANDLE_EX_FLAG_UNCHANGED_REFCOUNT,
                    (LPCSTR) frames[i], &mod) && mod) {
            GetModuleFileNameA(mod, name, MAX_PATH);
        }
        const char * base = strrchr(name, '\\\\');
        fprintf(stderr, "NEW_FAILED   #%u %s+0x%llx\\n", (unsigned) i, base ? base + 1 : name,
                (unsigned long long) ((const char *) frames[i] - (const char *) mod));
    }
    fflush(stderr);
    return 0;
}
static const int strixllama_new_handler_installed = [] { _set_new_handler(strixllama_new_handler); return 1; }();
#endif

'''),
    ],
}


def main():
    texts = {p: io.open(p, encoding="utf-8").read() for p in EDITS}
    if any(MARKER in t for t in texts.values()):
        print("already applied")
        return
    for p, pairs in EDITS.items():
        for old, new in pairs:
            if texts[p].count(old) != 1:
                sys.exit("anchor found %d times, expected once, in %s" % (texts[p].count(old), p))
            texts[p] = texts[p].replace(old, new, 1)
    for p, t in texts.items():
        io.open(p, "w", encoding="utf-8", newline="").write(t)
    print("patched", ", ".join(os.path.basename(p) for p in EDITS))


if __name__ == "__main__":
    main()
