#!/usr/bin/env python3
"""Save a slot's state with one device read per run of nearby cell ranges, not one per range

A conversation decoded alongside others is interleaved with them cell by cell, so its state is thousands of ranges per layer, and a synchronous device read per range made the server stall for 6-10 s whenever it saved one (a slot reused, a conversation handed to the disk tier). Runs of ranges are read as one span and cut on the host; the bytes are the same (every chunk of a disk-tier store written by both builds hashed identical).

Generated by tools/make_patch_script.py from the tree it must reproduce, so every anchor is
unique by construction. 1 hunks across 1 file(s).

Usage: python D:/Work/strixllama/patches/apply_state_read_coalesce.py [tree]
"""
import io
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
tree = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "src", "llama.cpp")
MARKER = 'kSpan'

EDITS = {
    os.path.join(tree, "src", "llama-context.cpp"): [
        ('''        // TODO: add backend support to batch tensor_get? or some other way to speed this up
        for (const auto & winfo : winfos) {
            ggml_backend_tensor_get(winfo.tensor, winfo.ptr, winfo.offset, winfo.size);
''',
         '''        // strixllama: one device read per run of nearby pieces instead of one per piece. A sequence that was
        // decoded alongside others sits interleaved with them, cell by cell, in a unified cache, so its state
        // is thousands of cell ranges per layer, and a synchronous read per range made saving one conversation
        // take 6-10 s with the whole server waiting. Pieces of one tensor whose offsets rise with gaps of at
        // most kGap bytes are read as one span (at most kSpan bytes) and cut on the host: the same bytes, in the
        // same places.
        constexpr size_t kGap  = (size_t) 1 << 20;
        constexpr size_t kSpan = (size_t) 256 << 20;
        std::vector<uint8_t> tmp;
        size_t i = 0;
        while (i < winfos.size()) {
            const write_info & w0 = winfos[i];
            size_t j   = i;
            size_t end = w0.offset + w0.size;
            while (j + 1 < winfos.size()) {
                const write_info & w = winfos[j + 1];
                if (w.tensor != w0.tensor || w.offset < end || w.offset - end > kGap || w.offset + w.size - w0.offset > kSpan) {
                    break;
                }
                ++j;
                end = w.offset + w.size;
            }
            if (j == i) {
                ggml_backend_tensor_get(w0.tensor, w0.ptr, w0.offset, w0.size);
            } else {
                tmp.resize(end - w0.offset);
                ggml_backend_tensor_get(w0.tensor, tmp.data(), w0.offset, tmp.size());
                for (size_t k = i; k <= j; ++k) {
                    memcpy(winfos[k].ptr, tmp.data() + (winfos[k].offset - w0.offset), winfos[k].size);
                }
            }
            i = j + 1;
'''),
    ],
}


def main():
    texts = {p: io.open(p, encoding="utf-8").read() for p in EDITS}
    if any(MARKER in t for t in texts.values()):
        print("already applied")
        return
    for p, pairs in EDITS.items():
        for old, new in pairs:
            if texts[p].count(old) != 1:
                sys.exit("anchor found %d times, expected once, in %s" % (texts[p].count(old), p))
            texts[p] = texts[p].replace(old, new, 1)
    for p, t in texts.items():
        io.open(p, "w", encoding="utf-8", newline="").write(t)
    print("patched", ", ".join(os.path.basename(p) for p in EDITS))


if __name__ == "__main__":
    main()
