#!/usr/bin/env python3
"""Keep the prompt cache out of system RAM, and stop MTP from deciding whether a cache entry is usable

The RAM tier's 8192 MiB default held ~8 GB of system memory on a machine whose GPU carve leaves 31.6 GB for the desktop, and alloc() refuses a state larger than that limit while persist() only ran on a state alloc() had accepted - so turning the limit down would have stopped every long conversation from reaching the disk tier. persist() now takes the buffers directly and prompt_save() falls back to a temporary. Three defects came out with it: the disk tier ranked candidates by f_keep, so a short entry that was a complete prefix (f_keep = 1.000) permanently shadowed a longer one for the same conversation - measured as a 49370-token entry beating the 79441-token entry and costing 30071 tokens of prefill; reopening a cached conversation with MTP off hit GGML_ASSERT(ctx_dft) and killed the server; and a miss left no trace in the log at all. Measured: server resident 7.1 GB -> 1.8 GB, the 79K conversation 96.6 s of prefill -> 17.3 s.

Generated by tools/make_patch_script.py from the tree it must reproduce, so every anchor is
unique by construction. 17 hunks across 3 file(s).

Usage: python patches/apply_cache_ram_and_mtp.py [tree]
"""
import io
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
tree = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "src", "llama.cpp")
MARKER = 'disk_wants'

EDITS = {
    os.path.join(tree, "tools", "server", "server-task.h"): [
        ('''    void persist(const server_prompt_cache_state & state);
''',
         '''    bool has_disk() const { return disk_limit > 0; }
    // false when the disk tier already holds this prompt or a longer one, so a caller that would have
    // to gather the state first (see prompt_save) can skip the work
    bool disk_wants(const server_prompt & prompt) const;
    void persist(const server_prompt_cache_state & state);
    // the same, from buffers the RAM tier does not own: this is what lets --cache-ram stay small
    void persist(const server_prompt & prompt, const std::vector<uint8_t> & data_main, const std::vector<uint8_t> & data_drft);
'''),
    ],
    os.path.join(tree, "tools", "server", "server-task.cpp"): [
        ('''
    if (it_best != states.end()) {
''',
         '''
    // strixllama: an entry written while MTP was off carries no draft state, and nothing here can
    // build one for a sequence the target is already deep into. Restoring the target alone would
    // leave the draft context empty and drafting from it would not match. Cheaper to be wrong about
    // the cache than about the tokens: process the prompt instead.
    if (it_best != states.end() && ctx_dft && it_best->data.drft.empty()) {
        SRV_WRN("%s", " - cached prompt carries no draft state and this server drafts: processing the prompt instead\\n");
        states.erase(it_best);
        it_best = states.end();
    }

    if (it_best != states.end()) {
'''),
        ('''            if (!data.empty()) {
                GGML_ASSERT(ctx_dft);

''',
         '''            // strixllama: this server may have MTP off while the entry was written with it on. There is
            // then no draft context to restore into and no drafting either, so the target state is
            // complete on its own - drop the draft half rather than assert on it, which is what aborted
            // the server the first time a cached conversation was reopened with MTP turned off.
            if (!data.empty() && !ctx_dft) {
                SRV_INF("%s", " - cached prompt carries a draft state and this server does not draft: keeping the target state\\n");
                data.clear();
                data.shrink_to_fit();
            }

            if (!data.empty()) {
'''),
        ('''        if (!spc_read_tokens(f, e.tokens, disk_has_mtmd)) continue;
''',
         '''        std::string why;
        try {
            if (!spc_read_tokens(f, e.tokens, disk_has_mtmd)) { why = "truncated or malformed token state"; }
        } catch (const std::exception & ex) {
            why = ex.what();
        }
        if (!why.empty()) {
            // unreadable here is unreadable for good: no lookup can ever restore it, and leaving it
            // in place keeps charging the limit for bytes nothing can use
            SRV_WRN(" - disk cache: dropping %s (%.2f GiB): %s\\n",
                    entry.path().filename().string().c_str(), e.bytes / (1024.0 * 1024.0 * 1024.0), why.c_str());
            std::filesystem::remove(entry.path(), ec);
            continue;
        }
'''),
        ('''
size_t server_prompt_cache::disk_size() const {
''',
         '''
bool server_prompt_cache::disk_wants(const server_prompt & prompt) const {
    if (disk_limit == 0 || prompt.tokens.size() == 0) return false;
    for (const auto & e : disk_index) {
        if (e.tokens.get_common_prefix(prompt.tokens) == prompt.tokens.size()) return false;
    }
    return true;
}

size_t server_prompt_cache::disk_size() const {
'''),
        ('''    if (disk_limit == 0 || state.prompt.tokens.size() == 0) return;
    const llama_tokens text = state.prompt.tokens.get_text_tokens();
    for (llama_token t : text) {
        if (t == LLAMA_TOKEN_NULL) return;      // media in the prompt: not persisted
    }
''',
         '''    persist(state.prompt, state.data.main, state.data.drft);
}

void server_prompt_cache::persist(const server_prompt & prompt, const std::vector<uint8_t> & data_main, const std::vector<uint8_t> & data_drft) {
    if (disk_limit == 0 || prompt.tokens.size() == 0) return;
    // media in the prompt is not persisted: the chunks would have to come back through an mmproj this
    // server may not have. get_text_tokens() drops the placeholders, so a short result is the tell -
    // scanning it for LLAMA_TOKEN_NULL never found one, because it had just removed them all.
    if (prompt.tokens.get_text_tokens().size() != prompt.tokens.size()) return;

'''),
        ('''        const size_t lcp = it->tokens.get_common_prefix(state.prompt.tokens);
''',
         '''        const size_t lcp = it->tokens.get_common_prefix(prompt.tokens);
'''),
        ('''        } else if (lcp == state.prompt.tokens.size()) {
''',
         '''        } else if (lcp == prompt.tokens.size()) {
'''),
        ('''    const std::vector<char> tok_bytes = state.prompt.tokens.serialize();
''',
         '''
    const std::vector<char> tok_bytes = prompt.tokens.serialize();
'''),
        ('''    snprintf(name, sizeof(name), "%016llx-%d.spc", (unsigned long long) h, (int) state.prompt.tokens.size());
''',
         '''    snprintf(name, sizeof(name), "%016llx-%d.spc", (unsigned long long) h, (int) prompt.tokens.size());
'''),
        ('''        spc_put_blob(f, state.data.main);
        spc_put_blob(f, state.data.drft);
        spc_put(f, (uint32_t) state.prompt.checkpoints.size());
        for (const auto & c : state.prompt.checkpoints) {
''',
         '''        spc_put_blob(f, data_main);
        spc_put_blob(f, data_drft);
        spc_put(f, (uint32_t) prompt.checkpoints.size());
        for (const auto & c : prompt.checkpoints) {
'''),
        ('''    disk_entry e { path, state.prompt.tokens.clone(), (size_t) std::filesystem::file_size(path, ec), ++disk_seq };
    disk_index.push_back(std::move(e));
''',
         '''
    const size_t bytes = (size_t) std::filesystem::file_size(path, ec);
    disk_index.push_back(disk_entry { path, prompt.tokens.clone(), bytes, ++disk_seq });
'''),
        ('''            (int) state.prompt.tokens.size(), (double) e.bytes / (1024.0 * 1024.0 * 1024.0), disk_index.size(), disk_size() / (1024.0 * 1024.0 * 1024.0));
''',
         '''            (int) prompt.tokens.size(), (double) bytes / (1024.0 * 1024.0 * 1024.0), disk_index.size(), disk_size() / (1024.0 * 1024.0 * 1024.0));
'''),
        ('''    auto best = disk_index.end();
    for (auto it = disk_index.begin(); it != disk_index.end(); ++it) {
''',
         '''    auto best = disk_index.end();
    auto near = disk_index.end();          // closest entry whether or not it was taken, for the miss line
    int  near_lcp = -1;
    int  best_lcp = -1;
    float best_keep = 0.0f, best_sim = 0.0f;
    for (auto it = disk_index.begin(); it != disk_index.end(); ++it) {
'''),
        ('''        if (f_keep_cur < 0.25f) continue;
        if (f_keep_best < f_keep_cur && f_sim_best < f_sim_cur) {
            f_keep_best = f_keep_cur;
            f_sim_best  = f_sim_cur;
            best = it;
''',
         '''        if (lcp_cur > near_lcp) { near_lcp = lcp_cur; near = it; }
        // f_keep guards against dragging a long state in to serve a short prefix; f_sim has to beat
        // what the slot or the RAM tier already offers, or the read buys nothing
        if (f_keep_cur < 0.25f || f_sim_cur <= f_sim_best) continue;
        // among what is left, take the entry that skips the most tokens. Ranking by f_keep the way
        // the RAM tier does lets a short entry that happens to be a complete prefix (f_keep = 1.000)
        // shadow a much longer one for the same conversation, because nothing can then exceed it:
        // measured here as a 49370-token entry beating the 79441-token entry of the same chat and
        // costing 30071 tokens of prefill, about 40 s.
        if (lcp_cur > best_lcp) {
            best_lcp  = lcp_cur;
            best_keep = f_keep_cur;
            best_sim  = f_sim_cur;
            best      = it;
'''),
        ('''    if (best == disk_index.end()) return nullptr;
''',
         '''    if (best != disk_index.end()) {
        f_keep_best = best_keep;
        f_sim_best  = best_sim;
    }
    if (best == disk_index.end()) {
        // the prefill that follows costs a minute or two on a long conversation, so name what was on
        // the shelf and how it lost: f_keep below 0.25 means the conversation forked away from the
        // entry, a base that already beats it means RAM or the slot covers more of the prompt
        if (near != disk_index.end()) {
            SRV_INF(" - disk cache: nothing taken for %d tokens (%zu on disk; closest has %d tokens, lcp = %d, f_keep = %.3f, f_sim = %.3f; base f_keep = %.3f, f_sim = %.3f)\\n",
                    (int) tokens_new.size(), disk_index.size(), (int) near->tokens.size(), near_lcp,
                    near->tokens.size() ? float(near_lcp) / near->tokens.size() : 0.0f,
                    tokens_new.size() ? float(near_lcp) / tokens_new.size() : 0.0f, f_keep_best, f_sim_best);
        } else {
            SRV_INF(" - disk cache: empty, %d tokens will be processed from scratch\\n", (int) tokens_new.size());
        }
        return nullptr;
    }
'''),
    ],
    os.path.join(tree, "tools", "server", "server-context.cpp"): [
        ('''        if (cur == nullptr) {
            return false;
''',
         '''        if (cur == nullptr) {
            // strixllama: alloc() declines a state larger than --cache-ram, and this machine keeps that
            // limit small on purpose - the KV cache lives in the GPU carve, and the prompt cache should
            // not take system memory the rest of the desktop needs. The disk tier is what carries a long
            // conversation across a restart, so write it from a temporary the RAM tier does not own.
            if (prompt_cache.has_disk() && prompt_cache.disk_wants(prompt)) {
                try {
                    std::vector<uint8_t> tmp_tgt(cur_size_tgt);
                    std::vector<uint8_t> tmp_dft(cur_size_dft);
                    llama_state_seq_get_data_ext(ctx_tgt, tmp_tgt.data(), cur_size_tgt, id, LLAMA_STATE_SEQ_FLAGS_NONE);
                    if (ctx_dft) {
                        llama_state_seq_get_data_ext(ctx_dft, tmp_dft.data(), cur_size_dft, id, LLAMA_STATE_SEQ_FLAGS_NONE);
                    }
                    prompt_cache.persist(prompt, tmp_tgt, tmp_dft);
                    return true;
                } catch (const std::bad_alloc &) {
                    SRV_WRN(" - disk cache: not enough memory to gather %.3f MiB of state\\n",
                            (cur_size_tgt + cur_size_dft) / (1024.0 * 1024.0));
                }
            }
            return false;
'''),
    ],
}


def main():
    texts = {p: io.open(p, encoding="utf-8").read() for p in EDITS}
    if any(MARKER in t for t in texts.values()):
        print("already applied")
        return
    for p, pairs in EDITS.items():
        for old, new in pairs:
            if texts[p].count(old) != 1:
                sys.exit("anchor found %d times, expected once, in %s" % (texts[p].count(old), p))
            texts[p] = texts[p].replace(old, new, 1)
    for p, t in texts.items():
        io.open(p, "w", encoding="utf-8", newline="").write(t)
    print("patched", ", ".join(os.path.basename(p) for p in EDITS))


if __name__ == "__main__":
    main()
