#!/usr/bin/env python3
"""The disk tier and the slot check work with a vision projector loaded

With a vision projector loaded every prompt counts as a media prompt to server_tokens::get_tokens(), which aborts on GGML_ASSERT(!has_mtmd). Version 3 of the disk tier called it to compare the prompt with the runs already written, so 0.1.13 and 0.1.14 aborted about ten seconds into the first long prompt whenever the disk tier and image input were both on - the combination a profile saved before 0.1.13 has, since both were on by default then. It reads the text tokens instead, which a prompt without media has exactly as many of. The check that a slot's tokens match its memory before a prompt batch (apply_slot_state_guard) was skipped whenever a projector was loaded, so it never ran with image input on; it now skips only prompts that hold media, whose positions run ahead of their cells.

Generated by tools/make_patch_script.py from the tree it must reproduce, so every anchor is
unique by construction. 4 hunks across 1 file(s).

Usage: python patches/apply_disk_v3_vision.py [tree]
"""
import io
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
tree = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "src", "llama.cpp")
MARKER = 'every prompt is a media prompt to'

EDITS = {
    os.path.join(tree, "tools", "server", "server-context.cpp"): [
        ('''        if (prompt.tokens.get_text_tokens().size() != (size_t) prompt.n_tokens()) {
''',
         '''        // the text tokens, not get_tokens(): with a vision projector loaded every prompt is a media prompt to
        // get_tokens(), which aborts, although this one has no media in it
        const llama_tokens text = prompt.tokens.get_text_tokens();
        if (text.size() != (size_t) prompt.n_tokens()) {
'''),
        ('''        {
            const llama_tokens & cur = prompt.tokens.get_tokens();
            const size_t lim = std::min(cur.size(), runs.tokens.size());
''',
         '''        {
            const llama_tokens & cur = text;
            const size_t lim = std::min(cur.size(), runs.tokens.size());
'''),
        ('''        {
            const llama_tokens & cur = prompt.tokens.get_tokens();
            runs.tokens.assign(cur.begin(), cur.begin() + std::min<size_t>(cur.size(), (size_t) cover(runs.tgt)));
        }
''',
         '''        runs.tokens.assign(text.begin(), text.begin() + std::min<size_t>(text.size(), (size_t) cover(runs.tgt)));
'''),
        ('''                    // is processed again from its start instead. Not checked with images, whose positions run ahead
                    // of their cells.
                    if (!slot.prompt.tokens.has_mtmd) {
''',
         '''                    // is processed again from its start instead. Not checked with images in the prompt, whose
                    // positions run ahead of their cells - but checked with a vision projector loaded and none in it.
                    if (slot.prompt.tokens.get_text_tokens().size() == slot.prompt.tokens.size()) {
'''),
    ],
}


def main():
    texts = {p: io.open(p, encoding="utf-8").read() for p in EDITS}
    if any(MARKER in t for t in texts.values()):
        print("already applied")
        return
    for p, pairs in EDITS.items():
        for old, new in pairs:
            if texts[p].count(old) != 1:
                sys.exit("anchor found %d times, expected once, in %s" % (texts[p].count(old), p))
            texts[p] = texts[p].replace(old, new, 1)
    for p, t in texts.items():
        io.open(p, "w", encoding="utf-8", newline="").write(t)
    print("patched", ", ".join(os.path.basename(p) for p in EDITS))


if __name__ == "__main__":
    main()
