#!/usr/bin/env python3
"""A leaving conversation also keeps a checkpoint every 32K tokens in the disk tier

Version 3 wrote a leaving conversation's state at its end and its last prompt's two latest checkpoints: a conversation read back from disk had nothing earlier, and a deeper rewind - an agent trimming an old tool result, an edited earlier message - processed it again from its first token (67.8K tokens, 79 s in the agent probe). Its older checkpoints go too now, one every 32768 tokens, each written once; with the manager's own --checkpoint-min-step 32768 those are the ones it keeps in memory.

Generated by tools/make_patch_script.py from the tree it must reproduce, so every anchor is
unique by construction. 4 hunks across 2 file(s).

Usage: python D:/Work/strixllama/patches/apply_disk_ckpt_step.py [tree]
"""
import io
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
tree = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "src", "llama.cpp")
MARKER = 'disk_ckpt_step'

EDITS = {
    os.path.join(tree, "tools", "server", "server-context.cpp"): [
        ('''        // leaves: the state at the end, and the last two checkpoints of its last prompt - just before its end, where a
''',
         '''        // leaves: the state at the end; the last two checkpoints of its last prompt - just before its end, where a
'''),
        ('''        // message. Checkpoints the store has already are named whenever; the older ones in memory are not written.
''',
         '''        // message; and before them one every disk_ckpt_step tokens, so a deeper rewind once the conversation is back
        // (an edited earlier message, an agent trimming old tool output) replays at most that much. Checkpoints the
        // store has already are named and count towards the spacing; nothing is written twice.
'''),
        ('''                    writable.insert(&*it);
                }
''',
         '''                    writable.insert(&*it);
                }
            }
            int64_t prev = -cache.disk_ckpt_step;          // the last checkpoint the entry keeps, in position order
            for (const auto & c : prompt.checkpoints) {
                if (c.n_tokens > n_entry || writable.count(&c)) {
                    continue;
                }
                if (c.n_tokens >= prev + cache.disk_ckpt_step) {
                    if (!c.data_tgt.empty()) {
                        writable.insert(&c);
                    }
                    prev = c.n_tokens;
                }
'''),
    ],
    os.path.join(tree, "tools", "server", "server-task.h"): [
        ('''    int32_t     disk_run      = 4096;   // version 3: positions in a run (STRIX_PROMPT_CACHE_RUN)
    int64_t     disk_seq      = 0;
''',
         '''    int32_t     disk_run      = 4096;   // version 3: positions in a run (STRIX_PROMPT_CACHE_RUN)
    int64_t     disk_ckpt_step = 32768; // version 3: a leaving conversation's older checkpoints kept this far apart
    int64_t     disk_seq      = 0;
'''),
    ],
}


def main():
    texts = {p: io.open(p, encoding="utf-8").read() for p in EDITS}
    if any(MARKER in t for t in texts.values()):
        print("already applied")
        return
    for p, pairs in EDITS.items():
        for old, new in pairs:
            if texts[p].count(old) != 1:
                sys.exit("anchor found %d times, expected once, in %s" % (texts[p].count(old), p))
            texts[p] = texts[p].replace(old, new, 1)
    for p, t in texts.items():
        io.open(p, "w", encoding="utf-8", newline="").write(t)
    print("patched", ", ".join(os.path.basename(p) for p in EDITS))


if __name__ == "__main__":
    main()
