#!/usr/bin/env python3
"""The QSA block list of a batch covers only its own sequences, so idle conversations in a multi-slot pool cost nothing per step

With several slots the cache is one pool, and a compact ubatch enumerated, keyed and scored the blocks of every conversation in it, the idle ones only to mark them invisible. A single decoding conversation at 23K beside 70K tokens of idle ones: 47.6 -> 44.8 ms/token (one slot alone: 44.1); a prefill beside them 999 -> 1064 t/s, as the score bounds now apply there too. The visible blocks keep their order, so a conversation with at least the selection budget of blocks gets bitwise the same tokens and probabilities; a shorter one fills the budget with invisible entries in other places, which can move the last bits. LLAMA_QSA_ACTIVE_BLOCKS=0 turns it off.

Generated by tools/make_patch_script.py from the tree it must reproduce, so every anchor is
unique by construction. 28 hunks across 4 file(s).

Usage: python D:/Work/strixllama/patches/apply_qsa_active_blocks.py [tree]
"""
import io
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
tree = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "src", "llama.cpp")
MARKER = 'qsa_active_blocks'

EDITS = {
    os.path.join(tree, "src", "llama-memory-hybrid-idx.cpp"): [
        ('''        ggml_tensor * bias, ggml_tensor * tail_idxs, const llama_ubatch * ubatch, uint32_t ratio, const qsa_kb_inputs * kb, const qsa_mixed_inputs * mixed) const {
    set_input_qsa_impl(cell_blk, blk_cells, blk_pos, bias, tail_idxs, ubatch, ratio, true, kb, mixed);
''',
         '''        ggml_tensor * bias, ggml_tensor * tail_idxs, const llama_ubatch * ubatch, uint32_t ratio, const qsa_kb_inputs * kb, const qsa_mixed_inputs * mixed,
        bool active_only) const {
    set_input_qsa_impl(cell_blk, blk_cells, blk_pos, bias, tail_idxs, ubatch, ratio, true, kb, mixed, active_only);
'''),
        ('''        const qsa_mixed_inputs * mixed) const {
''',
         '''        const qsa_mixed_inputs * mixed,
        bool active_only) const {
'''),
        ('''    const int64_t r        = ratio;

''',
         '''    const int64_t r        = ratio;

    // strixllama: n_blocks is the length of the block list the graph was built for; n_pb is the window of
    // position buckets the cells are grouped by. They are one number unless the list covers only the
    // ubatch's own sequences (active_only, llama_memory_hybrid_idx_context::qsa_active_blocks): then the
    // list is shorter than the window, and every cell of another sequence is left out of the grouping -
    // its blocks were enumerated before only to be marked invisible to every query of the ubatch.
    GGML_ASSERT(!active_only || (tail_idxs && bias->type == GGML_TYPE_I32 && n_ns == 1));
    const int64_t n_pb = active_only ? std::max(n_blocks, (n_kv + r - 1)/r) : n_blocks;
    std::bitset<LLAMA_MAX_SEQ> active_seqs;
    if (active_only) {
        for (int64_t i = 0; i < n_tokens; ++i) {
            for (int32_t k = 0; k < ubatch->n_seq_id[i]; ++k) { active_seqs.set(ubatch->seq_id[i][k]); }
        }
    }

'''),
        ('''    std::vector<int32_t>  grp_head(n_blocks);
''',
         '''    std::vector<int32_t>  grp_head(n_pb);
'''),
        ('''                    continue;
                }

                const int64_t idx = ranked ? rank[j] : cells.pos_get(j);
''',
         '''                    continue;
                }
                if (active_only && (cells.seq_get_all(j) & active_seqs).none()) {
                    continue;
                }

                const int64_t idx = ranked ? rank[j] : cells.pos_get(j);
'''),
        ('''                if (pb >= n_blocks) {
''',
         '''                if (pb >= n_pb) {
'''),
        ('''        for (int64_t pb = 0; pb < n_blocks; ++pb) {
''',
         '''        for (int64_t pb = 0; pb < n_pb; ++pb) {
'''),
        ('''                if (pb>=0 && pb<n_blocks) {
''',
         '''                if (pb>=0 && pb<n_pb) {
'''),
        ('''        const llama_memory_hybrid_idx::qsa_mixed_inputs * mixed) const {
''',
         '''        const llama_memory_hybrid_idx::qsa_mixed_inputs * mixed,
        bool active_only) const {
'''),
        ('''    mem->set_input_qsa_blocks(cell_blk, blk_cells, blk_pos, bias, tail_idxs, ubatch, ratio, kb, mixed);
''',
         '''    mem->set_input_qsa_blocks(cell_blk, blk_cells, blk_pos, bias, tail_idxs, ubatch, ratio, kb, mixed, active_only);
'''),
        ('''bool llama_memory_hybrid_idx_context::qsa_position_prefix(const llama_ubatch & ubatch) const {
''',
         '''bool llama_memory_hybrid_idx_context::qsa_position_prefix(const llama_ubatch & ubatch, bool active_only) const {
'''),
        ('''    return qsa_single_sequence_prefix(mem->get_mem_idx()->get_cells(seq),get_idx()->get_n_kv(),seq);
''',
         '''    // a list of the ubatch's own sequences is one sequence's position prefix only if the ubatch has one sequence
    if (active_only) {
        for (uint32_t i=0;i<ubatch.n_tokens;++i) {
            if (ubatch.n_seq_id[i]!=1 || ubatch.seq_id[i][0]!=seq) { return false; }
        }
    }
    return qsa_single_sequence_prefix(mem->get_mem_idx()->get_cells(seq),get_idx()->get_n_kv(),seq,active_only);
}

// strixllama: in a unified cache every slot's conversation sits in one pool of cells and the graph spans the
// pool (n_kv), so the block list of a compact ubatch used to hold every conversation's blocks, the idle ones
// marked invisible: a decoded token paid for the block keys, the scores and the enumeration of conversations
// that were not running. The list can hold the ubatch's own sequences alone: a block's cells share one
// sequence set, every block of another set was invisible to every query here, and the visible ones keep
// their order, so the same blocks are selected in the same order. A sequence with at least the selection's
// budget of visible blocks gets bitwise the same result; a shorter one fills the budget with invisible
// entries, which now sit after its own blocks rather than among them, and that can move the last bits of its
// attention (towards what a single-slot server computes, which has no other conversation to fill it with).
// The length is an upper bound: at most one cell per position per sequence while no image has been written
// (kb_pos_dup), so a sequence holds at most pos_max - pos_min + 1 cells; rounded up to a multiple of 64
// blocks (256 cells at ratio 4, the step of n_kv) so a graph is rebuilt as rarely as before, and never below
// the budget. A graph that rewrites every block key (kb_needs_full) keeps the whole pool: it is the one that
// refreshes the idle sequences' keys too. So does the reserve graph (positions all equal), which sizes the
// buffers for the widest graph. LLAMA_QSA_ACTIVE_BLOCKS=0 turns this off.
int64_t llama_memory_hybrid_idx_context::qsa_active_blocks(const llama_ubatch & ubatch, uint32_t ratio, int64_t min_blocks) const {
    static const bool on = !getenv("LLAMA_QSA_ACTIVE_BLOCKS") || atoi(getenv("LLAMA_QSA_ACTIVE_BLOCKS")) != 0;
    if (!on || mem == nullptr || get_idx() == nullptr || ratio == 0 || get_n_stream() != 1 ||
            mem->kb_needs_full() || mem->kb_pos_dup() || !qsa_scalar_visibility(ubatch)) {
        return 0;
    }
    bool same_pos = ubatch.n_tokens > 1;
    for (uint32_t i = 1; same_pos && i < ubatch.n_tokens; ++i) {
        if (ubatch.pos[i] != ubatch.pos[0]) { same_pos = false; }
    }
    if (same_pos) {
        return 0;
    }
    std::bitset<LLAMA_MAX_SEQ> seqs;
    for (uint32_t i = 0; i < ubatch.n_tokens; ++i) {
        for (int32_t k = 0; k < ubatch.n_seq_id[i]; ++k) { seqs.set(ubatch.seq_id[i][k]); }
    }
    const auto & cells = mem->get_mem_idx()->get_cells(ubatch.seq_id[0][0]);
    int64_t n_cells = 0;
    for (int32_t s = 0; s < LLAMA_MAX_SEQ; ++s) {
        if (!seqs.test(s)) {
            continue;
        }
        const llama_pos p0 = cells.seq_pos_min(s);
        const llama_pos p1 = cells.seq_pos_max(s);
        if (p0 < 0 || p1 < p0) {
            return 0;
        }
        n_cells += (int64_t) p1 - p0 + 1;
    }
    const int64_t full   = ((int64_t) get_idx()->get_n_kv() + ratio - 1)/ratio;
    const int64_t blocks = std::max(min_blocks, ((n_cells + ratio - 1)/ratio + 63)/64*64);
    return blocks < full ? blocks : 0;
'''),
    ],
    os.path.join(tree, "src", "llama-memory-hybrid-idx.h"): [
        ('''                             const qsa_mixed_inputs * mixed = nullptr) const;
''',
         '''                             const qsa_mixed_inputs * mixed = nullptr, bool active_only = false) const;
'''),
        ('''                            const qsa_kb_inputs * kb, const qsa_mixed_inputs * mixed = nullptr) const;
''',
         '''                            const qsa_kb_inputs * kb, const qsa_mixed_inputs * mixed = nullptr,
                            bool active_only = false) const;
'''),
        ('''    bool qsa_position_prefix(const llama_ubatch & ubatch) const;
''',
         '''    bool qsa_position_prefix(const llama_ubatch & ubatch, bool active_only = false) const;
    // strixllama: the length of a block list that covers only the ubatch's own sequences, at least min_blocks
    // (the selection's budget), or 0 when the list must cover every cell of the pool (see the definition)
    int64_t qsa_active_blocks(const llama_ubatch & ubatch, uint32_t ratio, int64_t min_blocks) const;
'''),
        ('''                             const llama_memory_hybrid_idx::qsa_mixed_inputs * mixed = nullptr) const;
''',
         '''                             const llama_memory_hybrid_idx::qsa_mixed_inputs * mixed = nullptr,
                             bool active_only = false) const;
'''),
    ],
    os.path.join(tree, "src", "models", "qwen4exp.cpp"): [
        ('''        const llama_ubatch & ubatch, int64_t blocks, int64_t strip, int64_t ratio, int64_t budget, bool compact) {
    // llama_context::graph_reserve builds a worst-case graph from a synthetic ubatch whose positions are all 0.
    // Bounding that graph would reserve compute buffers for a 4%-wide scorer and then execute full-width ones, so a
    // many-token ubatch whose positions are all identical is treated as synthetic and left unbounded.
    bool degenerate_pos = ubatch.pos && ubatch.n_tokens > 1;
    for (uint32_t i = 1; degenerate_pos && i < ubatch.n_tokens; ++i) {
        if (ubatch.pos[i] != ubatch.pos[0]) { degenerate_pos = false; }
    }
    if (!compact || ubatch.n_tokens<128 || degenerate_pos || !qwen4exp_qsa_flag("LLAMA_QSA_SCORE_BOUNDS") ||
            !mctx->qsa_position_prefix(ubatch)) {
        static unsigned off = 0;
        if (off++ < 2) { fprintf(stderr,"QSA_SCORE_BOUNDS inactive (compact=%d tokens=%u flag=%d prefix=%d)\\n",
                (int) compact, ubatch.n_tokens, (int) qwen4exp_qsa_flag("LLAMA_QSA_SCORE_BOUNDS"),
                (int) mctx->qsa_position_prefix(ubatch)); }
''',
         '''        const llama_ubatch & ubatch, int64_t blocks, int64_t strip, int64_t ratio, int64_t budget, bool compact,
        bool active_only = false) {
    // llama_context::graph_reserve builds a worst-case graph from a synthetic ubatch whose positions are all 0.
    // Bounding that graph would reserve compute buffers for a 4%-wide scorer and then execute full-width ones, so a
    // many-token ubatch whose positions are all identical is treated as synthetic and left unbounded.
    bool degenerate_pos = ubatch.pos && ubatch.n_tokens > 1;
    for (uint32_t i = 1; degenerate_pos && i < ubatch.n_tokens; ++i) {
        if (ubatch.pos[i] != ubatch.pos[0]) { degenerate_pos = false; }
    }
    if (!compact || ubatch.n_tokens<128 || degenerate_pos || !qwen4exp_qsa_flag("LLAMA_QSA_SCORE_BOUNDS") ||
            !mctx->qsa_position_prefix(ubatch, active_only)) {
        static unsigned off = 0;
        if (off++ < 2) { fprintf(stderr,"QSA_SCORE_BOUNDS inactive (compact=%d tokens=%u flag=%d prefix=%d)\\n",
                (int) compact, ubatch.n_tokens, (int) qwen4exp_qsa_flag("LLAMA_QSA_SCORE_BOUNDS"),
                (int) mctx->qsa_position_prefix(ubatch, active_only)); }
'''),
        ('''            mctx->set_input_qsa_blocks(cell_blk, blk_cells, blk_pos, bias, tail_idxs, ubatch, ratio, kbp, seq_blk ? &mx : nullptr);
''',
         '''            mctx->set_input_qsa_blocks(cell_blk, blk_cells, blk_pos, bias, tail_idxs, ubatch, ratio, kbp, seq_blk ? &mx : nullptr, active_only);
'''),
        ('''        const int64_t n_blocks = (n_kv + ratio - 1)/ratio;

        bool res = true;
''',
         '''        const bool blocks=qwen4exp_use_block_selection(blk_bias,n_stream,ratio,n_kv,
                params.ubatch,params.cparams,params.hparams);
        const bool scalar=blocks && params.hparams.n_swa==0 && mctx->qsa_scalar_visibility(params.ubatch);
        // strixllama: a compact graph's block list may cover only the ubatch's sequences (qsa_active_blocks)
        const int64_t n_active = scalar && qwen4exp_qsa_flag("LLAMA_QSA_COMPACT_METADATA") ?
                mctx->qsa_active_blocks(params.ubatch, ratio, params.hparams.indexer_top_k/ratio) : 0;
        const int64_t n_blocks = n_active > 0 ? n_active : (n_kv + ratio - 1)/ratio;

        bool res = true;

        res &= active_only == (n_active > 0);
'''),
        ('''        const bool blocks=qwen4exp_use_block_selection(blk_bias,n_stream,ratio,n_kv,
                params.ubatch,params.cparams,params.hparams);
        res &= (tail_idxs != nullptr) == blocks;
        const bool scalar=blocks && params.hparams.n_swa==0 && mctx->qsa_scalar_visibility(params.ubatch);
''',
         '''        res &= (tail_idxs != nullptr) == blocks;
'''),
        ('''                params.hparams.indexer_top_k/ratio,scalar && compact);
''',
         '''                params.hparams.indexer_top_k/ratio,scalar && compact,active_only);
'''),
        ('''    bool maskless = false;
    int64_t score_strip = 0;
''',
         '''    bool maskless = false;
    bool active_only = false;   // the block list covers only the ubatch's own sequences
    int64_t score_strip = 0;
'''),
        ('''    const int64_t n_blocks = (n_kv + r - 1)/r;

''',
         ''''''),
        ('''        cparams.causal_attn && !hparams.use_alibi;

''',
         '''        cparams.causal_attn && !hparams.use_alibi;

    // strixllama: a compact ubatch's block list covers only its own sequences when the memory allows it
    // (llama_memory_hybrid_idx_context::qsa_active_blocks); otherwise every cell of the pool
    const bool qsa_compact = qwen4exp_use_block_selection(blk_bias,n_stream,r,n_kv,ubatch,cparams,hparams) &&
        hparams.n_swa==0 && mctx_hyb->qsa_scalar_visibility(ubatch) && qwen4exp_qsa_flag("LLAMA_QSA_COMPACT_METADATA");
    const int64_t n_active = qsa_compact ? mctx_hyb->qsa_active_blocks(ubatch, r, hparams.indexer_top_k/r) : 0;
    const int64_t n_blocks = n_active > 0 ? n_active : (n_kv + r - 1)/r;

'''),
        ('''        qsa->compact = scalar && qwen4exp_qsa_flag("LLAMA_QSA_COMPACT_METADATA");
        // strixllama: only the qsa3 kernel honours the indices without a mask, and it declines batches under
''',
         '''        qsa->compact = scalar && qwen4exp_qsa_flag("LLAMA_QSA_COMPACT_METADATA");
        qsa->active_only = n_active > 0;
        // strixllama: only the qsa3 kernel honours the indices without a mask, and it declines batches under
'''),
        ('''                hparams.indexer_top_k/r,qsa->compact);
''',
         '''                hparams.indexer_top_k/r,qsa->compact,qsa->active_only);
'''),
    ],
    os.path.join(tree, "src", "prefix.h"): [
        ('''static bool qsa_single_sequence_prefix(const llama_kv_cells & cells, uint32_t count, llama_seq_id seq) {
''',
         '''// strixllama: active_only = the block list holds this sequence's blocks alone, so the other sequences' cells
// do not break the prefix; the sequence's own cells must still be its alone
static bool qsa_single_sequence_prefix(const llama_kv_cells & cells, uint32_t count, llama_seq_id seq, bool active_only = false) {
'''),
        ('''        if (cells.is_empty(i)) { continue; }
        if (cells.seq_get_all(i).count()!=1 || !cells.seq_has(i,seq) || cells.pos_get(i)<0) { return false; }
''',
         '''        if (cells.is_empty(i)) { continue; }
        if (active_only && !cells.seq_has(i,seq)) { continue; }
        if (cells.seq_get_all(i).count()!=1 || !cells.seq_has(i,seq) || cells.pos_get(i)<0) { return false; }
'''),
    ],
}


def main():
    texts = {p: io.open(p, encoding="utf-8").read() for p in EDITS}
    if any(MARKER in t for t in texts.values()):
        print("already applied")
        return
    for p, pairs in EDITS.items():
        for old, new in pairs:
            if texts[p].count(old) != 1:
                sys.exit("anchor found %d times, expected once, in %s" % (texts[p].count(old), p))
            texts[p] = texts[p].replace(old, new, 1)
    for p, t in texts.items():
        io.open(p, "w", encoding="utf-8", newline="").write(t)
    print("patched", ", ".join(os.path.basename(p) for p in EDITS))


if __name__ == "__main__":
    main()
