#!/usr/bin/env python3
"""IQ3_S experts through MMQ on HIP: no byte loops, LDS grid, and the compact routed path for every gate/up type.

On RDNA3.5 the IQ3_S MMQ tile loader ran at 123 GB/s where IQ4_NL ran at 195 on the same shapes: __vcmpne4/__vsub4 are byte loops on HIP (the mmvq vec-dot had already lost them), the grid was read from global memory, and above 16 tokens per step every type except IQ4_NL fell to 73 GB/s because the fork's compact routed MMQ path was gated to IQ4_NL. Sign bytes now come from two multiplies, the grid sits in LDS after the x tile, and the compact path takes IQ3_S and IQ4_XS: 149-157 GB/s from 8 to 64 tokens. test-backend-ops gains STRIX_MOE_PERF for this model's expert shapes.

Generated by tools/make_patch_script.py from the tree it must reproduce, so every anchor is
unique by construction. 9 hunks across 4 file(s).

Usage: python patches/apply_iq3s_mmq_hip.py [tree]
"""
import io
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
tree = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "src", "llama.cpp")
MARKER = 'strixllama_iq3s_sign_mask('

EDITS = {
    os.path.join(tree, "ggml", "src", "ggml-cuda", "vecdotq.cuh"): [
        ('''// strixllama: 0xFF in byte i when sign bit i is set, for the 4-weight halves of an IQ3_S sign byte
static __device__ const uint32_t strixllama_iq3s_sign_mask[16] = {
    0x00000000u, 0x000000FFu, 0x0000FF00u, 0x0000FFFFu, 0x00FF0000u, 0x00FF00FFu, 0x00FFFF00u, 0x00FFFFFFu,
    0xFF000000u, 0xFF0000FFu, 0xFF00FF00u, 0xFF00FFFFu, 0xFFFF0000u, 0xFFFF00FFu, 0xFFFFFF00u, 0xFFFFFFFFu,
};
''',
         '''// strixllama: 0xFF in byte i when sign bit i of the 4-bit half `s4` is set, for the 4-weight halves of
// an IQ3_S sign byte. Two multiplies and an and, no table: s4 * 0x00204081 puts bit i at position
// 8*i (plus stray copies the mask removes), and * 0xFF spreads each kept bit over its byte.
static __device__ __forceinline__ uint32_t strixllama_iq3s_sign_mask(const uint32_t s4) {
    return ((s4 * 0x00204081u) & 0x01010101u) * 0xFFu;
}
'''),
        ('''        const uint32_t m0 = strixllama_iq3s_sign_mask[signs_packed_8[l0/2] & 0x0F];
        const uint32_t m1 = strixllama_iq3s_sign_mask[signs_packed_8[l0/2] >> 4];
''',
         '''        const uint32_t m0 = strixllama_iq3s_sign_mask(signs_packed_8[l0/2] & 0x0F);
        const uint32_t m1 = strixllama_iq3s_sign_mask(signs_packed_8[l0/2] >> 4);
'''),
    ],
    os.path.join(tree, "ggml", "src", "ggml-cuda", "mmq.cuh"): [
        ('''    int * tile_x = tile_y + GGML_PAD(J*MMQ_TILE_Y_K, nwarps*warp_size);

''',
         '''    int * tile_x = tile_y + GGML_PAD(J*MMQ_TILE_Y_K, nwarps*warp_size);
#if defined(GGML_USE_HIP) && defined(AMD_WMMA_AVAILABLE)
    if constexpr (type == GGML_TYPE_IQ3_S) {
        // strixllama: load_tiles_iq3_s reads the 512-entry grid twice per 8 weights of every tile; from
        // LDS that is a ds_read instead of a global load through the vector cache. The copy sits right
        // after tile_x (mmq_get_nbytes_shared reserves it) and is filled per tile - a handful of times
        // per block against thousands of lookups.
        uint32_t * grid_lds = (uint32_t *) (tile_x + I * ggml_cuda_mmq_get_sram_stride(type, J, fallback));
        for (int i = threadIdx.y*warp_size + threadIdx.x; i < 512; i += nwarps*warp_size) {
            grid_lds[i] = iq3s_grid[i];
        }
        __syncthreads();
    }
#endif // GGML_USE_HIP && AMD_WMMA_AVAILABLE

'''),
        ('''    return a.type_x == GGML_TYPE_IQ4_NL && GGML_CUDA_CC_IS_RDNA3_5(cc) && !fallback &&
''',
         '''    // strixllama: the gate/up experts (IQ3_S, one layer IQ4_XS) take the same shapes as the IQ4_NL down
    // projection this path was written for; without it they fall off a cliff at 24+ tokens per step
    // (73 GB/s against 195 at 16, tools: test-backend-ops perf with STRIX_MOE_PERF)
    return (a.type_x == GGML_TYPE_IQ4_NL || a.type_x == GGML_TYPE_IQ3_S || a.type_x == GGML_TYPE_IQ4_XS) &&
        GGML_CUDA_CC_IS_RDNA3_5(cc) && !fallback &&
'''),
        ('''    return nbs_ids + nbs_x + GGML_PAD(nbs_y, config.nthreads*sizeof(int));
''',
         '''#if defined(GGML_USE_HIP)
    // strixllama: the static LDS grid copy (strixllama_iq3s_grid_lds) counts against the same budget
    const size_t nbs_grid = config.type == GGML_TYPE_IQ3_S ? 512*sizeof(uint32_t) : 0;
#else
    const size_t nbs_grid = 0;
#endif // GGML_USE_HIP
    return nbs_ids + nbs_x + GGML_PAD(nbs_y, config.nthreads*sizeof(int)) + nbs_grid;
'''),
    ],
    os.path.join(tree, "ggml", "src", "ggml-cuda", "mmq-load-tiles.cuh"): [
        ('''        for (int l = 0; l < QR3_S; ++l) {
            const int2 grid_pos = make_int2(
''',
         '''        for (int l = 0; l < QR3_S; ++l) {
#if defined(GGML_USE_HIP) && defined(AMD_WMMA_AVAILABLE)
            // strixllama: the LDS copy of the grid that mul_mat_q_process_tile fills right after the x tile
            const uint32_t * grid = (const uint32_t *) (x_qs + I*sram_stride);
            const int2 grid_pos = make_int2(
                grid[qs[2*l+0] | ((qh << (8 - 2*l)) & 0x100)],
                grid[qs[2*l+1] | ((qh << (7 - 2*l)) & 0x100)]);
#else
            const int2 grid_pos = make_int2(
'''),
        ('''                iq3s_grid[qs[2*l+1] | ((qh << (7 - 2*l)) & 0x100)]);

            const int signs0 = __vcmpne4(((signs_packed_8[l] & 0x03) << 7) | ((signs_packed_8[l] & 0x0C) << 21), 0x00000000);
''',
         '''                iq3s_grid[qs[2*l+1] | ((qh << (7 - 2*l)) & 0x100)]);
#endif // GGML_USE_HIP && AMD_WMMA_AVAILABLE

#if defined(GGML_USE_HIP)
            // strixllama: __vcmpne4 and __vsub4 are byte loops on HIP, and this runs once per 8 weights of
            // every tile. The grid magnitudes are odd and positive (1..15), so a negated byte is
            // (255 - g) + 1 with no carry out of the byte: xor with the byte mask, add 1 in the masked bytes.
            const uint32_t m0 = strixllama_iq3s_sign_mask(signs_packed_8[l] & 0x0F);
            const uint32_t m1 = strixllama_iq3s_sign_mask(signs_packed_8[l] >> 4);
            const int grid_l = (int) ((((uint32_t) grid_pos.x) ^ m0) + (m0 & 0x01010101u));
            const int grid_h = (int) ((((uint32_t) grid_pos.y) ^ m1) + (m1 & 0x01010101u));
#else
            const int signs0 = __vcmpne4(((signs_packed_8[l] & 0x03) << 7) | ((signs_packed_8[l] & 0x0C) << 21), 0x00000000);
'''),
        ('''            const int grid_l = __vsub4(grid_pos.x ^ signs0, signs0);
            const int grid_h = __vsub4(grid_pos.y ^ signs1, signs1);

#if defined(AMD_MFMA_AVAILABLE) || defined(TURING_MMA_AVAILABLE) || defined(AMD_WMMA_AVAILABLE)
''',
         '''            const int grid_l = __vsub4(grid_pos.x ^ signs0, signs0);
            const int grid_h = __vsub4(grid_pos.y ^ signs1, signs1);
#endif // GGML_USE_HIP

#if defined(AMD_MFMA_AVAILABLE) || defined(TURING_MMA_AVAILABLE) || defined(AMD_WMMA_AVAILABLE)
'''),
    ],
    os.path.join(tree, "tests", "test-backend-ops.cpp"): [
        ('''    std::vector<std::unique_ptr<test_case>> test_cases;
    for (int kv : {2048, 40704, 40960, 101120, 101376}) {
''',
         '''    std::vector<std::unique_ptr<test_case>> test_cases;

    // strixllama: this model's expert matmuls (Qwen3.8-Flash-Next UD-IQ4_XS: 512 experts, 10 used,
    // n_embd 2560, n_ff_exp 640; gate/up IQ3_S, down IQ4_NL) at decode-sized batches, plus the same
    // shapes in other quants, to tell the dequant's cost from the bytes' cost. STRIX_MOE_PERF=1.
    if (const char * moe = getenv("STRIX_MOE_PERF")) {
        std::vector<int> ns = {1, 4, 8, 16, 32};
        if (strchr(moe, ',') || atoi(moe) > 1) {           // STRIX_MOE_PERF=8,16,24,32,48,64
            ns.clear();
            for (const char * c = moe; *c; ) { ns.push_back(atoi(c)); c = strchr(c, ','); if (!c) break; ++c; }
        }
        for (int n : ns) {
            for (ggml_type t : {GGML_TYPE_IQ3_S, GGML_TYPE_IQ4_XS, GGML_TYPE_IQ4_NL, GGML_TYPE_Q4_0, GGML_TYPE_Q4_K, GGML_TYPE_Q8_0}) {
                test_cases.emplace_back(new test_mul_mat_id(t, GGML_TYPE_F32, 512, 10, false, 640, n, 2560));   // gate / up
            }
            for (ggml_type t : {GGML_TYPE_IQ4_NL, GGML_TYPE_Q4_0, GGML_TYPE_Q8_0}) {
                test_cases.emplace_back(new test_mul_mat_id(t, GGML_TYPE_F32, 512, 10, false, 2560, n, 640));   // down
            }
        }
        return test_cases;
    }
    for (int kv : {2048, 40704, 40960, 101120, 101376}) {
'''),
    ],
}


def main():
    texts = {p: io.open(p, encoding="utf-8").read() for p in EDITS}
    if any(MARKER in t for t in texts.values()):
        print("already applied")
        return
    for p, pairs in EDITS.items():
        for old, new in pairs:
            if texts[p].count(old) != 1:
                sys.exit("anchor found %d times, expected once, in %s" % (texts[p].count(old), p))
            texts[p] = texts[p].replace(old, new, 1)
    for p, t in texts.items():
        io.open(p, "w", encoding="utf-8", newline="").write(t)
    print("patched", ", ".join(os.path.basename(p) for p in EDITS))


if __name__ == "__main__":
    main()
