#!/usr/bin/env python3
"""IQ3_S expert gate/up on a dequantization spread over the block, with fewer VALU instructions and no load stalls

Prefill's largest kernel: the routed IQ3_S gate/up + SwiGLU (MMB_GLU) ran at 21 TFLOPS against a 53 TFLOPS WMMA peak. On RDNA3.5 the VALU and the WMMA unit do not overlap on a SIMD, so the dequantization's instructions are WMMA time: four threads per row instead of one, the sign put on an F16 copy of the grid so the scale product is one v_fma_mix (exact, so the same bf16), raw bytes kept whole until the dequantization (split at the load, they made every step wait on its loads), SGPR-base addressing and native-vector prefetch registers (a HIP uint4 array went through scratch), a valid-fragment dispatch hoisted out of the step loop, and a big-tile threshold of 32 rows. 25.0 -> 20.2 ms a layer at 8192 tokens on the recorded routing; the 18.6K real-text prefill 969 -> ~1080 t/s; 48 greedy tokens and every top-5 probability bitwise the same as 0.1.8. test-backend-ops gets the MOE_GLU case (STRIX_MOE_GLU_PERF, also in test mode) and STRIX_MOE_IDS_FILE, which replays routings recorded with STRIX_MMB_GLU_DUMP.

Generated by tools/make_patch_script.py from the tree it must reproduce, so every anchor is
unique by construction. 8 hunks across 2 file(s).

Usage: python patches/apply_moe_glu3.py [tree]
"""
import io
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
tree = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "src", "llama.cpp")
MARKER = 'mmb_tile_gemm_glu3'

EDITS = {
    os.path.join(tree, "ggml", "src", "ggml-cuda", "mmb.cu"): [
        ('''#include <unordered_set>

namespace {

typedef short v16s __attribute__((ext_vector_type(16)));
typedef float v8f  __attribute__((ext_vector_type(8)));
''',
         '''#include <type_traits>
#include <unordered_set>

namespace {

typedef short v16s __attribute__((ext_vector_type(16)));
typedef float v8f  __attribute__((ext_vector_type(8)));
typedef uint32_t mmb_u32x2 __attribute__((ext_vector_type(2)));
typedef uint32_t mmb_u32x4 __attribute__((ext_vector_type(4)));
'''),
        ('''
// F32 x F32 -> F32 GEMM with F32-equivalent precision on WMMA: each operand is split into F16 hi + F16 lo at tile load and
''',
         '''
// strixllama: the IQ3_S gate/up tile. BM = 64 and the step's dequantization is spread over the whole block, four
// threads per row with 16 of its 64 weights each (one thread per row left six of the eight waves waiting at the
// barrier). On RDNA3.5 the VALU and the WMMA unit do not run at the same time on a SIMD, so every instruction of
// the dequantization costs WMMA time; the rest is about spending fewer of them and never waiting on a load:
// - weight = bf16(d * (+-g)): g and -g are exact in F16 and d * g is exact in F32 (at most 20 significant bits),
//   so the sign goes onto the F16 grid value (an LDS copy of iq3s_grid with each byte as an F16) and the product
//   is one v_fma_mix: the same bits as bf16(+-(d * (float) g)) with no byte convert and no compare/select;
// - a thread's raw bytes stay whole in registers until it dequantizes them after the step's WMMAs: split into
//   bytes at the load, they made every step wait for its weight loads before the first WMMA;
// - the loads address the tile from a uniform base (the superblock of row 0, the step's column 0 of the
//   activations) with 32-bit per-thread offsets, and the prefetch registers are native vectors (a HIP uint4 array
//   here was not promoted to registers and went through scratch);
// - a column past the expert's tokens reads token 0: finite values in a column that is never stored, instead of
//   a branch and a zero fill per load;
// - the step loop is instantiated per count of this wave's valid fragments (a uniform branch outside the loop,
//   where a test per fragment branched around every WMMA pair), and a scheduling barrier keeps one 16-deep slice
//   of fragments in registers at a time.
// Each output element is the same WMMA chain over K as in mmb_tile_gemm_glu, so the results are bitwise the same.
template <int N, typename F> __device__ __forceinline__ void mmb_with_na0(const int na, F && f) {
    if (na == N) { f(std::integral_constant<int, N>{}); return; }
    if constexpr (N > 0) { mmb_with_na0<N - 1>(na, f); }
}
template <int BN, int WTM, int WTN, typename XRowFn, typename DRowFn>
__device__ __forceinline__ void mmb_tile_gemm_glu3(const uint8_t * __restrict__ Wg, const uint8_t * __restrict__ Wu, const uint32_t wrow_bytes,
        const uint16_t * __restrict__ Xh, const int K, XRowFn xrow, float * __restrict__ D, uint16_t * __restrict__ Dh, const bool store_f32,
        const int M, DRowFn drow, const int m0, const int n_cols, uint16_t * Ag, uint16_t * Au, uint16_t * Bs, const mmb_u32x2 * grid16) {
    constexpr int BM = 64, WAVES_M = BM / WTM, TM = WTM / 16, TN = WTN / 16;
    constexpr int B_ITEMS = (BN * 8) / MMB_NT;
    static_assert(BM * 4 == MMB_NT, "four threads per row of a 64-row tile");
    const int tid = threadIdx.x, lane = tid & 31, wave = __builtin_amdgcn_readfirstlane(tid >> 5);
    const int wm = wave % WAVES_M, wn = wave / WAVES_M;
    // this thread's row, and its 16 weights of a step: half ph of the quarter superblock, grid pairs pil and pil + 1
    const int prow = tid >> 2, ph = (tid & 3) >> 1, pil = (tid & 1) * 2;
    const uint32_t ro = (uint32_t) prow * wrow_bytes;
    const uint32_t o_qs = ro + 2 + 8 * ph + 2 * pil, o_qh = ro + 66 + ph, o_sg = ro + 74 + 4 * ph + pil, o_sc = ro + 106;
    struct raw3 { uint32_t qs; uint16_t d, sg; uint8_t qh, sc; };
    raw3 rg, ru;
    auto ld3 = [&](const uint8_t * __restrict__ sb, const int q, raw3 & r) __attribute__((always_inline)) {   // sb: the step's superblock of row 0
        r.d = *(const uint16_t *)(sb + ro);
        __builtin_memcpy(&r.qs, (sb + 16 * q) + o_qs, 4);
        r.qh = (sb + 2 * q)[o_qh];
        r.sg = *(const uint16_t *)((sb + 8 * q) + o_sg);
        r.sc = (sb + q)[o_sc];
    };
    auto dq3 = [&](const raw3 & r, uint32_t * arow) __attribute__((always_inline)) {
        typedef uint16_t u16x2 __attribute__((ext_vector_type(2)));
        const float d0 = mmb_h2f(r.d);
        const float d = d0 * (float) (1 + 2 * ((r.sc >> (4 * ph)) & 0xf));
        const uint32_t qhb = r.qh;
#pragma unroll
        for (int t = 0; t < 2; ++t) {
            const int il = pil + t;
            const mmb_u32x2 g1 = grid16[((r.qs >> (16 * t)) & 0xff) | ((qhb << (8 - 2 * il)) & 256)];
            const mmb_u32x2 g2 = grid16[((r.qs >> (16 * t + 8)) & 0xff) | ((qhb << (7 - 2 * il)) & 256)];
            const uint32_t sgn = (r.sg >> (8 * t)) & 0xff;
            const u16x2 s2 = __builtin_bit_cast(u16x2, sgn | (sgn << 15));   // lanes: the signs, and the signs >> 1
            const uint32_t gp[4] = {g1.x, g1.y, g2.x, g2.y};
            uint32_t * out = arow + (32 * ph + 8 * il) / 2;
#pragma unroll
            for (int q = 0; q < 4; ++q) {
                const uint16_t sh = (uint16_t)(15 - 2 * q);
                const uint32_t m = __builtin_bit_cast(uint32_t, s2 << (u16x2){sh, sh});   // bits 15, 31: signs 2q, 2q + 1
                const uint32_t gs = (m & 0x80008000u) | (gp[q] & 0x7fff7fffu);
                const float a = d * (float) __builtin_bit_cast(_Float16, (uint16_t)(gs & 0xffff));
                const float b = d * (float) __builtin_bit_cast(_Float16, (uint16_t)(gs >> 16));
                out[q] = mmb_pack2(a, b);
            }
        }
    };
    uint32_t boff[B_ITEMS];   // byte offset of this thread's 16 bytes of a step from the step's column 0 of token 0
#pragma unroll
    for (int i = 0; i < B_ITEMS; ++i) { const int c = tid + i * MMB_NT; const int t = xrow(c >> 3);
        boff[i] = ((uint32_t) (t >= 0 ? t : 0) * (uint32_t) K + (uint32_t) (c & 7) * 8) * 2; }
    mmb_u32x4 bst[B_ITEMS];
    uint32_t * const agr = (uint32_t *)(Ag + prow * MMB_LDS_STRIDE), * const aur = (uint32_t *)(Au + prow * MMB_LDS_STRIDE);
    auto load_regs = [&](const int ks) __attribute__((always_inline)) {
        const size_t sbo = (size_t)(ks >> 2) * 110;
        ld3(Wg + sbo, ks & 3, rg);
        ld3(Wu + sbo, ks & 3, ru);
        const uint8_t * xb = (const uint8_t *)(Xh + ks * MMB_BK);
#pragma unroll
        for (int i = 0; i < B_ITEMS; ++i) { bst[i] = *(const mmb_u32x4 *)(xb + boff[i]); }
    };
    auto store_lds = [&]() __attribute__((always_inline)) {
        dq3(rg, agr); dq3(ru, aur);
#pragma unroll
        for (int i = 0; i < B_ITEMS; ++i) { const int c = tid + i * MMB_NT; *(mmb_u32x4 *)(Bs + (c >> 3) * MMB_LDS_STRIDE + (c & 7) * 8) = bst[i]; }
    };
    v8f accg[TM][TN], accu[TM][TN];
#pragma unroll
    for (int i = 0; i < TM; ++i)
#pragma unroll
        for (int j = 0; j < TN; ++j)
#pragma unroll
            for (int e = 0; e < 8; ++e) { accg[i][j][e] = 0.f; accu[i][j][e] = 0.f; }
    // this wave's fragments that hold valid columns: a prefix of its TN (the rest are never computed or stored)
    const int rem = n_cols - wn * WTN;
    const int na = rem <= 0 ? 0 : rem >= WTN ? TN : (rem + 15) / 16;
    const int nks = K / MMB_BK;
    mmb_with_na0<TN>(na, [&](auto nac) __attribute__((always_inline)) {
        constexpr int NA = decltype(nac)::value;
        load_regs(0); store_lds(); __syncthreads();
        for (int ks = 0; ks < nks; ++ks) {
            if (ks + 1 < nks) load_regs(ks + 1);
            if constexpr (NA > 0) {
#pragma unroll
                for (int kk = 0; kk < MMB_BK; kk += 16) {
                    v16s ag[TM], au[TM], b[NA]; const int r = lane & 15;
#pragma unroll
                    for (int i = 0; i < TM; ++i) { const int off = (wm * WTM + i * 16 + r) * MMB_LDS_STRIDE + kk;
                        ag[i] = __builtin_bit_cast(v16s, (uint4[2]){*(const uint4 *)(Ag + off), *(const uint4 *)(Ag + off + 8)});
                        au[i] = __builtin_bit_cast(v16s, (uint4[2]){*(const uint4 *)(Au + off), *(const uint4 *)(Au + off + 8)}); }
#pragma unroll
                    for (int j = 0; j < NA; ++j) { const uint16_t * p = Bs + (wn * WTN + j * 16 + r) * MMB_LDS_STRIDE + kk;
                        b[j] = __builtin_bit_cast(v16s, (uint4[2]){*(const uint4 *)p, *(const uint4 *)(p + 8)}); }
#pragma unroll
                    for (int i = 0; i < TM; ++i)
#pragma unroll
                        for (int j = 0; j < NA; ++j) {
                            accg[i][j] = __builtin_amdgcn_wmma_f32_16x16x16_bf16_w32(b[j], ag[i], accg[i][j]);
                            accu[i][j] = __builtin_amdgcn_wmma_f32_16x16x16_bf16_w32(b[j], au[i], accu[i][j]);
                        }
                    __builtin_amdgcn_sched_barrier(0);
                }
            }
            __syncthreads();
            if (ks + 1 < nks) store_lds();
            __syncthreads();
        }
    });
    float * stg = (float *)((BN * MMB_LDS_STRIDE * 2 >= MMB_NT / 32 * 1024) ? Bs : Ag) + wave * 256;
#pragma unroll
    for (int i = 0; i < TM; ++i) {
        const int ml = wm * WTM + i * 16; const bool ok = ml < M - m0;
#pragma unroll
        for (int j = 0; j < TN; ++j) {
            if (ok && j < na) {
                v8f v;
#pragma unroll
                for (int e = 0; e < 8; ++e) { v[e] = ggml_cuda_op_silu_single(accg[i][j][e]) * accu[i][j][e]; }
                mmb_store_tile(v, stg, D, Dh, store_f32, M, drow, wn * WTN + j * 16, m0 + ml, lane);
            } else { __syncthreads(); __syncthreads(); }
        }
    }
}

template <int BN, int WTM, int WTN>
__global__ void __launch_bounds__(MMB_NT, 2)
mmb_routed_glu3_kernel(const uint8_t * __restrict__ Wg, const uint8_t * __restrict__ Wu, const size_t expert_bytes, const uint16_t * __restrict__ Xh,
        float * __restrict__ D, uint16_t * __restrict__ Dh, const bool store_f32,
        const int32_t * __restrict__ ids_src, const int32_t * __restrict__ ids_dst, const int32_t * __restrict__ bounds,
        const uint32_t * __restrict__ desc, const int M, const int K) {
    constexpr int BM = 64;
    __shared__ __align__(16) uint16_t Ag[BM * MMB_LDS_STRIDE];
    __shared__ __align__(16) uint16_t Au[BM * MMB_LDS_STRIDE];
    __shared__ __align__(16) uint16_t Bs[BN * MMB_LDS_STRIDE];
    __shared__ mmb_u32x2 grid16[512];   // iq3s_grid with each byte as an F16
    const uint32_t dsc = desc[blockIdx.y];
    if (dsc == UINT32_MAX) return;
    for (int i = threadIdx.x; i < 512; i += MMB_NT) {
        const uint32_t g = iq3s_grid[i];
        uint32_t h[4];
#pragma unroll
        for (int j = 0; j < 4; ++j) { h[j] = __builtin_bit_cast(uint16_t, (_Float16) (float) ((g >> (8 * j)) & 0xff)); }
        grid16[i] = (mmb_u32x2){h[0] | (h[1] << 16), h[2] | (h[3] << 16)};
    }
    __syncthreads();
    const int e = dsc & 0xffff, jt = dsc >> 16;
    const int r0 = bounds[e] + jt * BN, cnt = bounds[e + 1] - r0;
    const int m0 = blockIdx.x * BM;
    const uint32_t wrow_bytes = (uint32_t)(K / 256) * 110;
    mmb_tile_gemm_glu3<BN, WTM, WTN>(Wg + (size_t)e * expert_bytes + (size_t)m0 * wrow_bytes, Wu + (size_t)e * expert_bytes + (size_t)m0 * wrow_bytes, wrow_bytes, Xh, K,
        [&](int i) { return (i < cnt) ? ids_src[r0 + i] : -1; }, D, Dh, store_f32, M, [&](int i) { return (i < cnt) ? ids_dst[r0 + i] : -1; }, m0, cnt, Ag, Au, Bs, grid16);
}

// F32 x F32 -> F32 GEMM with F32-equivalent precision on WMMA: each operand is split into F16 hi + F16 lo at tile load and
'''),
        ('''    constexpr int BN_SMALL = 32, THRESH = 128;
    const int nbig_max   = n_rows / BN + E + 1;
    const int nsmall_max = E * ((THRESH + BN_SMALL - 1) / BN_SMALL) + 1;
    ggml_cuda_pool_alloc<uint32_t> desc_big(ctx.pool(), nbig_max);
    ggml_cuda_pool_alloc<uint32_t> desc_small(ctx.pool(), nsmall_max);
    mmb_build_desc2<<<1, 1024, 0, stream>>>(bounds.get(), desc_big.get(), desc_small.get(), E, nbig_max, nsmall_max, BN, BN_SMALL, THRESH);
    uint16_t * Dh = ggml_cuda_mmb_slot_reserve(ctx, 2, glu, (size_t) n_rows * M);
    const bool store_f32 = !ggml_cuda_mmb_is_bf16_only(glu);
    const bool iq3s = gw->type == GGML_TYPE_IQ3_S;
    static unsigned hits = 0; if (hits++ < 2) fprintf(stderr, "MMB_GLU fused gate/up+swiglu: M=%d K=%d rows=%d store_f32=%d type=%s\\n", M, K, n_rows, (int) store_f32, iq3s ? "IQ3_S" : "IQ4_NL");
    const uint8_t * Wg = (const uint8_t *) gw->data, * Wu = (const uint8_t *) uw->data; float * D = (float *) glu->data; const size_t eb = (size_t) gw->nb[2];
    dim3 gbig((M + 63) / 64, nbig_max), gsmall((M + 63) / 64, nsmall_max);
    if (iq3s) {
''',
         '''    const bool iq3s = gw->type == GGML_TYPE_IQ3_S;
    // strixllama: IQ3_S goes through mmb_tile_gemm_glu3; STRIX_MMB_GLU3=0 goes back to mmb_tile_gemm_glu (same results,
    // for A/B). glu3's tiles cost little besides their dequantization, so an expert of 32 rows or more is cheaper as one
    // big tile than as several small ones, each dequantizing the same weights again: its threshold is 32, not 128.
    static const bool glu3 = !getenv("STRIX_MMB_GLU3") || atoi(getenv("STRIX_MMB_GLU3")) != 0;
    const bool use3 = iq3s && glu3;
    constexpr int BN_SMALL = 32;
    const int thresh = use3 ? 32 : 128;
    const int nbig_max   = n_rows / BN + E + 1;
    const int nsmall_max = E * ((thresh + BN_SMALL - 1) / BN_SMALL) + 1;
    ggml_cuda_pool_alloc<uint32_t> desc_big(ctx.pool(), nbig_max);
    ggml_cuda_pool_alloc<uint32_t> desc_small(ctx.pool(), nsmall_max);
    mmb_build_desc2<<<1, 1024, 0, stream>>>(bounds.get(), desc_big.get(), desc_small.get(), E, nbig_max, nsmall_max, BN, BN_SMALL, thresh);
    // strixllama: STRIX_MMB_GLU_DUMP=<file> appends every call's rows per expert ("n_rows n_experts count0 count1 ...",
    // what test-backend-ops' STRIX_MOE_IDS_FILE replays); it synchronises the stream, so it is for recording only
    static const char * dump = getenv("STRIX_MMB_GLU_DUMP");
    if (dump) {
        std::vector<int32_t> hb(E + 1);
        CUDA_CHECK(cudaMemcpyAsync(hb.data(), bounds.get(), (E + 1) * sizeof(int32_t), cudaMemcpyDeviceToHost, stream));
        CUDA_CHECK(cudaStreamSynchronize(stream));
        if (FILE * f = fopen(dump, "a")) {
            fprintf(f, "%d %d", n_rows, E);
            for (int e = 0; e < E; ++e) { fprintf(f, " %d", hb[e + 1] - hb[e]); }
            fputc('\\n', f);
            fclose(f);
        }
    }
    uint16_t * Dh = ggml_cuda_mmb_slot_reserve(ctx, 2, glu, (size_t) n_rows * M);
    const bool store_f32 = !ggml_cuda_mmb_is_bf16_only(glu);
    static unsigned hits = 0; if (hits++ < 2) fprintf(stderr, "MMB_GLU fused gate/up+swiglu: M=%d K=%d rows=%d store_f32=%d type=%s\\n", M, K, n_rows, (int) store_f32, iq3s ? "IQ3_S" : "IQ4_NL");
    const uint8_t * Wg = (const uint8_t *) gw->data, * Wu = (const uint8_t *) uw->data; float * D = (float *) glu->data; const size_t eb = (size_t) gw->nb[2];
    dim3 gbig((M + 63) / 64, nbig_max), gsmall((M + 63) / 64, nsmall_max);
    if (use3) {
        GGML_ASSERT((size_t) n_rows_x * K * 2 < ((size_t) 1 << 32));   // glu3's 32-bit activation offsets
        mmb_routed_glu3_kernel<BN, 32, 32><<<gbig, MMB_NT, 0, stream>>>(Wg, Wu, eb, xhp, D, Dh, store_f32, ids_src1.get(), ids_dst.get(), bounds.get(), desc_big.get(), M, K);
        mmb_routed_glu3_kernel<BN_SMALL, 16, 16><<<gsmall, MMB_NT, 0, stream>>>(Wg, Wu, eb, xhp, D, Dh, store_f32, ids_src1.get(), ids_dst.get(), bounds.get(), desc_small.get(), M, K);
    } else if (iq3s) {
'''),
    ],
    os.path.join(tree, "tests", "test-backend-ops.cpp"): [
        ('''
static void init_mul_mat_id_ids(ggml_context * ctx, int n_mats) {
''',
         '''
// strixllama: STRIX_MOE_IDS_FILE (lines of "n_rows n_experts count0 count1 ..." as STRIX_MMB_GLU_DUMP writes them) replaces
// the uniform routing with recorded ones: the lines whose n_rows is a multiple of this test's token count and whose expert
// count matches, one per call in turn, each expert repeated count times and shuffled over the token slots
static bool init_recorded_ids(ggml_tensor * t, int n_mats) {
    static const char * path = getenv("STRIX_MOE_IDS_FILE");
    if (!path) {
        return false;
    }
    static std::vector<std::vector<int>> lines;
    static bool loaded = false;
    if (!loaded) {
        loaded = true;
        std::ifstream f(path);
        std::string l;
        while (std::getline(f, l)) {
            std::istringstream is(l);
            std::vector<int> v;
            int x;
            while (is >> x) {
                v.push_back(x);
            }
            if (v.size() > 2) {
                lines.push_back(v);
            }
        }
    }
    const int64_t n = t->ne[1];
    std::vector<const std::vector<int> *> cand;
    for (const auto & v : lines) {
        if (v[1] == n_mats && (int64_t) v.size() == 2 + n_mats && v[0] % n == 0 && v[0] / n <= t->ne[0]) {
            cand.push_back(&v);
        }
    }
    if (cand.empty()) {
        return false;
    }
    static size_t turn = 0;
    const std::vector<int> & v = *cand[turn++ % cand.size()];
    const int n_used = (int) (v[0] / n);
    std::vector<int32_t> pool;
    for (int e = 0; e < n_mats; e++) {
        pool.insert(pool.end(), v[2 + e], e);
    }
    std::default_random_engine rng(1234 + (unsigned) turn);
    std::shuffle(pool.begin(), pool.end(), rng);
    std::vector<int32_t> data(t->ne[0]);
    for (int64_t r = 0; r < n; r++) {
        for (int i = 0; i < t->ne[0]; i++) {
            data[i] = i < n_used ? pool[r * n_used + i] : i % n_mats;
        }
        ggml_backend_tensor_set(t, data.data(), r * t->nb[1], t->ne[0] * sizeof(int32_t));
    }
    return true;
}

static void init_mul_mat_id_ids(ggml_context * ctx, int n_mats) {
'''),
        ('''        if (t->type != GGML_TYPE_I32 || ggml_is_view_op(t->op)) {
            continue;
''',
         '''        if (t->type != GGML_TYPE_I32 || ggml_is_view_op(t->op)) {
            continue;
        }
        if (init_recorded_ids(t, n_mats)) {
            continue;
'''),
        ('''        return "MUL_MAT_ID_FUSION";
    }
''',
         '''        return "MUL_MAT_ID_FUSION";
    }
};

// strixllama: a MoE layer's gate and up projections and their SwiGLU, built the way build_moe_ffn builds them
// (up, then gate, then swiglu_split; the token activations broadcast across the used experts), so a backend's
// fused GLU path takes it as it would in the model. STRIX_MOE_GLU_PERF=8192,16384.
struct test_moe_glu : public test_case {
    const ggml_type type_a;
    const int n_mats;
    const int n_used;
    const int64_t m;    // n_ff
    const int64_t n;    // tokens
    const int64_t k;    // n_embd

    std::string vars() override {
        return VARS_TO_STR6(type_a, n_mats, n_used, m, n, k);
    }

    double max_nmse_err() override {
        return 5e-4;
    }

    uint64_t op_flops(ggml_tensor * t) override {
        GGML_UNUSED(t);
        return 2 * 2 * m * k * n * n_used;
    }

    test_moe_glu(ggml_type type_a, int n_mats, int n_used, int64_t m, int64_t n, int64_t k)
        : type_a(type_a), n_mats(n_mats), n_used(n_used), m(m), n(n), k(k) {}

    ggml_tensor * build_graph(ggml_context * ctx) override {
        ggml_tensor * gate_w = ggml_new_tensor_3d(ctx, type_a, k, m, n_mats);
        ggml_set_name(gate_w, "gate_w");
        ggml_tensor * up_w = ggml_new_tensor_3d(ctx, type_a, k, m, n_mats);
        ggml_set_name(up_w, "up_w");
        ggml_tensor * ids = ggml_new_tensor_2d(ctx, GGML_TYPE_I32, n_mats, n);
        ggml_set_name(ids, "ids");
        ids = ggml_view_2d(ctx, ids, n_used, n, ids->nb[1], 0);
        ggml_set_name(ids, "view_of_ids");
        ggml_tensor * x = ggml_new_tensor_3d(ctx, GGML_TYPE_F32, k, 1, n);
        ggml_set_name(x, "x");
        ggml_tensor * up = ggml_mul_mat_id(ctx, up_w, x, ids);
        ggml_set_name(up, "up");
        ggml_tensor * gate = ggml_mul_mat_id(ctx, gate_w, x, ids);
        ggml_set_name(gate, "gate");
        ggml_tensor * out = ggml_swiglu_split(ctx, gate, up);
        ggml_set_name(out, "out");
        return out;
    }

    void initialize_tensors(ggml_context * ctx) override {
        init_mul_mat_id_tensors(ctx, n_mats);
    }

    void reinit_perf_iter(ggml_context * ctx) override {
        init_mul_mat_id_ids(ctx, n_mats);
    }

    bool run_whole_graph() override { return true; }

    std::string op_desc(ggml_tensor * t) override {
        GGML_UNUSED(t);
        return "MOE_GLU";
    }
'''),
        ('''    }
    if (const char * moe = getenv("STRIX_MOE_PERF")) {
''',
         '''    }
    // strixllama: the prefill-sized MoE work of this model as the model builds it: the fused gate/up SwiGLU (IQ3_S in the
    // file, and IQ4_NL / IQ4_XS for comparison) and the down projection (IQ4_NL, and the five Q8_0 layers).
    // STRIX_MOE_GLU_PERF=8192 or a token list.
    if (const char * glu = getenv("STRIX_MOE_GLU_PERF")) {
        std::vector<int> ns = {8192};
        if (strchr(glu, ',') || atoi(glu) > 1) {
            ns.clear();
            for (const char * c = glu; *c; ) { ns.push_back(atoi(c)); c = strchr(c, ','); if (!c) break; ++c; }
        }
        const char * types = getenv("STRIX_MOE_GLU_TYPES");   // "iq3_s" by default; "all" adds the others
        const bool all = types && strcmp(types, "all") == 0;
        for (int n : ns) {
            for (ggml_type t : {GGML_TYPE_IQ3_S, GGML_TYPE_IQ4_NL, GGML_TYPE_IQ4_XS}) {
                if (t != GGML_TYPE_IQ3_S && !all) continue;
                test_cases.emplace_back(new test_moe_glu(t, 512, 10, 640, n, 2560));
            }
            for (ggml_type t : {GGML_TYPE_IQ4_NL, GGML_TYPE_Q8_0}) {
                if (t != GGML_TYPE_IQ4_NL && !all) continue;
                test_cases.emplace_back(new test_mul_mat_id(t, GGML_TYPE_F32, 512, 10, false, 2560, n, 640));   // down
            }
        }
        return test_cases;
    }
    if (const char * moe = getenv("STRIX_MOE_PERF")) {
'''),
        ('''            test_cases = make_test_cases_eval();
''',
         '''            // strixllama: STRIX_MOE_GLU_PERF also checks the prefill-sized MoE cases against the CPU in test mode
            test_cases = getenv("STRIX_MOE_GLU_PERF") ? make_test_cases_perf() : make_test_cases_eval();
'''),
    ],
}


def main():
    texts = {p: io.open(p, encoding="utf-8").read() for p in EDITS}
    if any(MARKER in t for t in texts.values()):
        print("already applied")
        return
    for p, pairs in EDITS.items():
        for old, new in pairs:
            if texts[p].count(old) != 1:
                sys.exit("anchor found %d times, expected once, in %s" % (texts[p].count(old), p))
            texts[p] = texts[p].replace(old, new, 1)
    for p, t in texts.items():
        io.open(p, "w", encoding="utf-8", newline="").write(t)
    print("patched", ", ".join(os.path.basename(p) for p in EDITS))


if __name__ == "__main__":
    main()
