#!/usr/bin/env python3
"""The HC gate and PLE conv fusions for Unsloth's weight types: Q8_0 HC weights, an F32 conv weight

The base fuses the hyper-connection gate (GEMM + sigmoid + stream mix) and the PLE conv taps, but only for IQ4_NL HC weights and an F16 conv weight - the author's file. Unsloth's keeps the HC weights at Q8_0 and the conv weight at F32, so LLAMA_HC_GATEMIX and LLAMA_PLE_CONV were inert there. The Q8_0 gate kernel reads the streams in F32 and keeps the gate in F32, as the unfused path does, so the result is bitwise the same.

Generated by tools/make_patch_script.py from the tree it must reproduce, so every anchor is
unique by construction. 26 hunks across 3 file(s).

Usage: python D:/Work/strixllama/patches/apply_hc_q8_fusions.py [tree]
"""
import io
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
tree = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "src", "llama.cpp")
MARKER = 'hc_gate_mix_kernel<4, 1, true>'

EDITS = {
    os.path.join(tree, "ggml", "src", "ggml-cuda", "mmb.cu"): [
        ('''template <int HC>
''',
         '''// strixllama: WTYPE 0 is IQ4_NL (the author's file), 1 is Q8_0 (Unsloth's, whose HC weights are Q8_0). XF32 reads
// the normalised streams as F32 and applies the sigmoid to the F32 accumulator, which is exactly what the unfused
// MMB GEMM + hc_mix_reduce do when the BF16 intermediates (LLAMA_MMB_HC16) are off - so it is bitwise the same
// result, only without writing the [hc*E, T] gate out and reading it back.
template <int HC, int WTYPE = 0, bool XF32 = false>
'''),
        ('''hc_gate_mix_kernel(const uint8_t * __restrict__ W, const uint16_t * __restrict__ Lo, const uint16_t * __restrict__ Xn, float * __restrict__ Out,
''',
         '''hc_gate_mix_kernel(const uint8_t * __restrict__ W, const uint16_t * __restrict__ Lo, const uint16_t * __restrict__ Xn,
        const float * __restrict__ XnF, float * __restrict__ Out,
'''),
        ('''    static_assert(BM <= MMB_NT, "one A row per thread");
    __shared__ __align__(16) uint16_t As[BM * MMB_LDS_STRIDE];
''',
         '''    static_assert(BM <= MMB_NT, "one A row per thread");
    static_assert(WTYPE == 0 || WTYPE == 1, "IQ4_NL or Q8_0");
    __shared__ __align__(16) uint16_t As[BM * MMB_LDS_STRIDE];
'''),
        ('''    const size_t wrow_bytes = (size_t)(K / 32) * 18;
    constexpr int B_ITEMS = (BN * 8) / MMB_NT;
    uint4 a0 = make_uint4(0,0,0,0), a1 = make_uint4(0,0,0,0); uint32_t a2 = 0; uint4 bst[B_ITEMS]; int brow[B_ITEMS];
''',
         '''    const size_t wrow_bytes = (size_t)(K / 32) * (WTYPE == 0 ? 18 : 34);
    constexpr int B_ITEMS = (BN * 8) / MMB_NT;
    uint4 a0 = make_uint4(0,0,0,0), a1 = make_uint4(0,0,0,0), a3 = make_uint4(0,0,0,0), a4 = make_uint4(0,0,0,0); uint32_t a2 = 0;
    uint4 bst[B_ITEMS]; int brow[B_ITEMS];
'''),
        ('''        if (tid < BM) { const uint8_t * p = arow + (size_t)ks * 36; a0 = *(const uint4 *)(p); a1 = *(const uint4 *)(p + 16); a2 = *(const uint32_t *)(p + 32); }
''',
         '''        if (tid < BM) {
            if constexpr (WTYPE == 0) { const uint8_t * p = arow + (size_t)ks * 36; a0 = *(const uint4 *)(p); a1 = *(const uint4 *)(p + 16); a2 = *(const uint32_t *)(p + 32); }
            else { const uint8_t * p = arow + (size_t)ks * 68;
                   a0 = *(const uint4 *)(p); a1 = *(const uint4 *)(p + 16); a3 = *(const uint4 *)(p + 32); a4 = *(const uint4 *)(p + 48); a2 = *(const uint32_t *)(p + 64); }
        }
'''),
        ('''        if (tid < BM) mmb_dq_row36(a0, a1, a2, (uint32_t *)(As + tid * MMB_LDS_STRIDE));
''',
         '''        if (tid < BM) {
            if constexpr (WTYPE == 0) mmb_dq_row36(a0, a1, a2, (uint32_t *)(As + tid * MMB_LDS_STRIDE));
            else                      mmb_dq_row68(a0, a1, a3, a4, a2, (uint32_t *)(As + tid * MMB_LDS_STRIDE));
        }
'''),
        ('''            const uint16_t * xr = Xn + (size_t)t * ((size_t)HC * E) + ch;
''',
         ''''''),
        ('''#pragma unroll
            for (int c = 0; c < HC; ++c) {
                const float g = __uint_as_float(((uint32_t) mmb_f2bf(acc[c][j][e])) << 16);   // the gate GEMM's BF16 epilogue rounding
                const float term = gm_mul_rn(gm_bf2f(xr[(size_t)c * E]), gm_sigmoid(g));
                s = (c == 0) ? term : gm_add_rn(s, term);
''',
         '''            if constexpr (XF32) {
                const float * xr = XnF + (size_t)t * ((size_t)HC * E) + ch;
#pragma unroll
                for (int c = 0; c < HC; ++c) {
                    const float term = gm_mul_rn(xr[(size_t)c * E], gm_sigmoid(acc[c][j][e]));
                    s = (c == 0) ? term : gm_add_rn(s, term);
                }
            } else {
                const uint16_t * xr = Xn + (size_t)t * ((size_t)HC * E) + ch;
#pragma unroll
                for (int c = 0; c < HC; ++c) {
                    const float g = __uint_as_float(((uint32_t) mmb_f2bf(acc[c][j][e])) << 16);   // the gate GEMM's BF16 epilogue rounding
                    const float term = gm_mul_rn(gm_bf2f(xr[(size_t)c * E]), gm_sigmoid(g));
                    s = (c == 0) ? term : gm_add_rn(s, term);
                }
'''),
        ('''    if (mmb_tall() && src0->type == GGML_TYPE_IQ4_NL && M <= 384 && K >= 4096 && T >= 2048) {   // tall-M tile: HC down|inject [10240 -> 324], activations read once
''',
         '''    // tall-M tile: HC down|inject [10240 -> 324], activations read once. strixllama: Q8_0 as well as IQ4_NL - Unsloth's
    // HC weights are Q8_0. Every output element sees the same WMMA sequence as in the 128-row tile, so the result is
    // bitwise the one the separate down and inject GEMMs give.
    if (mmb_tall() && (src0->type == GGML_TYPE_IQ4_NL || src0->type == GGML_TYPE_Q8_0) && M <= 384 && K >= 4096 && T >= 2048) {
'''),
        ('''        if (wide) { dim3 grid(1, (T + 63) / 64); mmb_dense_kernel<384, 64, 96, 32, 0><<<grid, MMB_NT, 0, stream>>>(W, xhp, D, (uint16_t *) nullptr, true, M, K, T); }
        else      { dim3 grid(1, (T + 31) / 32); mmb_dense_kernel<384, 32, 96, 16, 0><<<grid, MMB_NT, 0, stream>>>(W, xhp, D, (uint16_t *) nullptr, true, M, K, T); }
''',
         '''        const bool q8 = src0->type == GGML_TYPE_Q8_0;
        if (wide) { dim3 grid(1, (T + 63) / 64);
            if (q8) mmb_dense_kernel<384, 64, 96, 32, 1><<<grid, MMB_NT, 0, stream>>>(W, xhp, D, (uint16_t *) nullptr, true, M, K, T);
            else    mmb_dense_kernel<384, 64, 96, 32, 0><<<grid, MMB_NT, 0, stream>>>(W, xhp, D, (uint16_t *) nullptr, true, M, K, T); }
        else      { dim3 grid(1, (T + 31) / 32);
            if (q8) mmb_dense_kernel<384, 32, 96, 16, 1><<<grid, MMB_NT, 0, stream>>>(W, xhp, D, (uint16_t *) nullptr, true, M, K, T);
            else    mmb_dense_kernel<384, 32, 96, 16, 0><<<grid, MMB_NT, 0, stream>>>(W, xhp, D, (uint16_t *) nullptr, true, M, K, T); }
'''),
        ('''        static unsigned hits = 0; if (hits++ < 2) fprintf(stderr, "MMB_TALL%s dense M=%d K=%d T=%d\\n", wide ? "(wide 384x64)" : "(384x32)", M, K, T);
''',
         '''        static unsigned hits = 0; if (hits++ < 2) fprintf(stderr, "MMB_TALL%s dense M=%d K=%d T=%d type=%s\\n", wide ? "(wide 384x64)" : "(384x32)", M, K, T, ggml_type_name(src0->type));
'''),
        ('''    if (!mmb_gatemix_flag() || hc != 4 || w->type != GGML_TYPE_IQ4_NL || lo->type != GGML_TYPE_F32 || !ggml_is_contiguous(lo) || !ggml_is_contiguous(dst)) return false;
''',
         '''    // strixllama: Q8_0 too - Unsloth's file keeps the HC weights at Q8_0, so with IQ4_NL only this never fired there
    const bool q8 = w->type == GGML_TYPE_Q8_0;
    if (!mmb_gatemix_flag() || hc != 4 || (w->type != GGML_TYPE_IQ4_NL && !q8) || lo->type != GGML_TYPE_F32 || !ggml_is_contiguous(lo) || !ggml_is_contiguous(dst)) return false;
'''),
        ('''    const uint16_t * xn16 = ggml_cuda_mmb_cache_lookup(xn);
    if (!xn16) return false;
''',
         '''    // the Q8_0 kernel reads the streams in F32 and keeps the gate in F32: the unfused path's own numerics, so it can
    // only be taken when the F32 streams are there - i.e. when xn is not a BF16-only tensor (LLAMA_MMB_HC16)
    const bool xf32 = q8 && xn->type == GGML_TYPE_F32 && ggml_is_contiguous(xn) && !ggml_cuda_mmb_is_bf16_only(xn);
    const uint16_t * xn16 = xf32 ? nullptr : ggml_cuda_mmb_cache_lookup(xn);
    if (!xf32 && !xn16) return false;
'''),
        ('''    hc_gate_mix_kernel<4><<<grid, MMB_NT, 0, stream>>>((const uint8_t *) w->data, lo16, xn16, (float *) dst->data, outh, store_f32, E, K, T, scale, bias);
''',
         '''    if (xf32) {
        hc_gate_mix_kernel<4, 1, true><<<grid, MMB_NT, 0, stream>>>((const uint8_t *) w->data, lo16, nullptr, (const float *) xn->data, (float *) dst->data, outh, store_f32, E, K, T, scale, bias);
    } else if (q8) {
        hc_gate_mix_kernel<4, 1, false><<<grid, MMB_NT, 0, stream>>>((const uint8_t *) w->data, lo16, xn16, nullptr, (float *) dst->data, outh, store_f32, E, K, T, scale, bias);
    } else {
        hc_gate_mix_kernel<4, 0, false><<<grid, MMB_NT, 0, stream>>>((const uint8_t *) w->data, lo16, xn16, nullptr, (float *) dst->data, outh, store_f32, E, K, T, scale, bias);
    }
'''),
        ('''    static unsigned hits = 0; if (hits++ < 2) fprintf(stderr, "HC_GATEMIX fused gate GEMM + sigmoid + mix: E=%d K=%d T=%d\\n", E, K, T);
''',
         '''    static unsigned hits = 0; if (hits++ < 2) fprintf(stderr, "HC_GATEMIX fused gate GEMM + sigmoid + mix: E=%d K=%d T=%d type=%s%s\\n", E, K, T, ggml_type_name(w->type), xf32 ? " f32-streams" : "");
'''),
    ],
    os.path.join(tree, "ggml", "src", "ggml-cuda", "ggml-cuda.cu"): [
        ('''        if (w->type == GGML_TYPE_IQ4_NL && w->ne[0] == 320 && w->ne[1] == 10240 && ggml_node_has_n_uses(cgraph, i, 1) && ggml_cuda_mmb_supported_mm(w, lo, node)) {
''',
         '''        // strixllama: Q8_0 as well - Unsloth's file keeps the HC weights at Q8_0
        if ((w->type == GGML_TYPE_IQ4_NL || w->type == GGML_TYPE_Q8_0) && w->ne[0] == 320 && w->ne[1] == 10240 && ggml_node_has_n_uses(cgraph, i, 1) && ggml_cuda_mmb_supported_mm(w, lo, node)) {
'''),
    ],
    os.path.join(tree, "ggml", "src", "ggml-cuda", "ple-conv.cu"): [
        ('''#include <cstdlib>
static bool ple_conv_enabled() { static const int v = getenv("LLAMA_PLE_CONV") ? atoi(getenv("LLAMA_PLE_CONV")) : 0; return v != 0; }
''',
         '''#include <cstdlib>
#include <type_traits>
static bool ple_conv_enabled() { static const int v = getenv("LLAMA_PLE_CONV") ? atoi(getenv("LLAMA_PLE_CONV")) : 0; return v != 0; }
'''),
        ('''template <int K, int DIL, int TT>
''',
         '''// strixllama: the conv weight is F16 in the author's file and F32 in Unsloth's; either is widened exactly, so both
// give the unfused taps' result bit for bit
template <int K, int DIL, int TT, typename WT>
'''),
        ('''        const half * __restrict__ w, float * __restrict__ y, const int C, const int T) {
''',
         '''        const WT * __restrict__ w, float * __restrict__ y, const int C, const int T) {
'''),
        ('''    for (int k = 0; k < K; ++k) wr[k] = __half2float(w[c * K + k]);
''',
         '''    for (int k = 0; k < K; ++k) {
        if constexpr (std::is_same_v<WT, half>) wr[k] = __half2float(w[c * K + k]);
        else                                    wr[k] = w[c * K + k];
    }
'''),
        ('''    if (cc->op != GGML_OP_CONCAT || cc->type != GGML_TYPE_F32 || ggml_get_op_params_i32(cc, 0) != 0) return false;
''',
         '''    if ((cc->flags & GGML_TENSOR_FLAG_OUTPUT) || cc->op != GGML_OP_CONCAT || cc->type != GGML_TYPE_F32 || ggml_get_op_params_i32(cc, 0) != 0) return false;
'''),
        ('''            // MUL(tap_out[k], w_k) with w_k an F32 [C] cast of a view of the F16 model weight
''',
         '''            // MUL(tap_out[k], w_k) with w_k an F32 [C] view of the model weight: a cast of it when the file has it
            // in F16, the column itself when the file has it in F32 (Unsloth's)
'''),
        ('''            // resolve the model weight: cast(CPY) <- reshape/view <- cont <- view of W[K, C] F16
''',
         '''            // resolve the model weight: [cast(CPY) <-] reshape/view <- cont <- view of W[K, C]
'''),
        ('''            if (W->type != GGML_TYPE_F16 || W->ne[0] != 4 || W->ne[1] != C || !ggml_is_contiguous(W)) return false;
            if (wv->view_offs != (size_t) k * sizeof(ggml_fp16_t) || wv->nb[1] != W->nb[1]) return false;
''',
         '''            if ((W->type != GGML_TYPE_F16 && W->type != GGML_TYPE_F32) || W->ne[0] != 4 || W->ne[1] != C || !ggml_is_contiguous(W)) return false;
            if (wv->view_offs != (size_t) k * ggml_type_size(W->type) || wv->nb[1] != W->nb[1]) return false;
'''),
        ('''    if (su->type != GGML_TYPE_F32 || !ggml_is_contiguous(su) || su->ne[0] != C || su->ne[1] != T) return false;
    m.concat_idx = i; m.first_tap_idx = first_tap; m.silu_idx = silu; m.x = x; m.state = st; m.concat = cc; m.w = wroot; m.out = cgraph->nodes[silu];
''',
         '''    if (su->type != GGML_TYPE_F32 || !ggml_is_contiguous(su) || su->ne[0] != C || su->ne[1] != T) return false;
    // strixllama: the fusion writes only the concat's tail (what the state update copies out); its body is never
    // computed. So nothing outside the fused taps may read the concat, or a view of it that reaches before the tail.
    auto reads_body = [&](const ggml_tensor * s) {
        if (!s) return false;
        if (s == cc) return true;
        if (s->view_src != cc) return false;
        return !(s->op == GGML_OP_VIEW && s->ne[0] == H && (int64_t) (s->view_offs / sizeof(float)) >= tail_from);
    };
    for (int n = i + 1; n < cgraph->n_nodes; ++n) {
        if (n >= first_tap && n <= silu) continue;
        const ggml_tensor * t = cgraph->nodes[n];
        if (t->op == GGML_OP_VIEW || t->op == GGML_OP_RESHAPE || t->op == GGML_OP_TRANSPOSE || t->op == GGML_OP_PERMUTE) continue;
        for (int s = 0; s < GGML_MAX_SRC; ++s) if (reads_body(t->src[s])) return false;
    }
    m.concat_idx = i; m.first_tap_idx = first_tap; m.silu_idx = silu; m.x = x; m.state = st; m.concat = cc; m.w = wroot; m.out = cgraph->nodes[silu];
'''),
        ('''    ple_conv_kernel<4, 3, TT><<<grid, 256, 0, ctx.stream()>>>((const float *) m.state->data, (const float *) m.x->data,
        (const half *) m.w->data, (float *) m.out->data, (int) m.C, (int) m.T);
''',
         '''    if (m.w->type == GGML_TYPE_F32) {
        ple_conv_kernel<4, 3, TT, float><<<grid, 256, 0, ctx.stream()>>>((const float *) m.state->data, (const float *) m.x->data,
            (const float *) m.w->data, (float *) m.out->data, (int) m.C, (int) m.T);
    } else {
        ple_conv_kernel<4, 3, TT, half><<<grid, 256, 0, ctx.stream()>>>((const float *) m.state->data, (const float *) m.x->data,
            (const half *) m.w->data, (float *) m.out->data, (int) m.C, (int) m.T);
    }
    static unsigned hits = 0; if (hits++ < 2) fprintf(stderr, "PLE_CONV fused taps + silu: C=%lld T=%lld w=%s\\n", (long long) m.C, (long long) m.T, ggml_type_name(m.w->type));
'''),
    ],
}


def main():
    texts = {p: io.open(p, encoding="utf-8").read() for p in EDITS}
    if any(MARKER in t for t in texts.values()):
        print("already applied")
        return
    for p, pairs in EDITS.items():
        for old, new in pairs:
            if texts[p].count(old) != 1:
                sys.exit("anchor found %d times, expected once, in %s" % (texts[p].count(old), p))
            texts[p] = texts[p].replace(old, new, 1)
    for p, t in texts.items():
        io.open(p, "w", encoding="utf-8", newline="").write(t)
    print("patched", ", ".join(os.path.basename(p) for p in EDITS))


if __name__ == "__main__":
    main()
