#!/usr/bin/env python3
"""Several slots: every conversation keeps one run of the pool and a batch views only its own

With more than one slot the KV cache is one pool, and every graph viewed it from cell 0 to the last used cell, so a conversation paid for the others in the pool - most of all in the MTP draft, whose attention is dense. Each conversation now keeps one run of cells. Its tokens go after its last cell, a new one starts after the last conversation with some room left to it, and a batch that does not fit has the pool laid out again first: the conversations keep their order, each one of the batch gets the same room after it (LLAMA_KV_REGION_HEADROOM, 8192 cells, or an equal share of what is free) and an idle one none, and the runs slide towards the start or the end by device-to-device copies of both caches and the block keys, in pieces that never overwrite what is still to be copied. A restore that finds no run large enough lays the pool out the same way. The graph of a batch views only the run of its own conversations, every cell index in the inputs relative to it. One conversation beside idle ones computes exactly what it computes on a single slot, bitwise, MTP included, and as fast; a conversation that moved too. Block keys go stale per sequence instead of per pool, so a restore rebuilds only its own. LLAMA_KV_REGIONS=0 turns it off, LLAMA_KV_WINDOW=0 keeps the regions but views the pool as before, LLAMA_KV_REGION_MOVES=0 never moves a conversation.

Generated by tools/make_patch_script.py from the tree it must reproduce, so every anchor is
unique by construction. 77 hunks across 9 file(s).

Usage: python D:/Work/strixllama/patches/apply_kv_regions.py [tree]
"""
import io
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
tree = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "src", "llama.cpp")
MARKER = 'get_kv_window'

EDITS = {
    os.path.join(tree, "src", "llama-kv-cells.h"): [
        ('''#include <cstring>
#include <limits>
''',
         '''#include <cstring>
#include <iterator>
#include <limits>
'''),
        ('''            seq_pos[s].clear();
        }
''',
         '''            seq_pos[s].clear();
            seq_cells[s].clear();
        }
'''),
        ('''        return used.empty() ? 0 : *used.rbegin() + 1;
    }
''',
         '''        return used.empty() ? 0 : *used.rbegin() + 1;
    }

    // strixllama: the used cells in index order, for walking the runs of free cells between them
    const std::set<uint32_t> & used_set() const {
        return used;
    }
'''),
        ('''    }

    // note: call only if the cell is not empty
    llama_pos pos_get(uint32_t i) const {
''',
         '''    }

    // strixllama: the span of the cell array that holds sequence seq_id, [seq_cell_min, seq_cell_max]
    // return -1 if the sequence is not present
    int64_t seq_cell_min(llama_seq_id seq_id) const {
        assert(seq_id >= 0);
        assert(seq_id < LLAMA_MAX_SEQ);

        return seq_cells[seq_id].empty() ? -1 : (int64_t) *seq_cells[seq_id].begin();
    }

    int64_t seq_cell_max(llama_seq_id seq_id) const {
        assert(seq_id >= 0);
        assert(seq_id < LLAMA_MAX_SEQ);

        return seq_cells[seq_id].empty() ? -1 : (int64_t) *seq_cells[seq_id].rbegin();
    }

    // the number of cells that carry sequence seq_id
    uint32_t seq_cell_count(llama_seq_id seq_id) const {
        assert(seq_id >= 0);
        assert(seq_id < LLAMA_MAX_SEQ);

        return (uint32_t) seq_cells[seq_id].size();
    }

    // the (pos, cell) pairs of sequence seq_id, ordered by position
    const std::set<std::pair<llama_pos, uint32_t>> & seq_pos_cells(llama_seq_id seq_id) const {
        assert(seq_id >= 0);
        assert(seq_id < LLAMA_MAX_SEQ);

        return seq_pos[seq_id];
    }

    // strixllama: move the state of cell isrc to the empty cell idst (the KV data is moved by the caller)
    void mv(uint32_t isrc, uint32_t idst) {
        assert(isrc < pos.size());
        assert(idst < pos.size());
        assert(isrc != idst);
        assert(pos[idst] == -1 && seq[idst].none());
        assert(pos[isrc] != -1);
        assert(shift[isrc] == 0);

        seq_pos_rm(isrc);

        pos[idst] = pos[isrc];
        ext[idst] = ext[isrc];
        seq[idst] = seq[isrc];

        pos[isrc] = -1;
        ext[isrc].reset();
        seq[isrc].reset();

        used.erase(isrc);
        used.insert(idst);

        seq_pos_add(idst);
    }

    // strixllama: mv() for the n cells [isrc, isrc + n), all of sequence seq_id alone, to the empty cells
    // [idst, idst + n); the two ranges must not overlap. The index sets' nodes are moved rather than freed and
    // allocated again, and mv()'s scans over every sequence id are skipped: a rebalance moves tens of thousands
    // of cells, which took ~100 ms through mv().
    void mv_range(uint32_t isrc, uint32_t idst, uint32_t n, llama_seq_id seq_id) {
        assert(isrc + n <= idst || idst + n <= isrc);
        assert(isrc + n <= pos.size() && idst + n <= pos.size());
        assert(seq_id >= 0 && seq_id < LLAMA_MAX_SEQ);

        for (uint32_t j = 0; j < n; ++j) {
            if (pos[isrc + j] == -1 || seq[isrc + j].count() != 1 || !seq[isrc + j].test(seq_id) || shift[isrc + j] != 0) {
                for (uint32_t k = 0; k < n; ++k) {
                    mv(isrc + k, idst + k);
                }
                return;
            }
        }

        move_index(used,              isrc, idst, n);
        move_index(seq_cells[seq_id], isrc, idst, n);

        auto & sp = seq_pos[seq_id];
        for (uint32_t j = 0; j < n; ++j) {
            auto it = sp.find({ pos[isrc + j], isrc + j });
            assert(it != sp.end());
            auto next = std::next(it);
            auto nh = sp.extract(it);
            nh.value().second = idst + j;
            sp.insert(next, std::move(nh));
        }

        for (uint32_t j = 0; j < n; ++j) {
            assert(pos[idst + j] == -1 && seq[idst + j].none());

            pos[idst + j] = pos[isrc + j];
            ext[idst + j] = ext[isrc + j];
            seq[idst + j] = seq[isrc + j];

            pos[isrc + j] = -1;
            ext[isrc + j].reset();
            seq[isrc + j].reset();
        }
    }

    // note: call only if the cell is not empty
    llama_pos pos_get(uint32_t i) const {
'''),
        ('''
    // helper functions for updating `seq_pos`, once cell at a time:
''',
         '''
    // strixllama: the cells of each sequence in index order, kept in step with seq_pos. A unified cache
    // keeps a conversation in one run of cells, and the graph of a batch views only the run of its own
    // conversations (llama_kv_cache::get_kv_window), which needs a sequence's first and last cell.
    std::set<uint32_t> seq_cells[LLAMA_MAX_SEQ];

    // strixllama: the entries [isrc, isrc + n) of an index of cells, renumbered to [idst, idst + n) in place
    static void move_index(std::set<uint32_t> & index, uint32_t isrc, uint32_t idst, uint32_t n) {
        std::vector<std::set<uint32_t>::node_type> nodes;
        nodes.reserve(n);
        for (auto it = index.lower_bound(isrc); it != index.end() && *it < isrc + n; ) {
            auto next = std::next(it);
            nodes.push_back(index.extract(it));
            it = next;
        }
        auto hint = index.lower_bound(idst);
        for (auto & nh : nodes) {
            nh.value() = nh.value() - isrc + idst;
            hint = std::next(index.insert(hint, std::move(nh)));
        }
    }

    // helper functions for updating `seq_pos`, once cell at a time:
'''),
        ('''        GGML_UNUSED(n);
    }
''',
         '''        GGML_UNUSED(n);

        seq_cells[s].erase(i);
    }
'''),
        ('''        seq_pos[s].insert({ pos[i], i });
    }
''',
         '''        seq_pos[s].insert({ pos[i], i });

        seq_cells[s].insert(i);
    }
'''),
    ],
    os.path.join(tree, "src", "llama-kv-cache.cpp"): [
        ('''#include <cmath>
#include <cstring>
''',
         '''#include <cmath>
#include <cstdlib>
#include <cstring>
'''),
        ('''
        auto sinfos = prepare(ubatches);
''',
         '''
        // strixllama: when the batch does not fit after its conversations' last cells, rebalance the pool first
        if (regions && can_move()) {
            move_cells(plan_layout(ubatches));
        }

        auto sinfos = prepare(ubatches);
'''),
        ('''    GGML_UNUSED(optimize);

''',
         '''    GGML_UNUSED(optimize);

    lctx_sync = lctx;   // strixllama: see move_cells

'''),
        ('''
    uint32_t n_tokens = ubatch.n_tokens;
''',
         '''
    // strixllama: regions - each conversation after its last cell; whatever does not fit that way takes the
    // search below, which is always correct and only makes the batch's window wider
    if (regions && !cont) {
        slot_info res = find_slot_regions(ubatch);
        if (!res.empty()) {
            return res;
        }
    }

    uint32_t n_tokens = ubatch.n_tokens;
'''),
        ('''    assert(res.s1 >= res.s0);

    return res;
}

void llama_kv_cache::apply_ubatch(const slot_info & sinfo, const llama_ubatch & ubatch) {
''',
         '''    assert(res.s1 >= res.s0);

    return res;
}

//
// strixllama: regions
//

void llama_kv_cache::set_regions(bool on) {
    regions = on && n_stream == 1 && !v_trans && n_swa == 0 && swa_type == LLAMA_SWA_TYPE_NONE && other == nullptr;
}

bool llama_kv_cache::get_regions() const {
    return regions;
}

bool llama_kv_cache::can_move() const {
    return regions && lctx_sync != nullptr;
}

void llama_kv_cache::set_move_hook(std::function<void(const cell_move_vec_t &, bool)> hook) {
    move_hook = std::move(hook);
}

ggml_backend_t llama_kv_cache::backend_for(const ggml_tensor * t) const {
    if (lctx_sync == nullptr || t == nullptr || t->buffer == nullptr) {
        return nullptr;
    }

    ggml_backend_dev_t dev = ggml_backend_buft_get_device(ggml_backend_buffer_get_type(t->buffer));

    ggml_backend_sched_t sched = lctx_sync->get_sched();
    for (int i = 0; i < ggml_backend_sched_get_n_backends(sched); ++i) {
        ggml_backend_t backend = ggml_backend_sched_get_backend(sched, i);
        if (ggml_backend_get_device(backend) == dev) {
            return backend;
        }
    }

    return nullptr;
}

void llama_kv_cache::copy_rows(ggml_tensor * t, const cell_move_vec_t & moves) const {
    if (moves.empty()) {
        return;
    }

    ggml_init_params params = {
        /*.mem_size   =*/ 2*ggml_tensor_overhead(),
        /*.mem_buffer =*/ nullptr,
        /*.no_alloc   =*/ true,
    };

    ggml_context * ctx = ggml_init(params);
    GGML_ASSERT(ctx != nullptr);

    // on the stream the graphs run on: after the one before, before the next one, with nothing to wait for here
    ggml_backend_t backend = backend_for(t);
    if (backend == nullptr) {
        ggml_backend_sched_synchronize(lctx_sync->get_sched());
    }
    // LLAMA_KV_REGION_DEBUG=3: where every tensor's pieces are copied
    static const int dbg = getenv("LLAMA_KV_REGION_DEBUG") ? atoi(getenv("LLAMA_KV_REGION_DEBUG")) : 0;
    if (dbg >= 3) {
        fprintf(stderr, "kv regions: copy %s: backend %s, buffer %s\\n", ggml_get_name(t),
                backend ? ggml_backend_name(backend) : "none", t->buffer ? ggml_backend_buffer_name(t->buffer) : "none");
    }

    for (const auto & m : moves) {
        GGML_ASSERT(m.src + m.n <= m.dst || m.dst + m.n <= m.src);

        ggml_tensor * a = ggml_view_2d(ctx, t, t->ne[0], m.n, t->nb[1], (size_t) m.src*t->nb[1]);
        ggml_tensor * b = ggml_view_2d(ctx, t, t->ne[0], m.n, t->nb[1], (size_t) m.dst*t->nb[1]);

        ggml_backend_view_init(a);
        ggml_backend_view_init(b);

        if (backend != nullptr) {
            ggml_backend_tensor_copy_async(backend, backend, a, b);
        } else {
            ggml_backend_tensor_copy(a, b);
        }

        ggml_reset(ctx);
    }

    ggml_free(ctx);
}

void llama_kv_cache::move_cells(const cell_move_vec_t & moves, bool sync) {
    if (moves.empty()) {
        return;
    }

    GGML_ASSERT(can_move());

    const int64_t t_start_us = ggml_time_us();

    uint64_t n_cells = 0;
    for (const auto & m : moves) {
        n_cells += m.n;
    }

    apply_moves(moves);

    if (move_hook) {
        move_hook(moves, sync);
    }

    if (sync) {
        ggml_backend_sched_synchronize(lctx_sync->get_sched());
    }

    // on stderr like the other strixllama diagnostics: the server does not print llama's info lines
    static const bool quiet = getenv("LLAMA_KV_REGION_QUIET") != nullptr;
    if (!quiet) {
        fprintf(stderr, "kv regions: moved %llu cells in %zu pieces (%s) - queued in %.1f ms\\n",
                (unsigned long long) n_cells, moves.size(), layers.empty() ? "" : ggml_get_name(layers[0].k),
                (ggml_time_us() - t_start_us)/1000.0);
    }
}

// strixllama: the room a conversation of the batch gets after its last cell when the pool is rebalanced, and
// what a new conversation leaves after the one before it (LLAMA_KV_REGION_HEADROOM cells, 8192 by default -
// a long answer). Several conversations decoding together view the run from the first to the last of them,
// rooms included, so this is kept to what a turn needs rather than all the free space
static uint32_t llama_kv_region_headroom() {
    static const uint32_t h = [] {
        const char * e = getenv("LLAMA_KV_REGION_HEADROOM");
        const long   v = e ? atol(e) : 8192;
        return (uint32_t) std::max(0L, v);
    }();
    return h;
}

static uint32_t llama_kv_align_up  (uint32_t x) { return (x + 255u) & ~255u; }
static uint32_t llama_kv_align_down(uint32_t x) { return x & ~255u; }

// where a sequence with no cell yet starts: after all the others, with room left to the one before it (the
// headroom, or half of what is left when that is less), on a 256-cell boundary when there is space for one
int64_t llama_kv_cache::region_start(uint32_t need, uint32_t tail) const {
    const uint32_t size = v_cells[0].size();

    if ((uint64_t) tail + need > size) {
        return -1;
    }
    if (tail == 0) {
        return 0;
    }

    const uint32_t spare = size - tail - need;
    const uint32_t start = llama_kv_align_up(tail + std::min(llama_kv_region_headroom(), spare/2));

    return (uint64_t) start + need <= size ? (int64_t) start : (int64_t) tail;
}

llama_kv_cache::slot_info llama_kv_cache::find_slot_regions(const llama_ubatch & ubatch) const {
    if (n_stream != 1 || ubatch.n_tokens == 0) {
        return { };
    }

    const auto & cells = v_cells[0];

    // the ubatch's sequences in order of appearance, with their token counts; one sequence per token
    std::vector<llama_seq_id> seqs;
    std::vector<uint32_t>     count;
    std::vector<uint32_t>     tok_seq(ubatch.n_tokens);

    for (uint32_t i = 0; i < ubatch.n_tokens; ++i) {
        if (ubatch.n_seq_id[i] != 1) {
            return { };
        }

        const llama_seq_id s = ubatch.seq_id[i][0];

        uint32_t k = 0;
        while (k < seqs.size() && seqs[k] != s) {
            ++k;
        }
        if (k == seqs.size()) {
            seqs.push_back(s);
            count.push_back(0);
        }

        count[k]++;
        tok_seq[i] = k;
    }

    std::vector<std::pair<uint32_t, uint32_t>> taken;
    std::vector<uint32_t> cursor(seqs.size());

    uint32_t tail = cells.used_max_p1();

    for (uint32_t k = 0; k < seqs.size(); ++k) {
        const uint32_t n = count[k];

        int64_t start = cells.seq_cell_max(seqs[k]);
        if (start >= 0) {
            start += 1;
        } else {
            const auto it = planned_start.find(seqs[k]);
            start = it != planned_start.end() ? (int64_t) it->second : region_start(n, tail);
            if (start < 0) {
                return { };
            }
        }

        if ((uint64_t) start + n > cells.size()) {
            return { };
        }

        for (uint32_t j = 0; j < n; ++j) {
            if (!cells.is_empty(start + j)) {
                return { };
            }
        }

        for (const auto & t : taken) {
            if ((uint32_t) start < t.second && t.first < (uint32_t) start + n) {
                return { };
            }
        }

        taken.emplace_back((uint32_t) start, (uint32_t) start + n);
        cursor[k] = (uint32_t) start;
        tail = std::max(tail, (uint32_t) start + n);
    }

    slot_info res = {
        /*.s0   =*/ 0,
        /*.s1   =*/ 0,
        /*.strm =*/ { 0 },
        /*.idxs =*/ { { } },
    };

    res.idxs[0].reserve(ubatch.n_tokens);

    for (uint32_t i = 0; i < ubatch.n_tokens; ++i) {
        res.idxs[0].push_back(cursor[tok_seq[i]]++);
    }

    return res;
}

// The layout the pool needs for this batch, as the moves that make it - empty when the batch fits already (the
// common case: a few tokens after a conversation's last cell) or when no layout can hold it.
//
// The conversations keep their order in the pool and slide towards its start or its end. Each one of the batch
// is followed by the same room - the headroom, or an equal share of what is free when that is less - and an idle
// one by none; a new one goes after the last. Starts stay on 256-cell boundaries while that fits, so moves go in
// large pieces. The moves are ordered so that no copy overwrites a cell that is still to be copied: those that
// go towards the start first, lowest first, then those that go towards the end, highest first, and a
// conversation that moves by less than its own length goes in pieces no longer than the distance, in the
// direction it moves.
//
// Shared cells (one cell in several sequences) or interleaved conversations are left as they are: find_slot's
// search places those tokens. So is a full pool, which the server empties a slot of.
llama_kv_cache::cell_move_vec_t llama_kv_cache::plan_layout(const std::vector<llama_ubatch> & ubatches) const {
    cell_move_vec_t res;

    planned_start.clear();

    if (!regions || n_stream != 1) {
        return res;
    }

    static const bool on = [] {
        const char * e = getenv("LLAMA_KV_REGION_MOVES");
        return !e || atoi(e) != 0;
    }();
    if (!on) {
        return res;
    }

    const auto & cells = v_cells[0];
    const uint32_t size = cells.size();

    // the batch: its sequences in order of appearance and their token counts; one sequence per token
    std::vector<llama_seq_id> bseq;
    std::vector<uint32_t>     bcnt;

    for (const auto & ubatch : ubatches) {
        for (uint32_t i = 0; i < ubatch.n_tokens; ++i) {
            if (ubatch.n_seq_id[i] != 1) {
                return res;
            }

            const llama_seq_id s = ubatch.seq_id[i][0];

            uint32_t k = 0;
            while (k < bseq.size() && bseq[k] != s) {
                ++k;
            }
            if (k == bseq.size()) {
                bseq.push_back(s);
                bcnt.push_back(0);
            }

            bcnt[k]++;
        }
    }

    // does it fit as it is?
    {
        bool     fits = true;
        uint32_t tail = cells.used_max_p1();

        for (uint32_t k = 0; k < bseq.size() && fits; ++k) {
            const int64_t last = cells.seq_cell_max(bseq[k]);
            if (last >= 0) {
                fits = (uint64_t) last + 1 + bcnt[k] <= size;
                for (uint32_t j = 0; fits && j < bcnt[k]; ++j) {
                    fits = cells.is_empty((uint32_t) last + 1 + j);
                }
            } else {
                const int64_t start = region_start(bcnt[k], tail);
                fits = start >= 0;
                if (fits) {
                    tail = (uint32_t) start + bcnt[k];
                }
            }
        }

        if (fits) {
            return res;
        }
    }

    // every conversation in the pool, by its first cell
    struct seq_span {
        llama_seq_id s;
        uint32_t     c0;      // first cell
        uint32_t     c1;      // last cell
        uint32_t     n;       // cells
        uint32_t     add;     // this batch's tokens
        bool         ordered; // cells in position order
    };

    std::vector<seq_span> spans;
    uint64_t n_cells = 0;

    for (llama_seq_id s = 0; s < LLAMA_MAX_SEQ; ++s) {
        const uint32_t n = cells.seq_cell_count(s);
        if (n == 0) {
            continue;
        }

        bool     ordered = true;
        int64_t  prev    = -1;
        for (const auto & pc : cells.seq_pos_cells(s)) {
            ordered = ordered && (int64_t) pc.second > prev;
            prev    = pc.second;
        }

        spans.push_back({ s, (uint32_t) cells.seq_cell_min(s), (uint32_t) cells.seq_cell_max(s), n, 0, ordered });
        n_cells += n;
    }

    // a cell in several sequences is counted once per sequence
    if (n_cells != cells.get_used()) {
        return res;
    }

    std::sort(spans.begin(), spans.end(), [](const seq_span & a, const seq_span & b) { return a.c0 < b.c0; });

    for (size_t i = 1; i < spans.size(); ++i) {
        if (spans[i].c0 <= spans[i - 1].c1) {
            return res;   // interleaved
        }
    }

    std::vector<std::pair<llama_seq_id, uint32_t>> fresh;
    uint64_t n_add = 0;

    for (uint32_t k = 0; k < bseq.size(); ++k) {
        auto it = std::find_if(spans.begin(), spans.end(), [&](const seq_span & sp) { return sp.s == bseq[k]; });
        if (it != spans.end()) {
            it->add = bcnt[k];
        } else {
            fresh.emplace_back(bseq[k], bcnt[k]);
        }
        n_add += bcnt[k];
    }

    if (n_cells + n_add > size) {
        return res;   // full: the server frees a slot
    }

    const uint32_t n_act = (uint32_t) bseq.size();
    const uint32_t spare = (uint32_t) (size - n_cells - n_add);

    // the targets for a given room and alignment; the end of the last one, or past the pool if they do not fit
    std::vector<uint32_t> target(spans.size());
    std::vector<uint32_t> target_new(fresh.size());

    auto layout = [&](uint32_t room, bool align) -> uint64_t {
        uint64_t t = 0;
        for (size_t i = 0; i < spans.size(); ++i) {
            if (align) {
                t = llama_kv_align_up((uint32_t) std::min<uint64_t>(t, size));
            }
            target[i] = (uint32_t) std::min<uint64_t>(t, size);
            t += spans[i].n + (spans[i].add > 0 ? spans[i].add + room : 0);
        }
        for (size_t i = 0; i < fresh.size(); ++i) {
            if (align) {
                t = llama_kv_align_up((uint32_t) std::min<uint64_t>(t, size));
            }
            target_new[i] = (uint32_t) std::min<uint64_t>(t, size);
            t += fresh[i].second + (i + 1 < fresh.size() ? room : 0);
        }
        return t;
    };

    uint32_t room = llama_kv_align_down(std::min(llama_kv_region_headroom(), n_act > 0 ? spare/n_act : 0u));

    // alignment gives way first, then the room
    bool placed = false;
    for (uint32_t r : { room, 0u }) {
        for (bool align : { true, false }) {
            if (layout(r, align) <= size) {
                placed = true;
                room   = r;
                break;
            }
        }
        if (placed) {
            break;
        }
    }
    if (!placed) {
        return res;
    }

    // the pieces of one conversation's move, in the order they must be copied
    bool ok = true;

    auto emit = [&](const seq_span & sp, uint32_t to) {
        const bool dense = sp.ordered && sp.c1 - sp.c0 + 1 == sp.n;

        if (dense) {
            if (to == sp.c0) {
                return;
            }

            const uint32_t dist  = to > sp.c0 ? to - sp.c0 : sp.c0 - to;
            const uint32_t piece = std::min(dist, sp.n);

            // a short move of a long conversation would go in too many pieces: leave the pool as it is
            if ((sp.n + piece - 1)/piece > 1024) {
                ok = false;
                return;
            }

            if (to < sp.c0) {
                for (uint32_t o = 0; o < sp.n; o += piece) {
                    const uint32_t len = std::min(piece, sp.n - o);
                    res.push_back({ sp.c0 + o, to + o, len, sp.s, true });
                }
            } else {
                for (uint32_t o = sp.n; o > 0; ) {
                    const uint32_t len = std::min(piece, o);
                    o -= len;
                    res.push_back({ sp.c0 + o, to + o, len, sp.s, true });
                }
            }
            return;
        }

        // holes or cells out of position order: gathered in position order, which only works if the
        // destination does not overlap the cells it gathers
        if (to <= sp.c1 && sp.c0 < to + sp.n) {
            ok = false;
            return;
        }

        uint32_t d = to;
        for (const auto & pc : cells.seq_pos_cells(sp.s)) {
            const uint32_t c = pc.second;
            if (!res.empty() && res.back().seq == sp.s && res.back().src + res.back().n == c && res.back().dst + res.back().n == d) {
                res.back().n++;
            } else {
                res.push_back({ c, d, 1, sp.s, sp.ordered });
            }
            ++d;
        }
    };

    for (size_t i = 0; i < spans.size() && ok; ++i) {
        if (target[i] < spans[i].c0 || (target[i] == spans[i].c0 && spans[i].c1 - spans[i].c0 + 1 != spans[i].n)) {
            emit(spans[i], target[i]);
        }
    }
    for (size_t i = spans.size(); i > 0 && ok; --i) {
        if (target[i - 1] > spans[i - 1].c0) {
            emit(spans[i - 1], target[i - 1]);
        }
    }

    if (!ok) {
        res.clear();
        return res;
    }

    for (size_t i = 0; i < fresh.size(); ++i) {
        planned_start[fresh[i].first] = target_new[i];
    }

    static const int dbg = getenv("LLAMA_KV_REGION_DEBUG") ? atoi(getenv("LLAMA_KV_REGION_DEBUG")) : 0;
    if (dbg > 0) {
        fprintf(stderr, "kv regions: rebalance (%s) for %zu sequences of the batch, %zu in the pool, room %u:",
                layers.empty() ? "" : ggml_get_name(layers[0].k), bseq.size(), spans.size(), room);
        for (size_t i = 0; i < spans.size(); ++i) {
            fprintf(stderr, " seq %d %u->%u (%u%s)", spans[i].s, spans[i].c0, target[i], spans[i].n, spans[i].add ? " +" : "");
        }
        for (size_t i = 0; i < fresh.size(); ++i) {
            fprintf(stderr, " new seq %d at %u", fresh[i].first, target_new[i]);
        }
        fprintf(stderr, "\\n");
    }

    return res;
}

void llama_kv_cache::apply_moves(const cell_move_vec_t & moves) {
    GGML_ASSERT(n_stream == 1);

    for (const auto & layer : layers) {
        for (ggml_tensor * t : { layer.k, layer.v }) {
            if (t != nullptr) {
                copy_rows(t, moves);
            }
        }
    }

    auto & cells = v_cells[0];

    // in order: a piece may take cells an earlier one vacated, never cells a later one still reads
    for (const auto & m : moves) {
        cells.mv_range(m.src, m.dst, m.n, m.seq);
    }
}

void llama_kv_cache::apply_ubatch(const slot_info & sinfo, const llama_ubatch & ubatch) {
'''),
        ('''ggml_tensor * llama_kv_cache::get_k(ggml_context * ctx, int32_t il, uint32_t n_kv, const slot_info & sinfo) const {
''',
         '''// strixllama: under regions the graph views the run of cells that holds the ubatch's own sequences - their
// first to their last cell, padded as get_n_kv pads - instead of the pool up to its last used cell. Cells of
// other sequences inside the run are masked as before. Unchanged when that is no narrower (one conversation
// from cell 0, as on a single slot). LLAMA_KV_WINDOW=0 turns it off.
void llama_kv_cache::get_kv_window(const slot_info & sinfo, const llama_ubatch & ubatch, uint32_t & off, uint32_t & n_kv) const {
    off  = 0;
    n_kv = get_n_kv(sinfo);

    static const bool on = [] {
        const char * e = getenv("LLAMA_KV_WINDOW");
        return !e || atoi(e) != 0;
    }();

    if (!on || !regions || n_stream != 1 || sinfo.n_stream() != 1 || ubatch.n_tokens == 0) {
        return;
    }

    const auto & cells = v_cells[sinfo.strm[0]];

    std::bitset<LLAMA_MAX_SEQ> seen;

    int64_t lo = INT64_MAX;
    int64_t hi = -1;

    for (uint32_t i = 0; i < ubatch.n_tokens; ++i) {
        for (int32_t k = 0; k < ubatch.n_seq_id[i]; ++k) {
            const llama_seq_id s = ubatch.seq_id[i][k];
            if (s < 0 || s >= LLAMA_MAX_SEQ || seen.test(s)) {
                continue;
            }
            seen.set(s);

            const int64_t c0 = cells.seq_cell_min(s);
            const int64_t c1 = cells.seq_cell_max(s);
            if (c0 < 0) {
                continue;
            }

            lo = std::min(lo, c0);
            hi = std::max(hi, c1 + 1);
        }
    }

    if (hi <= lo) {
        return;
    }

    const uint32_t n_pad_cur = std::max(n_pad, 256u);

    const uint32_t n = std::min(cells.size(), std::max(n_pad_cur, GGML_PAD((uint32_t) (hi - lo), n_pad_cur)));
    if (n >= n_kv) {
        return;
    }

    off  = (uint32_t) std::min<int64_t>(lo, (int64_t) cells.size() - n);
    n_kv = n;

    // LLAMA_KV_REGION_DEBUG=2: every change of a cache's window
    static const int dbg = getenv("LLAMA_KV_REGION_DEBUG") ? atoi(getenv("LLAMA_KV_REGION_DEBUG")) : 0;
    if (dbg >= 2) {
        static thread_local std::map<const void *, std::pair<uint32_t, uint32_t>> last;
        auto & l = last[this];
        if (l.first != off || l.second != n_kv) {
            l = { off, n_kv };
            fprintf(stderr, "kv window: %s off=%u n_kv=%u (pool %u) tokens=%u lo=%lld hi=%lld\\n",
                    layers.empty() ? "" : ggml_get_name(layers[0].k), off, n_kv, get_n_kv(sinfo), ubatch.n_tokens,
                    (long long) lo, (long long) hi);
        }
    }
}

ggml_tensor * llama_kv_cache::get_k(ggml_context * ctx, int32_t il, uint32_t n_kv, const slot_info & sinfo, uint32_t off) const {
'''),
        ('''    assert(n_embd_k_gqa == hparams.n_embd_k_gqa(il));

''',
         '''    assert(n_embd_k_gqa == hparams.n_embd_k_gqa(il));
    GGML_ASSERT((uint64_t) off + n_kv <= kv_size);

'''),
        ('''            ggml_row_size(k->type, n_embd_k_gqa*kv_size)*sinfo.s0);
''',
         '''            ggml_row_size(k->type, n_embd_k_gqa*kv_size)*sinfo.s0 + ggml_row_size(k->type, n_embd_k_gqa)*off);
'''),
        ('''ggml_tensor * llama_kv_cache::get_v(ggml_context * ctx, int32_t il, uint32_t n_kv, const slot_info & sinfo) const {
''',
         '''ggml_tensor * llama_kv_cache::get_v(ggml_context * ctx, int32_t il, uint32_t n_kv, const slot_info & sinfo, uint32_t off) const {
'''),
        ('''    assert(n_embd_v_gqa >= hparams.n_embd_v_gqa(il));

''',
         '''    assert(n_embd_v_gqa >= hparams.n_embd_v_gqa(il));
    GGML_ASSERT((uint64_t) off + n_kv <= kv_size);

'''),
        ('''                ggml_row_size(v->type, n_embd_v_gqa*kv_size)*sinfo.s0);
''',
         '''                ggml_row_size(v->type, n_embd_v_gqa*kv_size)*sinfo.s0 + ggml_row_size(v->type, n_embd_v_gqa)*off);
'''),
        ('''            ggml_row_size(v->type, kv_size*n_embd_v_gqa)*sinfo.s0);
''',
         '''            ggml_row_size(v->type, kv_size*n_embd_v_gqa)*sinfo.s0 + ggml_row_size(v->type, off));
'''),
        ('''    int64_t n_tps;
};
''',
         '''    int64_t n_tps;

    // strixllama: the first cell of the graph's view
    uint32_t off;
};

// strixllama: the cells of a stream as the graph's view sees them, from its first cell (get_kv_window)
struct llama_kv_cells_view {
    const llama_kv_cells & cells;
    const uint32_t         off;

    bool                      is_empty(uint32_t j)                   const { return cells.is_empty(off + j); }
    bool                      seq_has (uint32_t j, llama_seq_id s)   const { return cells.seq_has(off + j, s); }
    llama_pos                 pos_get (uint32_t j)                   const { return cells.pos_get(off + j); }
    const llama_kv_cell_ext & ext_get (uint32_t j)                   const { return cells.ext_get(off + j); }
};
'''),
        ('''            const auto & cells = v_cells.at(seq_to_stream[seq_id]);
''',
         '''            const llama_kv_cells_view cells = { v_cells.at(seq_to_stream[seq_id]), args.off };
'''),
        ('''void llama_kv_cache::set_input_kq_mask(ggml_tensor * dst, const llama_ubatch * ubatch, bool causal_attn) const {
''',
         '''void llama_kv_cache::set_input_kq_mask(ggml_tensor * dst, const llama_ubatch * ubatch, bool causal_attn, uint32_t off) const {
'''),
        ('''        /*.n_tps            =*/ n_tps,
    };

''',
         '''        /*.n_tps            =*/ n_tps,
        /*.off              =*/ off,
    };

    GGML_ASSERT(off == 0 || (n_stream == 1 && (uint64_t) off + n_kv <= get_size()));

'''),
        ('''        } else {
            sinfo = find_slot(ubatch, false);
''',
         '''        } else {
            // strixllama: under regions the restored conversation gets one run of cells, after a rebalance if the
            // free cells are scattered; the moves are waited for, as the restore writes cells next
            if (regions && can_move()) {
                move_cells(plan_layout({ ubatch }), /* sync = */ true);
            }

            sinfo = find_slot(ubatch, false);
'''),
        ('''    n_kv = kv->get_n_kv(sinfos[i_cur]);
''',
         '''
    uint32_t n = 0;
    kv->get_kv_window(sinfos[i_cur], ubatches[i_cur], kv_off, n);
    n_kv = n;
'''),
        ('''
ggml_type llama_kv_cache_context::type_k() const {
''',
         '''
uint32_t llama_kv_cache_context::get_kv_off() const {
    return kv_off;
}

ggml_type llama_kv_cache_context::type_k() const {
'''),
        ('''    return kv->get_k(ctx, il, n_kv, sinfos[i_cur]);
''',
         '''    return kv->get_k(ctx, il, n_kv, sinfos[i_cur], kv_off);
'''),
        ('''    return kv->get_v(ctx, il, n_kv, sinfos[i_cur]);
''',
         '''    return kv->get_v(ctx, il, n_kv, sinfos[i_cur], kv_off);
'''),
        ('''    kv->set_input_kq_mask(dst, ubatch, causal_attn);
''',
         '''    kv->set_input_kq_mask(dst, ubatch, causal_attn, kv_off);
'''),
    ],
    os.path.join(tree, "src", "llama-kv-cache.h"): [
        ('''
#include <unordered_map>
''',
         '''
#include <functional>
#include <map>
#include <unordered_map>
'''),
        ('''
    // TODO: refactor the memory instances to not depend on `llama_model`
''',
         '''
    // strixllama: n cells of sequence seq moved from [src, src + n) to [dst, dst + n), data and state. A list of
    // them is applied in order: a later piece may take cells an earlier one vacated. `ordered`: the sequence's
    // cells were in position order, so a block's first cell stays its first cell (see llama_memory_hybrid_idx)
    struct cell_move {
        uint32_t     src;
        uint32_t     dst;
        uint32_t     n;
        llama_seq_id seq;
        bool         ordered;
    };

    using cell_move_vec_t = std::vector<cell_move>;

    // TODO: refactor the memory instances to not depend on `llama_model`
'''),
        ('''
    // state_read, plus the cells the restored tokens were placed in
''',
         '''
    // strixllama: regions. A unified cache with several sequences keeps each conversation in one run of cells,
    // and the pool compact: a conversation's tokens go after its last cell (find_slot), a new one after the last
    // conversation in the pool, with room left to the one before it. When the batch's tokens do not fit that
    // way, the layout is rebalanced first (plan_layout, move_cells): the conversations slide towards the start
    // or the end of the pool, in their order, so that every one in the batch has the same room after it and
    // the idle ones none. The graph of a batch then views only the run of its own conversations
    // (get_kv_window), so a conversation costs what it would on a cache of its own. Only for a cache whose
    // owner handles the window offset in every graph input it builds (llama_memory_hybrid_idx); what no layout
    // can hold falls back to the plain search, which is always correct and only makes the window wider.
    void set_regions(bool on);
    bool get_regions() const;

    // the moves that rebalance the pool so that every sequence of these ubatches fits after its last cell and a
    // new one after the last conversation; empty when they fit already or no layout can hold them
    cell_move_vec_t plan_layout(const std::vector<llama_ubatch> & ubatches) const;

    // move the cells' data and state: the copies are queued on the stream the context's graphs run on, after
    // them and before the next one; `sync` waits for them (a restore writes cells next). A cache that mirrors
    // another one (the qwen4exp indexer) is given the other's moves through its owner's hook.
    bool can_move() const;
    void move_cells(const cell_move_vec_t & moves, bool sync = false);
    void set_move_hook(std::function<void(const cell_move_vec_t &, bool)> hook);

    // copy the rows of the moves' pieces of a tensor on this cache's device, in order, queued as above
    void copy_rows(ggml_tensor * t, const cell_move_vec_t & moves) const;

    // state_read, plus the cells the restored tokens were placed in
'''),
        ('''    // get views of the current state of the cache
    ggml_tensor * get_k(ggml_context * ctx, int32_t il, uint32_t n_kv, const slot_info & sinfo) const;
    ggml_tensor * get_v(ggml_context * ctx, int32_t il, uint32_t n_kv, const slot_info & sinfo) const;
''',
         '''    // strixllama: the cells [off, off + n_kv) the graph of this ubatch views: the run that holds the ubatch's
    // own sequences when regions are on (see set_regions), else [0, get_n_kv())
    void get_kv_window(const slot_info & sinfo, const llama_ubatch & ubatch, uint32_t & off, uint32_t & n_kv) const;

    // get views of the current state of the cache
    // strixllama: off = the first cell of the view (get_kv_window)
    ggml_tensor * get_k(ggml_context * ctx, int32_t il, uint32_t n_kv, const slot_info & sinfo, uint32_t off = 0) const;
    ggml_tensor * get_v(ggml_context * ctx, int32_t il, uint32_t n_kv, const slot_info & sinfo, uint32_t off = 0) const;
'''),
        ('''    void set_input_k_shift(ggml_tensor * dst) const;

    void set_input_kq_mask   (ggml_tensor * dst, const llama_ubatch * ubatch, bool causal_attn) const;
    void set_input_pos_bucket(ggml_tensor * dst, const llama_ubatch * ubatch) const;

''',
         '''    void set_input_k_shift(ggml_tensor * dst) const;

    // strixllama: off = the first cell of the graph's view (get_kv_window)
    void set_input_kq_mask   (ggml_tensor * dst, const llama_ubatch * ubatch, bool causal_attn, uint32_t off = 0) const;
    void set_input_pos_bucket(ggml_tensor * dst, const llama_ubatch * ubatch) const;

'''),
        ('''
    size_t total_size() const;
''',
         '''
    // strixllama: regions (see set_regions)
    bool regions = false;
    // the context that runs this cache's graphs, from init_update (llama_context::decode calls it before
    // init_batch): move_cells queues its copies on that context's backend
    llama_context * lctx_sync = nullptr;
    // the owner's mirror of every move (see set_move_hook)
    std::function<void(const cell_move_vec_t &, bool)> move_hook;
    // where plan_layout put the sequences of its batch that hold no cell yet, for find_slot_regions
    mutable std::map<llama_seq_id, uint32_t> planned_start;

    // the slot of a ubatch under regions: each sequence after its last cell, a new one where plan_layout or
    // region_start puts it; empty if any of it does not fit, and find_slot searches instead
    slot_info find_slot_regions(const llama_ubatch & ubatch) const;

    // where a sequence with no cell yet starts, `tail` being the first cell after all the others; -1 if not there
    int64_t region_start(uint32_t need, uint32_t tail) const;

    // the backend of the device a tensor of this cache lives on, in the context that uses the cache
    ggml_backend_t backend_for(const ggml_tensor * t) const;

    void apply_moves(const cell_move_vec_t & moves);

    size_t total_size() const;
'''),
        ('''    uint32_t get_n_kv() const;

    ggml_type type_k() const;
    ggml_type type_v() const;
''',
         '''    uint32_t get_n_kv() const;

    // strixllama: the first cell of the graph's view of the cache (llama_kv_cache::get_kv_window)
    uint32_t get_kv_off() const;

    ggml_type type_k() const;
    ggml_type type_v() const;
'''),
        ('''    int32_t n_kv;
};
''',
         '''    int32_t n_kv;

    // strixllama: the view is [kv_off, kv_off + n_kv)
    uint32_t kv_off = 0;
};
'''),
    ],
    os.path.join(tree, "src", "llama-graph.h"): [
        ('''    ggml_tensor * self_k_rot = nullptr;
    ggml_tensor * self_v_rot = nullptr;

    // note: these have to be copies because in order to be able to reuse a graph, its inputs
''',
         '''    ggml_tensor * self_k_rot = nullptr;
    ggml_tensor * self_v_rot = nullptr;

    // strixllama: the first cell of the cache view the graph was built with (llama_kv_cache::get_kv_window);
    // the views carry it as an offset, so a graph is reusable only for the same one
    uint32_t kv_off = 0;

    // note: these have to be copies because in order to be able to reuse a graph, its inputs
'''),
    ],
    os.path.join(tree, "src", "llama-graph.cpp"): [
        ('''  //res &= self_v_idxs->ne[0] == params.ubatch.n_tokens; // TODO: need to move this to the unified cache and check there

    res &= can_reuse_kq_mask(self_kq_mask, mctx, params.ubatch, params.cparams);

    return res;
}
''',
         '''  //res &= self_v_idxs->ne[0] == params.ubatch.n_tokens; // TODO: need to move this to the unified cache and check there

    res &= can_reuse_kq_mask(self_kq_mask, mctx, params.ubatch, params.cparams);

    // strixllama: the cache views start at the window's first cell
    res &= kv_off == mctx->get_kv_off();

    return res;
}
'''),
        ('''  //res &= inp_attn->self_v_idxs->ne[0] == params.ubatch.n_tokens; // TODO: need to move this to the unified cache and check there

    res &= can_reuse_kq_mask(inp_attn->self_kq_mask, mctx->get_attn(), params.ubatch, params.cparams);

    res &= inp_rs->s_copy->ne[0] == mctx->get_recr()->get_n_rs();

''',
         '''  //res &= inp_attn->self_v_idxs->ne[0] == params.ubatch.n_tokens; // TODO: need to move this to the unified cache and check there

    res &= can_reuse_kq_mask(inp_attn->self_kq_mask, mctx->get_attn(), params.ubatch, params.cparams);

    // strixllama: the cache views start at the window's first cell
    res &= inp_attn->kv_off == mctx->get_attn()->get_kv_off();

    res &= inp_rs->s_copy->ne[0] == mctx->get_recr()->get_n_rs();

'''),
        ('''    inp->self_v_rot = mctx_cur->build_input_v_rot(ctx0);

    return inp;
}
''',
         '''    inp->self_v_rot = mctx_cur->build_input_v_rot(ctx0);

    inp->kv_off = mctx_cur->get_kv_off();

    return inp;
}
'''),
    ],
    os.path.join(tree, "src", "llama-memory-hybrid-idx.cpp"): [
        ('''        LLAMA_LOG_INFO("%s: QSA block-key cache: %zu layers, %.1f MiB\\n", __func__, kb_map.size(), bytes/1024.0/1024.0);
    }
}

''',
         '''        LLAMA_LOG_INFO("%s: QSA block-key cache: %zu layers, %.1f MiB\\n", __func__, kb_map.size(), bytes/1024.0/1024.0);
    }

    // strixllama: regions (llama_kv_cache::set_regions) - with several sequences in one unified pool, each
    // conversation keeps one run of cells and a batch's graph views only its own. The indexer mirrors the
    // attention cells, so both caches take the window, and the moves, together. LLAMA_KV_REGIONS=0 turns it off.
    {
        const char * env = getenv("LLAMA_KV_REGIONS");
        const bool on = unified && n_seq_max > 1 && (env == nullptr || atoi(env) != 0);
        get_mem_attn()->set_regions(on);
        if (mem_idx) {
            mem_idx->set_regions(on);
            if (get_mem_attn()->get_regions() != mem_idx->get_regions()) {
                get_mem_attn()->set_regions(false);
                mem_idx->set_regions(false);
            }
        }
        if (get_mem_attn()->get_regions()) {
            // every move of the attention cells - a rebalance for a batch or for a restore - moves the indexer's
            // cells and the block keys with them, in the same step
            get_mem_attn()->set_move_hook([this](const llama_kv_cache::cell_move_vec_t & moves, bool sync) {
                if (mem_idx) {
                    GGML_ASSERT(mem_idx->can_move());
                    mem_idx->move_cells(moves, sync);
                }
                kb_move_rows(moves);
            });
            fprintf(stderr, "kv regions: on, one run of cells per conversation, %u sequences, %u cells\\n", n_seq_max, kv_size);
        }
    }
}

'''),
        ('''bool llama_memory_hybrid_idx::kb_needs_full() const {
    return kb_full_gen != kb_gen;
}

void llama_memory_hybrid_idx::kb_mark_full() const {
    kb_full_gen = kb_gen;
}

bool llama_memory_hybrid_idx::kb_pos_dup() const {
    return kb_dup;
''',
         '''bool llama_memory_hybrid_idx::kb_needs_full(const llama_ubatch & ubatch) const {
    if (kb_stale.none() || !ubatch.seq_id || !ubatch.n_seq_id) {
        return false;
    }
    for (uint32_t i = 0; i < ubatch.n_tokens; ++i) {
        for (int32_t k = 0; k < ubatch.n_seq_id[i]; ++k) {
            const llama_seq_id s = ubatch.seq_id[i][k];
            if (s >= 0 && s < LLAMA_MAX_SEQ && kb_stale.test(s)) {
                return true;
            }
        }
    }
    return false;
}

void llama_memory_hybrid_idx::kb_mark_full(const llama_ubatch & ubatch) const {
    if (!ubatch.seq_id || !ubatch.n_seq_id) {
        return;
    }
    for (uint32_t i = 0; i < ubatch.n_tokens; ++i) {
        for (int32_t k = 0; k < ubatch.n_seq_id[i]; ++k) {
            const llama_seq_id s = ubatch.seq_id[i][k];
            if (s >= 0 && s < LLAMA_MAX_SEQ) {
                kb_stale.reset(s);
            }
        }
    }
}

void llama_memory_hybrid_idx::kb_mark_stale(llama_seq_id seq_id) {
    if (seq_id < 0 || seq_id >= LLAMA_MAX_SEQ) {
        kb_stale.set();
    } else {
        kb_stale.set(seq_id);
    }
}

bool llama_memory_hybrid_idx::kb_pos_dup() const {
    return kb_dup;
}

// A block's key sits at the row of its first cell. The moves lay a sequence out in position order, so its keys
// can follow their cells only if its cells were in that order already (then every block keeps its first cell);
// a sequence whose cells were not has its keys rebuilt once instead.
void llama_memory_hybrid_idx::kb_move_rows(const llama_kv_cache::cell_move_vec_t & moves) {
    llama_kv_cache::cell_move_vec_t rows;
    for (const auto & m : moves) {
        if (m.ordered) {
            rows.push_back(m);
        } else {
            kb_mark_stale(m.seq);
        }
    }
    for (const auto & [il, t] : kb_map) {
        get_mem_attn()->copy_rows(t, rows);
    }
'''),
        ('''
        // prepare the recurrent batches first
''',
         '''
        // strixllama: regions - when the batch does not fit after its conversations' last cells, the pool is
        // rebalanced first; the hook set in the constructor moves the indexer and the block keys along
        if (get_mem_attn()->can_move() && (!mem_idx || mem_idx->can_move())) {
            get_mem_attn()->move_cells(get_mem_attn()->plan_layout(ubatches));
        }

        // prepare the recurrent batches first
'''),
        ('''void llama_memory_hybrid_idx::clear(bool data) {
    kb_gen++;   // strixllama: block keys depend on positions and cell contents; rebuild them all once
    kb_dup = false;   // strixllama: no cells left, so no image cells either
''',
         '''void llama_memory_hybrid_idx::clear(bool data) {
    kb_mark_stale(-1);   // strixllama: block keys depend on positions and cell contents; rebuild them once
    kb_dup = false;   // strixllama: no cells left, so no image cells either
'''),
        ('''void llama_memory_hybrid_idx::seq_cp(llama_seq_id seq_id_src, llama_seq_id seq_id_dst, llama_pos p0, llama_pos p1) {
    llama_memory_hybrid::seq_cp(seq_id_src, seq_id_dst, p0, p1);
''',
         '''void llama_memory_hybrid_idx::seq_cp(llama_seq_id seq_id_src, llama_seq_id seq_id_dst, llama_pos p0, llama_pos p1) {
    // strixllama: the copy shares the source's cells, and with them block keys that may still have to be rebuilt
    if (seq_id_src >= 0 && seq_id_src < LLAMA_MAX_SEQ && kb_stale.test(seq_id_src)) {
        kb_mark_stale(seq_id_dst);
    }

    llama_memory_hybrid::seq_cp(seq_id_src, seq_id_dst, p0, p1);
'''),
        ('''    kb_gen++;   // strixllama: block keys depend on positions and cell contents; rebuild them all once
    llama_memory_hybrid::seq_add(seq_id, p0, p1, shift);

    if (mem_idx) {
        mem_idx->seq_add(seq_id, p0, p1, shift);
    }
}

void llama_memory_hybrid_idx::seq_div(llama_seq_id seq_id, llama_pos p0, llama_pos p1, int d) {
    kb_gen++;   // strixllama: block keys depend on positions and cell contents; rebuild them all once
''',
         '''    kb_mark_stale(-1);   // strixllama: block keys depend on positions; a shifted cell can be shared, so all of them
    llama_memory_hybrid::seq_add(seq_id, p0, p1, shift);

    if (mem_idx) {
        mem_idx->seq_add(seq_id, p0, p1, shift);
    }
}

void llama_memory_hybrid_idx::seq_div(llama_seq_id seq_id, llama_pos p0, llama_pos p1, int d) {
    kb_mark_stale(-1);   // strixllama: block keys depend on positions; a shifted cell can be shared, so all of them
'''),
        ('''void llama_memory_hybrid_idx::state_read(llama_io_read_i & io, llama_seq_id seq_id, llama_state_seq_flags flags) {
    kb_gen++;   // strixllama: block keys depend on positions and cell contents; rebuild them all once
    // note: repeats llama_memory_hybrid::state_read
''',
         '''void llama_memory_hybrid_idx::state_read(llama_io_read_i & io, llama_seq_id seq_id, llama_state_seq_flags flags) {
    kb_mark_stale(seq_id);   // strixllama: the restored cells' block keys were never written; rebuild them once
    // note: repeats llama_memory_hybrid::state_read
'''),
        ('''        if ((flags & LLAMA_STATE_SEQ_FLAGS_PARTIAL_ONLY) == 0) {
            get_mem_attn()->state_read_sinfo(io, seq_id, flags, mem_idx ? &sinfos_attn : nullptr, nullptr);
''',
         '''        if ((flags & LLAMA_STATE_SEQ_FLAGS_PARTIAL_ONLY) == 0) {
            // strixllama: the attention restore drops the sequence's old cells and may rebalance the pool before
            // it places the new ones (regions); the move hook repeats that rebalance on the indexer, which must
            // then hold the same cells - so the indexer drops them first too (its own restore would, later)
            if (mem_idx && seq_id >= 0 && get_mem_attn()->get_regions()) {
                mem_idx->seq_rm(seq_id, -1, -1);
            }
            get_mem_attn()->state_read_sinfo(io, seq_id, flags, mem_idx ? &sinfos_attn : nullptr, nullptr);
'''),
        ('''        ggml_tensor * bias, const llama_ubatch * ubatch, uint32_t ratio, bool blk_bias, const qsa_kb_inputs * kb) const {
    set_input_qsa_impl(cell_blk, blk_cells, blk_pos, bias, nullptr, ubatch, ratio, blk_bias, kb);
}

void llama_memory_hybrid_idx::set_input_qsa_blocks(
        ggml_tensor * cell_blk, ggml_tensor * blk_cells, ggml_tensor * blk_pos,
        ggml_tensor * bias, ggml_tensor * tail_idxs, const llama_ubatch * ubatch, uint32_t ratio, const qsa_kb_inputs * kb, const qsa_mixed_inputs * mixed,
        bool active_only) const {
    set_input_qsa_impl(cell_blk, blk_cells, blk_pos, bias, tail_idxs, ubatch, ratio, true, kb, mixed, active_only);
}
''',
         '''        ggml_tensor * bias, const llama_ubatch * ubatch, uint32_t ratio, bool blk_bias, const qsa_kb_inputs * kb,
        uint32_t kv_off) const {
    set_input_qsa_impl(cell_blk, blk_cells, blk_pos, bias, nullptr, ubatch, ratio, blk_bias, kb, nullptr, false, kv_off);
}

void llama_memory_hybrid_idx::set_input_qsa_blocks(
        ggml_tensor * cell_blk, ggml_tensor * blk_cells, ggml_tensor * blk_pos,
        ggml_tensor * bias, ggml_tensor * tail_idxs, const llama_ubatch * ubatch, uint32_t ratio, const qsa_kb_inputs * kb, const qsa_mixed_inputs * mixed,
        bool active_only, uint32_t kv_off) const {
    set_input_qsa_impl(cell_blk, blk_cells, blk_pos, bias, tail_idxs, ubatch, ratio, true, kb, mixed, active_only, kv_off);
}

// strixllama: the indexer cells as the graph's view sees them, from its first cell (llama_kv_cache::get_kv_window)
struct hybrid_idx_cells_view {
    const llama_kv_cells & cells;
    const uint32_t         off;

    bool                              is_empty   (uint32_t j)                 const { return cells.is_empty(off + j); }
    const llama_kv_cells::seq_set_t & seq_get_all(uint32_t j)                 const { return cells.seq_get_all(off + j); }
    bool                              seq_has    (uint32_t j, llama_seq_id s) const { return cells.seq_has(off + j, s); }
    llama_pos                         pos_get    (uint32_t j)                 const { return cells.pos_get(off + j); }
    const llama_kv_cell_ext &         ext_get    (uint32_t j)                 const { return cells.ext_get(off + j); }
    llama_pos                         seq_pos_min(llama_seq_id s)             const { return cells.seq_pos_min(s); }
};
'''),
        ('''        const qsa_mixed_inputs * mixed,
        bool active_only) const {
    GGML_ASSERT(ratio > 0);
''',
         '''        const qsa_mixed_inputs * mixed,
        bool active_only,
        uint32_t kv_off) const {
    GGML_ASSERT(ratio > 0);
'''),
        ('''    if (active_only) {
        for (int64_t i = 0; i < n_tokens; ++i) {
            for (int32_t k = 0; k < ubatch->n_seq_id[i]; ++k) { active_seqs.set(ubatch->seq_id[i][k]); }
        }
    }
''',
         '''    for (int64_t i = 0; i < n_tokens; ++i) {
        for (int32_t k = 0; k < ubatch->n_seq_id[i]; ++k) { active_seqs.set(ubatch->seq_id[i][k]); }
    }
    // strixllama: a cell of no sequence of this ubatch is invisible to every query in it, and its block key is
    // rebuilt by its own sequence's graph when it goes stale (kb_needs_full), so it is left out of the blocks.
    // That also keeps a window's foreign cells - the neighbours of the run a window views, whose positions have
    // nothing to do with it - out of the position buckets.
'''),
        ('''        const auto & cells = get_mem_idx()->get_cells(seq_of_stream);
''',
         '''        // strixllama: every index below is relative to the view's first cell
        GGML_ASSERT(kv_off == 0 || n_ns == 1);
        const hybrid_idx_cells_view cells = { get_mem_idx()->get_cells(seq_of_stream), kv_off };
'''),
        ('''                if (active_only && (cells.seq_get_all(j) & active_seqs).none()) {
''',
         '''                if ((cells.seq_get_all(j) & active_seqs).none()) {
'''),
        ('''                br[b] = b < n_bid ? bid_cell[b] : scratch;
''',
         '''                br[b] = b < n_bid ? (int32_t) kv_off + bid_cell[b] : scratch;
'''),
        ('''                dd[n_dirty] = bid_cell[b];
''',
         '''                dd[n_dirty] = (int32_t) kv_off + bid_cell[b];
'''),
        ('''    mem->set_input_qsa(cell_blk, blk_cells, blk_pos, bias, ubatch, ratio, blk_bias, kb);
''',
         '''    mem->set_input_qsa(cell_blk, blk_cells, blk_pos, bias, ubatch, ratio, blk_bias, kb, get_idx()->get_kv_off());
'''),
        ('''bool llama_memory_hybrid_idx_context::kb_needs_full() const {
    return mem ? mem->kb_needs_full() : false;
}

bool llama_memory_hybrid_idx_context::kb_pos_dup() const {
    return mem ? mem->kb_pos_dup() : false;
}

void llama_memory_hybrid_idx_context::kb_mark_full() const {
    if (mem) { mem->kb_mark_full(); }
''',
         '''bool llama_memory_hybrid_idx_context::kb_needs_full(const llama_ubatch & ubatch) const {
    return mem ? mem->kb_needs_full(ubatch) : false;
}

bool llama_memory_hybrid_idx_context::kb_pos_dup() const {
    return mem ? mem->kb_pos_dup() : false;
}

void llama_memory_hybrid_idx_context::kb_mark_full(const llama_ubatch & ubatch) const {
    if (mem) { mem->kb_mark_full(ubatch); }
'''),
        ('''    mem->set_input_qsa_blocks(cell_blk, blk_cells, blk_pos, bias, tail_idxs, ubatch, ratio, kb, mixed, active_only);
''',
         '''    mem->set_input_qsa_blocks(cell_blk, blk_cells, blk_pos, bias, tail_idxs, ubatch, ratio, kb, mixed, active_only,
            get_idx()->get_kv_off());
'''),
        ('''    return qsa_single_sequence_prefix(mem->get_mem_idx()->get_cells(seq),get_idx()->get_n_kv(),seq,active_only);
''',
         '''    // strixllama: set_input_qsa_impl leaves other sequences' cells out of the blocks, so they cannot break the
    // prefix; the window starts at get_kv_off()
    return qsa_single_sequence_prefix(mem->get_mem_idx()->get_cells(seq),get_idx()->get_n_kv(),seq,true,
            get_idx()->get_kv_off());
'''),
        ('''// the budget. A graph that rewrites every block key (kb_needs_full) keeps the whole pool: it is the one that
// refreshes the idle sequences' keys too. So does the reserve graph (positions all equal), which sizes the
// buffers for the widest graph. LLAMA_QSA_ACTIVE_BLOCKS=0 turns this off.
int64_t llama_memory_hybrid_idx_context::qsa_active_blocks(const llama_ubatch & ubatch, uint32_t ratio, int64_t min_blocks) const {
    static const bool on = !getenv("LLAMA_QSA_ACTIVE_BLOCKS") || atoi(getenv("LLAMA_QSA_ACTIVE_BLOCKS")) != 0;
    if (!on || mem == nullptr || get_idx() == nullptr || ratio == 0 || get_n_stream() != 1 ||
            mem->kb_needs_full() || mem->kb_pos_dup() || !qsa_scalar_visibility(ubatch)) {
''',
         '''// the budget. The reserve graph (positions all equal) keeps the whole pool: it sizes the buffers for the widest
// graph. LLAMA_QSA_ACTIVE_BLOCKS=0 turns this off.
int64_t llama_memory_hybrid_idx_context::qsa_active_blocks(const llama_ubatch & ubatch, uint32_t ratio, int64_t min_blocks) const {
    static const bool on = !getenv("LLAMA_QSA_ACTIVE_BLOCKS") || atoi(getenv("LLAMA_QSA_ACTIVE_BLOCKS")) != 0;
    if (!on || mem == nullptr || get_idx() == nullptr || ratio == 0 || get_n_stream() != 1 ||
            mem->kb_pos_dup() || !qsa_scalar_visibility(ubatch)) {
'''),
        ('''        for (uint32_t j=0;j<get_idx()->get_n_kv();++j) {
''',
         '''        const uint32_t off=get_idx()->get_kv_off();   // strixllama: the window's first cell
        for (uint32_t j=off;j<off+get_idx()->get_n_kv();++j) {
'''),
    ],
    os.path.join(tree, "src", "llama-memory-hybrid-idx.h"): [
        ('''    };
    void set_input_qsa(ggml_tensor * cell_blk, ggml_tensor * blk_cells, ggml_tensor * blk_pos,
''',
         '''    };
    // strixllama: kv_off = the first cell of the graph's view of the caches (llama_kv_cache::get_kv_window).
    // Every cell index these inputs carry is relative to it, except the block-key cache rows, which address
    // the whole cache tensor.
    void set_input_qsa(ggml_tensor * cell_blk, ggml_tensor * blk_cells, ggml_tensor * blk_pos,
'''),
        ('''                       bool blk_bias, const qsa_kb_inputs * kb = nullptr) const;
''',
         '''                       bool blk_bias, const qsa_kb_inputs * kb = nullptr, uint32_t kv_off = 0) const;
'''),
        ('''                             const qsa_mixed_inputs * mixed = nullptr, bool active_only = false) const;
''',
         '''                             const qsa_mixed_inputs * mixed = nullptr, bool active_only = false, uint32_t kv_off = 0) const;
'''),
        ('''    bool          kb_needs_full() const;      // positions moved (shift, restore, clear) since the last full write
    void          kb_mark_full() const;
''',
         '''    // strixllama: a sequence's block keys go stale when its positions move or its cells are restored or moved out
    // of order; the next graph of a ubatch holding it rebuilds every key of that ubatch's sequences
    bool          kb_needs_full(const llama_ubatch & ubatch) const;
    void          kb_mark_full(const llama_ubatch & ubatch) const;
'''),
        ('''    // the position, which the block-key cache cannot track - the graph must not wire the cache in.
    bool          kb_pos_dup() const;

private:
''',
         '''    // the position, which the block-key cache cannot track - the graph must not wire the cache in.
    bool          kb_pos_dup() const;


private:
'''),
        ('''                            const qsa_kb_inputs * kb, const qsa_mixed_inputs * mixed = nullptr,
                            bool active_only = false) const;

''',
         '''                            const qsa_kb_inputs * kb, const qsa_mixed_inputs * mixed = nullptr,
                            bool active_only = false, uint32_t kv_off = 0) const;

'''),
        ('''    uint64_t                             kb_gen      = 1;
    mutable uint64_t                     kb_full_gen = 0;
''',
         '''    // the sequences whose block keys have to be rebuilt (see kb_needs_full). All of them at the start and after
    // a clear, so the first graph of every sequence builds its keys the way it always has
    mutable std::bitset<LLAMA_MAX_SEQ>   kb_stale = std::bitset<LLAMA_MAX_SEQ>().set();
    void kb_mark_stale(llama_seq_id seq_id);   // < 0: every sequence
    // strixllama: regions - block-key rows follow their cells (llama_kv_cache::move_cells)
    void kb_move_rows(const llama_kv_cache::cell_move_vec_t & moves);
'''),
        ('''    bool          kb_needs_full() const;
    void          kb_mark_full() const;
''',
         '''    bool          kb_needs_full(const llama_ubatch & ubatch) const;
    void          kb_mark_full(const llama_ubatch & ubatch) const;
'''),
    ],
    os.path.join(tree, "src", "models", "qwen4exp.cpp"): [
        ('''        GGML_ASSERT(mctx_idx->get_n_kv() == inp->mctx->get_attn()->get_n_kv() &&
                "the indexer cache must track the attention cache cell for cell");
''',
         '''        GGML_ASSERT(mctx_idx->get_n_kv() == inp->mctx->get_attn()->get_n_kv() &&
                mctx_idx->get_kv_off() == inp->mctx->get_attn()->get_kv_off() &&
                "the indexer cache must track the attention cache cell for cell");
'''),
        ('''            inp_attn = inp_hyb->get_attn();
            // the MTP graph has no recurrent layers, so the hybrid input's recurrent tensors are never used and the
''',
         '''            inp_attn = inp_hyb->get_attn();
            GGML_ASSERT(m->get_idx()->get_n_kv() == m->get_attn()->get_n_kv() &&
                    m->get_idx()->get_kv_off() == m->get_attn()->get_kv_off() &&
                    "the indexer cache must track the attention cache cell for cell");
            // the MTP graph has no recurrent layers, so the hybrid input's recurrent tensors are never used and the
'''),
        ('''            mctx->kb_mark_full();
''',
         '''            mctx->kb_mark_full(*ubatch);
'''),
        ('''            res &= kb_full == mctx->kb_needs_full();
''',
         '''            res &= kb_full == mctx->kb_needs_full(params.ubatch);
'''),
        ('''            qsa->kb_full        = mctx_hyb->kb_needs_full();
''',
         '''            qsa->kb_full        = mctx_hyb->kb_needs_full(ubatch);
'''),
    ],
    os.path.join(tree, "src", "prefix.h"): [
        ('''// do not break the prefix; the sequence's own cells must still be its alone
static bool qsa_single_sequence_prefix(const llama_kv_cells & cells, uint32_t count, llama_seq_id seq, bool active_only = false) {
    if (count>cells.size()) { return false; }
''',
         '''// do not break the prefix; the sequence's own cells must still be its alone. off = the view's first cell.
static bool qsa_single_sequence_prefix(const llama_kv_cells & cells, uint32_t count, llama_seq_id seq, bool active_only = false,
        uint32_t off = 0) {
    if ((uint64_t) off+count>cells.size()) { return false; }
'''),
        ('''    for (uint32_t i=0;i<count;++i) {
''',
         '''    for (uint32_t i=off;i<off+count;++i) {
'''),
    ],
}


def main():
    texts = {p: io.open(p, encoding="utf-8").read() for p in EDITS}
    if any(MARKER in t for t in texts.values()):
        print("already applied")
        return
    for p, pairs in EDITS.items():
        for old, new in pairs:
            if texts[p].count(old) != 1:
                sys.exit("anchor found %d times, expected once, in %s" % (texts[p].count(old), p))
            texts[p] = texts[p].replace(old, new, 1)
    for p, t in texts.items():
        io.open(p, "w", encoding="utf-8", newline="").write(t)
    print("patched", ", ".join(os.path.basename(p) for p in EDITS))


if __name__ == "__main__":
    main()
