#!/usr/bin/env python3
"""A Q8_0 K/V cache for qwen4exp: half the memory, the same kernels

The sparse-attention prefill kernel (qsa3) reads K and V only through packed f16 layouts, so a Q8_0 cache is dequantized into them in the graph (a Q8_0 -> f16 copy kernel, cpy.cu) and the kernel accepts the type; the decode gather and the block-key rebuild read Q8_0 rows through the same get_rows as f16. The indexer's keys stay f16. V is not rotated for this architecture: qsa3's matrix-core sums move in the last bit with the V of keys they weight by zero - free cells after a conversation's last one, holding whatever an earlier conversation left - and the inverse rotation of the output spread that bit far enough that a conversation read back from disk parted from the same one kept in memory; K stays rotated. The disk tier deletes entries whose rows are another size (a cache of the other type) as it opens, as it does older formats. Target K/V at 262144 tokens: 6 GiB f16, 3.2 GiB Q8_0; mean KLD against f16 0.0139 +/- 0.0007 (f16 against itself at another batch size: 0.0116).

Generated by tools/make_patch_script.py from the tree it must reproduce, so every anchor is
unique by construction. 18 hunks across 9 file(s).

Usage: python D:/Work/strixllama/patches/apply_kv_q8_0.py [tree]
"""
import io
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
tree = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "src", "llama.cpp")
MARKER = 'qsa3_kv_type_ok'

EDITS = {
    os.path.join(tree, "ggml", "src", "ggml-cuda", "cpy.cu"): [
        ('''        *(cdstf + j + 1) = dq.y;
    }
''',
         '''        *(cdstf + j + 1) = dq.y;
    }
}

// strixllama: a Q8_0 KV cache read back as f16, as the packed layouts of the sparse attention kernels want it
static __device__ void cpy_blck_q8_0_f16(const char * cxi, char * cdsti) {
    half * cdsth = (half *)(cdsti);

#pragma unroll
    for (int j = 0; j < QK8_0; j += 2) {
        float2 dq;
        dequantize_q8_0(cxi, 0, j, dq);
        *(cdsth + j) = __float2half(dq.x);
        *(cdsth + j + 1) = __float2half(dq.y);
    }
'''),
        ('''    cpy_q_f32<cpy_blck_q8_0_f32, QK8_0><<<num_blocks, CUDA_CPY_BLOCK_SIZE, 0, stream>>>
        (cx, cdst, ne, ne00, ne01, ne02, nb00, nb01, nb02, nb03, ne10, ne11, ne12, nb10, nb11, nb12, nb13);
''',
         '''    cpy_q_f32<cpy_blck_q8_0_f32, QK8_0><<<num_blocks, CUDA_CPY_BLOCK_SIZE, 0, stream>>>
        (cx, cdst, ne, ne00, ne01, ne02, nb00, nb01, nb02, nb03, ne10, ne11, ne12, nb10, nb11, nb12, nb13);
}

static void ggml_cpy_q8_0_f16_cuda(
    const char * cx, char * cdst, const int64_t ne,
    const int64_t ne00, const int64_t ne01, const int64_t ne02, const int64_t nb00, const int64_t nb01, const int64_t nb02,
    const int64_t nb03, const int64_t ne10, const int64_t ne11, const int64_t ne12, const int64_t nb10, const int64_t nb11, const int64_t nb12, const int64_t nb13, cudaStream_t stream) {

    const int64_t num_blocks = (ne/QK8_0 + CUDA_CPY_BLOCK_SIZE - 1) / CUDA_CPY_BLOCK_SIZE;
    GGML_ASSERT(num_blocks <= INT_MAX);
    cpy_q_f32<cpy_blck_q8_0_f16, QK8_0><<<num_blocks, CUDA_CPY_BLOCK_SIZE, 0, stream>>>
        (cx, cdst, ne, ne00, ne01, ne02, nb00, nb01, nb02, nb03, ne10, ne11, ne12, nb10, nb11, nb12, nb13);
'''),
        ('''                (src0_ddc, src1_ddc, ne, ne00, ne01, ne02, nb00, nb01, nb02, nb03, ne10, ne11, ne12, nb10, nb11, nb12, nb13, main_stream);
    } else if (src0->type == GGML_TYPE_F32 && src1->type == GGML_TYPE_Q4_0) {
''',
         '''                (src0_ddc, src1_ddc, ne, ne00, ne01, ne02, nb00, nb01, nb02, nb03, ne10, ne11, ne12, nb10, nb11, nb12, nb13, main_stream);
    } else if (src0->type == GGML_TYPE_Q8_0 && src1->type == GGML_TYPE_F16) {
        ggml_cpy_q8_0_f16_cuda
                (src0_ddc, src1_ddc, ne, ne00, ne01, ne02, nb00, nb01, nb02, nb03, ne10, ne11, ne12, nb10, nb11, nb12, nb13, main_stream);
    } else if (src0->type == GGML_TYPE_F32 && src1->type == GGML_TYPE_Q4_0) {
'''),
    ],
    os.path.join(tree, "ggml", "src", "ggml-cuda", "ggml-cuda.cu"): [
        ('''                }
                if (src0_type == GGML_TYPE_F32 && src1_type == GGML_TYPE_Q4_0) {
''',
         '''                }
                if (src0_type == GGML_TYPE_Q8_0 && src1_type == GGML_TYPE_F16) {
                    return true;
                }
                if (src0_type == GGML_TYPE_F32 && src1_type == GGML_TYPE_Q4_0) {
'''),
    ],
    os.path.join(tree, "ggml", "src", "ggml-cuda", "qsa.cu"): [
        ('''
bool ggml_cuda_flash_attn_ext_qsa_supported(ggml_backend_cuda_context & ctx, const ggml_tensor * dst) {
''',
         '''
// strixllama: the kernel reads K and V only through their packed f16 copies (src 6 and 7), so the cache itself may
// be Q8_0 as well - the graph dequantizes it into them
static bool qsa3_kv_type_ok(const ggml_tensor * t) {
    return (t->type == GGML_TYPE_F16 && t->nb[0] == 2) || t->type == GGML_TYPE_Q8_0;
}

bool ggml_cuda_flash_attn_ext_qsa_supported(ggml_backend_cuda_context & ctx, const ggml_tensor * dst) {
'''),
        ('''    if (bias != 0 || softcap != 0 || q->type != GGML_TYPE_F32 || k->type != GGML_TYPE_F16 || v->type != GGML_TYPE_F16 ||
''',
         '''    if (bias != 0 || softcap != 0 || q->type != GGML_TYPE_F32 || !qsa3_kv_type_ok(k) || !qsa3_kv_type_ok(v) ||
'''),
        ('''        q->ne[3] != 1 || k->ne[3] != 1 || v->ne[3] != 1 || q->nb[0] != 4 || k->nb[0] != 2 || v->nb[0] != 2 ||
''',
         '''        q->ne[3] != 1 || k->ne[3] != 1 || v->ne[3] != 1 || q->nb[0] != 4 ||
'''),
    ],
    os.path.join(tree, "src", "llama-memory-hybrid-idx.cpp"): [
        ('''        return new llama_kv_cache(
            model, hparams_idx, type_k, type_v, v_trans, offload, unified,
''',
         '''        // strixllama: the indexer keys stay f16 whatever the attention cache is - they are pooled into the block keys
        // the selection is scored on, and they are ~1/8 of the attention cache
        return new llama_kv_cache(
            model, hparams_idx, GGML_TYPE_F16, GGML_TYPE_F16, v_trans, offload, unified,
'''),
    ],
    os.path.join(tree, "src", "llama-kv-cache.cpp"): [
        ('''        attn_rot_v =
            !attn_rot_disable &&
''',
         '''        // strixllama: qwen4exp keeps V as it is. Its sparse-attention prefill kernel (qsa3) sums P*V on the matrix
        // cores, and those sums move in the last bit with the V of keys they weight by zero - the free cells after
        // a conversation's last one, which hold whatever an earlier conversation left there. The inverse rotation
        // of the output spreads that bit over 64 dimensions, far enough to reach the tokens, so a conversation read
        // back from disk parted from the same one kept in memory; unrotated it does not. K rotated alone: mean KLD
        // against f16 0.0139 +/- 0.0007, both rotated 0.0137.
        attn_rot_v =
            !attn_rot_disable && model.arch != LLM_ARCH_QWEN4EXP &&
'''),
    ],
    os.path.join(tree, "src", "models", "qwen4exp.cpp"): [
        ('''    GGML_ASSERT(a->type == GGML_TYPE_F16 && b->type == GGML_TYPE_I32 && b->ne[1] == 1 && b->ne[2] == 1 && b->ne[3] == 1);
''',
         '''    // strixllama: a Q8_0 cache is dequantized by the same kernel on the way out
    GGML_ASSERT((a->type == GGML_TYPE_F16 || a->type == GGML_TYPE_Q8_0) && b->type == GGML_TYPE_I32 && b->ne[1] == 1 && b->ne[2] == 1 && b->ne[3] == 1);
'''),
        ('''    if (layout_prefill && pack_option && atoi(pack_option)!=0) {
        auto * original_keys=ggml_permute(ctx0,mctx_cur->get_k(ctx0,il),0,2,1,3);
''',
         '''    // strixllama: the sparse prefill kernel reads K and V only through these packed f16 layouts, so a Q8_0 cache is
    // dequantized into them here and the kernel does not change
    auto kv_for_packing = [&](ggml_tensor * t) {
        return t->type == GGML_TYPE_Q8_0 ? ggml_cast(ctx0, t, GGML_TYPE_F16) : t;
    };
    if (layout_prefill && pack_option && atoi(pack_option)!=0) {
        auto * original_keys=ggml_permute(ctx0,kv_for_packing(mctx_cur->get_k(ctx0,il)),0,2,1,3);
'''),
        ('''        auto * original_values=ggml_permute(ctx0,mctx_cur->get_v(ctx0,il),0,2,1,3);
''',
         '''        auto * original_values=ggml_permute(ctx0,kv_for_packing(mctx_cur->get_v(ctx0,il)),0,2,1,3);
'''),
        ('''            k->type == GGML_TYPE_F16 && v->type == GGML_TYPE_F16 && v->nb[1] <= v->nb[2] &&
''',
         '''            (k->type == GGML_TYPE_F16 || k->type == GGML_TYPE_Q8_0) && (v->type == GGML_TYPE_F16 || v->type == GGML_TYPE_Q8_0) &&
            v->nb[1] <= v->nb[2] &&
'''),
        ('''            GGML_ASSERT(q->ne[0] == 256 && k->type == GGML_TYPE_F16 && v->type == GGML_TYPE_F16);
''',
         '''            GGML_ASSERT(q->ne[0] == 256 && (k->type == GGML_TYPE_F16 || k->type == GGML_TYPE_Q8_0) &&
                                           (v->type == GGML_TYPE_F16 || v->type == GGML_TYPE_Q8_0));
'''),
    ],
    os.path.join(tree, "tools", "server", "server-task.h"): [
        ('''    // is the format this server writes (3 where its contexts serve rows by position, else 2): entries of an
    // earlier one are deleted as the store is opened
    void     set_disk(const std::string & root, size_t limit_mib, bool has_mtmd, const std::string & model_tag, int32_t version);
''',
         '''    // is the format this server writes (3 where its contexts serve rows by position, else 2), and row_tgt /
    // row_dft its rows' sizes (0 without a draft): entries of an earlier format, or with rows this server cannot
    // take, are deleted as the store is opened
    void     set_disk(const std::string & root, size_t limit_mib, bool has_mtmd, const std::string & model_tag, int32_t version,
                      uint64_t row_tgt = 0, uint64_t row_dft = 0);
'''),
    ],
    os.path.join(tree, "tools", "server", "server-task.cpp"): [
        ('''                                   int32_t version) {
''',
         '''                                   int32_t version, uint64_t row_tgt, uint64_t row_dft) {
'''),
        ('''        if (!scan_entry(stage, e, disk_has_mtmd, disk_version, why, foreign, old)) {
''',
         '''        bool ok = scan_entry(stage, e, disk_has_mtmd, disk_version, why, foreign, old);
        // rows of another size - a K/V cache of another type, or no draft where this server drafts - are as
        // unusable as an older format, and go the same way
        if (ok && e.version == (int32_t) SPC_V3 && row_tgt > 0 && (e.row_tgt != row_tgt || (row_dft > 0 && e.row_dft != row_dft))) {
            ok = false;
            old = true;
        }
        if (!ok) {
'''),
    ],
    os.path.join(tree, "tools", "server", "server-context.cpp"): [
        ('''                const bool rows = llama_strix_kv_row_size(ctx_tgt) > 0 && (!ctx_dft || llama_strix_kv_row_size(ctx_dft) > 0);
                prompt_cache->set_disk(dir, mib ? std::max(1, atoi(mib)) : 16384, mctx != nullptr, tag, rows ? 3 : 2);
''',
         '''                const uint64_t row_tgt = llama_strix_kv_row_size(ctx_tgt);
                const uint64_t row_dft = ctx_dft ? llama_strix_kv_row_size(ctx_dft) : 0;
                const bool rows = row_tgt > 0 && (!ctx_dft || row_dft > 0);
                prompt_cache->set_disk(dir, mib ? std::max(1, atoi(mib)) : 16384, mctx != nullptr, tag, rows ? 3 : 2,
                                       rows ? row_tgt : 0, rows ? row_dft : 0);
'''),
    ],
}


def main():
    texts = {p: io.open(p, encoding="utf-8").read() for p in EDITS}
    if any(MARKER in t for t in texts.values()):
        print("already applied")
        return
    for p, pairs in EDITS.items():
        for old, new in pairs:
            if texts[p].count(old) != 1:
                sys.exit("anchor found %d times, expected once, in %s" % (texts[p].count(old), p))
            texts[p] = texts[p].replace(old, new, 1)
    for p, t in texts.items():
        io.open(p, "w", encoding="utf-8", newline="").write(t)
    print("patched", ", ".join(os.path.basename(p) for p in EDITS))


if __name__ == "__main__":
    main()
