#!/usr/bin/env python3
"""Read a cache entry straight from the device instead of through the page cache

A 5.630 GiB entry took 11427 ms to read (505 MB/s) while the same file read with FILE_FLAG_NO_BUFFERING comes off the drive in 1671 ms (3451 MB/s); a copy written in one pass reads at the same speed, so it is neither fragmentation nor the drive. It is the cached I/O path: every GiB is DMA'd into the page cache and copied out again, on a machine where the GPU carve leaves 31.6 GB of system memory. The data is read once and handed to the GPU, so that copy is pure cost, and it evicts whatever the desktop was using. Reads now go through one aligned 8 MB staging buffer: 1656 ms at 3482 MB/s, and the 79K-token conversation returns in 8.1 s instead of 18.1. A volume that refuses unbuffered I/O falls back to a buffered handle, and a file that cannot be opened is no longer mistaken for a corrupt one and deleted. The log line splits the time into file and buffers.

Generated by tools/make_patch_script.py from the tree it must reproduce, so every anchor is
unique by construction. 13 hunks across 1 file(s).

Usage: python patches/apply_spc_direct_io.py [tree]
"""
import io
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
tree = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "src", "llama.cpp")
MARKER = 'FILE_FLAG_NO_BUFFERING'

EDITS = {
    os.path.join(tree, "tools", "server", "server-task.cpp"): [
        ('''#include <fstream>

''',
         '''#include <fstream>
#ifdef _WIN32
#  ifndef NOMINMAX
#    define NOMINMAX
#  endif
#  ifndef WIN32_LEAN_AND_MEAN
#    define WIN32_LEAN_AND_MEAN
#  endif
#  include <windows.h>
#endif

'''),
        ('''template <typename T> void spc_put(std::ofstream & f, const T & v) { f.write((const char *) &v, sizeof(v)); }
template <typename T> bool spc_get(std::ifstream & f, T & v) { f.read((char *) &v, sizeof(v)); return (bool) f; }
''',
         '''// strixllama: entries are read once and handed straight to the GPU, so the page cache only gets in
// the way - it copies every GiB twice and evicts whatever the desktop was using. On Windows the file
// is opened unbuffered and served through one aligned staging buffer; measured 505 -> ~3400 MB/s.
#ifdef _WIN32
struct spc_file {
    static constexpr size_t STAGE = 8u << 20;   // a multiple of every sector size in use

    HANDLE    h    = INVALID_HANDLE_VALUE;
    uint8_t * stage = nullptr;
    size_t    have = 0;     // valid bytes in stage
    size_t    used = 0;     // consumed from stage
    bool      bad  = false;

    ~spc_file() {
        if (h != INVALID_HANDLE_VALUE) CloseHandle(h);
        if (stage) VirtualFree(stage, 0, MEM_RELEASE);
    }

    bool open(const std::string & path) {
        const std::wstring w = std::filesystem::path(path).wstring();
        h = CreateFileW(w.c_str(), GENERIC_READ, FILE_SHARE_READ, nullptr, OPEN_EXISTING,
                        FILE_FLAG_NO_BUFFERING | FILE_FLAG_SEQUENTIAL_SCAN, nullptr);
        if (h == INVALID_HANDLE_VALUE) {
            // not every volume serves unbuffered reads; a buffered handle is slower, not broken
            h = CreateFileW(w.c_str(), GENERIC_READ, FILE_SHARE_READ, nullptr, OPEN_EXISTING,
                            FILE_FLAG_SEQUENTIAL_SCAN, nullptr);
        }
        if (h == INVALID_HANDLE_VALUE) return false;
        stage = (uint8_t *) VirtualAlloc(nullptr, STAGE, MEM_COMMIT | MEM_RESERVE, PAGE_READWRITE);
        if (!stage) { CloseHandle(h); h = INVALID_HANDLE_VALUE; return false; }
        return true;
    }

    bool refill() {
        DWORD got = 0;
        if (!ReadFile(h, stage, (DWORD) STAGE, &got, nullptr)) { bad = true; return false; }
        have = got;
        used = 0;
        return got > 0;
    }

    // sequential read; dst may be null to skip
    bool read(void * dst, size_t n) {
        uint8_t * out = (uint8_t *) dst;
        while (n > 0) {
            if (used == have && !refill()) return false;
            const size_t take = std::min(n, have - used);
            if (out) { memcpy(out, stage + used, take); out += take; }
            used += take;
            n    -= take;
        }
        return true;
    }

    explicit operator bool() const { return h != INVALID_HANDLE_VALUE && !bad; }
};
#else
struct spc_file {
    std::ifstream f;
    bool open(const std::string & path) { f.open(path, std::ios::binary); return (bool) f; }
    bool read(void * dst, size_t n) {
        if (dst) { f.read((char *) dst, n); } else { f.seekg((std::streamoff) n, std::ios::cur); }
        return (bool) f;
    }
    explicit operator bool() const { return (bool) f; }
};
#endif

template <typename T> void spc_put(std::ofstream & f, const T & v) { f.write((const char *) &v, sizeof(v)); }
template <typename T> bool spc_get(spc_file & f, T & v) { return f.read(&v, sizeof(v)); }
'''),
        ('''bool spc_get_blob(std::ifstream & f, std::vector<uint8_t> & v, uint64_t limit) {
''',
         '''// strixllama: an entry is 92 blobs (target state, draft state, three per context checkpoint) and a long
// conversation is several GiB of them, so it is worth knowing which half of "read" is the file and which
// is the buffer it goes into
struct spc_read_cost { int64_t alloc_us; int64_t read_us; uint64_t bytes; };
spc_read_cost g_spc_cost = {};
bool spc_get_blob(spc_file & f, std::vector<uint8_t> & v, uint64_t limit) {
'''),
        ('''    v.resize(n);
    if (n) f.read((char *) v.data(), n);
    return (bool) f;
''',
         '''    const int64_t t0 = ggml_time_us();
    v.resize(n);
    const int64_t t1 = ggml_time_us();
    const bool ok = n == 0 || f.read(v.data(), n);
    g_spc_cost.alloc_us += t1 - t0;
    g_spc_cost.read_us  += ggml_time_us() - t1;
    g_spc_cost.bytes    += n;
    return ok;
'''),
        ('''bool spc_read_tokens(std::ifstream & f, server_tokens & out, bool has_mtmd) {
''',
         '''bool spc_read_tokens(spc_file & f, server_tokens & out, bool has_mtmd) {
'''),
        ('''        std::ifstream f(entry.path(), std::ios::binary);
''',
         '''        spc_file f;
'''),
        ('''        if (!f.read(magic, 8) || memcmp(magic, STRIX_SPC_MAGIC, 8) != 0 || !spc_get(f, version) || version != STRIX_SPC_VERSION || !spc_get(f, mtmd)) {
''',
         '''        if (!f.open(entry.path().string()) || !f.read(magic, 8) || memcmp(magic, STRIX_SPC_MAGIC, 8) != 0 || !spc_get(f, version) || version != STRIX_SPC_VERSION || !spc_get(f, mtmd)) {
'''),
        ('''    auto near = disk_index.end();          // closest entry whether or not it was taken, for the miss line
    int  near_lcp = -1;
''',
         '''    auto closest = disk_index.end();          // closest entry whether or not it was taken, for the miss line
    int  closest_lcp = -1;
'''),
        ('''        if (lcp_cur > near_lcp) { near_lcp = lcp_cur; near = it; }
''',
         '''        if (lcp_cur > closest_lcp) { closest_lcp = lcp_cur; closest = it; }
'''),
        ('''        if (near != disk_index.end()) {
''',
         '''        if (closest != disk_index.end()) {
'''),
        ('''                    (int) tokens_new.size(), disk_index.size(), (int) near->tokens.size(), near_lcp,
                    near->tokens.size() ? float(near_lcp) / near->tokens.size() : 0.0f,
                    tokens_new.size() ? float(near_lcp) / tokens_new.size() : 0.0f, f_keep_best, f_sim_best);
''',
         '''                    (int) tokens_new.size(), disk_index.size(), (int) closest->tokens.size(), closest_lcp,
                    closest->tokens.size() ? float(closest_lcp) / closest->tokens.size() : 0.0f,
                    tokens_new.size() ? float(closest_lcp) / tokens_new.size() : 0.0f, f_keep_best, f_sim_best);
'''),
        ('''    std::ifstream f(best->path, std::ios::binary);
''',
         '''    g_spc_cost = {};
    spc_file f;
    if (!f.open(best->path)) {
        // a file that will not open is not a file that is corrupt: leave it alone
        SRV_WRN(" - disk cache: cannot open %s, skipping it this time\\n", best->path.c_str());
        return nullptr;
    }
'''),
        ('''    SRV_INF(" - disk cache: read %d tokens, %.3f GiB in %.0f ms (f_keep = %.3f, f_sim = %.3f)\\n",
            (int) state.prompt.tokens.size(), best->bytes / (1024.0 * 1024.0 * 1024.0), (ggml_time_us() - t0) / 1000.0, f_keep_best, f_sim_best);
''',
         '''    SRV_INF(" - disk cache: read %d tokens, %.3f GiB in %.0f ms (file %.0f ms at %.0f MB/s, buffers %.0f ms; f_keep = %.3f, f_sim = %.3f)\\n",
            (int) state.prompt.tokens.size(), best->bytes / (1024.0 * 1024.0 * 1024.0), (ggml_time_us() - t0) / 1000.0,
            g_spc_cost.read_us / 1000.0, g_spc_cost.read_us ? g_spc_cost.bytes / 1048576.0 / (g_spc_cost.read_us / 1e6) : 0.0,
            g_spc_cost.alloc_us / 1000.0, f_keep_best, f_sim_best);
'''),
    ],
}


def main():
    texts = {p: io.open(p, encoding="utf-8").read() for p in EDITS}
    if any(MARKER in t for t in texts.values()):
        print("already applied")
        return
    for p, pairs in EDITS.items():
        for old, new in pairs:
            if texts[p].count(old) != 1:
                sys.exit("anchor found %d times, expected once, in %s" % (texts[p].count(old), p))
            texts[p] = texts[p].replace(old, new, 1)
    for p, t in texts.items():
        io.open(p, "w", encoding="utf-8", newline="").write(t)
    print("patched", ", ".join(os.path.basename(p) for p in EDITS))


if __name__ == "__main__":
    main()
