#!/usr/bin/env python3
"""Compute buffers get 3% + 16 MiB of headroom, so a slightly larger graph does not reallocate them

A graph a few MiB larger than the reserved one made ggml-alloc free and reallocate the whole compute buffer (3.4 GiB for the qwen4exp target). ROCm on Windows keeps a freed device buffer's commit in its cache, where a request a few MiB larger can never reuse it, so every reallocation cost ~3.4 GiB of the machine's commit limit until the process ended - four conversations in four slots took the server to within 3 GiB of it, and a few more reallocations made any allocation fail ("bad allocation"). With the headroom there were none: the same workload peaks 7 GiB lower. GGML_ALLOC_DEBUG=1 reports every (re)allocation.

Generated by tools/make_patch_script.py from the tree it must reproduce, so every anchor is
unique by construction. 2 hunks across 1 file(s).

Usage: python D:/Work/strixllama/patches/apply_compute_buffer_headroom.py [tree]
"""
import io
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
tree = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "src", "llama.cpp")
MARKER = 'GGML_ALLOC_COMPUTE_PAD'

EDITS = {
    os.path.join(tree, "ggml", "src", "ggml-alloc.c"): [
        ('''        size_t chunk_size = talloc->chunks[n]->max_size;
        buf->chunks[n] = ggml_backend_buft_alloc_buffer(buft, chunk_size);
''',
         '''        size_t chunk_size = talloc->chunks[n]->max_size;
        // strixllama: headroom for compute buffers. A graph a few MiB larger than the one reserved made gallocr free and
        // reallocate the whole buffer (3.4 GiB for the qwen4exp target), and ROCm on Windows keeps a freed device buffer's
        // commit in its cache, where a request a few MiB larger than it can never be served again: every such
        // reallocation cost ~3.4 GiB of the machine's commit limit for the rest of the process. 3% + 16 MiB absorbs the
        // growth measured between graphs; GGML_ALLOC_COMPUTE_PAD=0 turns it off.
        if (usage == GGML_BACKEND_BUFFER_USAGE_COMPUTE && chunk_size > 0) {
            static int pad_on = -1;
            if (pad_on < 0) {
                const char * e = getenv("GGML_ALLOC_COMPUTE_PAD");
                pad_on = e == NULL || atoi(e) != 0;
            }
            if (pad_on) {
                const size_t max_size = ggml_backend_buft_get_max_size(buft);
                const size_t padded   = chunk_size + chunk_size/32 + ((size_t) 16 << 20);
                chunk_size = padded <= max_size ? padded : (chunk_size > max_size ? chunk_size : max_size);
            }
        }
        buf->chunks[n] = ggml_backend_buft_alloc_buffer(buft, chunk_size);
'''),
        ('''        if (realloc) {
#ifndef NDEBUG
''',
         '''        if (realloc) {
            // strixllama: GGML_ALLOC_DEBUG=1 reports every compute buffer (re)allocation, also in release builds
            {
                static int dbg = -1;
                if (dbg < 0) {
                    const char * e = getenv("GGML_ALLOC_DEBUG");
                    dbg = e != NULL && atoi(e) != 0;
                }
                if (dbg) {
                    const size_t cur_size_dbg = galloc->buffers[i] ? ggml_vbuffer_size(galloc->buffers[i]) : 0;
                    fprintf(stderr, "ggml-alloc: %s buffer %.2f -> %.2f MiB\\n", ggml_backend_buft_name(galloc->bufts[i]),
                            cur_size_dbg / 1048576.0, new_size / 1048576.0);
                }
            }
#ifndef NDEBUG
'''),
    ],
}


def main():
    texts = {p: io.open(p, encoding="utf-8").read() for p in EDITS}
    if any(MARKER in t for t in texts.values()):
        print("already applied")
        return
    for p, pairs in EDITS.items():
        for old, new in pairs:
            if texts[p].count(old) != 1:
                sys.exit("anchor found %d times, expected once, in %s" % (texts[p].count(old), p))
            texts[p] = texts[p].replace(old, new, 1)
    for p, t in texts.items():
        io.open(p, "w", encoding="utf-8", newline="").write(t)
    print("patched", ", ".join(os.path.basename(p) for p in EDITS))


if __name__ == "__main__":
    main()
