#!/usr/bin/env python3
"""STRIX_SPEC_DRAFT_BY_SLOTS: the draft length capped by how many slots generate

A step's draft is capped by the number of slots generating in it ("3,2,2,0": 3 tokens for one, 2 for two or three, none from four on; the manager sets it when MTP is on and there is more than one slot). In this mixture of experts every verified token reads the weights of ~10 more of its 512 experts, which conversations decoding together cannot share, and the expert kernels already run at the memory's bandwidth: four conversations with three draft tokens verify 16 tokens a step and touch ~138 experts where 4 tokens touch ~39. Four conversations at ~20K tokens each: 37.9 tok/s summed with 3 draft tokens, 47.4 with the cap. The MTP draft stops at the caller's cap instead of drafting to its own and being truncated. The draft model keeps processing every step, so drafting resumes as soon as fewer conversations generate.

Generated by tools/make_patch_script.py from the tree it must reproduce, so every anchor is
unique by construction. 3 hunks across 2 file(s).

Usage: python D:/Work/strixllama/patches/apply_spec_draft_by_slots.py [tree]
"""
import io
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
tree = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "src", "llama.cpp")
MARKER = 'STRIX_SPEC_DRAFT_BY_SLOTS'

EDITS = {
    os.path.join(tree, "common", "speculative.cpp"): [
        ('''
                auto & dp = dparams.at(seq_id);
                auto & result = *dp.result;

                result.push_back(id);

                if (params.n_max <= (int) result.size()) {
                    drafting[seq_id] = false;
                    n_drafting--;
                    continue;
                }

                if (chain_heads) {
''',
         '''
                auto & dp = dparams.at(seq_id);
                auto & result = *dp.result;

                result.push_back(id);

                // strixllama: the caller's cap as well (dp.n_max, which the server lowers when several slots
                // generate at once): a step past it would only be truncated
                if (params.n_max <= (int) result.size() || (dp.n_max > 0 && dp.n_max <= (int) result.size())) {
                    drafting[seq_id] = false;
                    n_drafting--;
                    continue;
                }

                if (chain_heads) {
'''),
    ],
    os.path.join(tree, "tools", "server", "server-context.cpp"): [
        ('''
        // determine which slots are generating and drafting
''',
         '''
        // strixllama: a draft pays for itself on one conversation, not on several at once. Every drafted token is
        // verified, and in this mixture of experts each verified token reads the weights of ~10 more experts;
        // several conversations already share the trunk's cost, so their drafts add verification they cannot
        // win back. STRIX_SPEC_DRAFT_BY_SLOTS caps the draft by how many slots generate this step: "3,2,2,0"
        // drafts 3 tokens for one, 2 for two or three and none from four on.
        int n_draft_cap = INT_MAX;
        if (spec) {
            static const std::vector<int> by_slots = [] {
                std::vector<int> v;
                const char * e = getenv("STRIX_SPEC_DRAFT_BY_SLOTS");
                for (const char * p = e; p && *p; ) {
                    v.push_back(std::max(0, atoi(p)));
                    p = strchr(p, ',');
                    p = p ? p + 1 : nullptr;
                }
                return v;
            }();
            if (!by_slots.empty()) {
                int n_gen = 0;
                for (const auto & s : slots) {
                    n_gen += s.state == SLOT_STATE_GENERATING;
                }
                if (n_gen > 0) {
                    n_draft_cap = by_slots[std::min<size_t>(n_gen, by_slots.size()) - 1];
                }
            }
        }

        // determine which slots are generating and drafting
'''),
        ('''                const int n_draft_max = slot.get_n_draft_max();
''',
         '''                const int n_draft_max = std::min(slot.get_n_draft_max(), n_draft_cap);
'''),
    ],
}


def main():
    texts = {p: io.open(p, encoding="utf-8").read() for p in EDITS}
    if any(MARKER in t for t in texts.values()):
        print("already applied")
        return
    for p, pairs in EDITS.items():
        for old, new in pairs:
            if texts[p].count(old) != 1:
                sys.exit("anchor found %d times, expected once, in %s" % (texts[p].count(old), p))
            texts[p] = texts[p].replace(old, new, 1)
    for p, t in texts.items():
        io.open(p, "w", encoding="utf-8", newline="").write(t)
    print("patched", ", ".join(os.path.basename(p) for p in EDITS))


if __name__ == "__main__":
    main()
