#!/usr/bin/env python3
"""BF16 weights from 9 columns on the MMB kernel, not hipBLAS

The sparse-attention indexer's projections are BF16. mul_mat_f takes BF16 up to 16 columns and the MMB kernel from 512 (LLAMA_MMB_MIN_T), so a batch of 17 to 511 tokens - the new part of most chat turns - went to hipBLAS, which loads each GEMM kernel from disk the first time it meets a shape: a 38-token batch took 572 ms instead of 200, and a chat's second turn 1557 ms to its first token instead of 1136. BF16 weights now take the MMB kernel from 9 columns, as F32 weights have since 0.2.0 (STRIX_MMB_BF16_MIN_T sets the limit). The numerics of those batches change (the MMB kernel's order of summation, BF16 activations as before); nothing else does.

Generated by tools/make_patch_script.py from the tree it must reproduce, so every anchor is
unique by construction. 1 hunks across 1 file(s).

Usage: python patches/apply_bf16_mid_batches.py [tree]
"""
import io
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
tree = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "src", "llama.cpp")
MARKER = 'STRIX_MMB_BF16_MIN_T'

EDITS = {
    os.path.join(tree, "ggml", "src", "ggml-cuda", "mmb.cu"): [
        ('''    if (T < (f32w ? f32_min_t : (int64_t) mmb_min_t()) || T > INT32_MAX / 4) return false;
''',
         '''    // strixllama: BF16 weights (the sparse-attention indexer's projections) likewise: mul_mat_f takes up to 16 columns
    // and this kernel took 512 on, so a 17-511 token batch - most chat turns - loaded hipBLAS's BF16 kernels, ~0.4 s
    static const int64_t bf16_min_t = getenv("STRIX_MMB_BF16_MIN_T") ? atoll(getenv("STRIX_MMB_BF16_MIN_T")) : 9;
    if (T < (f32w ? f32_min_t : bf16w ? bf16_min_t : (int64_t) mmb_min_t()) || T > INT32_MAX / 4) return false;
'''),
    ],
}


def main():
    texts = {p: io.open(p, encoding="utf-8").read() for p in EDITS}
    if any(MARKER in t for t in texts.values()):
        print("already applied")
        return
    for p, pairs in EDITS.items():
        for old, new in pairs:
            if texts[p].count(old) != 1:
                sys.exit("anchor found %d times, expected once, in %s" % (texts[p].count(old), p))
            texts[p] = texts[p].replace(old, new, 1)
    for p, t in texts.items():
        io.open(p, "w", encoding="utf-8", newline="").write(t)
    print("patched", ", ".join(os.path.basename(p) for p in EDITS))


if __name__ == "__main__":
    main()
