#!/usr/bin/env python3
"""The sparse-attention membership product of several conversations on its own kernel, not hipBLAS

With several conversations in one ubatch the compact scorer multiplies each block's sequence membership (F16, K = the number of sequences) with each token's. That product went to hipBLAS, which loads a kernel from disk the first time it meets a shape: 272 ms in the first step three conversations decoded together, and again as their blocks grow. A kernel of one thread an output element sums the K products in order; the membership is 0 or 1, so the result is exact. STRIX_SMALL_K=0 uses hipBLAS as before.

Generated by tools/make_patch_script.py from the tree it must reproduce, so every anchor is
unique by construction. 2 hunks across 1 file(s).

Usage: python D:/Work/strixllama/patches/apply_small_k_membership.py [tree]
"""
import io
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
tree = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "src", "llama.cpp")
MARKER = 'STRIX_SMALL_K'

EDITS = {
    os.path.join(tree, "ggml", "src", "ggml-cuda", "ggml-cuda.cu"): [
        ('''
static bool ggml_cuda_skinny_f32(ggml_backend_cuda_context & ctx, const ggml_tensor * src0, const ggml_tensor * src1, ggml_tensor * dst) {
''',
         '''
// strixllama: an F16 x F32 product with a tiny inner dimension - the compact sparse-attention scorer's block membership,
// K = the sequences of a ubatch - went to hipBLAS, which loads a kernel from disk the first time it meets a shape: a
// 272 ms stall in the first step three conversations decode together, and again as their blocks grow. One thread an
// output element, the K products summed in order (STRIX_SMALL_K=0: as before). The membership is 0 or 1, so exact.
static __global__ void k_small_k_f16(const half * __restrict__ a, const float * __restrict__ b, float * __restrict__ d,
        const int K, const int M, const int64_t sa, const int64_t sb, const int64_t sd) {
    const int m = blockIdx.x * blockDim.x + threadIdx.x;
    if (m >= M) {
        return;
    }
    const half  * ap = a + (int64_t) m * sa;
    const float * bp = b + (int64_t) blockIdx.y * sb;
    float acc = 0.0f;
    for (int k = 0; k < K; ++k) {
        acc = fmaf(__half2float(ap[k]), bp[k], acc);
    }
    d[(int64_t) blockIdx.y * sd + m] = acc;
}

static bool ggml_cuda_small_k(ggml_backend_cuda_context & ctx, const ggml_tensor * src0, const ggml_tensor * src1, ggml_tensor * dst) {
    static const bool on = !getenv("STRIX_SMALL_K") || atoi(getenv("STRIX_SMALL_K")) != 0;
    const int64_t K = src0->ne[0], M = src0->ne[1], N = src1->ne[1];
    if (!on || src0->type != GGML_TYPE_F16 || src1->type != GGML_TYPE_F32 || dst->type != GGML_TYPE_F32 || K > 32 ||
            src1->ne[0] != K || dst->ne[0] != M || dst->ne[1] != N || N > 65535 || M > INT_MAX ||
            src0->ne[2] != 1 || src0->ne[3] != 1 || src1->ne[2] != 1 || src1->ne[3] != 1 || dst->ne[2] != 1 || dst->ne[3] != 1 ||
            src0->nb[0] != sizeof(half) || src1->nb[0] != sizeof(float) || dst->nb[0] != sizeof(float) ||
            src0->nb[1] % sizeof(half) != 0 || src1->nb[1] % sizeof(float) != 0 || dst->nb[1] % sizeof(float) != 0) {
        return false;
    }
    const dim3 grid((unsigned) ((M + 255) / 256), (unsigned) N), block(256);
    k_small_k_f16<<<grid, block, 0, ctx.stream()>>>((const half *) src0->data, (const float *) src1->data, (float *) dst->data,
        (int) K, (int) M, src0->nb[1] / sizeof(half), src1->nb[1] / sizeof(float), dst->nb[1] / sizeof(float));
    CUDA_CHECK(cudaGetLastError());
    return true;
}

static bool ggml_cuda_skinny_f32(ggml_backend_cuda_context & ctx, const ggml_tensor * src0, const ggml_tensor * src1, ggml_tensor * dst) {
'''),
        ('''    if (hint != GGML_HINT_SRC0_IS_HADAMARD && ggml_cuda_hc_inject_take(ctx, src1, dst)) {
        return;
''',
         '''    if (hint != GGML_HINT_SRC0_IS_HADAMARD && ggml_cuda_hc_inject_take(ctx, src1, dst)) {
        return;
    }

    if (hint != GGML_HINT_SRC0_IS_HADAMARD && ggml_cuda_small_k(ctx, src0, src1, dst)) {
        return;
'''),
    ],
}


def main():
    texts = {p: io.open(p, encoding="utf-8").read() for p in EDITS}
    if any(MARKER in t for t in texts.values()):
        print("already applied")
        return
    for p, pairs in EDITS.items():
        for old, new in pairs:
            if texts[p].count(old) != 1:
                sys.exit("anchor found %d times, expected once, in %s" % (texts[p].count(old), p))
            texts[p] = texts[p].replace(old, new, 1)
    for p, t in texts.items():
        io.open(p, "w", encoding="utf-8", newline="").write(t)
    print("patched", ", ".join(os.path.basename(p) for p in EDITS))


if __name__ == "__main__":
    main()
