#!/usr/bin/env python3
"""A slot that fails part way loses its conversation; a prompt starts only on a cache that matches its tokens

GitHub issue #1: long agent sessions near the commit limit logged 'non-consecutive token position' - a batch fed the recurrent state positions it had seen already (143363 after 143362 with 1260 new tokens), or skipped some (151599 after 143363 with 8192) - and ended in a GPU fault. An exhausted commit limit throws std::bad_alloc from anywhere that allocates, and the server caught what a slot threw part way through its turn by releasing the slot and keeping its conversation: tokens added for a batch that never ran stayed in its list (and with one slot, left in a batch no slot owned, aborted the server on an assert), so the next request went on from positions the memory had never seen. A slot that throws now leaves the batch it was adding to and loses its conversation, as a decode error already did, and so does every slot an exception in pre-decode, decode or post-decode catches. Before a prompt batch the slot's tokens must also match its memory - positions up to the next one, the recurrent state at the last - or the prompt is processed from its start. STRIX_FAULT=<site>:<n> (ckpt, decode, post) throws std::bad_alloc on the n-th pass, for tests.

Generated by tools/make_patch_script.py from the tree it must reproduce, so every anchor is
unique by construction. 11 hunks across 1 file(s).

Usage: python D:/Work/strixllama/patches/apply_slot_state_guard.py [tree]
"""
import io
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
tree = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "src", "llama.cpp")
MARKER = 'strixllama_fault(const char * site)'

EDITS = {
    os.path.join(tree, "tools", "server", "server-context.cpp"): [
        ('''static const int strixllama_new_handler_installed = [] { _set_new_handler(strixllama_new_handler); return 1; }();
#endif

static common_speculative_output_limits server_output_limits(const common_params & params) {
''',
         '''static const int strixllama_new_handler_installed = [] { _set_new_handler(strixllama_new_handler); return 1; }();
#endif

// strixllama: fault injection for the paths an exhausted commit limit takes (STRIX_FAULT=<site>:<n>: the n-th pass
// through <site> - ckpt, decode or post - throws std::bad_alloc). For tests of the error handling only.
static void strixllama_fault(const char * site) {
    static const std::string spec = [] { const char * e = getenv("STRIX_FAULT"); return std::string(e ? e : ""); }();
    const size_t colon = spec.find(':');
    if (colon == std::string::npos || spec.compare(0, colon, site) != 0) {
        return;
    }
    static int n = 0;
    if (++n == atoi(spec.c_str() + colon + 1)) {
        fprintf(stderr, "STRIX_FAULT: %s #%d throws std::bad_alloc\\n", site, n);
        throw std::bad_alloc();
    }
}

static common_speculative_output_limits server_output_limits(const common_params & params) {
'''),
        ('''        return (int32_t)tokens.size();
    }
''',
         '''        return (int32_t)tokens.size();
    }

    // strixllama: the tokens of one slot out of a batch that is still being built (the slot failed part way)
    void drop_slot(int32_t id_slot) {
        GGML_ASSERT(!batch_rendered);
        std::vector<token> keep;
        std::vector<float> keep_embd;
        for (size_t i = 0; i < tokens.size(); ++i) {
            if (tokens[i].id_slot == id_slot) {
                continue;
            }
            if (has_embd) {
                keep_embd.insert(keep_embd.end(), embd.begin() + i*n_embd, embd.begin() + (i + 1)*n_embd);
            }
            keep.push_back(tokens[i]);
        }
        tokens.swap(keep);
        if (has_embd) {
            embd.swap(keep_embd);
            has_embd = !tokens.empty();
        }
    }
'''),
        ('''    void create_checkpoint(server_slot & slot, const int64_t n_tokens_cur, llama_pos pos_min, llama_pos pos_max) {
        const int id_task = slot.task->id;
''',
         '''    void create_checkpoint(server_slot & slot, const int64_t n_tokens_cur, llama_pos pos_min, llama_pos pos_max) {
        strixllama_fault("ckpt");
        const int id_task = slot.task->id;
'''),
        ('''
    void iterate(std::vector<server_slot> & slots, std::function<void(server_slot &)> callback) {
''',
         '''
    // strixllama: a slot that threw part way through its turn - adding to the batch, or changing its cache; an
    // exhausted commit limit throws std::bad_alloc from anywhere that allocates. Its tokens no longer say what its
    // memory holds, and a conversation that went on from there fed the recurrent state positions it had seen already,
    // or skipped some (GitHub issue #1); with one slot, its tokens left in a batch no slot owned aborted the server.
    // Its tokens leave the batch if that is still being built, and its conversation leaves the cache: the next
    // request for it is processed again, or read back from the disk tier.
    void slot_failed(server_slot & slot, const std::string & what) {
        SLT_ERR(slot, "got exception: %s\\n", what.c_str());
        send_error(slot, std::string("got exception: ") + what, ERROR_TYPE_SERVER);
        slot.release();
        if (!batch.batch_rendered) {
            batch.drop_slot(slot.id);
            if (batch.slot_batched == &slot) {
                batch.slot_batched = batch.size() > 0 ? get_slot_by_id(batch.tokens[0].id_slot) : nullptr;
            }
        }
        slot.prompt_clear();
    }

    void iterate(std::vector<server_slot> & slots, std::function<void(server_slot &)> callback) {
'''),
        ('''                SLT_ERR(slot, "got exception: %s\\n", e.what());
                send_error(slot, std::string("got exception: ") + e.what(), ERROR_TYPE_SERVER);
                slot.release();
''',
         '''                slot_failed(slot, e.what());
'''),
        ('''                SLT_ERR(*slot, "got exception: %s\\n", e.what());
                send_error(*slot, std::string("got exception: ") + e.what(), ERROR_TYPE_SERVER);
                slot->release();
''',
         '''                slot_failed(*slot, e.what());
'''),
        ('''
    void abort_all_slots(const std::string & reason) {
''',
         '''
    // strixllama: as for one slot that failed, every slot that was in the batch loses its conversation - how much of
    // the batch reached its memory is not known (the decode error path below does the same)
    void abort_all_slots(const std::string & reason) {
'''),
        ('''                send_error(slot, reason, ERROR_TYPE_SERVER);
                slot.release();
            }
        }
''',
         '''                send_error(slot, reason, ERROR_TYPE_SERVER);
                slot.release();
                slot.prompt_clear();
            }
        }
'''),
        ('''
                    // If using an alora, there may be uncached tokens that come
''',
         '''
                    // strixllama: the slot's tokens and its memory must agree before anything is added - the memory holds
                    // positions up to p0 - 1 and the recurrent state is at p0 - 1 (for a hybrid memory the lowest position
                    // is the recurrent one, the highest the lower of the two). If they do not, going on feeds the
                    // recurrent state positions it has seen already, or skips some (GitHub issue #1): the conversation
                    // is processed again from its start instead. Not checked with images, whose positions run ahead
                    // of their cells.
                    if (!slot.prompt.tokens.has_mtmd) {
                        auto * mem_tgt = llama_get_memory(ctx_tgt);
                        const llama_pos pos_max = llama_memory_seq_pos_max(mem_tgt, slot.id);
                        const llama_pos pos_min = llama_memory_seq_pos_min(mem_tgt, slot.id);
                        if (pos_max != p0 - 1 || pos_min > p0 - 1) {
                            SLT_WRN(slot, "the cache is out of step with its tokens: %d tokens, but the memory holds positions [%d, %d]; "
                                    "processing the prompt from its start\\n", slot.prompt.n_tokens(), pos_min, pos_max);
                            slot.prompt_clear();
                        }
                    }

                    // If using an alora, there may be uncached tokens that come
'''),
        ('''        queue_tasks.yield_to_queue([&]() {
            ret = llama_decode(ctx_tgt, batch_view);
''',
         '''        queue_tasks.yield_to_queue([&]() {
            strixllama_fault("decode");
            ret = llama_decode(ctx_tgt, batch_view);
'''),
        ('''    void post_decode(int32_t n_batch_tokens, int32_t off, llama_batch & batch_view) {
        // for checking if a given batch index is inside batch_view
''',
         '''    void post_decode(int32_t n_batch_tokens, int32_t off, llama_batch & batch_view) {
        strixllama_fault("post");
        // for checking if a given batch index is inside batch_view
'''),
    ],
}


def main():
    texts = {p: io.open(p, encoding="utf-8").read() for p in EDITS}
    if any(MARKER in t for t in texts.values()):
        print("already applied")
        return
    for p, pairs in EDITS.items():
        for old, new in pairs:
            if texts[p].count(old) != 1:
                sys.exit("anchor found %d times, expected once, in %s" % (texts[p].count(old), p))
            texts[p] = texts[p].replace(old, new, 1)
    for p, t in texts.items():
        io.open(p, "w", encoding="utf-8", newline="").write(t)
    print("patched", ", ".join(os.path.basename(p) for p in EDITS))


if __name__ == "__main__":
    main()
