#!/usr/bin/env python3
"""Gather the next prompt batch's per-layer-embedding rows while the current batch is on the GPU

The server knows the next batch; llama_strix_prefetch gathers and dequantizes its PLE rows in the background, and that batch's set_input takes them instead of reading ~131K scattered rows itself (0.2-0.7 s a batch). Also guards the prefetch hook, which llama_decode calls for every model, against casting a model of another architecture.

Generated by tools/make_patch_script.py from the tree it must reproduce, so every anchor is
unique by construction. 12 hunks across 5 file(s).

Usage: python D:/Work/strixllama/patches/apply_ple_pregather.py [tree]
"""
import io
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
tree = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "src", "llama.cpp")
MARKER = 'take_pregathered'

EDITS = {
    os.path.join(tree, "include", "llama.h"): [
        ('''
    // Set whether the context outputs embeddings or not
''',
         '''
    // strixllama: start reading, in the background, whatever the batch tokens[n_context..n_tokens) will read from
    // disk (the per-layer-embedding rows of models that stream them); the first n_context tokens are the ones that
    // precede it, which n-gram lookups reach back into. A caller that knows the next batch - a server walking a
    // long prompt - calls this before decoding the current one, so the reads overlap its compute and that batch's
    // gather becomes a copy; from then on llama_decode stops prefetching the batch it is handed. No-op for other
    // models.
    LLAMA_API void llama_strix_prefetch(struct llama_context * ctx, const llama_token * tokens, int32_t n_tokens, int32_t n_context);

    // Set whether the context outputs embeddings or not
'''),
    ],
    os.path.join(tree, "src", "llama-context.cpp"): [
        ('''
#include <cinttypes>
''',
         '''
#include <atomic>
#include <cinttypes>
'''),
        ('''static strixllama_decode_timing g_decode_timing;

''',
         '''static strixllama_decode_timing g_decode_timing;

// strixllama: set once a caller drives the per-layer-embedding prefetch itself (llama_strix_prefetch); llama_decode
// then leaves it alone, since a prefetch of the batch it is handed starts no earlier than the gather that reads the
// same rows, and launching one would wait for the caller's prefetch of the next batch to finish
static std::atomic<bool> g_strix_prefetch_external { false };

'''),
        ('''        extern void qwen4exp_ple_prefetch(const llama_model & model, const llama_token * tokens, int32_t n_tokens);
        if (batch_inp.token && batch_inp.n_tokens >= 4096) { qwen4exp_ple_prefetch(model, batch_inp.token, batch_inp.n_tokens); }
''',
         '''        extern void qwen4exp_ple_prefetch(const llama_model & model, const llama_token * tokens, int32_t n_tokens, int32_t n_skip, bool pregather);
        if (batch_inp.token && batch_inp.n_tokens >= 4096 && !g_strix_prefetch_external) { qwen4exp_ple_prefetch(model, batch_inp.token, batch_inp.n_tokens, 0, false); }
'''),
        ('''
void llama_set_abort_callback(llama_context * ctx, bool (*abort_callback)(void * data), void * abort_callback_data) {
''',
         '''
void llama_strix_prefetch(llama_context * ctx, const llama_token * tokens, int32_t n_tokens, int32_t n_context) {
    extern void qwen4exp_ple_prefetch(const llama_model & model, const llama_token * tokens, int32_t n_tokens, int32_t n_skip, bool pregather);
    g_strix_prefetch_external = true;
    if (ctx && tokens && n_tokens > n_context && n_context >= 0) {
        qwen4exp_ple_prefetch(ctx->get_model(), tokens, n_tokens, n_context, true);
    }
}

void llama_set_abort_callback(llama_context * ctx, bool (*abort_callback)(void * data), void * abort_callback_data) {
'''),
    ],
    os.path.join(tree, "src", "llama-lazy-reader.h"): [
        ('''#include <cstring>
#include <stdexcept>
''',
         '''#include <cstring>
#include <mutex>
#include <stdexcept>
'''),
        ('''
    // populate the page cache for the rows a later gather() will read; never writes any output, so a wrong
''',
         '''
    // strixllama: rows gathered ahead of time for a batch a caller announced (llama_strix_prefetch). The gather for
    // that batch takes them instead of reading them again, so it costs a copy rather than ~0.2-0.3 s of reads with
    // the GPU idle. Two slots: the next batch's pregather can finish before this batch takes its own.
    struct pregathered {
        std::vector<int32_t> rows;
        std::vector<uint8_t> data;      // rows.size() * head_dim floats
    };
    mutable std::mutex pre_mutex;
    mutable std::vector<pregathered> pre;

    void pregather(const int32_t * rows, int64_t n) const {
        pregathered p;
        p.rows.assign(rows, rows + n);
        p.data.resize((size_t) n * head_dim * sizeof(float));
        gather(rows, n, (float *) p.data.data());
        std::lock_guard<std::mutex> lock(pre_mutex);
        pre.push_back(std::move(p));
        if (pre.size() > 2) {
            pre.erase(pre.begin());
        }
    }

    // the gathered rows for `rows`, when a pregather covered them: the batch a caller announced can come out shorter
    // (it stops at a checkpoint or a message boundary), so a pregather that starts with these rows serves too
    bool take_pregathered(const int32_t * rows, int64_t n, std::vector<uint8_t> & out) const {
        std::lock_guard<std::mutex> lock(pre_mutex);
        for (auto it = pre.begin(); it != pre.end(); ++it) {
            if ((int64_t) it->rows.size() < n || memcmp(it->rows.data(), rows, (size_t) n * sizeof(int32_t)) != 0) {
                continue;
            }
            const size_t bytes = (size_t) n * head_dim * sizeof(float);
            if (it->data.size() == bytes) {
                out.swap(it->data);
            } else {
                out.resize(bytes);
                memcpy(out.data(), it->data.data(), bytes);
            }
            pre.erase(it);
            return true;
        }
        return false;
    }

    // populate the page cache for the rows a later gather() will read; never writes any output, so a wrong
'''),
    ],
    os.path.join(tree, "src", "models", "qwen4exp.cpp"): [
        ('''void qwen4exp_ple_prefetch(const llama_model & model_base, const llama_token * tokens, int32_t n_tokens) {
    if (!tokens || n_tokens < 4096) { return; }
''',
         '''// strixllama: `n_skip` leading tokens are context only (the n-gram lookups of the first real token reach back into
// them); with `pregather` the rows are gathered and dequantized for the gather of exactly that batch to take, rather
// than only warmed in the file cache
void qwen4exp_ple_prefetch(const llama_model & model_base, const llama_token * tokens, int32_t n_tokens,
                           int32_t n_skip, bool pregather) {
    // strixllama: llama_decode calls this for every model; the cast below is only valid for this one
    if (!tokens || n_tokens - n_skip < 4096 || model_base.arch != LLM_ARCH_QWEN4EXP) { return; }
'''),
        ('''    auto prefetch = [reader = pmodel.ple_reader, toks = std::move(toks), n_gram, n_heads, per_gram, eos, n_prev, hp]() {
''',
         '''    auto prefetch = [reader = pmodel.ple_reader, toks = std::move(toks), n_gram, n_heads, per_gram, eos, n_prev, hp, n_skip, pregather]() {
'''),
        ('''        reader->prefetch(idx.data(), (int64_t) idx.size());
''',
         '''        const int32_t * first = idx.data() + (size_t) n_skip * n_heads;
        const int64_t   count = (int64_t) idx.size() - (int64_t) n_skip * n_heads;
        if (pregather) {
            reader->pregather(first, count);
        } else {
            reader->prefetch(first, count);
        }
'''),
        ('''        staging.resize(idx.size() * pmodel.ple_reader->head_dim * sizeof(float));
        pmodel.ple_reader->gather(idx.data(), (int64_t) idx.size(), (float *) staging.data());
''',
         '''        // strixllama: rows a caller had gathered while the previous batch was on the GPU (llama_strix_prefetch)
        if (!pmodel.ple_reader->take_pregathered(idx.data(), (int64_t) idx.size(), staging)) {
            staging.resize(idx.size() * pmodel.ple_reader->head_dim * sizeof(float));
            pmodel.ple_reader->gather(idx.data(), (int64_t) idx.size(), (float *) staging.data());
        }
'''),
    ],
    os.path.join(tree, "tools", "server", "server-context.cpp"): [
        ('''
                    // the number of tokens added to the batch for the current slot
''',
         '''
                    // strixllama: while this batch is on the GPU, gather what the next one needs from disk - the
                    // model's per-layer-embedding rows, ~0.2-0.7 s a batch otherwise spent before its compute. The
                    // n-gram lookups reach back two tokens, so those come along as context.
                    if (slot.prompt.n_tokens() < slot.task->n_tokens()) {
                        const int64_t nxt = slot.prompt.n_tokens();
                        const int64_t end = std::min<int64_t>(slot.task->n_tokens(), nxt + n_batch);
                        const int64_t beg = std::max<int64_t>(0, nxt - 2);
                        if (end - nxt >= 4096) {
                            std::vector<llama_token> toks;
                            toks.reserve(end - beg);
                            bool media = false;
                            for (int64_t i = beg; i < end && !media; ++i) {
                                const llama_token t = input_tokens[i];
                                media = t == LLAMA_TOKEN_NULL;
                                if (!media) {
                                    toks.push_back(t);
                                }
                            }
                            if (!media) {                   // a batch with an image in it gathers for itself
                                llama_strix_prefetch(ctx_tgt, toks.data(), (int32_t) toks.size(), (int32_t) (nxt - beg));
                            }
                        }
                    }

                    // the number of tokens added to the batch for the current slot
'''),
    ],
}


def main():
    texts = {p: io.open(p, encoding="utf-8").read() for p in EDITS}
    if any(MARKER in t for t in texts.values()):
        print("already applied")
        return
    for p, pairs in EDITS.items():
        for old, new in pairs:
            if texts[p].count(old) != 1:
                sys.exit("anchor found %d times, expected once, in %s" % (texts[p].count(old), p))
            texts[p] = texts[p].replace(old, new, 1)
    for p, t in texts.items():
        io.open(p, "w", encoding="utf-8", newline="").write(t)
    print("patched", ", ".join(os.path.basename(p) for p in EDITS))


if __name__ == "__main__":
    main()
