#!/usr/bin/env python3
"""Per-dispatch HIP event timing for the CUDA/HIP graph loop (STRIX_NODE_TIMING=1).

Brackets every dispatch with stream events and prints the costliest nodes of each graph, which
is how the decode budget was taken apart. Needs GGML_CUDA_DISABLE_GRAPHS=1, because with graphs on
only the capture pass walks the node loop; each dispatch then costs about 23 us more, so read the
shape, not the absolute numbers.

It existed only as an uncommitted edit in the vendored tree - no script, not in the iq3s snapshot -
so a clean rebuild silently dropped it. tools/replay_bootstrap.py found that.

Generated by tools/make_patch_script.py from the tree it must reproduce, so every anchor is
unique by construction. 3 hunks across 1 file(s).

Usage: python patches/apply_node_timing.py [tree]
"""
import io
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
tree = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "src", "llama.cpp")
MARKER = 'STRIX_NODE_TIMING'

EDITS = {
    os.path.join(tree, "ggml", "src", "ggml-cuda", "ggml-cuda.cu"): [
        ('''
struct ggml_cuda_moe_weighted_reduction_match {
''',
         '''
// strixllama: STRIX_NODE_TIMING=1 (needs GGML_CUDA_DISABLE_GRAPHS=1) brackets every dispatch with
// stream events and prints the costliest nodes of each graph; see the report after the dispatch loop
#if defined(GGML_USE_HIP) && !defined(cudaEventElapsedTime)
#define cudaEventElapsedTime hipEventElapsedTime
#endif
static const bool g_strixllama_node_timing = getenv("STRIX_NODE_TIMING") != nullptr;
static std::vector<cudaEvent_t> g_strixllama_ev0, g_strixllama_ev1;
static std::vector<int> g_strixllama_ev_node;

struct ggml_cuda_moe_weighted_reduction_match {
'''),
        ('''
                int nodes_to_skip = ggml_cuda_try_fuse(cuda_ctx, cgraph, i);
''',
         '''
                // strixllama: STRIX_NODE_TIMING=1 (with GGML_CUDA_DISABLE_GRAPHS=1) brackets every dispatch,
                // fused or not, with stream events; the top entries are printed after the graph
                if (g_strixllama_node_timing) {
                    cudaEvent_t e; CUDA_CHECK(cudaEventCreateWithFlags(&e, 0)); CUDA_CHECK(cudaEventRecord(e, cuda_ctx->stream()));
                    g_strixllama_ev0.push_back(e); g_strixllama_ev_node.push_back(i);
                }
                struct strixllama_timing_close {
                    bool on; ggml_backend_cuda_context * ctx;
                    ~strixllama_timing_close() {
                        if (!on) { return; }
                        cudaEvent_t e; CUDA_CHECK(cudaEventCreateWithFlags(&e, 0)); CUDA_CHECK(cudaEventRecord(e, ctx->stream()));
                        g_strixllama_ev1.push_back(e);
                    }
                } strixllama_timing_guard{g_strixllama_node_timing, cuda_ctx};

                int nodes_to_skip = ggml_cuda_try_fuse(cuda_ctx, cgraph, i);
'''),
        ('''                    try_launch_concurrent_event(node);
               }
            }
        }
''',
         '''                    try_launch_concurrent_event(node);
               }
            }

            // strixllama: per-node timing report (STRIX_NODE_TIMING=1)
            if (g_strixllama_node_timing && !g_strixllama_ev0.empty() && g_strixllama_ev0.size() == g_strixllama_ev1.size()) {
                CUDA_CHECK(cudaStreamSynchronize(cuda_ctx->stream()));
                struct row { float ms; int node; };
                std::vector<row> rows;
                float total = 0.0f;
                for (size_t k = 0; k < g_strixllama_ev0.size(); ++k) {
                    float ms = 0.0f;
                    CUDA_CHECK(cudaEventElapsedTime(&ms, g_strixllama_ev0[k], g_strixllama_ev1[k]));
                    rows.push_back({ms, g_strixllama_ev_node[k]});
                    total += ms;
                    CUDA_CHECK(cudaEventDestroy(g_strixllama_ev0[k]));
                    CUDA_CHECK(cudaEventDestroy(g_strixllama_ev1[k]));
                }
                // aggregate by op + shape so the 48 copies of a layer op add up
                std::map<std::string, std::pair<float, int>> by_kind;
                for (const row & r : rows) {
                    const ggml_tensor * t = cgraph->nodes[r.node];
                    char key[256];
                    snprintf(key, sizeof(key), "%-18s %-12s [%lld,%lld,%lld,%lld]", ggml_op_name(t->op),
                             t->op == GGML_OP_UNARY ? ggml_unary_op_name(ggml_get_unary_op(t)) : (t->op == GGML_OP_GLU ? ggml_glu_op_name(ggml_get_glu_op(t)) : ""),
                             (long long) t->ne[0], (long long) t->ne[1], (long long) t->ne[2], (long long) t->ne[3]);
                    auto & e = by_kind[key];
                    e.first += r.ms; e.second += 1;
                }
                std::vector<std::pair<std::string, std::pair<float, int>>> agg(by_kind.begin(), by_kind.end());
                std::sort(agg.begin(), agg.end(), [](const auto & a, const auto & b) { return a.second.first > b.second.first; });
                fprintf(stderr, "NODE_TIMING: graph of %d nodes, %zu dispatches, %.2f ms of GPU time; top kinds:\\n", cgraph->n_nodes, rows.size(), total);
                for (size_t k = 0; k < agg.size() && k < 24; ++k) {
                    fprintf(stderr, "  %8.3f ms %4d x %s\\n", agg[k].second.first, agg[k].second.second, agg[k].first.c_str());
                }
                std::sort(rows.begin(), rows.end(), [](const row & a, const row & b) { return a.ms > b.ms; });
                for (size_t k = 0; k < rows.size() && k < 6; ++k) {
                    const ggml_tensor * t = cgraph->nodes[rows[k].node];
                    fprintf(stderr, "  single: %8.3f ms %s '%s' [%lld,%lld,%lld,%lld]\\n", rows[k].ms, ggml_op_name(t->op), t->name,
                            (long long) t->ne[0], (long long) t->ne[1], (long long) t->ne[2], (long long) t->ne[3]);
                }
                g_strixllama_ev0.clear(); g_strixllama_ev1.clear(); g_strixllama_ev_node.clear();
            }
        }
'''),
    ],
}


def main():
    texts = {p: io.open(p, encoding="utf-8").read() for p in EDITS}
    if any(MARKER in t for t in texts.values()):
        print("already applied")
        return
    for p, pairs in EDITS.items():
        for old, new in pairs:
            if texts[p].count(old) != 1:
                sys.exit("anchor found %d times, expected once, in %s" % (texts[p].count(old), p))
            texts[p] = texts[p].replace(old, new, 1)
    for p, t in texts.items():
        io.open(p, "w", encoding="utf-8", newline="").write(t)
    print("patched", ", ".join(os.path.basename(p) for p in EDITS))


if __name__ == "__main__":
    main()
