#!/usr/bin/env python3
"""Q6_K decode twins of the Q8_0 trunk (LLAMA_TRUNK_DECODE_Q6K).

In-memory Q6_K copies of the Q8_0 trunk tensors, used by build_lora_mm for batches of <= 8
tokens; prefill keeps the original weights. Off by default - it costs 2.9 GB, and at the production
context (262144 / ubatch 8192) that is enough to slow long prefills and fail a multi-turn chat.

Supersedes apply_trunk_decode_twins.py, which fails against clean upstream because its anchors were
written against an already-modified tree.

Generated by tools/make_patch_script.py from the tree it must reproduce, so every anchor is
unique by construction. 12 hunks across 3 file(s).

Usage: python patches/apply_trunk_twins.py [tree]
"""
import io
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
tree = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "src", "llama.cpp")
MARKER = 'LLAMA_TRUNK_DECODE_Q6K'

EDITS = {
    os.path.join(tree, "src", "llama-model.cpp"): [
        ('''#include <map>
#include <numeric>
''',
         '''#include <map>
#include <mutex>
#include <numeric>
'''),
        ('''
    buft_list_t cpu_buft_list;
''',
         '''
    // strixllama: metadata contexts and device buffers of the decode twins (build_decode_twins)
    std::vector<ggml_context_ptr>        twin_ctxs;
    std::vector<ggml_backend_buffer_ptr> twin_bufs;

    buft_list_t cpu_buft_list;
'''),
        ('''
llama_model::llama_model(const llama_model_params & params) : params(params), pimpl(std::make_unique<impl>()) {
''',
         '''
// strixllama: process-wide twin table. The graph context has no pointer to its model, so
// build_lora_mm looks weights up here; entries are removed when their model is destroyed.
static std::mutex g_decode_twin_mutex;
static std::unordered_map<const ggml_tensor *, ggml_tensor *> g_decode_twins;

ggml_tensor * llama_decode_twin(const ggml_tensor * w) {
    std::lock_guard<std::mutex> lock(g_decode_twin_mutex);
    const auto it = g_decode_twins.find(w);
    return it == g_decode_twins.end() ? nullptr : it->second;
}

int64_t llama_decode_twin_max_tokens() {
    static const int64_t v = []() {
        const char * e = getenv("LLAMA_TRUNK_DECODE_MAX_T");
        return e ? (int64_t) atoll(e) : (int64_t) 8;
    }();
    return v;
}

// strixllama: LLAMA_TRUNK_DECODE_Q6K=1 builds a Q6_K copy of every 2-D Q8_0 weight (the trunk: attention,
// delta-net, HC projections, shared experts, PLE key/value; token_embd excluded) in a device buffer of
// its own. The copy is made with the same ggml_quantize_chunk that llama-quantize uses, so it is
// byte-identical to a --tensor-type-file requant of the same tensors. Decode on this model streams
// the trunk once per token at the memory-bandwidth wall; Q6_K reads 23% fewer bytes there (measured
// -9% per token), while prefill keeps the Q8_0 originals, whose MMB path is faster. Costs the size of
// the copies (2.9 GB on Qwen3.8-Flash-Next) and a few seconds at load.
void llama_model::build_decode_twins() {
    const char * e = getenv("LLAMA_TRUNK_DECODE_Q6K");
    if (e == nullptr || atoi(e) == 0) {
        return;
    }
    const ggml_type ttype = GGML_TYPE_Q6_K;
    const int64_t t0 = ggml_time_us();

    std::map<ggml_backend_buffer_type_t, std::vector<std::pair<std::string, ggml_tensor *>>> groups;
    for (const auto & [name, t] : tensors_by_name) {
        if (t == nullptr || t->type != GGML_TYPE_Q8_0 || !ggml_is_matrix(t) || t->buffer == nullptr) {
            continue;
        }
        if (name == "token_embd.weight" || t->ne[0] % ggml_blck_size(ttype) != 0) {
            continue;
        }
        groups[ggml_backend_buffer_get_type(t->buffer)].emplace_back(name, t);
    }
    if (groups.empty()) {
        LLAMA_LOG_WARN("%s: LLAMA_TRUNK_DECODE_Q6K set but no 2-D Q8_0 weights found\\n", __func__);
        return;
    }

    size_t n_twins = 0, bytes = 0;
    const int n_threads = std::max(1, std::min(16, (int) std::thread::hardware_concurrency()));
    for (auto & [buft, list] : groups) {
        ggml_init_params ip = { ggml_tensor_overhead() * (list.size() + 1), nullptr, true };
        ggml_context * ctx = ggml_init(ip);
        if (ctx == nullptr) {
            throw std::runtime_error("failed to create decode twin context");
        }
        pimpl->twin_ctxs.emplace_back(ctx);
        std::vector<std::pair<ggml_tensor *, ggml_tensor *>> pairs;
        for (auto & [name, t] : list) {
            ggml_tensor * twin = ggml_new_tensor_2d(ctx, ttype, t->ne[0], t->ne[1]);
            ggml_format_name(twin, "%s.q6k", name.c_str());
            pairs.emplace_back(t, twin);
        }
        ggml_backend_buffer_t buf = ggml_backend_alloc_ctx_tensors_from_buft(ctx, buft);
        if (buf == nullptr) {
            throw std::runtime_error(format("failed to allocate decode twin buffer on %s", ggml_backend_buft_name(buft)));
        }
        pimpl->twin_bufs.emplace_back(buf);
        bytes += ggml_backend_buffer_get_size(buf);

        const auto * q8 = ggml_get_type_traits(GGML_TYPE_Q8_0);
        for (auto & [t, twin] : pairs) {
            const int64_t n_per_row = t->ne[0];
            const int64_t nrows     = t->ne[1];
            std::vector<uint8_t> src(ggml_nbytes(t));
            ggml_backend_tensor_get(t, src.data(), 0, src.size());
            std::vector<float> f32((size_t) n_per_row * nrows);
            q8->to_float(src.data(), f32.data(), (int64_t) f32.size());
            std::vector<uint8_t> dst(ggml_nbytes(twin));
            const int64_t rows_per_thread = (nrows + n_threads - 1) / n_threads;
            std::vector<std::thread> workers;
            for (int w = 0; w < n_threads; ++w) {
                const int64_t first = w * rows_per_thread;
                const int64_t count = std::min(rows_per_thread, nrows - first);
                if (count <= 0) {
                    break;
                }
                workers.emplace_back([&, first, count]() {
                    ggml_quantize_chunk(ttype, f32.data(), dst.data(), first * n_per_row, count, n_per_row, nullptr);
                });
            }
            for (auto & w : workers) {
                w.join();
            }
            ggml_backend_tensor_set(twin, dst.data(), 0, dst.size());
            decode_twins[t] = twin;
            ++n_twins;
        }
    }
    {
        std::lock_guard<std::mutex> lock(g_decode_twin_mutex);
        for (const auto & [t, twin] : decode_twins) {
            g_decode_twins[t] = twin;
        }
    }
    LLAMA_LOG_INFO("%s: %zu Q8_0 trunk tensors got %s decode twins (%.2f GiB, %d threads, %.1f s); used for batches of <= %lld tokens\\n",
            __func__, n_twins, ggml_type_name(ttype), bytes / 1024.0 / 1024.0 / 1024.0, n_threads,
            (ggml_time_us() - t0) / 1e6, (long long) llama_decode_twin_max_tokens());
}

llama_model::llama_model(const llama_model_params & params) : params(params), pimpl(std::make_unique<impl>()) {
'''),
        ('''        delete lora;
    }
''',
         '''        delete lora;
    }
    if (!decode_twins.empty()) {
        std::lock_guard<std::mutex> lock(g_decode_twin_mutex);
        for (const auto & [t, twin] : decode_twins) {
            g_decode_twins.erase(t);
        }
    }
'''),
        ('''
    return true;
''',
         '''
    // strixllama: optional Q6_K decode copies of the Q8_0 trunk (LLAMA_TRUNK_DECODE_Q6K=1)
    build_decode_twins();

    return true;
'''),
        ('''// strixllama: this definition is compiled on every platform; the Windows open lives in its
// _WIN32 branch below instead of in a separate stub that always fell back to mmap reads
''',
         ''''''),
        ('''    // CreateFileW, not ::open: the reader issues overlapped reads against this handle
''',
         ''''''),
        ('''    auto reader = std::make_unique<llama_lazy_reader>(fd, w->offs,
            ggml_row_size(t->type, t->ne[0]), t->ne[1], n_threads, t->type, t->ne[0]);
''',
         '''    std::unique_ptr<llama_lazy_reader> reader;
    try {
        reader = std::make_unique<llama_lazy_reader>(fd, w->offs,
                ggml_row_size(t->type, t->ne[0]), t->ne[1], n_threads, t->type, t->ne[0]);
    } catch (...) {
#ifdef _WIN32
        CloseHandle(fd);
#else
        ::close(fd);
#endif
        throw;
    }
'''),
        ('''#else
const llama_lazy_reader * llama_model_base::load_lazy_reader(llama_model_loader & ml, const char *, const ggml_tensor *) {
    if (ml.lazy.mode == LLAMA_LAZY_MODE_DIRECT) {
        LLAMA_LOG_WARN("%s: --lazy-mode on-direct is not supported on this platform, using lazy mmap reads\\n", __func__);
    }
    return nullptr;
}
#endif
''',
         '''
'''),
    ],
    os.path.join(tree, "src", "llama-model.h"): [
        ('''
    // for keeping track of associated LoRA adapters
''',
         '''
    // strixllama: decode-precision twins of the Q8_0 trunk (LLAMA_TRUNK_DECODE_Q6K=1). Built once the
    // weights are loaded, in their own device buffers; the originals are untouched, so prefill keeps
    // its numerics. build_lora_mm swaps a weight for its twin on batches of at most
    // llama_decode_twin_max_tokens() tokens (LLAMA_TRUNK_DECODE_MAX_T, default 8).
    std::unordered_map<const ggml_tensor *, ggml_tensor *> decode_twins;
    void build_decode_twins();

    // for keeping track of associated LoRA adapters
'''),
        ('''    std::unique_ptr<impl> pimpl;
};

llama_model * llama_model_create(llm_arch arch, const llama_model_params & params);
''',
         '''    std::unique_ptr<impl> pimpl;
};

// strixllama: the decode twin of a trunk weight (null if none) and the batch bound under which it is used
ggml_tensor * llama_decode_twin(const ggml_tensor * w);
int64_t       llama_decode_twin_max_tokens();

llama_model * llama_model_create(llm_arch arch, const llama_model_params & params);
'''),
    ],
    os.path.join(tree, "src", "llama-graph.cpp"): [
        ('''    ggml_tensor * res = ggml_mul_mat(ctx0, w, cur);
''',
         '''    // strixllama: decode-sized batches read the Q6_K twin of a Q8_0 trunk weight when one was built
    // (LLAMA_TRUNK_DECODE_Q6K); larger batches, and the LoRA lookup below, keep the original
    ggml_tensor * w_mm = w;
    if (n_tokens <= llama_decode_twin_max_tokens()) {
        if (ggml_tensor * twin = llama_decode_twin(w)) {
            w_mm = twin;
        }
    }
    ggml_tensor * res = ggml_mul_mat(ctx0, w_mm, cur);
'''),
    ],
}


def main():
    texts = {p: io.open(p, encoding="utf-8").read() for p in EDITS}
    if any(MARKER in t for t in texts.values()):
        print("already applied")
        return
    for p, pairs in EDITS.items():
        for old, new in pairs:
            if texts[p].count(old) != 1:
                sys.exit("anchor found %d times, expected once, in %s" % (texts[p].count(old), p))
            texts[p] = texts[p].replace(old, new, 1)
    for p, t in texts.items():
        io.open(p, "w", encoding="utf-8", newline="").write(t)
    print("patched", ", ".join(os.path.basename(p) for p in EDITS))


if __name__ == "__main__":
    main()
