#!/usr/bin/env python3
"""Q6_K weights on MMQ at every width on RDNA3.5, not hipBLAS

Upstream sends Q6_K to MMQ up to 256 columns and to hipBLAS above, and hipBLAS loads each GEMM kernel from disk the first time it meets a shape. The MTP draft head's Q6_K attention projection stalled 208 ms in the draft's first prompt batch, and a prompt's last batch is a new width almost every time: a fresh server's first answer came about 0.3 s later. On RDNA3.5 MMQ takes Q6_K at every width (STRIX_MMQ_Q6K_ANY=0: upstream's limit). In the shipped files the draft head's attn_v and hc_ffn_down are Q6_K, and so is the target's output projection. The server asks that for at most 16 rows, which MMQ already took; the perplexity tool asks for 8192, which now take MMQ too, whose activations are quantized: perplexity at 8K context 2.6814 against 2.6811.

Generated by tools/make_patch_script.py from the tree it must reproduce, so every anchor is
unique by construction. 2 hunks across 1 file(s).

Usage: python patches/apply_q6k_mmq_rdna35.py [tree]
"""
import io
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
tree = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "src", "llama.cpp")
MARKER = 'STRIX_MMQ_Q6K_ANY'

EDITS = {
    os.path.join(tree, "ggml", "src", "ggml-cuda", "mmq.cu"): [
        ('''                case GGML_TYPE_Q6_K:
''',
         '''                case GGML_TYPE_Q6_K: {
                    // strixllama: above 256 columns hipBLAS was the pick, and it loads each GEMM kernel from disk the
                    // first time it meets a shape - the MTP draft's Q6_K attn_v stalled 208 ms in the draft's first
                    // prompt batch, and a prompt's last batch is a new width almost every time. On RDNA3.5 MMQ takes
                    // every width (STRIX_MMQ_Q6K_ANY=0: upstream's limit)
                    static const bool any = !getenv("STRIX_MMQ_Q6K_ANY") || atoi(getenv("STRIX_MMQ_Q6K_ANY")) != 0;
                    if (any && GGML_CUDA_CC_IS_RDNA3_5(cc)) {
                        return true;
                    }
'''),
        ('''                    return ne11 <= (GGML_CUDA_CC_IS_RDNA3_0(cc) ? 128 : 256);
                case GGML_TYPE_IQ2_XS:
''',
         '''                    return ne11 <= (GGML_CUDA_CC_IS_RDNA3_0(cc) ? 128 : 256);
                }
                case GGML_TYPE_IQ2_XS:
'''),
    ],
}


def main():
    texts = {p: io.open(p, encoding="utf-8").read() for p in EDITS}
    if any(MARKER in t for t in texts.values()):
        print("already applied")
        return
    for p, pairs in EDITS.items():
        for old, new in pairs:
            if texts[p].count(old) != 1:
                sys.exit("anchor found %d times, expected once, in %s" % (texts[p].count(old), p))
            texts[p] = texts[p].replace(old, new, 1)
    for p, t in texts.items():
        io.open(p, "w", encoding="utf-8", newline="").write(t)
    print("patched", ", ".join(os.path.basename(p) for p in EDITS))


if __name__ == "__main__":
    main()
