#!/usr/bin/env python3
"""Three small products of a several-conversation verify step off one-workgroup kernels

A verify step of several conversations carries 5-16 tokens, and three of its products still ran with a few workgroups for the whole GPU. The GDN conv input's concat of a transposed batch of 2-31 tokens took the non-contiguous kernel, one 256-thread block per channel and sequence for 3 + tokens values; it now takes the tiled transpose from 2 tokens (STRIX_CONCAT_T_MIN). The sparse-attention indexer's BF16 k projection [2560 x 128] at 9-32 columns took MMB's one 128-row tile; BF16 weights now run the vector kernel over column chunks there, as F32 ones do (STRIX_BF16_VEC_CHUNK_MAX). Quantized weights of at most 1024 output rows - the hyper-connection down projection, the attention k and v, the shared expert - took three to five MMQ tiles at 9-32 columns; they now run the vector kernel over 8-column chunks (STRIX_Q_VEC_CHUNK_MAX, STRIX_Q_VEC_CHUNK_ROWS). A nine-token verify step 104-106 -> 99-100 ms. One token per conversation, and batches of more than 32, are unchanged.

Generated by tools/make_patch_script.py from the tree it must reproduce, so every anchor is
unique by construction. 3 hunks across 2 file(s).

Usage: python patches/apply_verify_small_products.py [tree]
"""
import io
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
tree = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "src", "llama.cpp")
MARKER = 'STRIX_Q_VEC_CHUNK_ROWS'

EDITS = {
    os.path.join(tree, "ggml", "src", "ggml-cuda", "ggml-cuda.cu"): [
        ('''    static const int64_t f32_vec_chunk_max = getenv("STRIX_F32_VEC_CHUNK_MAX") ? atoll(getenv("STRIX_F32_VEC_CHUNK_MAX")) : 32;
    const bool vec_chunks = (ne01 <= 64 && ne11 <= 64) || (src0->type == GGML_TYPE_F32 && ne11 <= f32_vec_chunk_max);
''',
         '''    // strixllama: and a BF16 weight of any height at 9-32 columns (STRIX_BF16_VEC_CHUNK_MAX): the sparse-attention
    // indexer's k projection [2560 x 128] took the MMB kernel's one 128-row tile there, one workgroup for the whole GPU
    static const int64_t f32_vec_chunk_max  = getenv("STRIX_F32_VEC_CHUNK_MAX")  ? atoll(getenv("STRIX_F32_VEC_CHUNK_MAX"))  : 32;
    static const int64_t bf16_vec_chunk_max = getenv("STRIX_BF16_VEC_CHUNK_MAX") ? atoll(getenv("STRIX_BF16_VEC_CHUNK_MAX")) : 32;
    const bool vec_chunks = (ne01 <= 64 && ne11 <= 64) || (src0->type == GGML_TYPE_F32 && ne11 <= f32_vec_chunk_max)
        || (src0->type == GGML_TYPE_BF16 && ne11 <= bf16_vec_chunk_max);
'''),
        ('''        ggml_cuda_mul_mat_f(ctx, src0, src1, nullptr, dst);
        return;
''',
         '''        ggml_cuda_mul_mat_f(ctx, src0, src1, nullptr, dst);
        return;
    }
    // strixllama: a quantized weight of at most STRIX_Q_VEC_CHUNK_ROWS output rows (1024) at 9-32 columns
    // (STRIX_Q_VEC_CHUNK_MAX, 0: off) - the hyper-connection down projection [10240 x 320], the attention k and v, the
    // shared expert - is a handful of MMQ tiles, and MMQ has no stream-k on RDNA: three to five workgroups for the whole
    // GPU. The vector kernel over 8-column chunks reads the weight twice and still takes about half the time. Taller
    // weights stay on MMQ: for the [6144 x 2560] projections the second read cost more than the tiles lose
    static const int64_t q_vec_chunk_max  = getenv("STRIX_Q_VEC_CHUNK_MAX")  ? atoll(getenv("STRIX_Q_VEC_CHUNK_MAX"))  : 32;
    static const int64_t q_vec_chunk_rows = getenv("STRIX_Q_VEC_CHUNK_ROWS") ? atoll(getenv("STRIX_Q_VEC_CHUNK_ROWS")) : 1024;
    if (ggml_is_quantized(src0->type) && ne11 > MMVQ_MAX_BATCH_SIZE && ne11 <= q_vec_chunk_max && ne01 <= q_vec_chunk_rows
            && src0->ne[2] == 1 && src0->ne[3] == 1 && src1->ne[2] == 1 && src1->ne[3] == 1
            && ggml_cuda_should_use_mmvq(src0->type, cc, MMVQ_MAX_BATCH_SIZE)) {
        const int64_t chunk = MMVQ_MAX_BATCH_SIZE;
        for (int64_t c0 = 0; c0 < ne11; c0 += chunk) {
            const int64_t nc = std::min<int64_t>(chunk, ne11 - c0);
            ggml_tensor src1_c = *src1;
            src1_c.ne[1] = nc;
            src1_c.data  = (char *) src1->data + c0*src1->nb[1];
            ggml_tensor dst_c = *dst;
            dst_c.ne[1] = nc;
            dst_c.data  = (char *) dst->data + c0*dst->nb[1];
            ggml_cuda_mul_mat_vec_q(ctx, src0, &src1_c, nullptr, &dst_c);
        }
        return;
'''),
    ],
    os.path.join(tree, "ggml", "src", "ggml-cuda", "concat.cu"): [
        ('''    if (dst->type == GGML_TYPE_F32 && GGML_CUDA_CC_IS_RDNA3_5(ggml_cuda_info().devices[ggml_cuda_get_device()].cc) && dim == 0 && src1->ne[0] >= 32 && src0->ne[3] == 1 && src1->ne[3] == 1 && dst->ne[3] == 1 &&
''',
         '''    // strixllama: the tiled transpose from 2 tokens on (STRIX_CONCAT_T_MIN): below 32 the GDN conv input of a verify
    // step - [3 + tokens, 10240, sequences] - took the non-contiguous kernel, one block of 256 threads per channel and
    // sequence for 3 + tokens values, ~30K blocks at three conversations. One token is contiguous and unchanged
    static const int64_t concat_t_min = getenv("STRIX_CONCAT_T_MIN") ? atoll(getenv("STRIX_CONCAT_T_MIN")) : 2;
    if (dst->type == GGML_TYPE_F32 && GGML_CUDA_CC_IS_RDNA3_5(ggml_cuda_info().devices[ggml_cuda_get_device()].cc) && dim == 0 && src1->ne[0] >= concat_t_min && src0->ne[3] == 1 && src1->ne[3] == 1 && dst->ne[3] == 1 &&
'''),
    ],
}


def main():
    texts = {p: io.open(p, encoding="utf-8").read() for p in EDITS}
    if any(MARKER in t for t in texts.values()):
        print("already applied")
        return
    for p, pairs in EDITS.items():
        for old, new in pairs:
            if texts[p].count(old) != 1:
                sys.exit("anchor found %d times, expected once, in %s" % (texts[p].count(old), p))
            texts[p] = texts[p].replace(old, new, 1)
    for p, t in texts.items():
        io.open(p, "w", encoding="utf-8", newline="").write(t)
    print("patched", ", ".join(os.path.basename(p) for p in EDITS))


if __name__ == "__main__":
    main()
