#!/usr/bin/env python3
"""A disk tier under the server's prompt cache, so a conversation that leaves the server comes back without its prefill.

The RAM prompt cache (--cache-ram) already holds what a hybrid model needs to resume - the tokens, the state and the recurrent checkpoints - but it is lost with the process and bounded by RAM. Every entry that enters it is now also written to STRIX_PROMPT_CACHE_DIR (one file each: tokens, target and draft state, checkpoints), and a miss in RAM is looked up on disk with the same prefix criteria before the prompt is processed from scratch. On Qwen3.8-Flash-Next a 34K-token session is 1.3-1.7 GB, reads back in about 1.4 s, and the next turn then processes 13 tokens instead of 33911 (38 s). Bounded by STRIX_PROMPT_CACHE_MIB, oldest first; entries with media are not persisted.

Generated by tools/make_patch_script.py from the tree it must reproduce, so every anchor is
unique by construction. 6 hunks across 3 file(s).

Usage: python patches/apply_prompt_cache_disk.py [tree]
"""
import io
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
tree = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "src", "llama.cpp")
MARKER = 'load_from_disk'

EDITS = {
    os.path.join(tree, "tools", "server", "server-task.h"): [
        ('''    void update();
};
''',
         '''    void update();

    // strixllama: a disk tier under the RAM cache. Every entry that goes into the RAM cache is also
    // written to disk_dir (tokens, state, checkpoints - the checkpoints are what let a hybrid model
    // resume at all), and a miss in RAM is looked up on disk with the same prefix criteria before the
    // prompt is processed from scratch. A 34K-token session of Qwen3.8-Flash-Next is ~1.3 GB and reads
    // back in well under a second against ~40 s of prefill. Entries with media are not persisted.
    struct disk_entry {
        std::string   path;
        server_tokens tokens;
        size_t        bytes;
        int64_t       order;    // larger = more recently written or used
    };

    std::string             disk_dir;
    size_t                  disk_limit = 0;      // bytes, 0 = no disk tier
    bool                    disk_has_mtmd = false;
    int64_t                 disk_seq = 0;
    std::vector<disk_entry> disk_index;

    void set_disk(const std::string & dir, size_t limit_mib, bool has_mtmd);
    size_t disk_size() const;
    void persist(const server_prompt_cache_state & state);
    // appends the best disk entry to `states` when it beats (f_keep_best, f_sim_best); returns it or nullptr
    server_prompt_cache_state * load_from_disk(const server_tokens & tokens_new, float & f_keep_best, float & f_sim_best);
};
'''),
    ],
    os.path.join(tree, "tools", "server", "server-task.cpp"): [
        ('''#include <sstream>

''',
         '''#include <sstream>
#include <chrono>
#include <filesystem>
#include <fstream>

'''),
        ('''
    if (it_best != states.end()) {
''',
         '''
    // strixllama: the disk tier, with the same criteria, only when it would beat what is in RAM
    if (disk_limit > 0) {
        if (server_prompt_cache_state * from_disk = load_from_disk(tokens_new, f_keep_best, f_sim_best)) {
            it_best = std::prev(states.end());
            GGML_ASSERT(&*it_best == from_disk);
        }
    }

    if (it_best != states.end()) {
'''),
        ('''                (const void *)&state, state.prompt.n_tokens(), state.prompt.checkpoints.size(), state.size() / (1024.0 * 1024.0));
    }
}
''',
         '''                (const void *)&state, state.prompt.n_tokens(), state.prompt.checkpoints.size(), state.size() / (1024.0 * 1024.0));
    }
}

// strixllama: the disk tier. One file per entry:
//   "STRIXSPC" u32 version u32 has_mtmd
//   u64 n_token_bytes  bytes            (server_tokens::serialize)
//   u64 n_main bytes | u64 n_drft bytes (llama_state_seq data, target and draft)
//   u32 n_checkpoints, then per checkpoint: i64 n_tokens i32 pos_min i32 pos_max, u64 n_tgt bytes, u64 n_dft bytes, u64 n_spec bytes
namespace {
const char STRIX_SPC_MAGIC[8] = {'S','T','R','I','X','S','P','C'};
const uint32_t STRIX_SPC_VERSION = 1;

template <typename T> void spc_put(std::ofstream & f, const T & v) { f.write((const char *) &v, sizeof(v)); }
template <typename T> bool spc_get(std::ifstream & f, T & v) { f.read((char *) &v, sizeof(v)); return (bool) f; }
void spc_put_blob(std::ofstream & f, const std::vector<uint8_t> & v) { spc_put(f, (uint64_t) v.size()); if (!v.empty()) f.write((const char *) v.data(), v.size()); }
bool spc_get_blob(std::ifstream & f, std::vector<uint8_t> & v, uint64_t limit) {
    uint64_t n = 0;
    if (!spc_get(f, n) || n > limit) return false;
    v.resize(n);
    if (n) f.read((char *) v.data(), n);
    return (bool) f;
}
// tokens as the serialized bytes, reinterpreted the way slot restore does
bool spc_read_tokens(std::ifstream & f, server_tokens & out, bool has_mtmd) {
    std::vector<uint8_t> raw;
    if (!spc_get_blob(f, raw, 1ull << 30) || raw.size() % sizeof(llama_token) != 0) return false;
    llama_tokens packed(raw.size() / sizeof(llama_token));
    if (!packed.empty()) memcpy(packed.data(), raw.data(), raw.size());
    out = server_tokens::deserialize(packed, has_mtmd);
    return true;
}
int64_t spc_now() {
    return std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::system_clock::now().time_since_epoch()).count();
}
}

void server_prompt_cache::set_disk(const std::string & dir, size_t limit_mib, bool has_mtmd) {
    std::error_code ec;
    std::filesystem::create_directories(dir, ec);
    disk_dir      = dir;
    disk_limit    = limit_mib * 1024ull * 1024ull;
    disk_has_mtmd = has_mtmd;
    disk_index.clear();
    for (const auto & entry : std::filesystem::directory_iterator(dir, ec)) {
        if (!entry.is_regular_file() || entry.path().extension() != ".spc") continue;
        std::ifstream f(entry.path(), std::ios::binary);
        char magic[8]; uint32_t version = 0, mtmd = 0;
        if (!f.read(magic, 8) || memcmp(magic, STRIX_SPC_MAGIC, 8) != 0 || !spc_get(f, version) || version != STRIX_SPC_VERSION || !spc_get(f, mtmd)) {
            SRV_WRN(" - disk cache: skipping %s (not a cache file)\\n", entry.path().string().c_str());
            continue;
        }
        disk_entry e { entry.path().string(), server_tokens(), (size_t) entry.file_size(ec), 0 };
        if (!spc_read_tokens(f, e.tokens, disk_has_mtmd)) continue;
        // order by the file's own write time, so the index survives restarts in LRU order
        e.order = std::chrono::duration_cast<std::chrono::milliseconds>(entry.last_write_time(ec).time_since_epoch()).count();
        disk_seq = std::max(disk_seq, e.order);
        disk_index.push_back(std::move(e));
    }
    SRV_INF("disk prompt cache: %zu entries, %.1f GiB in %s (limit %.1f GiB)\\n",
            disk_index.size(), disk_size() / (1024.0 * 1024.0 * 1024.0), dir.c_str(), disk_limit / (1024.0 * 1024.0 * 1024.0));
}

size_t server_prompt_cache::disk_size() const {
    size_t res = 0;
    for (const auto & e : disk_index) res += e.bytes;
    return res;
}

void server_prompt_cache::persist(const server_prompt_cache_state & state) {
    if (disk_limit == 0 || state.prompt.tokens.size() == 0) return;
    const llama_tokens text = state.prompt.tokens.get_text_tokens();
    for (llama_token t : text) {
        if (t == LLAMA_TOKEN_NULL) return;      // media in the prompt: not persisted
    }
    // entries that are a prefix of this one are obsolete, on disk as in RAM
    std::error_code ec;
    for (auto it = disk_index.begin(); it != disk_index.end();) {
        const size_t lcp = it->tokens.get_common_prefix(state.prompt.tokens);
        if (lcp == it->tokens.size()) {
            std::filesystem::remove(it->path, ec);
            it = disk_index.erase(it);
        } else if (lcp == state.prompt.tokens.size()) {
            return;                              // already covered by a longer entry on disk
        } else {
            ++it;
        }
    }
    const std::vector<char> tok_bytes = state.prompt.tokens.serialize();
    uint64_t h = 1469598103934665603ull;
    for (char c : tok_bytes) { h ^= (uint8_t) c; h *= 1099511628211ull; }
    char name[64];
    snprintf(name, sizeof(name), "%016llx-%d.spc", (unsigned long long) h, (int) state.prompt.tokens.size());
    const std::string path = (std::filesystem::path(disk_dir) / name).string();
    const std::string part = path + ".part";
    {
        std::ofstream f(part, std::ios::binary | std::ios::trunc);
        if (!f) { SRV_WRN(" - disk cache: cannot write %s\\n", part.c_str()); return; }
        f.write(STRIX_SPC_MAGIC, 8);
        spc_put(f, STRIX_SPC_VERSION);
        spc_put(f, (uint32_t) (disk_has_mtmd ? 1 : 0));
        spc_put(f, (uint64_t) tok_bytes.size());
        f.write(tok_bytes.data(), tok_bytes.size());
        spc_put_blob(f, state.data.main);
        spc_put_blob(f, state.data.drft);
        spc_put(f, (uint32_t) state.prompt.checkpoints.size());
        for (const auto & c : state.prompt.checkpoints) {
            spc_put(f, (int64_t) c.n_tokens);
            spc_put(f, (int32_t) c.pos_min);
            spc_put(f, (int32_t) c.pos_max);
            spc_put_blob(f, c.data_tgt);
            spc_put_blob(f, c.data_dft);
            spc_put_blob(f, c.data_spec);
        }
        if (!f) { SRV_WRN(" - disk cache: write failed for %s\\n", part.c_str()); f.close(); std::filesystem::remove(part, ec); return; }
    }
    std::filesystem::rename(part, path, ec);
    if (ec) { std::filesystem::remove(part, ec); SRV_WRN(" - disk cache: cannot place %s\\n", path.c_str()); return; }
    disk_entry e { path, state.prompt.tokens.clone(), (size_t) std::filesystem::file_size(path, ec), ++disk_seq };
    disk_index.push_back(std::move(e));
    // least recently written or used goes first
    while (disk_index.size() > 1 && disk_size() > disk_limit) {
        auto oldest = disk_index.begin();
        for (auto it = disk_index.begin(); it != disk_index.end(); ++it) {
            if (it->order < oldest->order) oldest = it;
        }
        if (oldest->path == path) break;
        std::filesystem::remove(oldest->path, ec);
        disk_index.erase(oldest);
    }
    SRV_INF(" - disk cache: wrote %d tokens, %.3f GiB (%zu entries, %.1f GiB on disk)\\n",
            (int) state.prompt.tokens.size(), (double) e.bytes / (1024.0 * 1024.0 * 1024.0), disk_index.size(), disk_size() / (1024.0 * 1024.0 * 1024.0));
}

server_prompt_cache_state * server_prompt_cache::load_from_disk(const server_tokens & tokens_new, float & f_keep_best, float & f_sim_best) {
    auto best = disk_index.end();
    for (auto it = disk_index.begin(); it != disk_index.end(); ++it) {
        const int lcp_cur = it->tokens.get_common_prefix(tokens_new);
        const float f_keep_cur = float(lcp_cur) / it->tokens.size();
        const float f_sim_cur  = float(lcp_cur) / tokens_new.size();
        if (f_keep_cur < 0.25f) continue;
        if (f_keep_best < f_keep_cur && f_sim_best < f_sim_cur) {
            f_keep_best = f_keep_cur;
            f_sim_best  = f_sim_cur;
            best = it;
        }
    }
    if (best == disk_index.end()) return nullptr;

    const int64_t t0 = ggml_time_us();
    std::ifstream f(best->path, std::ios::binary);
    char magic[8]; uint32_t version = 0, mtmd = 0;
    server_prompt_cache_state state;
    bool ok = f.read(magic, 8) && memcmp(magic, STRIX_SPC_MAGIC, 8) == 0 && spc_get(f, version) && version == STRIX_SPC_VERSION && spc_get(f, mtmd)
        && spc_read_tokens(f, state.prompt.tokens, disk_has_mtmd)
        && spc_get_blob(f, state.data.main, 1ull << 40) && spc_get_blob(f, state.data.drft, 1ull << 40);
    uint32_t n_ckpt = 0;
    ok = ok && spc_get(f, n_ckpt) && n_ckpt <= 4096;
    for (uint32_t i = 0; ok && i < n_ckpt; ++i) {
        common_prompt_checkpoint c;
        int64_t n_tokens = 0; int32_t pos_min = 0, pos_max = 0;
        ok = spc_get(f, n_tokens) && spc_get(f, pos_min) && spc_get(f, pos_max)
            && spc_get_blob(f, c.data_tgt, 1ull << 40) && spc_get_blob(f, c.data_dft, 1ull << 40) && spc_get_blob(f, c.data_spec, 1ull << 40);
        if (ok) {
            c.n_tokens = n_tokens; c.pos_min = pos_min; c.pos_max = pos_max;
            state.prompt.checkpoints.push_back(std::move(c));
        }
    }
    if (!ok) {
        SRV_WRN(" - disk cache: %s is unreadable, dropping it\\n", best->path.c_str());
        std::error_code ec;
        std::filesystem::remove(best->path, ec);
        disk_index.erase(best);
        return nullptr;
    }
    best->order = ++disk_seq;
    SRV_INF(" - disk cache: read %d tokens, %.3f GiB in %.0f ms (f_keep = %.3f, f_sim = %.3f)\\n",
            (int) state.prompt.tokens.size(), best->bytes / (1024.0 * 1024.0 * 1024.0), (ggml_time_us() - t0) / 1000.0, f_keep_best, f_sim_best);
    states.push_back(std::move(state));
    return &states.back();
}
'''),
    ],
    os.path.join(tree, "tools", "server", "server-context.cpp"): [
        ('''            llama_state_seq_get_data_ext(ctx_dft, cur->data.drft.data(), cur_size_dft, id, LLAMA_STATE_SEQ_FLAGS_NONE);
        }

        return true;
''',
         '''            llama_state_seq_get_data_ext(ctx_dft, cur->data.drft.data(), cur_size_dft, id, LLAMA_STATE_SEQ_FLAGS_NONE);
        }

        // strixllama: the disk tier keeps a copy, checkpoints included
        prompt_cache.persist(*cur);

        return true;
'''),
        ('''            prompt_cache = std::make_unique<server_prompt_cache>(params_base.cache_ram_mib, n_ctx);
        } else {
''',
         '''            prompt_cache = std::make_unique<server_prompt_cache>(params_base.cache_ram_mib, n_ctx);

            // strixllama: STRIX_PROMPT_CACHE_DIR / STRIX_PROMPT_CACHE_MIB add a disk tier under the RAM cache
            // (tools/manager.py sets them from the "disk prompt cache" switch)
            if (const char * dir = getenv("STRIX_PROMPT_CACHE_DIR"); dir && *dir) {
                const char * mib = getenv("STRIX_PROMPT_CACHE_MIB");
                prompt_cache->set_disk(dir, mib ? std::max(1, atoi(mib)) : 16384, mctx != nullptr);
            }
        } else {
'''),
    ],
}


def main():
    texts = {p: io.open(p, encoding="utf-8").read() for p in EDITS}
    if any(MARKER in t for t in texts.values()):
        print("already applied")
        return
    for p, pairs in EDITS.items():
        for old, new in pairs:
            if texts[p].count(old) != 1:
                sys.exit("anchor found %d times, expected once, in %s" % (texts[p].count(old), p))
            texts[p] = texts[p].replace(old, new, 1)
    for p, t in texts.items():
        io.open(p, "w", encoding="utf-8", newline="").write(t)
    print("patched", ", ".join(os.path.basename(p) for p in EDITS))


if __name__ == "__main__":
    main()
