#!/usr/bin/env python3
"""Restore a conversation from the disk tier with parallel reads, and leave its checkpoints on disk

A 79K-token conversation is 2.3 GiB of state and ~3.3 GB of checkpoints, of which a rewind reads one. The checkpoints now stay in the store, pinned for the slot like paged-out ones, and the chunks are read by four threads: 5.63 GiB in 2724 ms became 2.33 GiB in 734 ms, token-identical.

Generated by tools/make_patch_script.py from the tree it must reproduce, so every anchor is
unique by construction. 26 hunks across 3 file(s).

Usage: python D:/Work/strixllama/patches/apply_disk_restore_lazy.py [tree]
"""
import io
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
tree = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "src", "llama.cpp")
MARKER = 'checkpoints left on disk'

EDITS = {
    os.path.join(tree, "tools", "server", "server-task.h"): [
        ('''    // strixllama: `before_restore` is called with the token count of the entry about to replace `prompt`, before
    // its state goes into the KV cache - the caller makes room for it there, and lets go of what the old prompt held
    bool load(server_prompt & prompt, const server_tokens & tokens_new, llama_context * ctx_tgt, llama_context * ctx_dft, int32_t id_slot,
              const std::function<void(size_t)> & before_restore = nullptr);

    void update();

    // strixllama: a disk tier under the RAM cache; the files and their formats are described in
    // server-task.cpp. Entries are content-addressed and written by a background thread, so saving a
    // conversation again writes only what changed, never the whole state in one burst.
    struct disk_ckpt_ref {
        uint64_t key;
        int64_t  n_tokens;
        int32_t  pos_min;
        int32_t  pos_max;
        uint64_t size_tgt;
        uint64_t size_dft;
        uint64_t size_spec;
    };
''',
         '''    // strixllama: a disk tier under the RAM cache; the files and their formats are described in
    // server-task.cpp. Entries are content-addressed and written by a background thread, so saving a
    // conversation again writes only what changed, never the whole state in one burst.
    struct disk_ckpt_ref {
        uint64_t key;
        int64_t  n_tokens;
        int32_t  pos_min;
        int32_t  pos_max;
        uint64_t size_tgt;
        uint64_t size_dft;
        uint64_t size_spec;
    };
    // a slot's checkpoints handed back to the store: (n_tokens, pos_min, pos_max) -> the ref it is stored under
    using ckpt_paged_map = std::map<std::tuple<int64_t, int32_t, int32_t>, disk_ckpt_ref>;

    // strixllama: `before_restore` is called with the token count of the entry about to replace `prompt`, before
    // its state goes into the KV cache - the caller makes room for it there, and lets go of what the old prompt held.
    // With `paged_out`, an entry restored from the disk tier leaves its checkpoints there: `prompt` gets them without
    // their bytes and `paged_out` says where they are (pinned), exactly as if the slot had paged them out itself - a
    // 79K-token conversation carries ~3.3 GB of checkpoints of which a rewind reads one.
    bool load(server_prompt & prompt, const server_tokens & tokens_new, llama_context * ctx_tgt, llama_context * ctx_dft, int32_t id_slot,
              const std::function<void(size_t)> & before_restore = nullptr, ckpt_paged_map * paged_out = nullptr);

    void update();
'''),
        ('''    // a slot's checkpoints handed back to the store: (n_tokens, pos_min, pos_max) -> the ref it is stored under
    using ckpt_paged_map = std::map<std::tuple<int64_t, int32_t, int32_t>, disk_ckpt_ref>;
    // hand a gathered state to the writer; `wait` blocks while the queue is full instead of giving up. Checkpoints
    // with no bytes are ones the slot handed back, and `paged` says where they are
    bool     persist(const server_prompt & prompt, std::vector<uint8_t> && data_main, std::vector<uint8_t> && data_drft, bool wait,
                     const ckpt_paged_map * paged = nullptr);
    // checkpoints are cold data - only a rewind reads one - so an idle slot drops the bytes of those the store
    // holds; returns the bytes freed
    uint64_t ckpt_page_out(const server_tokens & tokens, std::list<common_prompt_checkpoint> & ckpts, ckpt_paged_map & paged);
    // and reads one back when a rewind picks it. False when it is not this conversation's any more, or unreadable
    bool     ckpt_page_in(const server_tokens & tokens, const ckpt_paged_map & paged, common_prompt_checkpoint & c);
    // a paged-out checkpoint holds a reference in the store, so eviction cannot delete it while the slot may
    // still rewind to it; the slot lets go when it is cleared or takes another conversation
    void     ckpt_release(ckpt_paged_map & paged);
    // appends the best disk entry to `states` when it beats (f_keep_best, f_sim_best); returns it or nullptr
    server_prompt_cache_state * load_from_disk(const server_tokens & tokens_new, float & f_keep_best, float & f_sim_best);
''',
         '''    // hand a gathered state to the writer; `wait` blocks while the queue is full instead of giving up. Checkpoints
    // with no bytes are ones the slot handed back, and `paged` says where they are
    bool     persist(const server_prompt & prompt, std::vector<uint8_t> && data_main, std::vector<uint8_t> && data_drft, bool wait,
                     const ckpt_paged_map * paged = nullptr);
    // checkpoints are cold data - only a rewind reads one - so an idle slot drops the bytes of those the store
    // holds; returns the bytes freed
    uint64_t ckpt_page_out(const server_tokens & tokens, std::list<common_prompt_checkpoint> & ckpts, ckpt_paged_map & paged);
    // and reads one back when a rewind picks it. False when it is not this conversation's any more, or unreadable
    bool     ckpt_page_in(const server_tokens & tokens, const ckpt_paged_map & paged, common_prompt_checkpoint & c);
    // a paged-out checkpoint holds a reference in the store, so eviction cannot delete it while the slot may
    // still rewind to it; the slot lets go when it is cleared or takes another conversation
    void     ckpt_release(ckpt_paged_map & paged);
    // appends the best disk entry to `states` when it beats (f_keep_best, f_sim_best); returns it or nullptr. With
    // `paged`, a version 2 entry's checkpoints stay on disk: pinned and named in `paged`, bytes read on demand
    server_prompt_cache_state * load_from_disk(const server_tokens & tokens_new, float & f_keep_best, float & f_sim_best,
                                               ckpt_paged_map * paged = nullptr);
'''),
    ],
    os.path.join(tree, "tools", "server", "server-task.cpp"): [
        ('''#include <array>
#include <chrono>
''',
         '''#include <array>
#include <atomic>
#include <chrono>
'''),
        ('''#include <set>

''',
         '''#include <set>
#include <system_error>

'''),
        ('''                               const std::function<void(size_t)> & before_restore) {
''',
         '''                               const std::function<void(size_t)> & before_restore, ckpt_paged_map * paged_out) {
'''),
        ('''    // strixllama: the disk tier, with the same criteria, only when it would beat what is in RAM
''',
         '''    // strixllama: the disk tier, with the same criteria, only when it would beat what is in RAM. Its checkpoints
    // stay on disk when the caller can page them in (disk_paged holds their pins until the slot takes them); such
    // a state must never stay in the RAM tier, whose entries are complete, so every way out below drops it
    ckpt_paged_map disk_paged;
    bool from_disk = false;
'''),
        ('''        if (server_prompt_cache_state * from_disk = load_from_disk(tokens_new, f_keep_best, f_sim_best)) {
''',
         '''        if (server_prompt_cache_state * s = load_from_disk(tokens_new, f_keep_best, f_sim_best, paged_out ? &disk_paged : nullptr)) {
'''),
        ('''            GGML_ASSERT(&*it_best == from_disk);
''',
         '''            GGML_ASSERT(&*it_best == s);
            from_disk = true;
'''),
        ('''        }
    }

    // strixllama: an entry written while MTP was off carries no draft state, and nothing here can
''',
         '''        }
    }
    auto drop_from_disk = [&]() {
        if (from_disk) {
            states.erase(it_best);
            it_best = states.end();
            ckpt_release(disk_paged);
            from_disk = false;
        }
    };

    // strixllama: an entry written while MTP was off carries no draft state, and nothing here can
'''),
        ('''        states.erase(it_best);
        it_best = states.end();
''',
         '''        if (from_disk) {
            drop_from_disk();
        } else {
            states.erase(it_best);
            it_best = states.end();
        }
'''),
        ('''                SRV_ERR("failed to restore state with size %zu\\n", size);

''',
         '''                SRV_ERR("failed to restore state with size %zu\\n", size);
                drop_from_disk();

'''),
        ('''                    SRV_WRN("failed to restore state with size %zu\\n", size);

''',
         '''                    SRV_WRN("failed to restore state with size %zu\\n", size);
                    drop_from_disk();

'''),
        ('''        states.erase(it_best);
    }
''',
         '''        states.erase(it_best);

        // strixllama: the slot takes the pins of the checkpoints that stayed on disk; a RAM-tier state brings its
        // checkpoints whole
        if (paged_out) {
            *paged_out = from_disk ? std::move(disk_paged) : ckpt_paged_map {};
        }
        from_disk = false;
    }
'''),
        ('''// a whole entry into memory. Chunks and checkpoints are checked against their hashes: a state that is
// wrong in one byte decodes into nonsense, and XXH3 over 5.6 GiB costs ~0.2 s. Throws std::bad_alloc when
// there is no memory for it, which says nothing about the entry.
''',
         '''// chunks are separate files, and one reader leaves the drive idle between them: 2.8 GB/s from one thread
// against 6.5 GB/s from four, measured unbuffered on this machine (eight add nothing)
constexpr int SPC_READERS = 4;

// an entry into memory. Chunks and checkpoints are checked against their hashes: a state that is wrong in
// one byte decodes into nonsense, and XXH3 over 5.6 GiB costs ~0.2 s. With `lazy_ckpts` a version 2 entry's
// checkpoints are left on disk and come back as their headers only (no bytes); the caller pins and pages them.
// Throws std::bad_alloc when there is no memory for it, which says nothing about the entry.
'''),
        ('''                server_prompt_cache_state & state, std::string & why, read_fault & fault) {
''',
         '''                server_prompt_cache_state & state, std::string & why, read_fault & fault, bool lazy_ckpts = false) {
'''),
        ('''        uint64_t off = 0;
        for (const auto & c : refs) {
            if (off + c.size > size) {
''',
         '''        std::vector<uint64_t> offs(refs.size());
        uint64_t off = 0;
        for (size_t i = 0; i < refs.size(); ++i) {
            if (off + refs[i].size > size) {
'''),
        ('''            const int64_t r0 = ggml_time_us();
            const bool ok = f.open(chunk_path(dir, c.hi, c.lo)) && f.read(v.data() + off, c.size);
            f.close();
            g_spc_cost.read_us += ggml_time_us() - r0;
            g_spc_cost.bytes   += c.size;
            const disk_chunk_ref got = ok ? chunk_ref(v.data() + off, c.size) : disk_chunk_ref {};
            if (!ok || got.hi != c.hi || got.lo != c.lo) {
                why = (ok ? "chunk does not match its name: " : "missing chunk ") + chunk_hex(c.hi, c.lo);
                fault.chunk = true;
                fault.hi = c.hi;
                fault.lo = c.lo;
                return false;
''',
         '''            offs[i] = off;
            off += refs[i].size;
        }
        if (off != size) {
            why = "chunk list shorter than the state";
            return false;
        }
        // the chunks land in disjoint ranges of v; each reader has its own staging buffer, and this thread
        // uses the caller's. A reader that cannot get a buffer leaves its share to the others.
        std::atomic<size_t>   next   { 0 };
        std::atomic<bool>     failed { false };
        std::atomic<uint64_t> bytes  { 0 };
        std::mutex            fault_mu;
        auto reader = [&](spc_file * fp) {
            std::unique_ptr<spc_stage> own_st;
            std::unique_ptr<spc_file>  own_f;
            if (!fp) {
                try {
                    own_st = std::make_unique<spc_stage>();
                } catch (const std::bad_alloc &) {
                    return;
                }
                own_f = std::make_unique<spc_file>(*own_st);
                fp = own_f.get();
'''),
        ('''            off += c.size;
''',
         '''            for (size_t i; !failed && (i = next.fetch_add(1)) < refs.size(); ) {
                const auto & c = refs[i];
                const bool ok = fp->open(chunk_path(dir, c.hi, c.lo)) && fp->read(v.data() + offs[i], c.size);
                fp->close();
                const disk_chunk_ref got = ok ? chunk_ref(v.data() + offs[i], c.size) : disk_chunk_ref {};
                if (!ok || got.hi != c.hi || got.lo != c.lo) {
                    std::lock_guard<std::mutex> lk(fault_mu);
                    if (!failed.exchange(true)) {
                        why = (ok ? "chunk does not match its name: " : "missing chunk ") + chunk_hex(c.hi, c.lo);
                        fault.chunk = true;
                        fault.hi = c.hi;
                        fault.lo = c.lo;
                    }
                    return;
                }
                bytes += c.size;
            }
        };
        const int64_t r0 = ggml_time_us();
        std::vector<std::thread> pool;
        for (int t = 1; t < SPC_READERS && (size_t) t < refs.size(); ++t) {
            try {
                pool.emplace_back(reader, nullptr);
            } catch (const std::system_error &) {
                break;                                  // fewer readers, same result
            }
'''),
        ('''        return off == size;
''',
         '''        reader(&f);
        for (auto & t : pool) {
            t.join();
        }
        g_spc_cost.read_us += ggml_time_us() - r0;
        g_spc_cost.bytes   += bytes;
        return !failed;
'''),
        ('''        if (!read_ckpt(f, ckpt_path(dir, k.key), k, c)) {       // its blobs time themselves
''',
         '''        if (lazy_ckpts) {
            c.n_tokens = k.n_tokens;                    // the header: a rewind reads the bytes if it picks this one
            c.pos_min  = k.pos_min;
            c.pos_max  = k.pos_max;
        } else if (!read_ckpt(f, ckpt_path(dir, k.key), k, c)) {       // its blobs time themselves
'''),
        ('''server_prompt_cache_state * server_prompt_cache::load_from_disk(const server_tokens & tokens_new, float & f_keep_best, float & f_sim_best) {
''',
         '''server_prompt_cache_state * server_prompt_cache::load_from_disk(const server_tokens & tokens_new, float & f_keep_best, float & f_sim_best,
                                                                ckpt_paged_map * paged) {
'''),
        ('''    try {
        spc_stage stage;
        ok = read_entry(stage, disk_dir, *best, disk_has_mtmd, state, why, fault);
''',
         '''    // a version 2 entry's checkpoints are objects of their own in the store: when the caller can page them in,
    // they stay there (a 79K-token conversation carries ~3.3 GB of them; a rewind reads one)
    const bool lazy = paged && best->version != (int32_t) SPC_V1;
    try {
        spc_stage stage;
        ok = read_entry(stage, disk_dir, *best, disk_has_mtmd, state, why, fault, lazy);
'''),
        ('''    }
    f_keep_best = best_keep;
''',
         '''    }
    // the checkpoints left on disk are pinned, as a slot pins the ones it pages out: eviction of this entry must not
    // delete one the restored conversation may still rewind to. One the store no longer has is left out.
    size_t n_left = 0;
    if (lazy) {
        paged->clear();
        auto it = state.prompt.checkpoints.begin();
        for (const auto & k : best->ckpts) {
            GGML_ASSERT(it != state.prompt.checkpoints.end() && it->n_tokens == k.n_tokens);
            auto stored = disk_ckpts.find(k.key);
            if (stored == disk_ckpts.end()) {
                it = state.prompt.checkpoints.erase(it);
                continue;
            }
            stored->second.refs++;
            (*paged)[{ k.n_tokens, k.pos_min, k.pos_max }] = k;
            ++n_left;
            ++it;
        }
    }
    f_keep_best = best_keep;
'''),
        ('''    SRV_INF(" - disk cache: read %d tokens (v%d), %.3f GiB in %.0f ms (file %.0f ms at %.0f MB/s, buffers %.0f ms%s; f_keep = %.3f, f_sim = %.3f)\\n",
''',
         '''    SRV_INF(" - disk cache: read %d tokens (v%d), %.3f GiB in %.0f ms (file %.0f ms at %.0f MB/s, buffers %.0f ms%s%s; f_keep = %.3f, f_sim = %.3f)\\n",
'''),
        ('''            g_spc_cost.alloc_us / 1000.0, waited_ms >= 1.0 ? (", waited " + std::to_string((int) waited_ms) + " ms for the writer").c_str() : "",
            f_keep_best, f_sim_best);
''',
         '''            g_spc_cost.alloc_us / 1000.0, waited_ms >= 1.0 ? (", waited " + std::to_string((int) waited_ms) + " ms for the writer").c_str() : "",
            lazy ? (", " + std::to_string(n_left) + " checkpoints left on disk").c_str() : "",
            f_keep_best, f_sim_best);
'''),
    ],
    os.path.join(tree, "tools", "server", "server-context.cpp"): [
        ('''        bool res = prompt_cache.load(prompt, tokens, ctx_tgt, ctx_dft, id, before_restore);
''',
         '''        // an entry restored from the disk tier leaves its checkpoints there, pinned for this slot like paged-out ones
        bool res = prompt_cache.load(prompt, tokens, ctx_tgt, ctx_dft, id, before_restore, &ckpt_paged);
'''),
    ],
}


def main():
    texts = {p: io.open(p, encoding="utf-8").read() for p in EDITS}
    if any(MARKER in t for t in texts.values()):
        print("already applied")
        return
    for p, pairs in EDITS.items():
        for old, new in pairs:
            if texts[p].count(old) != 1:
                sys.exit("anchor found %d times, expected once, in %s" % (texts[p].count(old), p))
            texts[p] = texts[p].replace(old, new, 1)
    for p, t in texts.items():
        io.open(p, "w", encoding="utf-8", newline="").write(t)
    print("patched", ", ".join(os.path.basename(p) for p in EDITS))


if __name__ == "__main__":
    main()
