#!/usr/bin/env python3
"""A slot named by id that holds nothing reads its conversation back from the prompt cache

get_available_slot computes how much of a slot's conversation a request keeps as f_sim * n_prompt / n_slot, and saves and reloads through the prompt cache when that is under half. For a slot named by id that holds nothing - emptied to make room for another conversation - that is 0/0, a NaN, which compares false: the prompt cache was never asked, and a 173K-token conversation sent back to its slot was processed again from its first token (186 s) although the disk tier held all of it. An empty slot now keeps nothing, so it takes the cache path.

Generated by tools/make_patch_script.py from the tree it must reproduce, so every anchor is
unique by construction. 1 hunks across 1 file(s).

Usage: python D:/Work/strixllama/patches/apply_empty_slot_cache.py [tree]
"""
import io
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
tree = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "src", "llama.cpp")
MARKER = 'a slot named by id that holds nothing has nothing to keep'

EDITS = {
    os.path.join(tree, "tools", "server", "server-context.cpp"): [
        ('''                const float f_keep = (f_sim_best*task.tokens.size()) / ret->prompt.tokens.size();
''',
         '''                // strixllama: a slot named by id that holds nothing has nothing to keep - 0/0 here was a NaN, which
                // compares false, so such a slot skipped the prompt cache and a long conversation sent back to its
                // emptied slot was processed again from its first token instead of read back from the disk tier
                const float f_keep = ret->prompt.tokens.empty() ? 0.0f :
                    (f_sim_best*task.tokens.size()) / ret->prompt.tokens.size();
'''),
    ],
}


def main():
    texts = {p: io.open(p, encoding="utf-8").read() for p in EDITS}
    if any(MARKER in t for t in texts.values()):
        print("already applied")
        return
    for p, pairs in EDITS.items():
        for old, new in pairs:
            if texts[p].count(old) != 1:
                sys.exit("anchor found %d times, expected once, in %s" % (texts[p].count(old), p))
            texts[p] = texts[p].replace(old, new, 1)
    for p, t in texts.items():
        io.open(p, "w", encoding="utf-8", newline="").write(t)
    print("patched", ", ".join(os.path.basename(p) for p in EDITS))


if __name__ == "__main__":
    main()
