#!/usr/bin/env python3
"""Sparse attention for a ubatch that serves several slots: mixed-sequence decode and prefill stay on the sparse path.

With more than one slot the server's equal-length split puts several sequences in one ubatch. The sparse path declined those (one sequence per ubatch), so they fell back to dense attention over the whole pool - four users 35K deep decoded slower together than one alone - and the reserve graph, being mixed, kept a dense f16 mask of n_ctx x ubatch (2-4 GiB) plus a 1-2 GiB block bias. Now: the block-key cache's gap check is per sequence (it tripped on any multi-stream decode and stayed off for every stream); the decode gather batches every query on the kernel's sequence axis with f16 rows (one gather and one flash-attention call per layer instead of one per query, so a 16-query verify step stays sparse); and a compact ubatch of several sequences carries which sequence owns each block as a 0/1 membership matrix the scorer multiplies with the token's one-hot slot, so mixed decode and mixed prefill take the same compact, maskless path as a single sequence and the mixed reserve needs no dense mask at all: four slots at 262144 x 8192 load and cost 1.3 GB over one.

Generated by tools/make_patch_script.py from the tree it must reproduce, so every anchor is
unique by construction. 38 hunks across 4 file(s).

Usage: python patches/apply_multi_stream_qsa.py [tree]
"""
import io
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
tree = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "src", "llama.cpp")
MARKER = 'qsa_mixed_inputs'

EDITS = {
    os.path.join(tree, "src", "llama-memory-hybrid-idx.h"): [
        ('''    };
    void set_input_qsa(ggml_tensor * cell_blk, ggml_tensor * blk_cells, ggml_tensor * blk_pos,
''',
         '''    };
    // strixllama: a compact ubatch that serves several sequences (unified cache, equal-length split).
    // The position half of the visibility stays in `bias`; which sequence owns a block is a 0/1
    // membership matrix the scorer multiplies with the token's one-hot sequence slot (block-graph.inc):
    //   seq_blk F32 [n_seqs_unq, n_blocks]  1 where the block's cells belong to that sequence
    //   seq_tok F32 [n_seqs_unq, n_tokens]  one-hot slot of each token's sequence (ubatch.seq_idx)
    // Slots are the ubatch's own numbering (seq_id_unq), so the graph shape depends only on their count.
    struct qsa_mixed_inputs {
        ggml_tensor * seq_blk = nullptr;
        ggml_tensor * seq_tok = nullptr;
    };
    void set_input_qsa(ggml_tensor * cell_blk, ggml_tensor * blk_cells, ggml_tensor * blk_pos,
'''),
        ('''                             const llama_ubatch * ubatch, uint32_t ratio, const qsa_kb_inputs * kb = nullptr) const;
''',
         '''                             const llama_ubatch * ubatch, uint32_t ratio, const qsa_kb_inputs * kb = nullptr,
                             const qsa_mixed_inputs * mixed = nullptr) const;
'''),
        ('''                            const qsa_kb_inputs * kb) const;
''',
         '''                            const qsa_kb_inputs * kb, const qsa_mixed_inputs * mixed = nullptr) const;
'''),
        ('''                             const llama_memory_hybrid_idx::qsa_kb_inputs * kb = nullptr) const;
''',
         '''                             const llama_memory_hybrid_idx::qsa_kb_inputs * kb = nullptr,
                             const llama_memory_hybrid_idx::qsa_mixed_inputs * mixed = nullptr) const;
'''),
    ],
    os.path.join(tree, "src", "llama-memory-hybrid-idx.cpp"): [
        ('''#include <algorithm>
#include <cassert>
''',
         '''#include <algorithm>
#include <bitset>
#include <cassert>
'''),
        ('''        {
            std::map<llama_seq_id, llama_pos> next_pos;
''',
         '''        {
            // strixllama: per token and per sequence. A ubatch that serves several slots at once
            // (unified cache, equal-length split) carries tokens of several sequences, so its first
            // and last tokens belong to different sequences; comparing them as one made the flag
            // trip on any multi-stream decode, and it is sticky, so the block-key cache then stayed
            // off for every sequence, single streams included (measured: ROPE and GET_ROWS over
            // every block of the pool back in each step, 8% slower single-stream decode).
            std::map<llama_seq_id, llama_pos> next_pos;
'''),
        ('''                if (ub.n_tokens == 0 || !ub.pos || !ub.seq_id || !ub.seq_id[0]) {
''',
         '''                if (ub.n_tokens == 0 || !ub.pos || !ub.seq_id) {
'''),
        ('''                const llama_seq_id s  = ub.seq_id[0][0];
                const auto         it = next_pos.find(s);
                const llama_pos    expect = it != next_pos.end()
                    ? it->second
                    : get_mem_attn()->seq_pos_max(s) + 1;
                if (ub.pos[0] > expect) {
''',
         '''                bool gap = false;
                for (uint32_t i = 0; i < ub.n_tokens && !gap; ++i) {
                    if (!ub.seq_id[i]) {
                        continue;
                    }
                    const llama_seq_id s  = ub.seq_id[i][0];
                    const auto         it = next_pos.find(s);
                    const llama_pos    expect = it != next_pos.end()
                        ? it->second
                        : get_mem_attn()->seq_pos_max(s) + 1;
                    gap = ub.pos[i] > expect;
                    next_pos[s] = ub.pos[i] + 1;
                }
                if (gap) {
'''),
        ('''                next_pos[s] = ub.pos[ub.n_tokens - 1] + 1;
''',
         ''''''),
        ('''        ggml_tensor * bias, ggml_tensor * tail_idxs, const llama_ubatch * ubatch, uint32_t ratio, const qsa_kb_inputs * kb) const {
    set_input_qsa_impl(cell_blk, blk_cells, blk_pos, bias, tail_idxs, ubatch, ratio, true, kb);
''',
         '''        ggml_tensor * bias, ggml_tensor * tail_idxs, const llama_ubatch * ubatch, uint32_t ratio, const qsa_kb_inputs * kb, const qsa_mixed_inputs * mixed) const {
    set_input_qsa_impl(cell_blk, blk_cells, blk_pos, bias, tail_idxs, ubatch, ratio, true, kb, mixed);
'''),
        ('''        const qsa_kb_inputs * kb) const {
''',
         '''        const qsa_kb_inputs * kb,
        const qsa_mixed_inputs * mixed) const {
'''),
        ('''    int32_t * limits = compact ? (int32_t *) bias->data : nullptr;
    if (compact) {
''',
         '''    int32_t * limits = compact ? (int32_t *) bias->data : nullptr;
    // strixllama: several sequences in one compact ubatch - the membership inputs carry the sequence half
    const bool mixed_seqs = compact && mixed != nullptr && mixed->seq_blk != nullptr && mixed->seq_tok != nullptr;
    if (compact) {
'''),
        ('''        for (int64_t i=0;i<n_tokens;++i) { GGML_ASSERT(ubatch->seq_id[i][0] == ubatch->seq_id[0][0]); }
''',
         '''        if (mixed_seqs) {
            GGML_ASSERT(ubatch->seq_idx && ubatch->seq_id_unq && ubatch->n_seqs_unq >= 1);
            GGML_ASSERT(mixed->seq_blk->type == GGML_TYPE_F32 && mixed->seq_tok->type == GGML_TYPE_F32);
            GGML_ASSERT(mixed->seq_blk->ne[0] == ubatch->n_seqs_unq && mixed->seq_blk->ne[1] == n_blocks);
            GGML_ASSERT(mixed->seq_tok->ne[0] == ubatch->n_seqs_unq && mixed->seq_tok->ne[1] == n_tps);
            GGML_ASSERT(mixed->seq_blk->data && mixed->seq_tok->data);
        } else {
            for (int64_t i=0;i<n_tokens;++i) { GGML_ASSERT(ubatch->seq_id[i][0] == ubatch->seq_id[0][0]); }
        }
'''),
        ('''                limits[b] = b<n_bid && cells.seq_has((uint32_t)bid_cell[b],seq) ? bid_idx[b] : INT32_MAX;
''',
         '''                // with several sequences the position half stays per block and the ownership goes to seq_blk
                limits[b] = b<n_bid && (mixed_seqs || cells.seq_has((uint32_t)bid_cell[b],seq)) ? bid_idx[b] : INT32_MAX;
            }
            if (mixed_seqs) {
                const int64_t n_slots = mixed->seq_blk->ne[0];
                float * sb = (float *) mixed->seq_blk->data;
                float * st = (float *) mixed->seq_tok->data;
                std::fill(sb, sb + n_slots*n_blocks, 0.0f);
                std::fill(st, st + n_slots*n_tps,    0.0f);
                for (int32_t b = 0; b < n_bid; ++b) {
                    const auto & owners = cells.seq_get_all((uint32_t) bid_cell[b]);
                    for (int64_t sl = 0; sl < n_slots; ++sl) {
                        if (owners.test(ubatch->seq_id_unq[sl])) { sb[b*n_slots + sl] = 1.0f; }
                    }
                }
                for (int64_t ii = 0; ii < n_tps; ++ii) {
                    const int32_t sl = ubatch->seq_idx[ubatch->seq_id[ii][0]];
                    GGML_ASSERT(sl >= 0 && sl < n_slots);
                    st[ii*n_slots + sl] = 1.0f;
                }
'''),
        ('''        const llama_memory_hybrid_idx::qsa_kb_inputs * kb) const {
    GGML_ASSERT(mem != nullptr);
    mem->set_input_qsa_blocks(cell_blk, blk_cells, blk_pos, bias, tail_idxs, ubatch, ratio, kb);
''',
         '''        const llama_memory_hybrid_idx::qsa_kb_inputs * kb,
        const llama_memory_hybrid_idx::qsa_mixed_inputs * mixed) const {
    GGML_ASSERT(mem != nullptr);
    mem->set_input_qsa_blocks(cell_blk, blk_cells, blk_pos, bias, tail_idxs, ubatch, ratio, kb, mixed);
'''),
        ('''    const llama_seq_id seq=ubatch.seq_id[0][0];
    for (uint32_t i=0;i<ubatch.n_tokens;++i) {
        if (ubatch.n_seq_id[i]<1 || !ubatch.seq_id[i] || ubatch.seq_id[i][0]!=seq ||
''',
         '''    // strixllama: several sequences in one ubatch are fine (set_input_qsa_impl's membership inputs carry
    // which sequence owns a block) as long as every token names exactly one and no image or gap has
    // been written: those cells need the ranked enumeration, which only a single-sequence ubatch gets.
    const llama_seq_id seq=ubatch.seq_id[0][0];
    std::bitset<LLAMA_MAX_SEQ> seqs;
    for (uint32_t i=0;i<ubatch.n_tokens;++i) {
        if (ubatch.n_seq_id[i]<1 || !ubatch.seq_id[i] || ubatch.seq_id[i][0]<0 || ubatch.seq_id[i][0]>=LLAMA_MAX_SEQ ||
'''),
        ('''                ubatch.pos[i]<0 || ubatch.pos[i]>=16777216) { return false; }
        for (uint32_t axis=1;axis<ubatch.n_pos;++axis) {
''',
         '''                ubatch.pos[i]<0 || ubatch.pos[i]>=16777216) { return false; }
        if (ubatch.seq_id[i][0]!=seq && ubatch.n_seq_id[i]!=1) { return false; }
        seqs.set(ubatch.seq_id[i][0]);
        for (uint32_t axis=1;axis<ubatch.n_pos;++axis) {
'''),
        ('''            if (ubatch.pos[i+axis*ubatch.n_tokens]!=ubatch.pos[i]) { return false; }
        }
''',
         '''            if (ubatch.pos[i+axis*ubatch.n_tokens]!=ubatch.pos[i]) { return false; }
        }
    }
    if (seqs.count()>1) {
        if (mem->kb_pos_dup() || !ubatch.seq_idx || !ubatch.seq_id_unq || ubatch.n_seqs_unq!=seqs.count()) { return false; }
        for (uint32_t i=0;i<ubatch.n_tokens;++i) {
            if (ubatch.n_seq_id[i]!=1 || ubatch.seq_idx[ubatch.seq_id[i][0]]<0) { return false; }
        }
'''),
        ('''            if (!cells.is_empty(j) && cells.seq_has(j,seq) && cells.ext_get(j).is_2d_gt(cells.pos_get(j),cells.pos_get(j))) { return false; }
''',
         '''            if (!cells.is_empty(j) && (cells.seq_get_all(j) & seqs).any() && cells.ext_get(j).is_2d_gt(cells.pos_get(j),cells.pos_get(j))) { return false; }
'''),
    ],
    os.path.join(tree, "src", "models", "block-graph.inc"): [
        ('''        ggml_tensor *limits,int64_t blocks,int64_t first,int64_t queries) {
''',
         '''        ggml_tensor *limits,int64_t blocks,int64_t first,int64_t queries,
        ggml_tensor *seq_blk=nullptr,ggml_tensor *seq_tok=nullptr) {
'''),
        ('''    auto *visible=ggml_step(ctx,ggml_sub(ctx,ggml_repeat(ctx,tails,score),starts));
    return ggml_add(ctx,score,ggml_log(ctx,visible));
''',
         '''    auto *visible=ggml_step(ctx,ggml_sub(ctx,ggml_repeat(ctx,tails,score),starts));
    if (seq_blk) {
        // strixllama: several sequences in the ubatch - a block is visible only to the sequence that owns it.
        // membership = seq_blk^T seq_tok is exactly 0 or 1 per (block, token); f16 for the key side so the
        // product takes the same kernel as the indexer score (an f32 x f32 mul_mat is not exercised here)
        GGML_ASSERT(seq_tok && seq_blk->ne[0]==seq_tok->ne[0] && seq_blk->ne[1]>=score->ne[0] && seq_tok->ne[1]>=first+queries);
        const int64_t n_slots=seq_blk->ne[0];
        auto *blk=ggml_cast(ctx,ggml_view_2d(ctx,seq_blk,n_slots,score->ne[0],seq_blk->nb[1],0),GGML_TYPE_F16);
        auto *tok=ggml_view_2d(ctx,seq_tok,n_slots,queries,seq_tok->nb[1],first*seq_tok->nb[1]);
        auto *member=ggml_mul_mat(ctx,blk,tok);
        visible=ggml_mul(ctx,visible,ggml_step(ctx,ggml_scale_bias(ctx,member,1.0f,-0.5f)));
    }
    return ggml_add(ctx,score,ggml_log(ctx,visible));
'''),
    ],
    os.path.join(tree, "src", "models", "qwen4exp.cpp"): [
        ('''            mctx->set_input_qsa_blocks(cell_blk, blk_cells, blk_pos, bias, tail_idxs, ubatch, ratio, kbp);
''',
         '''            llama_memory_hybrid_idx::qsa_mixed_inputs mx;
            mx.seq_blk = seq_blk; mx.seq_tok = seq_tok;
            mctx->set_input_qsa_blocks(cell_blk, blk_cells, blk_pos, bias, tail_idxs, ubatch, ratio, kbp, seq_blk ? &mx : nullptr);
'''),
        ('''                params.ubatch.n_tokens/n_stream >= 128);
        if (tail_idxs) { res &= tail_idxs->ne[1] == params.ubatch.n_tokens/n_stream; }
''',
         '''                params.ubatch.n_tokens/n_stream >= 128);
        // strixllama: the membership inputs exist for a compact ubatch of several sequences, sized by their count
        res &= (seq_blk != nullptr) == (compact && params.ubatch.n_seqs_unq > 1);
        if (seq_blk) {
            res &= seq_blk->ne[0] == params.ubatch.n_seqs_unq && seq_blk->ne[1] == n_blocks;
            res &= seq_tok->ne[0] == params.ubatch.n_seqs_unq && seq_tok->ne[1] == params.ubatch.n_tokens/n_stream;
        }
        if (tail_idxs) { res &= tail_idxs->ne[1] == params.ubatch.n_tokens/n_stream; }
'''),
        ('''            if (kb_dirty_dst) { res &= kb_dirty_dst->ne[0] == params.ubatch.n_tokens/n_stream/ratio + 4; }
''',
         '''            if (kb_dirty_dst) { res &= kb_dirty_dst->ne[0] == params.ubatch.n_tokens/n_stream/ratio + 2*(int64_t) params.ubatch.n_seqs_unq + 2; }
'''),
        ('''    ggml_tensor * tail_idxs = nullptr;
    bool compact = false;
''',
         '''    ggml_tensor * tail_idxs = nullptr;
    // strixllama: several sequences in a compact ubatch (llama_memory_hybrid_idx::qsa_mixed_inputs)
    ggml_tensor * seq_blk = nullptr;   // F32 [n_seqs_unq, n_blocks]
    ggml_tensor * seq_tok = nullptr;   // F32 [n_seqs_unq, n_tokens/n_stream]
    bool compact = false;
'''),
        ('''        }
        // strixllama: block-key cache inputs (llama_memory_hybrid_idx::qsa_kb_inputs); single stream, 1-D
''',
         '''        }
        // strixllama: a compact ubatch of several sequences (unified cache, several slots decoding or
        // prefilling in one step) carries the block ownership as membership inputs; this is what keeps
        // the mixed-sequence graph - the reserve graph included - off the dense n_kv x n_tokens mask
        if (qsa->compact && ubatch.n_seqs_unq > 1) {
            qsa->seq_blk = ggml_new_tensor_2d(ctx0, GGML_TYPE_F32, ubatch.n_seqs_unq, n_blocks);
            qsa->seq_tok = ggml_new_tensor_2d(ctx0, GGML_TYPE_F32, ubatch.n_seqs_unq, n_tps);
            ggml_set_input(qsa->seq_blk);
            ggml_set_input(qsa->seq_tok);
        }
        // strixllama: block-key cache inputs (llama_memory_hybrid_idx::qsa_kb_inputs); single stream, 1-D
'''),
        ('''            const int64_t dirty_max = n_tps/r + 4;
''',
         '''            // strixllama: a ubatch of several sequences can complete up to two blocks per sequence
            const int64_t dirty_max = n_tps/r + 2*(int64_t) ubatch.n_seqs_unq + 2;
'''),
        ('''            score = qwen4exp_apply_compact_visibility(ctx0,score,inp->bias,n_blocks,first,n_query);
''',
         '''            score = qwen4exp_apply_compact_visibility(ctx0,score,inp->bias,n_blocks,first,n_query,inp->seq_blk,inp->seq_tok);
'''),
        ('''//
// This makes decode sparse, which is what the model intends and what prefill already does; it is not
''',
         '''//
// All queries go through one gather and one flash-attention call: the queries sit on the kernel's
// sequence axis (ne[3]), each with its own K/V slab and mask row, so the node count does not grow
// with the batch. That is what lets a ubatch that serves several slots (4 streams x 4 verify tokens
// = 16 queries) stay on this path instead of falling back to dense attention over the whole pool.
// The gathered rows stay f16: ggml_get_rows only offers an f32 result, which doubled the traffic
// (read f16, write f32, read f32, write f16) - the CUDA kernel casts to whatever the destination
// is, so the node is built here with an f16 destination.
//
// This makes decode sparse, which is what the model intends and what prefill already does; it is not
'''),
        ('''// bit-identical to the dense decode it replaces.
static ggml_tensor * qwen4exp_gather_attn(ggml_context * ctx0, ggml_tensor * q, ggml_tensor * k,
''',
         '''// bit-identical to the dense decode it replaces.
static ggml_tensor * qwen4exp_get_rows_f16(ggml_context * ctx, ggml_tensor * a, ggml_tensor * b) {
    GGML_ASSERT(a->type == GGML_TYPE_F16 && b->type == GGML_TYPE_I32 && b->ne[1] == 1 && b->ne[2] == 1 && b->ne[3] == 1);
    ggml_tensor * result = ggml_new_tensor_2d(ctx, GGML_TYPE_F16, a->ne[0], b->ne[0]);
    result->op     = GGML_OP_GET_ROWS;
    result->src[0] = a;
    result->src[1] = b;
    return result;
}

static ggml_tensor * qwen4exp_gather_attn(ggml_context * ctx0, ggml_tensor * q, ggml_tensor * k,
'''),
        ('''
    // [head_k, n_head_kv, n_kv] -> [head_k*n_head_kv, n_kv], so a cell is one row
''',
         '''
    GGML_ASSERT(ggml_is_contiguous(top_k) && top_k->ne[1] >= n_query);

    // [head_k, n_head_kv, n_kv] -> [head_k*n_head_kv, n_kv], so a cell is one row
'''),
        ('''    ggml_tensor * out = nullptr;
    for (int64_t qi = 0; qi < n_query; ++qi) {
        ggml_tensor * idx = ggml_cont(ctx0, ggml_view_2d(ctx0, top_k, width, 1, top_k->nb[1], qi*top_k->nb[1]));
''',
         '''    // every query's selection at once: [width, n_query] -> [n_sel, n_query]
    ggml_tensor * idx = ggml_view_2d(ctx0, top_k, width, n_query, top_k->nb[1], 0);
'''),
        ('''        // shift by one so "no cell" (-1) becomes 0 and the zero padding means the same thing
        ggml_tensor * shifted = ggml_pad(ctx0, ggml_scale_bias(ctx0, ggml_cast(ctx0, idx, GGML_TYPE_F32), 1.0f, 1.0f),
                (int) (n_sel - width), 0, 0, 0);
        ggml_tensor * valid = ggml_step(ctx0, shifted);
        ggml_tensor * rows  = ggml_cast(ctx0, ggml_relu(ctx0, ggml_scale_bias(ctx0, shifted, 1.0f, -1.0f)), GGML_TYPE_I32);
        ggml_tensor * mask  = ggml_cast(ctx0, ggml_log(ctx0, valid), GGML_TYPE_F16);   // 0 where selected, -inf elsewhere
        mask = ggml_cont(ctx0, ggml_reshape_4d(ctx0, mask, n_sel, 1, 1, 1));
''',
         '''    // shift by one so "no cell" (-1) becomes 0 and the zero padding means the same thing
    ggml_tensor * shifted = ggml_pad(ctx0, ggml_scale_bias(ctx0, ggml_cast(ctx0, idx, GGML_TYPE_F32), 1.0f, 1.0f),
            (int) (n_sel - width), 0, 0, 0);
    ggml_tensor * valid = ggml_step(ctx0, shifted);
    ggml_tensor * rows  = ggml_cast(ctx0, ggml_relu(ctx0, ggml_scale_bias(ctx0, shifted, 1.0f, -1.0f)), GGML_TYPE_I32);
    rows = ggml_reshape_1d(ctx0, rows, n_sel*n_query);
    ggml_tensor * mask  = ggml_cast(ctx0, ggml_log(ctx0, valid), GGML_TYPE_F16);   // 0 where selected, -inf elsewhere
    mask = ggml_cont(ctx0, ggml_reshape_4d(ctx0, mask, n_sel, 1, 1, n_query));
'''),
        ('''        ggml_tensor * kg = ggml_cast(ctx0, ggml_get_rows(ctx0, k2d, rows), GGML_TYPE_F16);
        ggml_tensor * vg = ggml_cast(ctx0, ggml_get_rows(ctx0, v2d, rows), GGML_TYPE_F16);
        kg = ggml_permute(ctx0, ggml_reshape_3d(ctx0, kg, head_k,    n_head_kv, n_sel), 0, 2, 1, 3);
        vg = ggml_permute(ctx0, ggml_reshape_3d(ctx0, vg, v->ne[0], n_head_kv, n_sel), 0, 2, 1, 3);
''',
         '''    // one K/V slab per query on the sequence axis: [head, n_sel, n_head_kv, n_query]
    ggml_tensor * kg = qwen4exp_get_rows_f16(ctx0, k2d, rows);
    ggml_tensor * vg = qwen4exp_get_rows_f16(ctx0, v2d, rows);
    kg = ggml_permute(ctx0, ggml_reshape_4d(ctx0, kg, head_k,    n_head_kv, n_sel, n_query), 0, 2, 1, 3);
    vg = ggml_permute(ctx0, ggml_reshape_4d(ctx0, vg, v->ne[0], n_head_kv, n_sel, n_query), 0, 2, 1, 3);
'''),
        ('''        // q is [head_k, n_head_q, n_query]; one query at a time, laid out as the kernel wants
        ggml_tensor * q1 = ggml_permute(ctx0, ggml_view_3d(ctx0, q, q->ne[0], q->ne[1], 1,
                q->nb[1], q->nb[2], qi*q->nb[2]), 0, 2, 1, 3);
''',
         '''    // q is [head_k, n_head_q, n_query]; one query per sequence, laid out as the kernel wants
    ggml_tensor * q4 = ggml_permute(ctx0, ggml_view_4d(ctx0, q, q->ne[0], q->ne[1], 1, n_query,
            q->nb[1], q->nb[2], q->nb[2], 0), 0, 2, 1, 3);
'''),
        ('''        ggml_tensor * cur = ggml_flash_attn_ext(ctx0, q1, kg, vg, mask, kq_scale, 0.0f, 0.0f);
        ggml_flash_attn_ext_set_prec(cur, GGML_PREC_F32);
        out = out ? ggml_concat(ctx0, out, cur, 2) : cur;
    }
    return out;
''',
         '''    ggml_tensor * cur = ggml_flash_attn_ext(ctx0, q4, kg, vg, mask, kq_scale, 0.0f, 0.0f);
    ggml_flash_attn_ext_set_prec(cur, GGML_PREC_F32);
    return cur;   // [head_v, n_head_q, 1, n_query]
'''),
        ('''        }();
        static const int64_t gather_max_t = []() {
''',
         '''        }();
        // 32 covers eight slots verifying a draft of 3 each; above that the gather reads more than it saves
        static const int64_t gather_max_t = []() {
'''),
        ('''            return e ? (int64_t) atoll(e) : (int64_t) 8;
''',
         '''            return e ? (int64_t) atoll(e) : (int64_t) 32;
'''),
    ],
}


def main():
    texts = {p: io.open(p, encoding="utf-8").read() for p in EDITS}
    if any(MARKER in t for t in texts.values()):
        print("already applied")
        return
    for p, pairs in EDITS.items():
        for old, new in pairs:
            if texts[p].count(old) != 1:
                sys.exit("anchor found %d times, expected once, in %s" % (texts[p].count(old), p))
            texts[p] = texts[p].replace(old, new, 1)
    for p, t in texts.items():
        io.open(p, "w", encoding="utf-8", newline="").write(t)
    print("patched", ", ".join(os.path.basename(p) for p in EDITS))


if __name__ == "__main__":
    main()
