#!/usr/bin/env python3
"""The drafts of one speculative step are the same length for every conversation

The target's hybrid memory splits a batch into ubatches with the same number of tokens for every sequence, so when several conversations drafted 2, 2 and 1 tokens the verify ran as two or three passes of the whole model, each a graph the HIP graph cache had not seen (a rebuild of ~28 ms and 8500 separate launches): 200-440 ms where an even batch takes ~120. With three conversations at 4K tokens that made MTP slower than no drafting (28.1 against 43.9 tok/s summed). The MTP drafter keeps a sequence that turns unconfident drafting while another is still confident and cuts all to the longest confident run; the server cuts every draft to the shortest when a generating slot drafted nothing, unless one replays accepted tokens. Three conversations 28.1 -> 44.3 tok/s, two 25.9-35.8 -> 42.7 (4K tokens each); at 20K 39.6 -> 44.1 and 39.6-42.4 -> 41.5. One conversation is unchanged. STRIX_SPEC_EVEN_DRAFTS=0 drafts as before.

Generated by tools/make_patch_script.py from the tree it must reproduce, so every anchor is
unique by construction. 6 hunks across 2 file(s).

Usage: python D:/Work/strixllama/patches/apply_spec_even_drafts.py [tree]
"""
import io
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
tree = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "src", "llama.cpp")
MARKER = 'STRIX_SPEC_EVEN_DRAFTS'

EDITS = {
    os.path.join(tree, "common", "speculative.cpp"): [
        ('''            }
        }

        int i = 0;

        while (n_drafting > 0) {
''',
         '''            }
        }

        // strixllama: several sequences drafting at once draft the same number of tokens (STRIX_SPEC_EVEN_DRAFTS=0: each
        // stops at its own first unconfident token, as upstream). The target's hybrid memory splits a batch into
        // ubatches of equal tokens per sequence, so drafts of 2, 2 and 1 tokens made the verify three passes of the
        // whole model, each a graph the HIP graph cache had not seen: 200-440 ms where an even batch takes ~120. A
        // sequence that turns unconfident keeps drafting while another is still confident, and all are cut to the
        // longest confident run.
        static const bool even_env = !getenv("STRIX_SPEC_EVEN_DRAFTS") || atoi(getenv("STRIX_SPEC_EVEN_DRAFTS")) != 0;
        const bool even = even_env && n_drafting > 1;
        std::vector<bool> confident(n_seq, true);
        std::vector<int>  conf_len(n_seq, 0);
        int n_confident = n_drafting;

        int i = 0;

        while (n_drafting > 0) {
'''),
        ('''                // only collect very high-confidence draft tokens
                if (cur_p->data[0].p < params.p_min) {
                    drafting[seq_id] = false;
                    n_drafting--;

                    continue;
                }

                common_sampler_accept(smpl, id, true);

                auto & dp = dparams.at(seq_id);
                auto & result = *dp.result;

                result.push_back(id);

                // strixllama: the caller's cap as well (dp.n_max, which the server lowers when several slots
''',
         '''                // only collect very high-confidence draft tokens
                if (cur_p->data[0].p < params.p_min) {
                    if (!even) {
                        drafting[seq_id] = false;
                        n_drafting--;

                        continue;
                    }
                    // an unconfident sequence pads this step; the end of the step stops all once none is confident
                    if (confident[seq_id]) {
                        confident[seq_id] = false;
                        n_confident--;
                    }
                }

                common_sampler_accept(smpl, id, true);

                auto & dp = dparams.at(seq_id);
                auto & result = *dp.result;

                result.push_back(id);
                if (confident[seq_id]) {
                    conf_len[seq_id] = (int) result.size();
                }

                // strixllama: the caller's cap as well (dp.n_max, which the server lowers when several slots
'''),
        ('''                if (params.n_max <= (int) result.size() || (dp.n_max > 0 && dp.n_max <= (int) result.size())) {
                    drafting[seq_id] = false;
                    n_drafting--;
                    continue;
                }

''',
         '''                if (params.n_max <= (int) result.size() || (dp.n_max > 0 && dp.n_max <= (int) result.size())) {
                    drafting[seq_id] = false;
                    n_drafting--;
                    if (even && confident[seq_id]) {
                        confident[seq_id] = false;
                        n_confident--;
                    }
                    continue;
                }

'''),
        ('''                i_last[seq_id] = batch.n_tokens - 1;
            }

            if (batch.n_tokens == 0) {
                break;
            }

''',
         '''                i_last[seq_id] = batch.n_tokens - 1;
            }

            if (batch.n_tokens == 0 || (even && n_confident == 0)) {
                break;
            }

'''),
        ('''            llama_set_nextn_layer_offset(ctx_dft, 0); // restore default for non-draft decodes
        }
''',
         '''            llama_set_nextn_layer_offset(ctx_dft, 0); // restore default for non-draft decodes
        }

        if (even) {
            // every draft cut to the longest confident run (and to the shortest draft, when a caller's cap ended one)
            int len = 0;
            for (llama_seq_id seq_id = 0; seq_id < (llama_seq_id) n_seq; ++seq_id) {
                if (dparams[seq_id].drafting) {
                    len = std::max(len, conf_len[seq_id]);
                }
            }
            for (llama_seq_id seq_id = 0; seq_id < (llama_seq_id) n_seq; ++seq_id) {
                if (dparams[seq_id].drafting) {
                    len = std::min(len, (int) dparams[seq_id].result->size());
                }
            }
            for (llama_seq_id seq_id = 0; seq_id < (llama_seq_id) n_seq; ++seq_id) {
                if (dparams[seq_id].drafting && (int) dparams[seq_id].result->size() > len) {
                    dparams[seq_id].result->resize(len);
                }
            }
        }
'''),
    ],
    os.path.join(tree, "tools", "server", "server-context.cpp"): [
        ('''
        // make checkpoints if needed
''',
         '''
        // strixllama: the drafter makes the drafts of one step the same length (STRIX_SPEC_EVEN_DRAFTS); a generating slot
        // that drafted nothing this step (its cap ran out, it cannot speculate) would still make the verify batch
        // uneven, and the hybrid memory would run it as several passes of the whole model. Every draft is cut to the
        // shortest, unless a slot replays tokens it has already accepted.
        if (spec && generating.size() > 1) {
            static const bool even = !getenv("STRIX_SPEC_EVEN_DRAFTS") || atoi(getenv("STRIX_SPEC_EVEN_DRAFTS")) != 0;
            bool replay = false;
            size_t len = SIZE_MAX;
            for (const server_slot * s : generating) {
                replay = replay || s->spec_is_replay;
                len = std::min(len, s->spec_draft.size());
            }
            if (even && !replay) {
                for (server_slot * s : generating) {
                    if (s->spec_draft.size() > len) {
                        s->spec_draft.resize(len);
                    }
                }
            }
        }

        // make checkpoints if needed
'''),
    ],
}


def main():
    texts = {p: io.open(p, encoding="utf-8").read() for p in EDITS}
    if any(MARKER in t for t in texts.values()):
        print("already applied")
        return
    for p, pairs in EDITS.items():
        for old, new in pairs:
            if texts[p].count(old) != 1:
                sys.exit("anchor found %d times, expected once, in %s" % (texts[p].count(old), p))
            texts[p] = texts[p].replace(old, new, 1)
    for p, t in texts.items():
        io.open(p, "w", encoding="utf-8", newline="").write(t)
    print("patched", ", ".join(os.path.basename(p) for p in EDITS))


if __name__ == "__main__":
    main()
