#!/usr/bin/env python3
"""STRIX_STATE_HASH and STRIX_V3_VERIFY: hashes of a slot's state, and restored runs read back

Debugging aids, off unless set. STRIX_STATE_HASH logs XXH3 hashes of a slot's recurrent state and of its whole state as a task starts, after every prompt batch, and as a conversation leaves for the disk tier: two runs that should agree are compared batch by batch, which is how a restored conversation that parted from a resident one was traced to one batch and one query row. STRIX_V3_VERIFY reads every run the disk tier restores back out of the cache and checks it against the hash it is named by.

Generated by tools/make_patch_script.py from the tree it must reproduce, so every anchor is
unique by construction. 5 hunks across 2 file(s).

Usage: python D:/Work/strixllama/patches/apply_state_hash_debug.py [tree]
"""
import io
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
tree = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "src", "llama.cpp")
MARKER = 'STRIX_STATE_HASH'

EDITS = {
    os.path.join(tree, "tools", "server", "server-context.cpp"): [
        ('''#include "mtmd-helper.h"

''',
         '''#include "mtmd-helper.h"
#define XXH_INLINE_ALL
#include "vendor/hash/xxhash/xxhash.h"

'''),
        ('''                end_ckpt.update_tgt(ctx_tgt, id, LLAMA_STATE_SEQ_FLAGS_PARTIAL_ONLY);
                end_ckpt.update_dft(ctx_dft, id, LLAMA_STATE_SEQ_FLAGS_PARTIAL_ONLY);
''',
         '''                end_ckpt.update_tgt(ctx_tgt, id, LLAMA_STATE_SEQ_FLAGS_PARTIAL_ONLY);
                if (getenv("STRIX_STATE_HASH")) {
                    SLT_INF(*this, "STATE_HASH end state as it leaves: %zu bytes, %016llx (%lld tokens)\\n", end_ckpt.data_tgt.size(),
                            (unsigned long long) XXH3_64bits(end_ckpt.data_tgt.data(), end_ckpt.data_tgt.size()), (long long) n_entry);
                }
                end_ckpt.update_dft(ctx_dft, id, LLAMA_STATE_SEQ_FLAGS_PARTIAL_ONLY);
'''),
        ('''    void print_timings_pp() const {
        const double t_prompt_total = stats.t_prompt_ms();
''',
         '''    void print_timings_pp() const {
        // STRIX_STATE_HASH: the slot's state after every prompt batch, to find the first batch where two runs part
        // (debugging only)
        if (getenv("STRIX_STATE_HASH") && prompt.n_tokens() > 0) {
            for (const llama_state_seq_flags fl : { (llama_state_seq_flags) LLAMA_STATE_SEQ_FLAGS_PARTIAL_ONLY, (llama_state_seq_flags) 0 }) {
                std::vector<uint8_t> st(llama_state_seq_get_size_ext(ctx_tgt, id, fl));
                llama_state_seq_get_data_ext(ctx_tgt, st.data(), st.size(), id, fl);
                SLT_INF(*this, "STATE_HASH batch %s: %016llx at %d tokens\\n", fl ? "recurrent" : "whole",
                        (unsigned long long) XXH3_64bits(st.data(), st.size()), prompt.n_tokens());
            }
        }

        const double t_prompt_total = stats.t_prompt_ms();
'''),
        ('''
                        // keep track how many tokens we can reuse from the previous state
''',
         '''
                        // STRIX_STATE_HASH: what the slot holds as a task starts - the recurrent part and the whole
                        // state - to tell a restored conversation from a resident one (debugging only)
                        if (getenv("STRIX_STATE_HASH") && slot.prompt.n_tokens() > 0) {
                            for (const llama_state_seq_flags fl : { (llama_state_seq_flags) LLAMA_STATE_SEQ_FLAGS_PARTIAL_ONLY, (llama_state_seq_flags) 0 }) {
                                std::vector<uint8_t> st(llama_state_seq_get_size_ext(ctx_tgt, slot.id, fl));
                                llama_state_seq_get_data_ext(ctx_tgt, st.data(), st.size(), slot.id, fl);
                                SLT_INF(slot, "STATE_HASH %s: %zu bytes, %016llx (%d tokens)\\n", fl ? "recurrent" : "whole", st.size(),
                                        (unsigned long long) XXH3_64bits(st.data(), st.size()), slot.prompt.n_tokens());
                            }
                        }

                        // keep track how many tokens we can reuse from the previous state
'''),
    ],
    os.path.join(tree, "tools", "server", "server-task.cpp"): [
        ('''            }
            ++n_read;
''',
         '''            }
            // STRIX_V3_VERIFY: read a whole run back out of the cache and check it against the hash it is named by
            if (ok && items[i].take == items[i].r.n && getenv("STRIX_V3_VERIFY")) {
                std::vector<uint8_t> back((size_t) items[i].row * (size_t) items[i].r.n);
                const bool got = llama_strix_kv_get_rows(items[i].ctx, id_slot, items[i].r.pos0, items[i].r.n, back.data(), back.size());
                const XXH128_hash_t h = XXH3_128bits(back.data(), back.size());
                if (!got || h.high64 != items[i].r.hi || h.low64 != items[i].r.lo) {
                    SRV_WRN(" - disk cache: VERIFY run at %d (%d rows, %s) reads back different%s\\n", items[i].r.pos0, items[i].r.n,
                            items[i].ctx == ctx_tgt ? "target" : "draft", got ? "" : " (no rows)");
                }
            }
            ++n_read;
'''),
    ],
}


def main():
    texts = {p: io.open(p, encoding="utf-8").read() for p in EDITS}
    if any(MARKER in t for t in texts.values()):
        print("already applied")
        return
    for p, pairs in EDITS.items():
        for old, new in pairs:
            if texts[p].count(old) != 1:
                sys.exit("anchor found %d times, expected once, in %s" % (texts[p].count(old), p))
            texts[p] = texts[p].replace(old, new, 1)
    for p, t in texts.items():
        io.open(p, "w", encoding="utf-8", newline="").write(t)
    print("patched", ", ".join(os.path.basename(p) for p in EDITS))


if __name__ == "__main__":
    main()
