#!/usr/bin/env python3
"""The MoE router and the routed experts of a several-conversation verify step on the vector kernel

A verify step of several conversations drafting carries 5-16 tokens, one more than two kernels take. The MoE router, an F32 [2560 x 512], goes past the vector kernel at 9 columns and fell to the MMB kernel's 128-row tiles: four workgroups for the whole GPU, ~250 us a product, 11 ms of a nine-token step. It now runs the vector kernel over column chunks up to 32 columns (STRIX_F32_VEC_CHUNK_MAX). The routed experts past the vector kernel's limit (4 tokens for IQ3_S, 6 for IQ4_NL) went to the tiled MMQ kernel, which stages a tile per expert for the one or two tokens an expert gets; they now run as chunks of 4 tokens through the vector kernel up to 16 tokens (STRIX_MOE_VEC_CHUNK=0: off; STRIX_MOE_VEC_CHUNK_MAX_T), 397 -> 289 us for a gate/up product at nine tokens and 499 -> 387 for the down, 5 ms of the step. Batches of one to four tokens, and batches of more than 32, are unchanged.

Generated by tools/make_patch_script.py from the tree it must reproduce, so every anchor is
unique by construction. 2 hunks across 1 file(s).

Usage: python patches/apply_small_batch_decode.py [tree]
"""
import io
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
tree = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "src", "llama.cpp")
MARKER = 'STRIX_MOE_VEC_CHUNK'

EDITS = {
    os.path.join(tree, "ggml", "src", "ggml-cuda", "ggml-cuda.cu"): [
        ('''    if (!ggml_is_quantized(src0->type) && ne01 <= 64 && ne11 > MMVF_MAX_BATCH_SIZE && ne11 <= 64
''',
         '''    // strixllama: and an F32 weight of any height at 9-32 columns (STRIX_F32_VEC_CHUNK_MAX): the MoE router
    // [2560 x 512] of a nine-token verify step - three conversations drafting two tokens each - took the MMB
    // kernel's 128-row tiles there, four workgroups for the whole GPU: ~250 us a product, the step +11 ms
    static const int64_t f32_vec_chunk_max = getenv("STRIX_F32_VEC_CHUNK_MAX") ? atoll(getenv("STRIX_F32_VEC_CHUNK_MAX")) : 32;
    const bool vec_chunks = (ne01 <= 64 && ne11 <= 64) || (src0->type == GGML_TYPE_F32 && ne11 <= f32_vec_chunk_max);
    if (!ggml_is_quantized(src0->type) && vec_chunks && ne11 > MMVF_MAX_BATCH_SIZE
'''),
        ('''                    return;
                }
            }
        }
''',
         '''                    return;
                }
            }
        }

        // strixllama: a verify step of several conversations (5-16 tokens) is more than the vector kernel takes
        // (IQ3_S 4, IQ4_NL 6 on RDNA 3.5), and the tiled kernel pays per expert for staging a tile it barely fills: a
        // nine-token step's routed experts 397 -> 289 us a product for the gate/up, 499 -> 387 for the down, the step
        // -5 ms. Chunks of STRIX_MOE_VEC_CHUNK tokens (0: off) through the vector kernel instead, up to
        // STRIX_MOE_VEC_CHUNK_MAX_T tokens; past that the tiled kernel's one read of an expert for all its tokens wins
        static const int moe_vec_chunk = getenv("STRIX_MOE_VEC_CHUNK") ? atoi(getenv("STRIX_MOE_VEC_CHUNK")) : 4;
        static const int moe_vec_chunk_max_t = getenv("STRIX_MOE_VEC_CHUNK_MAX_T") ? atoi(getenv("STRIX_MOE_VEC_CHUNK_MAX_T")) : 16;
        if (moe_vec_chunk > 0 && ggml_is_quantized(src0->type) && ne2 > 1 && ne2 <= moe_vec_chunk_max_t && ne12 == ne2) {
            const int chunk = std::min(moe_vec_chunk, get_mmvq_mmid_max_batch(src0->type, cc));
            if (chunk >= 1) {
                for (int64_t t0 = 0; t0 < ne2; t0 += chunk) {
                    const int64_t nt = std::min<int64_t>(chunk, ne2 - t0);
                    ggml_tensor src1_c = *src1;
                    src1_c.ne[2] = nt;
                    src1_c.data  = (char *) src1->data + t0*src1->nb[2];
                    ggml_tensor ids_c = *ids;
                    ids_c.ne[1] = nt;
                    ids_c.data  = (char *) ids->data + t0*ids->nb[1];
                    ggml_tensor dst_c = *dst;
                    dst_c.ne[2] = nt;
                    dst_c.data  = (char *) dst->data + t0*dst->nb[2];
                    ggml_cuda_mul_mat_vec_q(ctx, src0, &src1_c, &ids_c, &dst_c);
                }
                return;
            }
        }
'''),
    ],
}


def main():
    texts = {p: io.open(p, encoding="utf-8").read() for p in EDITS}
    if any(MARKER in t for t in texts.values()):
        print("already applied")
        return
    for p, pairs in EDITS.items():
        for old, new in pairs:
            if texts[p].count(old) != 1:
                sys.exit("anchor found %d times, expected once, in %s" % (texts[p].count(old), p))
            texts[p] = texts[p].replace(old, new, 1)
    for p, t in texts.items():
        io.open(p, "w", encoding="utf-8", newline="").write(t)
    print("patched", ", ".join(os.path.basename(p) for p in EDITS))


if __name__ == "__main__":
    main()
