#!/usr/bin/env python3
"""The gated delta net reads its states in place: the recurrent state gather is marked when it can be skipped

A batch's recurrent states are gathered (GET_ROWS by s_copy) into scratch before the gated delta net, which writes its new states and rollback snapshots back to the cells they came from. When every sequence reads a row of its own cell - its newest state, or a rollback snapshot after the MTP drafts a verify pass rejected - build_rs marks the gather ('SGIP' in op_params[0]) and the HIP backend reads the rows s_copy names straight from the cache: 3 MB a sequence a layer, ~7 ms a step at eight conversations. The condition is s_copy_own_cell, which unlike s_copy consumes no rollback index (a first version called s_copy at graph build, so after rejected drafts the net kept the state that had seen them), and it is compared in every hybrid input's can_reuse, so MTP decoding keeps its graphs. STRIX_GDN_GATHER_SKIP=0 keeps the gather.

Generated by tools/make_patch_script.py from the tree it must reproduce, so every anchor is
unique by construction. 9 hunks across 4 file(s).

Usage: python D:/Work/strixllama/patches/apply_gdn_direct_rows.py [tree]
"""
import io
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
tree = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "src", "llama.cpp")
MARKER = 'gather_in_place'

EDITS = {
    os.path.join(tree, "src", "llama-memory-recurrent.cpp"): [
        ('''    return (int32_t)(idx * mem->size) + src0;
}
''',
         '''    return (int32_t)(idx * mem->size) + src0;
}

bool llama_memory_recurrent_context::s_copy_own_cell(int n) const {
    // s_copy(i) is idx * size + src0: rollback group idx of cell src0
    for (int i = 0; i < n; ++i) {
        const uint32_t cell_idx = i + mem->head;
        if (mem->cells[cell_idx].src0 != (int32_t) cell_idx) {
            return false;
        }
    }
    return true;
}
'''),
    ],
    os.path.join(tree, "src", "llama-memory-recurrent.h"): [
        ('''    int32_t s_copy(int i) const;

private:
    const llama_memory_status status;
''',
         '''    int32_t s_copy(int i) const;

    // strixllama: whether every i < n reads its state from a row of its own cell (head + i: the newest state, or a
    // rollback snapshot of it), the cell its new state is written to. Unlike s_copy it consumes no rollback index
    bool s_copy_own_cell(int n) const;

private:
    const llama_memory_status status;
'''),
    ],
    os.path.join(tree, "src", "llama-graph.cpp"): [
        ('''    res &= rs_z == mctx->get_rs_z();

''',
         '''    res &= rs_z == mctx->get_rs_z();
    res &= gather_in_place == in_place(mctx, params.ubatch.n_seqs);

'''),
        ('''    res &= inp_rs->s_copy_main->ne[0]  == params.ubatch.n_seqs;
    res &= inp_rs->s_copy_extra->ne[0] == mctx->get_recr()->get_n_rs() - params.ubatch.n_seqs;

    res &= inp_rs->head == mctx->get_recr()->get_head();
    res &= inp_rs->rs_z == mctx->get_recr()->get_rs_z();

    return res;
}

// TODO: Hybrid input classes are a bit redundant.
''',
         '''    res &= inp_rs->s_copy_main->ne[0]  == params.ubatch.n_seqs;
    res &= inp_rs->s_copy_extra->ne[0] == mctx->get_recr()->get_n_rs() - params.ubatch.n_seqs;

    res &= inp_rs->head == mctx->get_recr()->get_head();
    res &= inp_rs->rs_z == mctx->get_recr()->get_rs_z();
    // strixllama: whether the state gather may be skipped is part of the graph (llm_graph_input_rs::gather_in_place)
    res &= inp_rs->gather_in_place == llm_graph_input_rs::in_place(mctx->get_recr(), params.ubatch.n_seqs);

    return res;
}

// TODO: Hybrid input classes are a bit redundant.
'''),
        ('''    res &= inp_rs->s_copy_main->ne[0]  == params.ubatch.n_seqs;
    res &= inp_rs->s_copy_extra->ne[0] == mctx->get_recr()->get_n_rs() - params.ubatch.n_seqs;

    res &= inp_rs->head == mctx->get_recr()->get_head();
    res &= inp_rs->rs_z == mctx->get_recr()->get_rs_z();

    return res;
}

void llm_graph_input_mem_hybrid_iswa::set_input(const llama_ubatch * ubatch) {
''',
         '''    res &= inp_rs->s_copy_main->ne[0]  == params.ubatch.n_seqs;
    res &= inp_rs->s_copy_extra->ne[0] == mctx->get_recr()->get_n_rs() - params.ubatch.n_seqs;

    res &= inp_rs->head == mctx->get_recr()->get_head();
    res &= inp_rs->rs_z == mctx->get_recr()->get_rs_z();
    // strixllama: whether the state gather may be skipped is part of the graph (llm_graph_input_rs::gather_in_place)
    res &= inp_rs->gather_in_place == llm_graph_input_rs::in_place(mctx->get_recr(), params.ubatch.n_seqs);

    return res;
}

void llm_graph_input_mem_hybrid_iswa::set_input(const llama_ubatch * ubatch) {
'''),
        ('''    res &= inp_rs->s_copy_main->ne[0]  == params.ubatch.n_seqs;
    res &= inp_rs->s_copy_extra->ne[0] == mctx->get_recr()->get_n_rs() - params.ubatch.n_seqs;

    res &= inp_rs->head == mctx->get_recr()->get_head();
    res &= inp_rs->rs_z == mctx->get_recr()->get_rs_z();

    return res;
}

void llm_graph_input_sampling::set_input(const llama_ubatch * ubatch) {
''',
         '''    res &= inp_rs->s_copy_main->ne[0]  == params.ubatch.n_seqs;
    res &= inp_rs->s_copy_extra->ne[0] == mctx->get_recr()->get_n_rs() - params.ubatch.n_seqs;

    res &= inp_rs->head == mctx->get_recr()->get_head();
    res &= inp_rs->rs_z == mctx->get_recr()->get_rs_z();
    // strixllama: whether the state gather may be skipped is part of the graph (llm_graph_input_rs::gather_in_place)
    res &= inp_rs->gather_in_place == llm_graph_input_rs::in_place(mctx->get_recr(), params.ubatch.n_seqs);

    return res;
}

void llm_graph_input_sampling::set_input(const llama_ubatch * ubatch) {
'''),
        ('''    inp->rs_z = mctx_cur->get_rs_z();

    return inp;
}
''',
         '''    inp->rs_z = mctx_cur->get_rs_z();
    inp->gather_in_place = llm_graph_input_rs::in_place(mctx_cur, n_seqs);

    return inp;
}

bool llm_graph_input_rs::in_place(const llama_memory_recurrent_context * mctx, int64_t n_seqs) {
    static const bool off = getenv("STRIX_GDN_GATHER_SKIP") && atoi(getenv("STRIX_GDN_GATHER_SKIP")) == 0;
    // not s_copy(), which consumes a pending rollback (the MTP drafts a verify pass rejected): set_input, which calls
    // it after this, would then read the newest state instead of the rolled-back one. A rollback does not change the
    // answer here, so MTP decoding keeps reusing its graphs
    return !off && n_seqs >= 1 && mctx->s_copy_own_cell((int) n_seqs);
}
'''),
        ('''    return build_rs(s, inp->s_copy_main, inp->s_copy_extra, state_size, n_seqs,
                    kv_state->get_n_rs(), kv_state->get_head(), kv_state->get_size(), kv_state->get_rs_z(),
                    get_state_rows);
''',
         '''    ggml_tensor * states = build_rs(s, inp->s_copy_main, inp->s_copy_extra, state_size, n_seqs,
                    kv_state->get_n_rs(), kv_state->get_head(), kv_state->get_size(), kv_state->get_rs_z(),
                    get_state_rows);
    // strixllama: each sequence gathers a row of the cell its new state is written to (see
    // llm_graph_input_rs::gather_in_place); the HIP backend reads 'SGIP' in op_params[0] of the gather
    if (inp->gather_in_place && states->op == GGML_OP_GET_ROWS) {
        states->op_params[0] = 0x53474950;
    }
    return states;
'''),
    ],
    os.path.join(tree, "src", "llama-graph.h"): [
        ('''    int32_t rs_z;
};
''',
         '''    int32_t rs_z;

    // strixllama: every sequence of the batch reads its state from a row of the cell it is written back to (its newest
    // state or a rollback snapshot), the usual case; build_rs then marks its gather so a backend may read the rows
    // s_copy names directly instead. Part of the graph, so it must match for reuse
    bool gather_in_place = false;
    static bool in_place(const llama_memory_recurrent_context * mctx, int64_t n_seqs);
};
'''),
    ],
}


def main():
    texts = {p: io.open(p, encoding="utf-8").read() for p in EDITS}
    if any(MARKER in t for t in texts.values()):
        print("already applied")
        return
    for p, pairs in EDITS.items():
        for old, new in pairs:
            if texts[p].count(old) != 1:
                sys.exit("anchor found %d times, expected once, in %s" % (texts[p].count(old), p))
            texts[p] = texts[p].replace(old, new, 1)
    for p, t in texts.items():
        io.open(p, "w", encoding="utf-8", newline="").write(t)
    print("patched", ", ".join(os.path.basename(p) for p in EDITS))


if __name__ == "__main__":
    main()
