#!/usr/bin/env python3
"""Several slots: every conversation keeps one run of the pool and a batch views only its own

With more than one slot the KV cache is one pool, and every graph viewed it from cell 0 to the last used cell, so a conversation paid for the others in the pool - most of all in the MTP draft, whose attention is dense. Each conversation now keeps one run of cells: its tokens go after its last cell, a new one starts in the middle of the largest free run, and one that has no room left moves to a larger run first (both caches and the block keys, device to device, ~20 ms per 23K cells). The graph of a batch views only the run of its own conversations, every cell index in the inputs relative to it. One conversation beside idle ones computes exactly what it computes on a single slot, bitwise, MTP included, and as fast; a conversation that moved too. Block keys go stale per sequence instead of per pool, so a restore rebuilds only its own. LLAMA_KV_REGIONS=0 turns it off, LLAMA_KV_WINDOW=0 keeps the regions but views the pool as before.

Generated by tools/make_patch_script.py from the tree it must reproduce, so every anchor is
unique by construction. 73 hunks across 9 file(s).

Usage: python D:/Work/strixllama/patches/apply_kv_regions.py [tree]
"""
import io
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
tree = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "src", "llama.cpp")
MARKER = 'get_kv_window'

EDITS = {
    os.path.join(tree, "src", "llama-kv-cells.h"): [
        ('''            seq_pos[s].clear();
        }
''',
         '''            seq_pos[s].clear();
            seq_cells[s].clear();
        }
'''),
        ('''        return used.empty() ? 0 : *used.rbegin() + 1;
    }
''',
         '''        return used.empty() ? 0 : *used.rbegin() + 1;
    }

    // strixllama: the used cells in index order, for walking the runs of free cells between them
    const std::set<uint32_t> & used_set() const {
        return used;
    }
'''),
        ('''    }

    // note: call only if the cell is not empty
    llama_pos pos_get(uint32_t i) const {
''',
         '''    }

    // strixllama: the span of the cell array that holds sequence seq_id, [seq_cell_min, seq_cell_max]
    // return -1 if the sequence is not present
    int64_t seq_cell_min(llama_seq_id seq_id) const {
        assert(seq_id >= 0);
        assert(seq_id < LLAMA_MAX_SEQ);

        return seq_cells[seq_id].empty() ? -1 : (int64_t) *seq_cells[seq_id].begin();
    }

    int64_t seq_cell_max(llama_seq_id seq_id) const {
        assert(seq_id >= 0);
        assert(seq_id < LLAMA_MAX_SEQ);

        return seq_cells[seq_id].empty() ? -1 : (int64_t) *seq_cells[seq_id].rbegin();
    }

    // the number of cells that carry sequence seq_id
    uint32_t seq_cell_count(llama_seq_id seq_id) const {
        assert(seq_id >= 0);
        assert(seq_id < LLAMA_MAX_SEQ);

        return (uint32_t) seq_cells[seq_id].size();
    }

    // the (pos, cell) pairs of sequence seq_id, ordered by position
    const std::set<std::pair<llama_pos, uint32_t>> & seq_pos_cells(llama_seq_id seq_id) const {
        assert(seq_id >= 0);
        assert(seq_id < LLAMA_MAX_SEQ);

        return seq_pos[seq_id];
    }

    // strixllama: move the state of cell isrc to the empty cell idst (the KV data is moved by the caller)
    void mv(uint32_t isrc, uint32_t idst) {
        assert(isrc < pos.size());
        assert(idst < pos.size());
        assert(isrc != idst);
        assert(pos[idst] == -1 && seq[idst].none());
        assert(pos[isrc] != -1);
        assert(shift[isrc] == 0);

        seq_pos_rm(isrc);

        pos[idst] = pos[isrc];
        ext[idst] = ext[isrc];
        seq[idst] = seq[isrc];

        pos[isrc] = -1;
        ext[isrc].reset();
        seq[isrc].reset();

        used.erase(isrc);
        used.insert(idst);

        seq_pos_add(idst);
    }

    // note: call only if the cell is not empty
    llama_pos pos_get(uint32_t i) const {
'''),
        ('''
    // helper functions for updating `seq_pos`, once cell at a time:
''',
         '''
    // strixllama: the cells of each sequence in index order, kept in step with seq_pos. A unified cache
    // keeps a conversation in one run of cells, and the graph of a batch views only the run of its own
    // conversations (llama_kv_cache::get_kv_window), which needs a sequence's first and last cell.
    std::set<uint32_t> seq_cells[LLAMA_MAX_SEQ];

    // helper functions for updating `seq_pos`, once cell at a time:
'''),
        ('''        GGML_UNUSED(n);
    }
''',
         '''        GGML_UNUSED(n);

        seq_cells[s].erase(i);
    }
'''),
        ('''        seq_pos[s].insert({ pos[i], i });
    }
''',
         '''        seq_pos[s].insert({ pos[i], i });

        seq_cells[s].insert(i);
    }
'''),
    ],
    os.path.join(tree, "src", "llama-kv-cache.cpp"): [
        ('''#include <cmath>
#include <cstring>
''',
         '''#include <cmath>
#include <cstdlib>
#include <cstring>
'''),
        ('''
        auto sinfos = prepare(ubatches);
''',
         '''
        // strixllama: a conversation whose tokens do not fit after its last cell moves to a larger run first
        if (regions && can_move()) {
            move_cells(plan_moves(ubatches));
        }

        auto sinfos = prepare(ubatches);
'''),
        ('''    GGML_UNUSED(optimize);

''',
         '''    GGML_UNUSED(optimize);

    lctx_sync = lctx;   // strixllama: see move_cells

'''),
        ('''
    uint32_t n_tokens = ubatch.n_tokens;
''',
         '''
    // strixllama: regions - each conversation after its last cell; whatever does not fit that way takes the
    // search below, which is always correct and only makes the batch's window wider
    if (regions && !cont) {
        slot_info res = find_slot_regions(ubatch);
        if (!res.empty()) {
            return res;
        }
    }

    uint32_t n_tokens = ubatch.n_tokens;
'''),
        ('''    assert(res.s1 >= res.s0);

    return res;
}

void llama_kv_cache::apply_ubatch(const slot_info & sinfo, const llama_ubatch & ubatch) {
''',
         '''    assert(res.s1 >= res.s0);

    return res;
}

//
// strixllama: regions
//

void llama_kv_cache::set_regions(bool on) {
    regions = on && n_stream == 1 && !v_trans && n_swa == 0 && swa_type == LLAMA_SWA_TYPE_NONE && other == nullptr;
}

bool llama_kv_cache::get_regions() const {
    return regions;
}

bool llama_kv_cache::can_move() const {
    return regions && lctx_sync != nullptr;
}

void llama_kv_cache::move_cells(const cell_move_vec_t & moves) {
    if (moves.empty()) {
        return;
    }

    GGML_ASSERT(can_move());

    // the graphs already submitted may still read or write these cells
    ggml_backend_sched_synchronize(lctx_sync->get_sched());

    const int64_t t_start_us = ggml_time_us();

    uint64_t n_cells = 0;
    for (const auto & m : moves) {
        n_cells += m.n;
    }

    apply_moves(moves);

    // on stderr like the other strixllama diagnostics: the server does not print llama's info lines
    fprintf(stderr, "kv regions: moved %llu cells in %zu runs (%s) in %.1f ms\\n",
            (unsigned long long) n_cells, moves.size(), layers.empty() ? "" : ggml_get_name(layers[0].k),
            (ggml_time_us() - t_start_us)/1000.0);
}

// where a sequence with no cell starts: in the largest run of free cells that holds `room`, at the run's start
// when nothing precedes it, else in its middle, so that the conversation before it can grow too - the split a
// buddy allocator makes. The largest run, because nothing says how long the conversation will get.
int64_t llama_kv_cache::region_start(const llama_kv_cells & cells, uint32_t need,
        const std::vector<std::pair<uint32_t, uint32_t>> & taken, uint32_t room) const {
    const uint32_t size = cells.size();

    // the occupied runs: the used cells, and the runs this plan has already given away
    std::vector<std::pair<uint32_t, uint32_t>> occ(taken.begin(), taken.end());
    {
        const auto & used = cells.used_set();
        auto it = used.begin();
        while (it != used.end()) {
            const uint32_t r0 = *it;
            uint32_t r1 = r0 + 1;
            for (++it; it != used.end() && *it == r1; ++it) {
                ++r1;
            }
            occ.emplace_back(r0, r1);
        }
    }
    std::sort(occ.begin(), occ.end());

    int64_t  best0 = -1;
    uint32_t best_len = 0;

    uint32_t cur = 0;
    auto consider = [&](uint32_t g0, uint32_t g1) {
        if (g1 > g0 && g1 - g0 >= room && g1 - g0 > best_len) {
            best0    = g0;
            best_len = g1 - g0;
        }
    };
    for (const auto & r : occ) {
        if (r.first > cur) {
            consider(cur, r.first);
        }
        cur = std::max(cur, r.second);
    }
    if (cur < size) {
        consider(cur, size);
    }

    if (best0 < 0 || best_len < need) {
        return -1;
    }

    // LLAMA_KV_REGION_PACK=1 (a test knob): the first run that holds `room`, from its start, so that
    // conversations sit back to back and every one that grows has to move
    static const bool pack = [] {
        const char * e = getenv("LLAMA_KV_REGION_PACK");
        return e != nullptr && atoi(e) != 0;
    }();
    if (pack) {
        cur = 0;
        for (const auto & r : occ) {
            if (r.first > cur && r.first - cur >= room) {
                return cur;
            }
            cur = std::max(cur, r.second);
        }
        return cur < size && size - cur >= room ? (int64_t) cur : -1;
    }

    if (best0 == 0) {
        return 0;
    }

    // the middle of the run, on a 256-cell boundary when one fits
    const uint32_t g0 = (uint32_t) best0;
    uint32_t start = g0 + (best_len - need)/2;
    const uint32_t aligned = start & ~255u;
    if (aligned >= g0) {
        start = aligned;
    }

    return start;
}

llama_kv_cache::slot_info llama_kv_cache::find_slot_regions(const llama_ubatch & ubatch) const {
    if (n_stream != 1 || ubatch.n_tokens == 0) {
        return { };
    }

    const auto & cells = v_cells[0];

    // the ubatch's sequences in order of appearance, with their token counts; one sequence per token
    std::vector<llama_seq_id> seqs;
    std::vector<uint32_t>     count;
    std::vector<uint32_t>     tok_seq(ubatch.n_tokens);

    for (uint32_t i = 0; i < ubatch.n_tokens; ++i) {
        if (ubatch.n_seq_id[i] != 1) {
            return { };
        }

        const llama_seq_id s = ubatch.seq_id[i][0];

        uint32_t k = 0;
        while (k < seqs.size() && seqs[k] != s) {
            ++k;
        }
        if (k == seqs.size()) {
            seqs.push_back(s);
            count.push_back(0);
        }

        count[k]++;
        tok_seq[i] = k;
    }

    std::vector<std::pair<uint32_t, uint32_t>> taken;
    std::vector<uint32_t> cursor(seqs.size());

    for (uint32_t k = 0; k < seqs.size(); ++k) {
        const uint32_t n = count[k];

        int64_t start = cells.seq_cell_max(seqs[k]);
        if (start >= 0) {
            start += 1;
        } else {
            start = region_start(cells, n, taken, n);
            if (start < 0) {
                return { };
            }
        }

        if ((uint64_t) start + n > cells.size()) {
            return { };
        }

        for (uint32_t j = 0; j < n; ++j) {
            if (!cells.is_empty(start + j)) {
                return { };
            }
        }

        for (const auto & t : taken) {
            if ((uint32_t) start < t.second && t.first < (uint32_t) start + n) {
                return { };
            }
        }

        taken.emplace_back((uint32_t) start, (uint32_t) start + n);
        cursor[k] = (uint32_t) start;
    }

    slot_info res = {
        /*.s0   =*/ 0,
        /*.s1   =*/ 0,
        /*.strm =*/ { 0 },
        /*.idxs =*/ { { } },
    };

    res.idxs[0].reserve(ubatch.n_tokens);

    for (uint32_t i = 0; i < ubatch.n_tokens; ++i) {
        res.idxs[0].push_back(cursor[tok_seq[i]]++);
    }

    return res;
}

// A sequence of the batch whose tokens do not fit after its last cell moves, all of it and in position order,
// to a run with room to grow - twice what it will hold, as a vector grows, but at most 32K cells more - so that
// the next tokens append again.
// A sequence that shares cells with another one stays (moving a shared cell would take it from the other
// sequence), as does one with no run large enough: find_slot's search places their tokens.
llama_kv_cache::cell_move_vec_t llama_kv_cache::plan_moves(const std::vector<llama_ubatch> & ubatches) const {
    cell_move_vec_t res;

    if (!regions || n_stream != 1) {
        return res;
    }

    static const bool on = [] {
        const char * e = getenv("LLAMA_KV_REGION_MOVES");
        return !e || atoi(e) != 0;
    }();
    if (!on) {
        return res;
    }

    const auto & cells = v_cells[0];

    std::vector<llama_seq_id> seqs;
    std::vector<uint32_t>     count;

    for (const auto & ubatch : ubatches) {
        for (uint32_t i = 0; i < ubatch.n_tokens; ++i) {
            if (ubatch.n_seq_id[i] != 1) {
                return res;
            }

            const llama_seq_id s = ubatch.seq_id[i][0];

            uint32_t k = 0;
            while (k < seqs.size() && seqs[k] != s) {
                ++k;
            }
            if (k == seqs.size()) {
                seqs.push_back(s);
                count.push_back(0);
            }

            count[k]++;
        }
    }

    std::vector<std::pair<uint32_t, uint32_t>> taken;

    for (uint32_t k = 0; k < seqs.size(); ++k) {
        const llama_seq_id s = seqs[k];

        const int64_t last = cells.seq_cell_max(s);
        if (last < 0) {
            continue;
        }

        bool fits = (uint64_t) last + 1 + count[k] <= cells.size();
        for (uint32_t j = 0; fits && j < count[k]; ++j) {
            fits = cells.is_empty((uint32_t) last + 1 + j);
        }
        if (fits) {
            continue;
        }

        const auto & pcs = cells.seq_pos_cells(s);

        bool shared = false;
        for (const auto & pc : pcs) {
            if (cells.seq_count(pc.second) != 1) {
                shared = true;
                break;
            }
        }
        if (shared) {
            continue;
        }

        const uint32_t need  = cells.seq_cell_count(s) + count[k];
        const uint32_t room  = need + std::min(need, 32768u);
        const int64_t  start = region_start(cells, need, taken, room);
        if (start < 0) {
            if (getenv("LLAMA_KV_REGION_DEBUG")) {
                fprintf(stderr, "kv regions: no run of %u cells for seq %d, its tokens take the search\\n", room, s);
            }
            continue;
        }

        taken.emplace_back((uint32_t) start, (uint32_t) start + need);

        uint32_t d = (uint32_t) start;
        for (const auto & pc : pcs) {
            const uint32_t c = pc.second;
            if (!res.empty() && res.back().seq == s && res.back().src + res.back().n == c && res.back().dst + res.back().n == d) {
                res.back().n++;
            } else {
                res.push_back({ c, d, 1, s });
            }
            ++d;
        }

        if (getenv("LLAMA_KV_REGION_DEBUG")) {
            fprintf(stderr, "kv regions: seq %d (%u cells from %lld, %u new) moves to %u (%s)\\n", s,
                    cells.seq_cell_count(s), (long long) cells.seq_cell_min(s), count[k], (uint32_t) start,
                    layers.empty() ? "" : ggml_get_name(layers[0].k));
        }
    }

    return res;
}

// copy rows [src, src + n) of t over rows [dst, dst + n) on the device; the ranges must not overlap
static void llama_kv_copy_rows(ggml_tensor * t, uint32_t src, uint32_t dst, uint32_t n) {
    GGML_ASSERT(src + n <= dst || dst + n <= src);

    ggml_init_params params = {
        /*.mem_size   =*/ 2*ggml_tensor_overhead(),
        /*.mem_buffer =*/ nullptr,
        /*.no_alloc   =*/ true,
    };

    ggml_context * ctx = ggml_init(params);
    GGML_ASSERT(ctx != nullptr);

    ggml_tensor * a = ggml_view_2d(ctx, t, t->ne[0], n, t->nb[1], (size_t) src*t->nb[1]);
    ggml_tensor * b = ggml_view_2d(ctx, t, t->ne[0], n, t->nb[1], (size_t) dst*t->nb[1]);

    ggml_backend_view_init(a);
    ggml_backend_view_init(b);

    ggml_backend_tensor_copy(a, b);

    ggml_free(ctx);
}

void llama_kv_cache::apply_moves(const cell_move_vec_t & moves) {
    GGML_ASSERT(n_stream == 1);

    for (const auto & layer : layers) {
        for (ggml_tensor * t : { layer.k, layer.v }) {
            if (t == nullptr) {
                continue;
            }

            for (const auto & m : moves) {
                llama_kv_copy_rows(t, m.src, m.dst, m.n);
            }
        }
    }

    auto & cells = v_cells[0];

    for (const auto & m : moves) {
        for (uint32_t j = 0; j < m.n; ++j) {
            cells.mv(m.src + j, m.dst + j);
        }
    }
}

void llama_kv_cache::apply_ubatch(const slot_info & sinfo, const llama_ubatch & ubatch) {
'''),
        ('''ggml_tensor * llama_kv_cache::get_k(ggml_context * ctx, int32_t il, uint32_t n_kv, const slot_info & sinfo) const {
''',
         '''// strixllama: under regions the graph views the run of cells that holds the ubatch's own sequences - their
// first to their last cell, padded as get_n_kv pads - instead of the pool up to its last used cell. Cells of
// other sequences inside the run are masked as before. Unchanged when that is no narrower (one conversation
// from cell 0, as on a single slot). LLAMA_KV_WINDOW=0 turns it off.
void llama_kv_cache::get_kv_window(const slot_info & sinfo, const llama_ubatch & ubatch, uint32_t & off, uint32_t & n_kv) const {
    off  = 0;
    n_kv = get_n_kv(sinfo);

    static const bool on = [] {
        const char * e = getenv("LLAMA_KV_WINDOW");
        return !e || atoi(e) != 0;
    }();

    if (!on || !regions || n_stream != 1 || sinfo.n_stream() != 1 || ubatch.n_tokens == 0) {
        return;
    }

    const auto & cells = v_cells[sinfo.strm[0]];

    std::bitset<LLAMA_MAX_SEQ> seen;

    int64_t lo = INT64_MAX;
    int64_t hi = -1;

    for (uint32_t i = 0; i < ubatch.n_tokens; ++i) {
        for (int32_t k = 0; k < ubatch.n_seq_id[i]; ++k) {
            const llama_seq_id s = ubatch.seq_id[i][k];
            if (s < 0 || s >= LLAMA_MAX_SEQ || seen.test(s)) {
                continue;
            }
            seen.set(s);

            const int64_t c0 = cells.seq_cell_min(s);
            const int64_t c1 = cells.seq_cell_max(s);
            if (c0 < 0) {
                continue;
            }

            lo = std::min(lo, c0);
            hi = std::max(hi, c1 + 1);
        }
    }

    if (hi <= lo) {
        return;
    }

    const uint32_t n_pad_cur = std::max(n_pad, 256u);

    const uint32_t n = std::min(cells.size(), std::max(n_pad_cur, GGML_PAD((uint32_t) (hi - lo), n_pad_cur)));
    if (n >= n_kv) {
        return;
    }

    off  = (uint32_t) std::min<int64_t>(lo, (int64_t) cells.size() - n);
    n_kv = n;

    // LLAMA_KV_REGION_DEBUG=2: every change of a cache's window
    static const int dbg = getenv("LLAMA_KV_REGION_DEBUG") ? atoi(getenv("LLAMA_KV_REGION_DEBUG")) : 0;
    if (dbg >= 2) {
        static thread_local std::map<const void *, std::pair<uint32_t, uint32_t>> last;
        auto & l = last[this];
        if (l.first != off || l.second != n_kv) {
            l = { off, n_kv };
            fprintf(stderr, "kv window: %s off=%u n_kv=%u (pool %u) tokens=%u lo=%lld hi=%lld\\n",
                    layers.empty() ? "" : ggml_get_name(layers[0].k), off, n_kv, get_n_kv(sinfo), ubatch.n_tokens,
                    (long long) lo, (long long) hi);
        }
    }
}

ggml_tensor * llama_kv_cache::get_k(ggml_context * ctx, int32_t il, uint32_t n_kv, const slot_info & sinfo, uint32_t off) const {
'''),
        ('''    assert(n_embd_k_gqa == hparams.n_embd_k_gqa(il));

''',
         '''    assert(n_embd_k_gqa == hparams.n_embd_k_gqa(il));
    GGML_ASSERT((uint64_t) off + n_kv <= kv_size);

'''),
        ('''            ggml_row_size(k->type, n_embd_k_gqa*kv_size)*sinfo.s0);
''',
         '''            ggml_row_size(k->type, n_embd_k_gqa*kv_size)*sinfo.s0 + ggml_row_size(k->type, n_embd_k_gqa)*off);
'''),
        ('''ggml_tensor * llama_kv_cache::get_v(ggml_context * ctx, int32_t il, uint32_t n_kv, const slot_info & sinfo) const {
''',
         '''ggml_tensor * llama_kv_cache::get_v(ggml_context * ctx, int32_t il, uint32_t n_kv, const slot_info & sinfo, uint32_t off) const {
'''),
        ('''    assert(n_embd_v_gqa >= hparams.n_embd_v_gqa(il));

''',
         '''    assert(n_embd_v_gqa >= hparams.n_embd_v_gqa(il));
    GGML_ASSERT((uint64_t) off + n_kv <= kv_size);

'''),
        ('''                ggml_row_size(v->type, n_embd_v_gqa*kv_size)*sinfo.s0);
''',
         '''                ggml_row_size(v->type, n_embd_v_gqa*kv_size)*sinfo.s0 + ggml_row_size(v->type, n_embd_v_gqa)*off);
'''),
        ('''            ggml_row_size(v->type, kv_size*n_embd_v_gqa)*sinfo.s0);
''',
         '''            ggml_row_size(v->type, kv_size*n_embd_v_gqa)*sinfo.s0 + ggml_row_size(v->type, off));
'''),
        ('''    int64_t n_tps;
};
''',
         '''    int64_t n_tps;

    // strixllama: the first cell of the graph's view
    uint32_t off;
};

// strixllama: the cells of a stream as the graph's view sees them, from its first cell (get_kv_window)
struct llama_kv_cells_view {
    const llama_kv_cells & cells;
    const uint32_t         off;

    bool                      is_empty(uint32_t j)                   const { return cells.is_empty(off + j); }
    bool                      seq_has (uint32_t j, llama_seq_id s)   const { return cells.seq_has(off + j, s); }
    llama_pos                 pos_get (uint32_t j)                   const { return cells.pos_get(off + j); }
    const llama_kv_cell_ext & ext_get (uint32_t j)                   const { return cells.ext_get(off + j); }
};
'''),
        ('''            const auto & cells = v_cells.at(seq_to_stream[seq_id]);
''',
         '''            const llama_kv_cells_view cells = { v_cells.at(seq_to_stream[seq_id]), args.off };
'''),
        ('''void llama_kv_cache::set_input_kq_mask(ggml_tensor * dst, const llama_ubatch * ubatch, bool causal_attn) const {
''',
         '''void llama_kv_cache::set_input_kq_mask(ggml_tensor * dst, const llama_ubatch * ubatch, bool causal_attn, uint32_t off) const {
'''),
        ('''        /*.n_tps            =*/ n_tps,
    };

''',
         '''        /*.n_tps            =*/ n_tps,
        /*.off              =*/ off,
    };

    GGML_ASSERT(off == 0 || (n_stream == 1 && (uint64_t) off + n_kv <= get_size()));

'''),
        ('''    n_kv = kv->get_n_kv(sinfos[i_cur]);
''',
         '''
    uint32_t n = 0;
    kv->get_kv_window(sinfos[i_cur], ubatches[i_cur], kv_off, n);
    n_kv = n;
'''),
        ('''
ggml_type llama_kv_cache_context::type_k() const {
''',
         '''
uint32_t llama_kv_cache_context::get_kv_off() const {
    return kv_off;
}

ggml_type llama_kv_cache_context::type_k() const {
'''),
        ('''    return kv->get_k(ctx, il, n_kv, sinfos[i_cur]);
''',
         '''    return kv->get_k(ctx, il, n_kv, sinfos[i_cur], kv_off);
'''),
        ('''    return kv->get_v(ctx, il, n_kv, sinfos[i_cur]);
''',
         '''    return kv->get_v(ctx, il, n_kv, sinfos[i_cur], kv_off);
'''),
        ('''    kv->set_input_kq_mask(dst, ubatch, causal_attn);
''',
         '''    kv->set_input_kq_mask(dst, ubatch, causal_attn, kv_off);
'''),
    ],
    os.path.join(tree, "src", "llama-kv-cache.h"): [
        ('''
    // TODO: refactor the memory instances to not depend on `llama_model`
''',
         '''
    // strixllama: n cells of sequence seq moved from [src, src + n) to [dst, dst + n), data and state
    struct cell_move {
        uint32_t     src;
        uint32_t     dst;
        uint32_t     n;
        llama_seq_id seq;
    };

    using cell_move_vec_t = std::vector<cell_move>;

    // TODO: refactor the memory instances to not depend on `llama_model`
'''),
        ('''
    // state_read, plus the cells the restored tokens were placed in
''',
         '''
    // strixllama: regions. A unified cache with several sequences keeps each conversation in one run of cells:
    // its tokens go after its last cell (find_slot), a new one starts in the middle of the largest free run, and
    // one that has no room left moves to a larger run first (plan_moves, applied by update()). The graph of a
    // batch then views only the run of its own conversations (get_kv_window), so a conversation costs what it
    // would on a cache of its own. Only for a cache whose owner handles the window offset in every graph input
    // it builds (llama_memory_hybrid_idx); anything that does not fit falls back to the plain search, which is
    // always correct and only makes the window wider.
    void set_regions(bool on);
    bool get_regions() const;

    // the moves that give every sequence of these ubatches room after its last cell; empty when none is
    // needed or none is possible (find_slot's search places the tokens then)
    cell_move_vec_t plan_moves(const std::vector<llama_ubatch> & ubatches) const;

    // move the cells' data and state now; a cache that mirrors another one (the qwen4exp indexer) is given the
    // other's moves. Needs the context whose graphs use the cache, to wait for them first (see can_move)
    bool can_move() const;
    void move_cells(const cell_move_vec_t & moves);

    // state_read, plus the cells the restored tokens were placed in
'''),
        ('''    // get views of the current state of the cache
    ggml_tensor * get_k(ggml_context * ctx, int32_t il, uint32_t n_kv, const slot_info & sinfo) const;
    ggml_tensor * get_v(ggml_context * ctx, int32_t il, uint32_t n_kv, const slot_info & sinfo) const;
''',
         '''    // strixllama: the cells [off, off + n_kv) the graph of this ubatch views: the run that holds the ubatch's
    // own sequences when regions are on (see set_regions), else [0, get_n_kv())
    void get_kv_window(const slot_info & sinfo, const llama_ubatch & ubatch, uint32_t & off, uint32_t & n_kv) const;

    // get views of the current state of the cache
    // strixllama: off = the first cell of the view (get_kv_window)
    ggml_tensor * get_k(ggml_context * ctx, int32_t il, uint32_t n_kv, const slot_info & sinfo, uint32_t off = 0) const;
    ggml_tensor * get_v(ggml_context * ctx, int32_t il, uint32_t n_kv, const slot_info & sinfo, uint32_t off = 0) const;
'''),
        ('''    void set_input_k_shift(ggml_tensor * dst) const;

    void set_input_kq_mask   (ggml_tensor * dst, const llama_ubatch * ubatch, bool causal_attn) const;
    void set_input_pos_bucket(ggml_tensor * dst, const llama_ubatch * ubatch) const;

''',
         '''    void set_input_k_shift(ggml_tensor * dst) const;

    // strixllama: off = the first cell of the graph's view (get_kv_window)
    void set_input_kq_mask   (ggml_tensor * dst, const llama_ubatch * ubatch, bool causal_attn, uint32_t off = 0) const;
    void set_input_pos_bucket(ggml_tensor * dst, const llama_ubatch * ubatch) const;

'''),
        ('''
    size_t total_size() const;
''',
         '''
    // strixllama: regions (see set_regions)
    bool regions = false;
    // the context that runs this cache's graphs, from init_update (llama_context::decode calls it before
    // init_batch): move_cells synchronizes its scheduler before touching the cache
    llama_context * lctx_sync = nullptr;

    // the slot of a ubatch under regions: each sequence after its last cell, a new one where region_start puts
    // it; empty if any of it does not fit, and find_slot searches instead
    slot_info find_slot_regions(const llama_ubatch & ubatch) const;

    // where a run of `need` cells starts for a sequence that has no cell yet, avoiding `taken`; -1 if nowhere
    int64_t region_start(const llama_kv_cells & cells, uint32_t need,
            const std::vector<std::pair<uint32_t, uint32_t>> & taken, uint32_t room) const;

    void apply_moves(const cell_move_vec_t & moves);

    size_t total_size() const;
'''),
        ('''    uint32_t get_n_kv() const;

    ggml_type type_k() const;
    ggml_type type_v() const;
''',
         '''    uint32_t get_n_kv() const;

    // strixllama: the first cell of the graph's view of the cache (llama_kv_cache::get_kv_window)
    uint32_t get_kv_off() const;

    ggml_type type_k() const;
    ggml_type type_v() const;
'''),
        ('''    int32_t n_kv;
};
''',
         '''    int32_t n_kv;

    // strixllama: the view is [kv_off, kv_off + n_kv)
    uint32_t kv_off = 0;
};
'''),
    ],
    os.path.join(tree, "src", "llama-graph.h"): [
        ('''    ggml_tensor * self_k_rot = nullptr;
    ggml_tensor * self_v_rot = nullptr;

    // note: these have to be copies because in order to be able to reuse a graph, its inputs
''',
         '''    ggml_tensor * self_k_rot = nullptr;
    ggml_tensor * self_v_rot = nullptr;

    // strixllama: the first cell of the cache view the graph was built with (llama_kv_cache::get_kv_window);
    // the views carry it as an offset, so a graph is reusable only for the same one
    uint32_t kv_off = 0;

    // note: these have to be copies because in order to be able to reuse a graph, its inputs
'''),
    ],
    os.path.join(tree, "src", "llama-graph.cpp"): [
        ('''  //res &= self_v_idxs->ne[0] == params.ubatch.n_tokens; // TODO: need to move this to the unified cache and check there

    res &= can_reuse_kq_mask(self_kq_mask, mctx, params.ubatch, params.cparams);

    return res;
}
''',
         '''  //res &= self_v_idxs->ne[0] == params.ubatch.n_tokens; // TODO: need to move this to the unified cache and check there

    res &= can_reuse_kq_mask(self_kq_mask, mctx, params.ubatch, params.cparams);

    // strixllama: the cache views start at the window's first cell
    res &= kv_off == mctx->get_kv_off();

    return res;
}
'''),
        ('''  //res &= inp_attn->self_v_idxs->ne[0] == params.ubatch.n_tokens; // TODO: need to move this to the unified cache and check there

    res &= can_reuse_kq_mask(inp_attn->self_kq_mask, mctx->get_attn(), params.ubatch, params.cparams);

    res &= inp_rs->s_copy->ne[0] == mctx->get_recr()->get_n_rs();

''',
         '''  //res &= inp_attn->self_v_idxs->ne[0] == params.ubatch.n_tokens; // TODO: need to move this to the unified cache and check there

    res &= can_reuse_kq_mask(inp_attn->self_kq_mask, mctx->get_attn(), params.ubatch, params.cparams);

    // strixllama: the cache views start at the window's first cell
    res &= inp_attn->kv_off == mctx->get_attn()->get_kv_off();

    res &= inp_rs->s_copy->ne[0] == mctx->get_recr()->get_n_rs();

'''),
        ('''    inp->self_v_rot = mctx_cur->build_input_v_rot(ctx0);

    return inp;
}
''',
         '''    inp->self_v_rot = mctx_cur->build_input_v_rot(ctx0);

    inp->kv_off = mctx_cur->get_kv_off();

    return inp;
}
'''),
    ],
    os.path.join(tree, "src", "llama-memory-hybrid-idx.cpp"): [
        ('''        LLAMA_LOG_INFO("%s: QSA block-key cache: %zu layers, %.1f MiB\\n", __func__, kb_map.size(), bytes/1024.0/1024.0);
    }
}

''',
         '''        LLAMA_LOG_INFO("%s: QSA block-key cache: %zu layers, %.1f MiB\\n", __func__, kb_map.size(), bytes/1024.0/1024.0);
    }

    // strixllama: regions (llama_kv_cache::set_regions) - with several sequences in one unified pool, each
    // conversation keeps one run of cells and a batch's graph views only its own. The indexer mirrors the
    // attention cells, so both caches take the window, and the moves, together. LLAMA_KV_REGIONS=0 turns it off.
    {
        const char * env = getenv("LLAMA_KV_REGIONS");
        const bool on = unified && n_seq_max > 1 && (env == nullptr || atoi(env) != 0);
        get_mem_attn()->set_regions(on);
        if (mem_idx) {
            mem_idx->set_regions(on);
            if (get_mem_attn()->get_regions() != mem_idx->get_regions()) {
                get_mem_attn()->set_regions(false);
                mem_idx->set_regions(false);
            }
        }
        if (get_mem_attn()->get_regions()) {
            fprintf(stderr, "kv regions: on, one run of cells per conversation, %u sequences, %u cells\\n", n_seq_max, kv_size);
        }
    }
}

'''),
        ('''bool llama_memory_hybrid_idx::kb_needs_full() const {
    return kb_full_gen != kb_gen;
}

void llama_memory_hybrid_idx::kb_mark_full() const {
    kb_full_gen = kb_gen;
}

bool llama_memory_hybrid_idx::kb_pos_dup() const {
    return kb_dup;
''',
         '''bool llama_memory_hybrid_idx::kb_needs_full(const llama_ubatch & ubatch) const {
    if (kb_stale.none() || !ubatch.seq_id || !ubatch.n_seq_id) {
        return false;
    }
    for (uint32_t i = 0; i < ubatch.n_tokens; ++i) {
        for (int32_t k = 0; k < ubatch.n_seq_id[i]; ++k) {
            const llama_seq_id s = ubatch.seq_id[i][k];
            if (s >= 0 && s < LLAMA_MAX_SEQ && kb_stale.test(s)) {
                return true;
            }
        }
    }
    return false;
}

void llama_memory_hybrid_idx::kb_mark_full(const llama_ubatch & ubatch) const {
    if (!ubatch.seq_id || !ubatch.n_seq_id) {
        return;
    }
    for (uint32_t i = 0; i < ubatch.n_tokens; ++i) {
        for (int32_t k = 0; k < ubatch.n_seq_id[i]; ++k) {
            const llama_seq_id s = ubatch.seq_id[i][k];
            if (s >= 0 && s < LLAMA_MAX_SEQ) {
                kb_stale.reset(s);
            }
        }
    }
}

void llama_memory_hybrid_idx::kb_mark_stale(llama_seq_id seq_id) {
    if (seq_id < 0 || seq_id >= LLAMA_MAX_SEQ) {
        kb_stale.set();
    } else {
        kb_stale.set(seq_id);
    }
}

bool llama_memory_hybrid_idx::kb_pos_dup() const {
    return kb_dup;
}

// copy rows [src, src + n) of t over rows [dst, dst + n) on the device
static void hybrid_idx_copy_rows(ggml_tensor * t, uint32_t src, uint32_t dst, uint32_t n) {
    GGML_ASSERT(src + n <= dst || dst + n <= src);

    ggml_init_params params = {
        /*.mem_size   =*/ 2*ggml_tensor_overhead(),
        /*.mem_buffer =*/ nullptr,
        /*.no_alloc   =*/ true,
    };

    ggml_context * ctx = ggml_init(params);
    GGML_ASSERT(ctx != nullptr);

    ggml_tensor * a = ggml_view_2d(ctx, t, t->ne[0], n, t->nb[1], (size_t) src*t->nb[1]);
    ggml_tensor * b = ggml_view_2d(ctx, t, t->ne[0], n, t->nb[1], (size_t) dst*t->nb[1]);

    ggml_backend_view_init(a);
    ggml_backend_view_init(b);

    ggml_backend_tensor_copy(a, b);

    ggml_free(ctx);
}

void llama_memory_hybrid_idx::kb_move_rows(const llama_kv_cache::cell_move_vec_t & moves) {
    for (const auto & [il, t] : kb_map) {
        for (const auto & m : moves) {
            hybrid_idx_copy_rows(t, m.src, m.dst, m.n);
        }
    }
'''),
        ('''
        // prepare the recurrent batches first
''',
         '''
        // strixllama: regions - a conversation whose tokens do not fit after its last cell moves to a larger run
        // first. The indexer mirrors the attention cells, so it moves with them, in the same step.
        if (get_mem_attn()->can_move() && (!mem_idx || mem_idx->can_move())) {
            const auto moves = get_mem_attn()->plan_moves(ubatches);
            if (!moves.empty()) {
                get_mem_attn()->move_cells(moves);
                if (mem_idx) {
                    mem_idx->move_cells(moves);
                }

                // A block's key sits at the row of its first cell. The moves lay each sequence out in position
                // order, so its block keys can move with their cells only if its cells were already in that
                // order (then every block keeps its first cell); otherwise that sequence's are rebuilt once.
                bool ordered = true;
                for (size_t i = 1; i < moves.size() && ordered; ++i) {
                    if (moves[i].seq == moves[i - 1].seq) {
                        ordered = moves[i - 1].src + moves[i - 1].n <= moves[i].src;
                    }
                }
                if (ordered) {
                    kb_move_rows(moves);
                } else {
                    for (const auto & m : moves) {
                        kb_mark_stale(m.seq);
                    }
                }
            }
        }

        // prepare the recurrent batches first
'''),
        ('''void llama_memory_hybrid_idx::clear(bool data) {
    kb_gen++;   // strixllama: block keys depend on positions and cell contents; rebuild them all once
    kb_dup = false;   // strixllama: no cells left, so no image cells either
''',
         '''void llama_memory_hybrid_idx::clear(bool data) {
    kb_mark_stale(-1);   // strixllama: block keys depend on positions and cell contents; rebuild them once
    kb_dup = false;   // strixllama: no cells left, so no image cells either
'''),
        ('''void llama_memory_hybrid_idx::seq_cp(llama_seq_id seq_id_src, llama_seq_id seq_id_dst, llama_pos p0, llama_pos p1) {
    llama_memory_hybrid::seq_cp(seq_id_src, seq_id_dst, p0, p1);
''',
         '''void llama_memory_hybrid_idx::seq_cp(llama_seq_id seq_id_src, llama_seq_id seq_id_dst, llama_pos p0, llama_pos p1) {
    // strixllama: the copy shares the source's cells, and with them block keys that may still have to be rebuilt
    if (seq_id_src >= 0 && seq_id_src < LLAMA_MAX_SEQ && kb_stale.test(seq_id_src)) {
        kb_mark_stale(seq_id_dst);
    }

    llama_memory_hybrid::seq_cp(seq_id_src, seq_id_dst, p0, p1);
'''),
        ('''    kb_gen++;   // strixllama: block keys depend on positions and cell contents; rebuild them all once
    llama_memory_hybrid::seq_add(seq_id, p0, p1, shift);

    if (mem_idx) {
        mem_idx->seq_add(seq_id, p0, p1, shift);
    }
}

void llama_memory_hybrid_idx::seq_div(llama_seq_id seq_id, llama_pos p0, llama_pos p1, int d) {
    kb_gen++;   // strixllama: block keys depend on positions and cell contents; rebuild them all once
''',
         '''    kb_mark_stale(-1);   // strixllama: block keys depend on positions; a shifted cell can be shared, so all of them
    llama_memory_hybrid::seq_add(seq_id, p0, p1, shift);

    if (mem_idx) {
        mem_idx->seq_add(seq_id, p0, p1, shift);
    }
}

void llama_memory_hybrid_idx::seq_div(llama_seq_id seq_id, llama_pos p0, llama_pos p1, int d) {
    kb_mark_stale(-1);   // strixllama: block keys depend on positions; a shifted cell can be shared, so all of them
'''),
        ('''void llama_memory_hybrid_idx::state_read(llama_io_read_i & io, llama_seq_id seq_id, llama_state_seq_flags flags) {
    kb_gen++;   // strixllama: block keys depend on positions and cell contents; rebuild them all once
    // note: repeats llama_memory_hybrid::state_read
''',
         '''void llama_memory_hybrid_idx::state_read(llama_io_read_i & io, llama_seq_id seq_id, llama_state_seq_flags flags) {
    kb_mark_stale(seq_id);   // strixllama: the restored cells' block keys were never written; rebuild them once
    // note: repeats llama_memory_hybrid::state_read
'''),
        ('''        ggml_tensor * bias, const llama_ubatch * ubatch, uint32_t ratio, bool blk_bias, const qsa_kb_inputs * kb) const {
    set_input_qsa_impl(cell_blk, blk_cells, blk_pos, bias, nullptr, ubatch, ratio, blk_bias, kb);
}

void llama_memory_hybrid_idx::set_input_qsa_blocks(
        ggml_tensor * cell_blk, ggml_tensor * blk_cells, ggml_tensor * blk_pos,
        ggml_tensor * bias, ggml_tensor * tail_idxs, const llama_ubatch * ubatch, uint32_t ratio, const qsa_kb_inputs * kb, const qsa_mixed_inputs * mixed,
        bool active_only) const {
    set_input_qsa_impl(cell_blk, blk_cells, blk_pos, bias, tail_idxs, ubatch, ratio, true, kb, mixed, active_only);
}
''',
         '''        ggml_tensor * bias, const llama_ubatch * ubatch, uint32_t ratio, bool blk_bias, const qsa_kb_inputs * kb,
        uint32_t kv_off) const {
    set_input_qsa_impl(cell_blk, blk_cells, blk_pos, bias, nullptr, ubatch, ratio, blk_bias, kb, nullptr, false, kv_off);
}

void llama_memory_hybrid_idx::set_input_qsa_blocks(
        ggml_tensor * cell_blk, ggml_tensor * blk_cells, ggml_tensor * blk_pos,
        ggml_tensor * bias, ggml_tensor * tail_idxs, const llama_ubatch * ubatch, uint32_t ratio, const qsa_kb_inputs * kb, const qsa_mixed_inputs * mixed,
        bool active_only, uint32_t kv_off) const {
    set_input_qsa_impl(cell_blk, blk_cells, blk_pos, bias, tail_idxs, ubatch, ratio, true, kb, mixed, active_only, kv_off);
}

// strixllama: the indexer cells as the graph's view sees them, from its first cell (llama_kv_cache::get_kv_window)
struct hybrid_idx_cells_view {
    const llama_kv_cells & cells;
    const uint32_t         off;

    bool                              is_empty   (uint32_t j)                 const { return cells.is_empty(off + j); }
    const llama_kv_cells::seq_set_t & seq_get_all(uint32_t j)                 const { return cells.seq_get_all(off + j); }
    bool                              seq_has    (uint32_t j, llama_seq_id s) const { return cells.seq_has(off + j, s); }
    llama_pos                         pos_get    (uint32_t j)                 const { return cells.pos_get(off + j); }
    const llama_kv_cell_ext &         ext_get    (uint32_t j)                 const { return cells.ext_get(off + j); }
    llama_pos                         seq_pos_min(llama_seq_id s)             const { return cells.seq_pos_min(s); }
};
'''),
        ('''        const qsa_mixed_inputs * mixed,
        bool active_only) const {
    GGML_ASSERT(ratio > 0);
''',
         '''        const qsa_mixed_inputs * mixed,
        bool active_only,
        uint32_t kv_off) const {
    GGML_ASSERT(ratio > 0);
'''),
        ('''    if (active_only) {
        for (int64_t i = 0; i < n_tokens; ++i) {
            for (int32_t k = 0; k < ubatch->n_seq_id[i]; ++k) { active_seqs.set(ubatch->seq_id[i][k]); }
        }
    }
''',
         '''    for (int64_t i = 0; i < n_tokens; ++i) {
        for (int32_t k = 0; k < ubatch->n_seq_id[i]; ++k) { active_seqs.set(ubatch->seq_id[i][k]); }
    }
    // strixllama: a cell of no sequence of this ubatch is invisible to every query in it, and its block key is
    // rebuilt by its own sequence's graph when it goes stale (kb_needs_full), so it is left out of the blocks.
    // That also keeps a window's foreign cells - the neighbours of the run a window views, whose positions have
    // nothing to do with it - out of the position buckets.
'''),
        ('''        const auto & cells = get_mem_idx()->get_cells(seq_of_stream);
''',
         '''        // strixllama: every index below is relative to the view's first cell
        GGML_ASSERT(kv_off == 0 || n_ns == 1);
        const hybrid_idx_cells_view cells = { get_mem_idx()->get_cells(seq_of_stream), kv_off };
'''),
        ('''                if (active_only && (cells.seq_get_all(j) & active_seqs).none()) {
''',
         '''                if ((cells.seq_get_all(j) & active_seqs).none()) {
'''),
        ('''                br[b] = b < n_bid ? bid_cell[b] : scratch;
''',
         '''                br[b] = b < n_bid ? (int32_t) kv_off + bid_cell[b] : scratch;
'''),
        ('''                dd[n_dirty] = bid_cell[b];
''',
         '''                dd[n_dirty] = (int32_t) kv_off + bid_cell[b];
'''),
        ('''    mem->set_input_qsa(cell_blk, blk_cells, blk_pos, bias, ubatch, ratio, blk_bias, kb);
''',
         '''    mem->set_input_qsa(cell_blk, blk_cells, blk_pos, bias, ubatch, ratio, blk_bias, kb, get_idx()->get_kv_off());
'''),
        ('''bool llama_memory_hybrid_idx_context::kb_needs_full() const {
    return mem ? mem->kb_needs_full() : false;
}

bool llama_memory_hybrid_idx_context::kb_pos_dup() const {
    return mem ? mem->kb_pos_dup() : false;
}

void llama_memory_hybrid_idx_context::kb_mark_full() const {
    if (mem) { mem->kb_mark_full(); }
''',
         '''bool llama_memory_hybrid_idx_context::kb_needs_full(const llama_ubatch & ubatch) const {
    return mem ? mem->kb_needs_full(ubatch) : false;
}

bool llama_memory_hybrid_idx_context::kb_pos_dup() const {
    return mem ? mem->kb_pos_dup() : false;
}

void llama_memory_hybrid_idx_context::kb_mark_full(const llama_ubatch & ubatch) const {
    if (mem) { mem->kb_mark_full(ubatch); }
'''),
        ('''    mem->set_input_qsa_blocks(cell_blk, blk_cells, blk_pos, bias, tail_idxs, ubatch, ratio, kb, mixed, active_only);
''',
         '''    mem->set_input_qsa_blocks(cell_blk, blk_cells, blk_pos, bias, tail_idxs, ubatch, ratio, kb, mixed, active_only,
            get_idx()->get_kv_off());
'''),
        ('''    return qsa_single_sequence_prefix(mem->get_mem_idx()->get_cells(seq),get_idx()->get_n_kv(),seq,active_only);
''',
         '''    // strixllama: set_input_qsa_impl leaves other sequences' cells out of the blocks, so they cannot break the
    // prefix; the window starts at get_kv_off()
    return qsa_single_sequence_prefix(mem->get_mem_idx()->get_cells(seq),get_idx()->get_n_kv(),seq,true,
            get_idx()->get_kv_off());
'''),
        ('''// the budget. A graph that rewrites every block key (kb_needs_full) keeps the whole pool: it is the one that
// refreshes the idle sequences' keys too. So does the reserve graph (positions all equal), which sizes the
// buffers for the widest graph. LLAMA_QSA_ACTIVE_BLOCKS=0 turns this off.
int64_t llama_memory_hybrid_idx_context::qsa_active_blocks(const llama_ubatch & ubatch, uint32_t ratio, int64_t min_blocks) const {
    static const bool on = !getenv("LLAMA_QSA_ACTIVE_BLOCKS") || atoi(getenv("LLAMA_QSA_ACTIVE_BLOCKS")) != 0;
    if (!on || mem == nullptr || get_idx() == nullptr || ratio == 0 || get_n_stream() != 1 ||
            mem->kb_needs_full() || mem->kb_pos_dup() || !qsa_scalar_visibility(ubatch)) {
''',
         '''// the budget. The reserve graph (positions all equal) keeps the whole pool: it sizes the buffers for the widest
// graph. LLAMA_QSA_ACTIVE_BLOCKS=0 turns this off.
int64_t llama_memory_hybrid_idx_context::qsa_active_blocks(const llama_ubatch & ubatch, uint32_t ratio, int64_t min_blocks) const {
    static const bool on = !getenv("LLAMA_QSA_ACTIVE_BLOCKS") || atoi(getenv("LLAMA_QSA_ACTIVE_BLOCKS")) != 0;
    if (!on || mem == nullptr || get_idx() == nullptr || ratio == 0 || get_n_stream() != 1 ||
            mem->kb_pos_dup() || !qsa_scalar_visibility(ubatch)) {
'''),
        ('''        for (uint32_t j=0;j<get_idx()->get_n_kv();++j) {
''',
         '''        const uint32_t off=get_idx()->get_kv_off();   // strixllama: the window's first cell
        for (uint32_t j=off;j<off+get_idx()->get_n_kv();++j) {
'''),
    ],
    os.path.join(tree, "src", "llama-memory-hybrid-idx.h"): [
        ('''    };
    void set_input_qsa(ggml_tensor * cell_blk, ggml_tensor * blk_cells, ggml_tensor * blk_pos,
''',
         '''    };
    // strixllama: kv_off = the first cell of the graph's view of the caches (llama_kv_cache::get_kv_window).
    // Every cell index these inputs carry is relative to it, except the block-key cache rows, which address
    // the whole cache tensor.
    void set_input_qsa(ggml_tensor * cell_blk, ggml_tensor * blk_cells, ggml_tensor * blk_pos,
'''),
        ('''                       bool blk_bias, const qsa_kb_inputs * kb = nullptr) const;
''',
         '''                       bool blk_bias, const qsa_kb_inputs * kb = nullptr, uint32_t kv_off = 0) const;
'''),
        ('''                             const qsa_mixed_inputs * mixed = nullptr, bool active_only = false) const;
''',
         '''                             const qsa_mixed_inputs * mixed = nullptr, bool active_only = false, uint32_t kv_off = 0) const;
'''),
        ('''    bool          kb_needs_full() const;      // positions moved (shift, restore, clear) since the last full write
    void          kb_mark_full() const;
''',
         '''    // strixllama: a sequence's block keys go stale when its positions move or its cells are restored or moved out
    // of order; the next graph of a ubatch holding it rebuilds every key of that ubatch's sequences
    bool          kb_needs_full(const llama_ubatch & ubatch) const;
    void          kb_mark_full(const llama_ubatch & ubatch) const;
'''),
        ('''    // the position, which the block-key cache cannot track - the graph must not wire the cache in.
    bool          kb_pos_dup() const;

private:
''',
         '''    // the position, which the block-key cache cannot track - the graph must not wire the cache in.
    bool          kb_pos_dup() const;


private:
'''),
        ('''                            const qsa_kb_inputs * kb, const qsa_mixed_inputs * mixed = nullptr,
                            bool active_only = false) const;

''',
         '''                            const qsa_kb_inputs * kb, const qsa_mixed_inputs * mixed = nullptr,
                            bool active_only = false, uint32_t kv_off = 0) const;

'''),
        ('''    uint64_t                             kb_gen      = 1;
    mutable uint64_t                     kb_full_gen = 0;
''',
         '''    // the sequences whose block keys have to be rebuilt (see kb_needs_full). All of them at the start and after
    // a clear, so the first graph of every sequence builds its keys the way it always has
    mutable std::bitset<LLAMA_MAX_SEQ>   kb_stale = std::bitset<LLAMA_MAX_SEQ>().set();
    void kb_mark_stale(llama_seq_id seq_id);   // < 0: every sequence
    // strixllama: regions - block-key rows follow their cells (llama_kv_cache::move_cells)
    void kb_move_rows(const llama_kv_cache::cell_move_vec_t & moves);
'''),
        ('''    bool          kb_needs_full() const;
    void          kb_mark_full() const;
''',
         '''    bool          kb_needs_full(const llama_ubatch & ubatch) const;
    void          kb_mark_full(const llama_ubatch & ubatch) const;
'''),
    ],
    os.path.join(tree, "src", "models", "qwen4exp.cpp"): [
        ('''        GGML_ASSERT(mctx_idx->get_n_kv() == inp->mctx->get_attn()->get_n_kv() &&
                "the indexer cache must track the attention cache cell for cell");
''',
         '''        GGML_ASSERT(mctx_idx->get_n_kv() == inp->mctx->get_attn()->get_n_kv() &&
                mctx_idx->get_kv_off() == inp->mctx->get_attn()->get_kv_off() &&
                "the indexer cache must track the attention cache cell for cell");
'''),
        ('''            inp_attn = inp_hyb->get_attn();
            // the MTP graph has no recurrent layers, so the hybrid input's recurrent tensors are never used and the
''',
         '''            inp_attn = inp_hyb->get_attn();
            GGML_ASSERT(m->get_idx()->get_n_kv() == m->get_attn()->get_n_kv() &&
                    m->get_idx()->get_kv_off() == m->get_attn()->get_kv_off() &&
                    "the indexer cache must track the attention cache cell for cell");
            // the MTP graph has no recurrent layers, so the hybrid input's recurrent tensors are never used and the
'''),
        ('''            mctx->kb_mark_full();
''',
         '''            mctx->kb_mark_full(*ubatch);
'''),
        ('''            res &= kb_full == mctx->kb_needs_full();
''',
         '''            res &= kb_full == mctx->kb_needs_full(params.ubatch);
'''),
        ('''            qsa->kb_full        = mctx_hyb->kb_needs_full();
''',
         '''            qsa->kb_full        = mctx_hyb->kb_needs_full(ubatch);
'''),
    ],
    os.path.join(tree, "src", "prefix.h"): [
        ('''// do not break the prefix; the sequence's own cells must still be its alone
static bool qsa_single_sequence_prefix(const llama_kv_cells & cells, uint32_t count, llama_seq_id seq, bool active_only = false) {
    if (count>cells.size()) { return false; }
''',
         '''// do not break the prefix; the sequence's own cells must still be its alone. off = the view's first cell.
static bool qsa_single_sequence_prefix(const llama_kv_cells & cells, uint32_t count, llama_seq_id seq, bool active_only = false,
        uint32_t off = 0) {
    if ((uint64_t) off+count>cells.size()) { return false; }
'''),
        ('''    for (uint32_t i=0;i<count;++i) {
''',
         '''    for (uint32_t i=off;i<off+count;++i) {
'''),
    ],
}


def main():
    texts = {p: io.open(p, encoding="utf-8").read() for p in EDITS}
    if any(MARKER in t for t in texts.values()):
        print("already applied")
        return
    for p, pairs in EDITS.items():
        for old, new in pairs:
            if texts[p].count(old) != 1:
                sys.exit("anchor found %d times, expected once, in %s" % (texts[p].count(old), p))
            texts[p] = texts[p].replace(old, new, 1)
    for p, t in texts.items():
        io.open(p, "w", encoding="utf-8", newline="").write(t)
    print("patched", ", ".join(os.path.basename(p) for p in EDITS))


if __name__ == "__main__":
    main()
