#!/usr/bin/env python3
"""Freed KV cells are zeroed (STRIX_KV_ZERO_FREED=0 leaves them)

A cell a sequence gives up - seq_rm, seq_keep, a move's vacated cells, clear - has its K and V rows zeroed by asynchronous copies from a zero tensor kept in each cache buffer, queued on the stream the graphs run on. The sparse-attention prefill kernel reads past a conversation's last cell up to its block boundary with a weight of exactly zero, but its matrix-core sums still moved in the last bit with what those cells held: a result depended on who had used the cells before (a rejected draft, an earlier conversation). About 0.5% of decode with MTP. V stays unrotated for qwen4exp as apply_kv_q8_0 left it: with zeroed cells a rotated V would be safe, but the disk tier's q8_0 conversations are stored unrotated in rows of the same size, and the quality is the same within error (mean KLD against f16 0.0139 against 0.0137 rotated, +/- 0.0007).

Generated by tools/make_patch_script.py from the tree it must reproduce, so every anchor is
unique by construction. 15 hunks across 2 file(s).

Usage: python D:/Work/strixllama/patches/apply_kv_zero_freed.py [tree]
"""
import io
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
tree = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "src", "llama.cpp")
MARKER = 'STRIX_KV_ZERO_FREED'

EDITS = {
    os.path.join(tree, "src", "llama-kv-cache.cpp"): [
        ('''                /*.mem_size   =*/ size_t(2u*(1 + n_stream)*n_layer*ggml_tensor_overhead()),
''',
         '''                /*.mem_size   =*/ size_t((2u*(1 + n_stream)*n_layer + 2)*ggml_tensor_overhead()),
'''),
        ('''    const bool is_mla = hparams.is_mla();

''',
         '''    const bool is_mla = hparams.is_mla();

    // strixllama: the widest K and V rows per buffer type, for zero_cells' source
    std::map<ggml_backend_buffer_type_t, std::pair<int64_t, int64_t>> widest;

'''),
        ('''        layers.push_back({ il, k, v, k_stream, v_stream, });
    }
''',
         '''        layers.push_back({ il, k, v, k_stream, v_stream, });

        auto & w = widest[buft];
        w.first  = std::max<int64_t>(w.first,  has_k ? n_embd_k_gqa : 0);
        w.second = std::max<int64_t>(w.second, has_v && !v_trans ? n_embd_v_gqa : 0);
    }

    // strixllama: zeros to copy over freed cells (zero_cells): 256 rows of each K/V type in each buffer, cleared with
    // the buffer below and never written
    for (const auto & [buft, w] : widest) {
        ggml_context * ctx = ctx_for_buft(buft);
        const int64_t n_zero = 256;
        auto add = [&](ggml_type type, int64_t row) {
            if (row > 0) {
                ggml_tensor * z = ggml_new_tensor_1d(ctx, type, n_zero*row);
                ggml_format_name(z, "cache_%szero_%s", name_tag, ggml_type_name(type));
                zero_src.push_back({ buft, type, z });
            }
        };
        if (type_k == type_v) {
            add(type_k, std::max(w.first, w.second));
        } else {
            add(type_k, w.first);
            add(type_v, w.second);
        }
    }
'''),
        ('''        // a conversation's last one, which hold whatever an earlier conversation left there. The inverse rotation
        // of the output spreads that bit over 64 dimensions, far enough to reach the tokens, so a conversation read
        // back from disk parted from the same one kept in memory; unrotated it does not. K rotated alone: mean KLD
        // against f16 0.0139 +/- 0.0007, both rotated 0.0137.
''',
         '''        // a conversation's last one. Before freed cells were zeroed (zero_cells) they held whatever an earlier
        // conversation left there, and the inverse rotation of the output spread that bit far enough that a
        // conversation read back from disk parted from the same one kept in memory. With zeroed cells a rotated V
        // would be safe, but the disk tier's q8_0 conversations are stored unrotated and their rows are the same
        // size either way, so rotating now would read them wrong; the quality is the same within error (mean KLD
        // against f16: K rotated alone 0.0139 +/- 0.0007, both rotated 0.0137).
'''),
        ('''void llama_kv_cache::clear(bool data) {
    for (uint32_t s = 0; s < n_stream; ++s) {
''',
         '''void llama_kv_cache::clear(bool data) {
    // strixllama: a cleared cache has no stale rows either (see zero_cells)
    static const bool zero_on = [] { const char * e = getenv("STRIX_KV_ZERO_FREED"); return !e || atoi(e) != 0; }();
    if (!data && zero_on && !other) {
        if (lctx_sync != nullptr) {
            ggml_backend_sched_synchronize(lctx_sync->get_sched());
        }
        data = true;
    }

    for (uint32_t s = 0; s < n_stream; ++s) {
'''),
        ('''        uint32_t new_head = cells.size();

        for (uint32_t i = 0; i < cells.size(); ++i) {
            if (!cells.pos_in(i, p0, p1)) {
''',
         '''        uint32_t new_head = cells.size();

        std::vector<std::pair<uint32_t, uint32_t>> freed;

        for (uint32_t i = 0; i < cells.size(); ++i) {
            if (!cells.pos_in(i, p0, p1)) {
'''),
        ('''                    new_head = i;
                }
            }
        }

        // If we freed up a slot, set head to it so searching can start there.
''',
         '''                    new_head = i;
                }
                if (!freed.empty() && freed.back().second == i) {
                    freed.back().second = i + 1;
                } else {
                    freed.push_back({ i, i + 1 });
                }
            }
        }

        zero_cells(seq_to_stream[seq_id], freed);

        // If we freed up a slot, set head to it so searching can start there.
'''),
        ('''
            for (uint32_t i = 0; i < cells.size(); ++i) {
''',
         '''
            std::vector<std::pair<uint32_t, uint32_t>> freed;

            for (uint32_t i = 0; i < cells.size(); ++i) {
'''),
        ('''                    new_head = i;
                }
            }

            // If we freed up a slot, set head to it so searching can start there.
''',
         '''                    new_head = i;
                }
                if (!freed.empty() && freed.back().second == i) {
                    freed.back().second = i + 1;
                } else {
                    freed.push_back({ i, i + 1 });
                }
            }

            zero_cells(s, freed);

            // If we freed up a slot, set head to it so searching can start there.
'''),
        ('''    uint32_t new_head = cells.size();

    for (uint32_t i = 0; i < cells.size(); ++i) {
        if (cells.seq_keep(i, seq_id)) {
''',
         '''    uint32_t new_head = cells.size();

    std::vector<std::pair<uint32_t, uint32_t>> freed;

    for (uint32_t i = 0; i < cells.size(); ++i) {
        if (cells.seq_keep(i, seq_id)) {
'''),
        ('''                new_head = i;
            }
        }
    }

    // If we freed up a slot, set head to it so searching can start there.
''',
         '''                new_head = i;
            }
            if (!freed.empty() && freed.back().second == i) {
                freed.back().second = i + 1;
            } else {
                freed.push_back({ i, i + 1 });
            }
        }
    }

    zero_cells(seq_to_stream[seq_id], freed);

    // If we freed up a slot, set head to it so searching can start there.
'''),
        ('''        ggml_reset(ctx);
    }
''',
         '''        ggml_reset(ctx);
    }

    ggml_free(ctx);
}

void llama_kv_cache::zero_cells(uint32_t strm, const std::vector<std::pair<uint32_t, uint32_t>> & ranges) const {
    static const bool on = [] { const char * e = getenv("STRIX_KV_ZERO_FREED"); return !e || atoi(e) != 0; }();
    if (!on || ranges.empty() || zero_src.empty() || other != nullptr) {
        return;
    }

    ggml_init_params params = {
        /*.mem_size   =*/ 2*ggml_tensor_overhead(),
        /*.mem_buffer =*/ nullptr,
        /*.no_alloc   =*/ true,
    };

    ggml_context * ctx = ggml_init(params);
    GGML_ASSERT(ctx != nullptr);

    bool synced = false;
    for (const auto & layer : layers) {
        for (ggml_tensor * t : { layer.k, layer.v }) {
            if (t == nullptr || t->buffer == nullptr || t->data == nullptr || (t == layer.v && v_trans)) {
                continue;
            }

            const ggml_backend_buffer_type_t buft = ggml_backend_buffer_get_type(t->buffer);
            ggml_tensor * z = nullptr;
            for (const auto & zs : zero_src) {
                if (zs.buft == buft && zs.type == t->type) {
                    z = zs.t;
                    break;
                }
            }
            if (z == nullptr || z->data == nullptr) {
                continue;
            }

            // on the stream the graphs run on, as copy_rows: after the reads queued before, before the next graph
            ggml_backend_t backend = backend_for(t);
            if (backend == nullptr && !synced && lctx_sync != nullptr) {
                ggml_backend_sched_synchronize(lctx_sync->get_sched());
                synced = true;
            }

            const int64_t z_rows = ggml_nelements(z) / t->ne[0];
            for (const auto & r : ranges) {
                for (uint32_t c = r.first; c < r.second; ) {
                    const uint32_t n = (uint32_t) std::min<int64_t>(r.second - c, z_rows);

                    ggml_tensor * a = ggml_view_1d(ctx, z, (int64_t) n*t->ne[0], 0);
                    ggml_tensor * b = ggml_view_1d(ctx, t, (int64_t) n*t->ne[0], (size_t) strm*t->nb[2] + (size_t) c*t->nb[1]);

                    ggml_backend_view_init(a);
                    ggml_backend_view_init(b);

                    if (backend != nullptr) {
                        ggml_backend_tensor_copy_async(backend, backend, a, b);
                    } else {
                        ggml_backend_tensor_copy(a, b);
                    }

                    ggml_reset(ctx);
                    c += n;
                }
            }
        }
    }
'''),
        ('''        cells.mv_range(m.src, m.dst, m.n, m.seq);
    }
}

''',
         '''        cells.mv_range(m.src, m.dst, m.n, m.seq);
    }

    // strixllama: what the pieces left behind is free now - zeroed after the copies that read it, on their stream
    std::vector<std::pair<uint32_t, uint32_t>> freed;
    for (const auto & m : moves) {
        for (uint32_t i = m.src; i < m.src + m.n; ++i) {
            if (!cells.is_empty(i)) {
                continue;
            }
            if (!freed.empty() && freed.back().second == i) {
                freed.back().second = i + 1;
            } else {
                freed.push_back({ i, i + 1 });
            }
        }
    }
    zero_cells(0, freed);
}

'''),
    ],
    os.path.join(tree, "src", "llama-kv-cache.h"): [
        ('''    void copy_rows(ggml_tensor * t, const cell_move_vec_t & moves) const;

private:
    // the cells of positions [p0, p0 + n) of seq_id as runs of consecutive cells, in position order (seq_rows_*)
''',
         '''    void copy_rows(ggml_tensor * t, const cell_move_vec_t & moves) const;

    // strixllama: zero the rows of cells [first, second) of stream strm in every layer, queued as above. A cell is
    // zeroed as it is freed, so what a later conversation finds in the free cells it attends past its end - its
    // own last block of keys holds some - is always the same: the matrix cores' sums move in the last bit with
    // the values of keys they weight by zero (STRIX_KV_ZERO_FREED=0 leaves freed cells as they are)
    void zero_cells(uint32_t strm, const std::vector<std::pair<uint32_t, uint32_t>> & ranges) const;

private:
    // the cells of positions [p0, p0 + n) of seq_id as runs of consecutive cells, in position order (seq_rows_*)
'''),
        ('''    std::function<void(const cell_move_vec_t &, bool)> move_hook;
    // where plan_layout put the sequences of its batch that hold no cell yet, for find_slot_regions
''',
         '''    std::function<void(const cell_move_vec_t &, bool)> move_hook;
    // strixllama: zero_cells' source - zeros in each buffer, one tensor per K/V type, never written
    struct zero_src_t { ggml_backend_buffer_type_t buft; ggml_type type; ggml_tensor * t; };
    std::vector<zero_src_t> zero_src;
    // where plan_layout put the sequences of its batch that hold no cell yet, for find_slot_regions
'''),
    ],
}


def main():
    texts = {p: io.open(p, encoding="utf-8").read() for p in EDITS}
    if any(MARKER in t for t in texts.values()):
        print("already applied")
        return
    for p, pairs in EDITS.items():
        for old, new in pairs:
            if texts[p].count(old) != 1:
                sys.exit("anchor found %d times, expected once, in %s" % (texts[p].count(old), p))
            texts[p] = texts[p].replace(old, new, 1)
    for p, t in texts.items():
        io.open(p, "w", encoding="utf-8", newline="").write(t)
    print("patched", ", ".join(os.path.basename(p) for p in EDITS))


if __name__ == "__main__":
    main()
