#!/usr/bin/env python3
"""Record why the expert route sort stays bitonic.

Comment only. A counting sort was tried here and lost: 906 against 946 t/s pp16384, perplexity
identical. Kept so the next reader does not repeat it.

Generated by tools/make_patch_script.py from the tree it must reproduce, so every anchor is
unique by construction. 1 hunks across 1 file(s).

Usage: python patches/apply_mmid_sort_note.py [tree]
"""
import io
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
tree = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "src", "llama.cpp")
MARKER = 'counting sort was tried'

EDITS = {
    os.path.join(tree, "ggml", "src", "ggml-cuda", "mmid.cu"): [
        ('''
static __global__ void mm_ids_route_sort(
''',
         '''
// strixllama 2026-09-17: a counting sort was tried here, following halogen CHANGELOG 0.5.3 ("expert
// ordering produced by general-purpose sort...counted out directly instead", reported +4.6% at 8k
// and +8.1% at 32k). On this kernel it LOST: 904.26 and, with the expert ids cached in LDS so
// global memory is read once, 906.35 pp16384 against 946.06 for the bitonic sort below (3 reps,
// perplexity identical at 2.3786 either way). The atomic cursor in the scatter serialises threads
// landing on one expert and the 512-wide scan costs more than the sort it replaces - the bitonic
// version runs entirely in LDS with no atomics at all, which suits 1024 elements. Reverted; the
// gain halogen saw must come from their own engine's ordering code, not from this shape.
static __global__ void mm_ids_route_sort(
'''),
    ],
}


def main():
    texts = {p: io.open(p, encoding="utf-8").read() for p in EDITS}
    if any(MARKER in t for t in texts.values()):
        print("already applied")
        return
    for p, pairs in EDITS.items():
        for old, new in pairs:
            if texts[p].count(old) != 1:
                sys.exit("anchor found %d times, expected once, in %s" % (texts[p].count(old), p))
            texts[p] = texts[p].replace(old, new, 1)
    for p, t in texts.items():
        io.open(p, "w", encoding="utf-8", newline="").write(t)
    print("patched", ", ".join(os.path.basename(p) for p in EDITS))


if __name__ == "__main__":
    main()
