#!/usr/bin/env python3
"""A rebuilt block-key cache scores with the keys as the cache holds them

With the block-key cache on, every graph scores the sparse-attention blocks with keys read back from the cache, which holds them in F16 - except the graph that rebuilds the cache (the first of a conversation, and the first after a restore or a checkpoint rewind), which scored with the F32 keys it had just computed. So a conversation restored to position n and one that simply went on from n selected slightly different blocks on their next batch: same tokens, logprobs apart by up to 0.34. The rebuild now reads its keys back from the cache like every other graph, and a restore continues bitwise as the resident conversation does. Perplexity at ctx 4096 is unchanged to four places at ubatch 4096 and 512 (2.6476, 2.6510), identical to the cache switched off.

Generated by tools/make_patch_script.py from the tree it must reproduce, so every anchor is
unique by construction. 1 hunks across 1 file(s).

Usage: python D:/Work/strixllama/patches/apply_qsa_kb_rebuild_f16.py [tree]
"""
import io
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
tree = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "src", "llama.cpp")
MARKER = 'score with the keys as the cache holds them (F16)'

EDITS = {
    os.path.join(tree, "src", "models", "qwen4exp.cpp"): [
        ('''            ggml_build_forward_expand(gf, ggml_set_rows(ctx0, kb, ggml_reshape_2d(ctx0, pooled, idx_dim, n_blocks), inp->kb_bid_rows));
        }
''',
         '''            ggml_build_forward_expand(gf, ggml_set_rows(ctx0, kb, ggml_reshape_2d(ctx0, pooled, idx_dim, n_blocks), inp->kb_bid_rows));
            // score with the keys as the cache holds them (F16), as every later graph does: a rebuild - the first
            // graph of a conversation, one after a restore or a rewind - then selects what the cache would have
            pooled = ggml_get_rows(ctx0, kb, inp->kb_bid_rows);
            pooled = ggml_reshape_3d(ctx0, pooled, idx_dim, n_blocks, n_stream);
        }
'''),
    ],
}


def main():
    texts = {p: io.open(p, encoding="utf-8").read() for p in EDITS}
    if any(MARKER in t for t in texts.values()):
        print("already applied")
        return
    for p, pairs in EDITS.items():
        for old, new in pairs:
            if texts[p].count(old) != 1:
                sys.exit("anchor found %d times, expected once, in %s" % (texts[p].count(old), p))
            texts[p] = texts[p].replace(old, new, 1)
    for p, t in texts.items():
        io.open(p, "w", encoding="utf-8", newline="").write(t)
    print("patched", ", ".join(os.path.basename(p) for p in EDITS))


if __name__ == "__main__":
    main()
